import type { NewCityPlace } from "./schema";

// ~100 Bengaluru places across kinds. Coordinates are real (verified to ~3
// decimals); fees and timings are seeded approximations and get replaced by
// Google Places data at runtime when an API key is configured.
//
// kind: attraction | temple | museum | park | lake | restaurant | mall |
//       nightlife | market | viewpoint | church
// category: heritage | spiritual | nature | art | shopping | food | nightlife
type Seed = Omit<NewCityPlace, "id" | "createdAt">;

const BLR = "Bangalore";

function p(s: Seed): Seed {
  return { ...s, city: BLR };
}

export const bangaloreCityPlaces: Seed[] = [
  // --- Heritage / Palaces / Forts ---
  p({
    slug: "blr-bengaluru-palace",
    name: "Bengaluru Palace",
    city: BLR,
    kind: "attraction",
    category: "heritage",
    area: "Vasanthnagar",
    shortDescription: "Tudor-style royal palace modelled on Windsor Castle, built 1878.",
    description:
      "Built by the Wodeyars of Mysore in 1878 on land formerly owned by Reverend Garrett. The fortified Tudor-Revival mansion has carved wooden interiors, an art gallery and a guided audio tour. Used for concerts and events.",
    entryFeePerPerson: 260,
    idealMinutesAtPlace: 90,
    openTime: "10:00",
    closeTime: "17:30",
    openDays: "All",
    tags: "palace,heritage,audio-tour,photography",
    latitude: "12.9988",
    longitude: "77.5921",
    popularity: 88,
  }),
  p({
    slug: "blr-tipu-summer-palace",
    name: "Tipu Sultan's Summer Palace",
    city: BLR,
    kind: "attraction",
    category: "heritage",
    area: "Kalasipalyam",
    shortDescription: "Tipu Sultan's 18th-century teak-pillared summer retreat.",
    description:
      "A two-storey Indo-Islamic palace completed in 1791. Decorated frescoes, fluted pillars and an ASI museum on the ground floor with arms and royal artefacts. Pair with Bangalore Fort across the road.",
    entryFeePerPerson: 25,
    idealMinutesAtPlace: 45,
    openTime: "08:30",
    closeTime: "17:30",
    openDays: "All",
    tags: "palace,heritage,asi,history",
    latitude: "12.9595",
    longitude: "77.5731",
    popularity: 80,
  }),
  p({
    slug: "blr-bangalore-fort",
    name: "Bangalore Fort",
    city: BLR,
    kind: "attraction",
    category: "heritage",
    area: "Kalasipalyam",
    shortDescription: "Surviving Delhi Gate of Kempegowda's 16th-century mud fort, rebuilt in stone by Hyder Ali.",
    description:
      "Originally a mud fort by Kempegowda I in 1537, rebuilt in granite by Hyder Ali in 1761. The Delhi Gate and a small section of curtain wall survive. Inside, see the Ganesha temple and information panels on Tipu's last stand here in 1791.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 30,
    openTime: "08:00",
    closeTime: "18:00",
    openDays: "All",
    tags: "fort,heritage,kempegowda,free",
    latitude: "12.9624",
    longitude: "77.5743",
    popularity: 70,
  }),
  p({
    slug: "blr-vidhana-soudha",
    name: "Vidhana Soudha",
    city: BLR,
    kind: "attraction",
    category: "heritage",
    area: "Sampangi Rama Nagar",
    shortDescription: "Karnataka's neo-Dravidian state legislature — the city's signature landmark.",
    description:
      "Completed in 1956 in granite, with four-storey Dravidian-inspired domes and the iconic 'Government Work is God's Work' inscription on the porch. Best viewed at night when lit. Interior visits by special permission only.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 30,
    openTime: "00:00",
    closeTime: "23:59",
    openDays: "All",
    tags: "landmark,architecture,night-view,free",
    latitude: "12.9794",
    longitude: "77.5912",
    popularity: 92,
  }),
  p({
    slug: "blr-attara-kacheri",
    name: "Attara Kacheri (High Court)",
    city: BLR,
    kind: "attraction",
    category: "heritage",
    area: "Cubbon Park",
    shortDescription: "Cherry-red 1864 colonial high court building beside Cubbon Park.",
    description:
      "The 'eighteen offices' — a striking Greco-Roman building in vermillion red, built 1864 to house Mysore administration. Now the Karnataka High Court. Photograph from outside; no public entry to chambers.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 15,
    openTime: "00:00",
    closeTime: "23:59",
    openDays: "All",
    tags: "colonial,architecture,photography,free",
    latitude: "12.9780",
    longitude: "77.5908",
    popularity: 75,
  }),
  p({
    slug: "blr-mayo-hall",
    name: "Mayo Hall",
    city: BLR,
    kind: "attraction",
    category: "heritage",
    area: "MG Road",
    shortDescription: "Two-storey 1883 colonial hall built in memory of Viceroy Lord Mayo.",
    description:
      "A Victorian Gothic municipal hall constructed in 1883 with semi-circular arches and an elegant double staircase. Used today as a magistrate's court; occasional public events.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 15,
    openTime: "10:00",
    closeTime: "17:00",
    openDays: "Mon-Sat",
    tags: "colonial,architecture,free",
    latitude: "12.9719",
    longitude: "77.6053",
    popularity: 55,
  }),
  p({
    slug: "blr-bhoga-nandeeshwara",
    name: "Bhoga Nandeeshwara Temple",
    city: BLR,
    kind: "temple",
    category: "spiritual",
    area: "Nandi village",
    shortDescription: "9th-century Ganga-era temple complex at the base of Nandi Hills.",
    description:
      "One of the oldest temples in Karnataka, with shrines from the Ganga, Chola, Hoysala and Vijayanagara periods. The Kalyani tank and the trinity of Arunachaleshwara, Bhoga Nandeeshwara and Uma Maheshwara shrines are the highlights.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 60,
    openTime: "06:00",
    closeTime: "20:00",
    openDays: "All",
    tags: "temple,heritage,ganga,free",
    latitude: "13.3358",
    longitude: "77.6817",
    popularity: 70,
  }),

  // --- Temples ---
  p({
    slug: "blr-bull-temple",
    name: "Dodda Basavana Gudi (Bull Temple)",
    city: BLR,
    kind: "temple",
    category: "spiritual",
    area: "Basavanagudi",
    shortDescription: "Monolithic 4.6 m granite Nandi from Kempegowda's era.",
    description:
      "Built by Kempegowda I in 1537, the Bull Temple's deity is a single carved granite Nandi over 4.5 m tall and 6 m long. Visit during the annual Kadalekai Parishe (groundnut fair) in late November.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 30,
    openTime: "06:00",
    closeTime: "20:00",
    openDays: "All",
    tags: "temple,kempegowda,nandi,free",
    latitude: "12.9408",
    longitude: "77.5654",
    popularity: 90,
  }),
  p({
    slug: "blr-gavi-gangadhareshwara",
    name: "Gavi Gangadhareshwara Temple",
    city: BLR,
    kind: "temple",
    category: "spiritual",
    area: "Gavipuram",
    shortDescription: "Rock-cut cave temple where sunlight strikes the Shiva linga on Makar Sankranti.",
    description:
      "A cave temple from the 9th century. On 14 January each year, the setting sun passes between two granite pillars and lights up the inner sanctum — an astronomical alignment Kempegowda is said to have engineered.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 30,
    openTime: "07:00",
    closeTime: "20:30",
    openDays: "All",
    tags: "temple,cave,kempegowda,free,makar-sankranti",
    latitude: "12.9436",
    longitude: "77.5670",
    popularity: 80,
  }),
  p({
    slug: "blr-iskcon-rajajinagar",
    name: "ISKCON Sri Radha Krishna Temple",
    city: BLR,
    kind: "temple",
    category: "spiritual",
    area: "Rajajinagar",
    shortDescription: "Hilltop ISKCON complex with gilded shrines and a 17 m gold-plated dhwaja-stambha.",
    description:
      "A landmark complex on Hare Krishna Hill with six shrines including Krishna-Balarama, Radha-Krishna and Narasimha. Massive evening aarti, on-site Govinda's restaurant for prasadam meals. Avoid weekends if you want a quieter visit.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 90,
    openTime: "04:15",
    closeTime: "20:30",
    openDays: "All",
    tags: "temple,iskcon,vegetarian,prasadam",
    latitude: "13.0094",
    longitude: "77.5512",
    popularity: 95,
  }),
  p({
    slug: "blr-banashankari",
    name: "Banashankari Amma Temple",
    city: BLR,
    kind: "temple",
    category: "spiritual",
    area: "Banashankari",
    shortDescription: "Goddess Banashankari shrine — Friday's traditional lamp lighting is the highlight.",
    description:
      "The temple sees thousands every Friday and Tuesday for Rahukala puja, when devotees light lamps in steel bowls floating in the goddess's pool. The current structure dates to the 17th century with later additions.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 30,
    openTime: "06:00",
    closeTime: "21:00",
    openDays: "All",
    tags: "temple,goddess,friday-puja,free",
    latitude: "12.9251",
    longitude: "77.5575",
    popularity: 85,
  }),
  p({
    slug: "blr-ragigudda-anjaneya",
    name: "Ragigudda Sri Prasanna Anjaneya Swamy Temple",
    city: BLR,
    kind: "temple",
    category: "spiritual",
    area: "Jayanagar 9th Block",
    shortDescription: "Hilltop Hanuman temple with 360° views of south Bangalore.",
    description:
      "Sits atop a small hillock called Ragi Gudda. Climb the granite steps for the temple's monolithic Anjaneya idol. The surrounding park is a popular morning walking spot.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 45,
    openTime: "06:00",
    closeTime: "20:30",
    openDays: "All",
    tags: "temple,hanuman,sunset,free",
    latitude: "12.9046",
    longitude: "77.5747",
    popularity: 75,
  }),
  p({
    slug: "blr-halasuru-someshwara",
    name: "Halasuru Someshwara Temple",
    city: BLR,
    kind: "temple",
    category: "spiritual",
    area: "Halasuru (Ulsoor)",
    shortDescription: "Chola-era Shiva temple expanded by Kempegowda — gopuram and carved pillars.",
    description:
      "Dates to the Chola period (around 12th century) with major Vijayanagara-era additions. Carved pillars depict Girijakalyana and the wedding of Shiva and Parvati. A working temple at the heart of Old Ulsoor.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 30,
    openTime: "06:00",
    closeTime: "12:00",
    openDays: "All",
    tags: "temple,chola,kempegowda,heritage,free",
    latitude: "12.9794",
    longitude: "77.6210",
    popularity: 72,
  }),
  p({
    slug: "blr-dodda-ganapathi",
    name: "Sri Dodda Ganapathi Temple",
    city: BLR,
    kind: "temple",
    category: "spiritual",
    area: "Basavanagudi",
    shortDescription: "Single monolithic 5.5 m Ganesha — Bull Temple's neighbour.",
    description:
      "A 5.5 m tall Ganesha carved from a single granite block, anointed daily with 100 kg of butter on a rotation and decorated for festivals. Walk five minutes to the Bull Temple after.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 30,
    openTime: "07:00",
    closeTime: "13:00",
    openDays: "All",
    tags: "temple,ganesha,monolith,free",
    latitude: "12.9434",
    longitude: "77.5667",
    popularity: 85,
  }),
  p({
    slug: "blr-kadu-malleshwara",
    name: "Sri Kadu Malleshwara Temple",
    city: BLR,
    kind: "temple",
    category: "spiritual",
    area: "Malleshwaram",
    shortDescription: "17th-century Shiva temple that gave Malleshwaram its name.",
    description:
      "Built by Shivaji's brother Venkoji in the 17th century. The shrines of Mallikarjuna and Parvati are at the heart of Old Malleshwaram. The street market just outside is a lively stop on the way out.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 30,
    openTime: "06:00",
    closeTime: "12:30",
    openDays: "All",
    tags: "temple,malleshwaram,heritage,free",
    latitude: "13.0057",
    longitude: "77.5707",
    popularity: 70,
  }),
  p({
    slug: "blr-karya-siddhi-hanuman",
    name: "Karya Siddhi Hanuman Temple",
    city: BLR,
    kind: "temple",
    category: "spiritual",
    area: "Giri Nagar",
    shortDescription: "Sri Ganapathy Sachchidananda Ashrama's central Hanuman shrine.",
    description:
      "Built by Sri Ganapathy Sachchidananda Swamiji. The main hall holds large Hanuman, Rama and Sita idols. Free annaprasadam is served at noon. Powerful evening Hanuman Chalisa group recital.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 45,
    openTime: "06:00",
    closeTime: "20:30",
    openDays: "All",
    tags: "temple,hanuman,annadanam,free",
    latitude: "12.9442",
    longitude: "77.5421",
    popularity: 80,
  }),

  // --- Churches & Mosques ---
  p({
    slug: "blr-st-marys-basilica",
    name: "St Mary's Basilica",
    city: BLR,
    kind: "church",
    category: "spiritual",
    area: "Shivajinagar",
    shortDescription: "Bangalore's oldest church and Karnataka's only minor basilica.",
    description:
      "Built in 1882 in Gothic style. Famous for the September feast of St Mary, when the statue is carried through Shivajinagar in a candle-lit procession that draws lakhs.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 30,
    openTime: "06:00",
    closeTime: "20:00",
    openDays: "All",
    tags: "church,gothic,heritage,free",
    latitude: "12.9858",
    longitude: "77.6056",
    popularity: 78,
  }),
  p({
    slug: "blr-st-marks-cathedral",
    name: "St Mark's Cathedral",
    city: BLR,
    kind: "church",
    category: "spiritual",
    area: "MG Road",
    shortDescription: "1808 Anglican cathedral with stained-glass windows and a domed central nave.",
    description:
      "Founded in 1808 and rebuilt after the 1923 fire. The dome is modelled on St Paul's, London. Sunday services at 7, 8:30 and 10:30 are open to visitors.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 30,
    openTime: "08:00",
    closeTime: "18:00",
    openDays: "All",
    tags: "church,colonial,anglican,free",
    latitude: "12.9716",
    longitude: "77.5950",
    popularity: 72,
  }),
  p({
    slug: "blr-infant-jesus-shrine",
    name: "Infant Jesus Shrine",
    city: BLR,
    kind: "church",
    category: "spiritual",
    area: "Viveknagar",
    shortDescription: "Crowd-magnet Catholic shrine — Thursday novenas draw thousands.",
    description:
      "A modern Catholic shrine modelled on the Infant Jesus of Prague. Thursday novena masses are the major draw; tens of thousands attend. Less crowded on weekday mornings.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 30,
    openTime: "06:00",
    closeTime: "20:30",
    openDays: "All",
    tags: "church,catholic,novena,free",
    latitude: "12.9555",
    longitude: "77.6233",
    popularity: 78,
  }),
  p({
    slug: "blr-jumma-masjid",
    name: "Jumma Masjid",
    city: BLR,
    kind: "attraction",
    category: "spiritual",
    area: "OPH Road",
    shortDescription: "City's largest Friday mosque, built 1940 over an 18th-century foundation.",
    description:
      "Five-storey mosque built over a foundation that dates to Hyder Ali's reign. The white-marble facade and onion domes are a city landmark. Visitors are welcome between prayer times; modest dress required.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 30,
    openTime: "05:00",
    closeTime: "21:00",
    openDays: "All",
    tags: "mosque,heritage,architecture,free",
    latitude: "12.9784",
    longitude: "77.6058",
    popularity: 70,
  }),
  p({
    slug: "blr-gurudwara-ulsoor",
    name: "Gurudwara Sri Guru Singh Sabha (Ulsoor)",
    city: BLR,
    kind: "attraction",
    category: "spiritual",
    area: "Ulsoor",
    shortDescription: "Sikh gurudwara beside Ulsoor Lake — daily langar is open to all.",
    description:
      "The principal gurudwara of Bangalore, beside Ulsoor Lake. Daily langar is served from 12-3 and 7-9; visitors are warmly welcomed. Cover your head before entering.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 45,
    openTime: "04:00",
    closeTime: "21:00",
    openDays: "All",
    tags: "gurudwara,sikh,langar,free",
    latitude: "12.9819",
    longitude: "77.6225",
    popularity: 75,
  }),

  // --- Museums ---
  p({
    slug: "blr-vitm",
    name: "Visvesvaraya Industrial & Technological Museum",
    city: BLR,
    kind: "museum",
    category: "art",
    area: "Kasturba Road",
    shortDescription: "Hands-on science museum with the BTM Boeing 737 cockpit and Wright Brothers exhibits.",
    description:
      "Run by the National Council of Science Museums. Highlights include the Wright Brothers gallery, BIOTECH revolution, Engine Hall and a real Boeing 737 cockpit. Great with kids.",
    entryFeePerPerson: 95,
    idealMinutesAtPlace: 150,
    openTime: "09:30",
    closeTime: "18:00",
    openDays: "All",
    tags: "museum,science,kids,hands-on",
    latitude: "12.9763",
    longitude: "77.5949",
    popularity: 88,
  }),
  p({
    slug: "blr-hal-aerospace",
    name: "HAL Heritage Centre & Aerospace Museum",
    city: BLR,
    kind: "museum",
    category: "art",
    area: "HAL Old Airport Road",
    shortDescription: "India's first aerospace museum — vintage HAL aircraft, simulators, mock ATC.",
    description:
      "Run by Hindustan Aeronautics Limited. The outdoor lot has decommissioned MiGs, Marut, Kiran and the LCA Tejas demonstrator; indoors, flight simulators and an interactive mock ATC tower.",
    entryFeePerPerson: 50,
    idealMinutesAtPlace: 120,
    openTime: "09:00",
    closeTime: "17:00",
    openDays: "All",
    tags: "museum,aviation,aircraft,kids",
    latitude: "12.9618",
    longitude: "77.6671",
    popularity: 82,
  }),
  p({
    slug: "blr-ngma",
    name: "National Gallery of Modern Art",
    city: BLR,
    kind: "museum",
    category: "art",
    area: "Manikyavelu Mansion, Palace Road",
    shortDescription: "Modernist Indian art in a restored 1900s heritage mansion.",
    description:
      "Three floors of works by Raja Ravi Varma, Amrita Sher-Gil, Tagore, Husain, K K Hebbar and contemporary South Indian artists. The 1900s Manikyavelu mansion itself is half the appeal.",
    entryFeePerPerson: 20,
    idealMinutesAtPlace: 90,
    openTime: "10:00",
    closeTime: "17:00",
    openDays: "Tue-Sun",
    tags: "museum,art,heritage,modern",
    latitude: "12.9907",
    longitude: "77.5868",
    popularity: 78,
  }),
  p({
    slug: "blr-nimhans-brain-museum",
    name: "NIMHANS Brain Museum",
    city: BLR,
    kind: "museum",
    category: "art",
    area: "NIMHANS, Hosur Road",
    shortDescription: "Real human brain specimens with curator-led explanations of how things go wrong.",
    description:
      "On the NIMHANS campus. Visitors handle actual preserved brains while a neuroscientist explains stroke, dementia, tumors and trauma. Saturday-only and free; arrive 30 min early.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 90,
    openTime: "10:00",
    closeTime: "13:00",
    openDays: "Sat",
    tags: "museum,medical,free,neuro,unique",
    latitude: "12.9437",
    longitude: "77.5963",
    popularity: 86,
  }),
  p({
    slug: "blr-nehru-planetarium",
    name: "Jawaharlal Nehru Planetarium",
    city: BLR,
    kind: "museum",
    category: "art",
    area: "Sri T Chowdaiah Road",
    shortDescription: "45-minute sky shows under a 15 m hemisphere — alternate Eng/Kannada.",
    description:
      "Multiple shows daily. The Sky Theatre programmes change every few months. The Science Park outside has interactive exhibits and a sundial. Book online to skip the queue.",
    entryFeePerPerson: 100,
    idealMinutesAtPlace: 75,
    openTime: "10:30",
    closeTime: "17:30",
    openDays: "Tue-Sun",
    tags: "planetarium,kids,science,show",
    latitude: "12.9852",
    longitude: "77.5879",
    popularity: 82,
  }),
  p({
    slug: "blr-government-museum",
    name: "Government Museum",
    city: BLR,
    kind: "museum",
    category: "art",
    area: "Kasturba Road",
    shortDescription: "1865 museum with Hoysala stone sculpture, Harappan finds and Mysore paintings.",
    description:
      "One of India's oldest museums. Eighteen galleries including Hoysala temple sculpture from Halebid, Harappan artefacts and Mysore-style paintings on canvas and palm-leaf.",
    entryFeePerPerson: 20,
    idealMinutesAtPlace: 75,
    openTime: "10:00",
    closeTime: "17:00",
    openDays: "Tue-Sun",
    tags: "museum,history,sculpture,heritage",
    latitude: "12.9742",
    longitude: "77.5985",
    popularity: 70,
  }),
  p({
    slug: "blr-ime",
    name: "Indian Music Experience Museum",
    city: BLR,
    kind: "museum",
    category: "art",
    area: "JP Nagar 7th Phase",
    shortDescription: "Interactive music museum — Hindustani, Carnatic, film, folk, electronic.",
    description:
      "India's first interactive music museum, with the Sound Garden, instrument galleries, the Carnatic and Hindustani halls, and a film-music studio. Book a 90-minute slot online.",
    entryFeePerPerson: 250,
    idealMinutesAtPlace: 120,
    openTime: "10:00",
    closeTime: "18:30",
    openDays: "Tue-Sun",
    tags: "museum,music,interactive,kids",
    latitude: "12.8804",
    longitude: "77.6038",
    popularity: 80,
  }),
  p({
    slug: "blr-chitrakala-parishath",
    name: "Karnataka Chitrakala Parishath",
    city: BLR,
    kind: "museum",
    category: "art",
    area: "Kumara Park East",
    shortDescription: "Sprawling art college campus with rotating exhibitions across 18 galleries.",
    description:
      "Karnataka's largest art institution. Permanent collections of Mysore-Tanjore, Russian, leather puppet and Roerich art. The campus also hosts the annual Chitra Santhe art fair on the first Sunday of January.",
    entryFeePerPerson: 20,
    idealMinutesAtPlace: 90,
    openTime: "10:00",
    closeTime: "17:30",
    openDays: "All",
    tags: "museum,art,chitra-santhe",
    latitude: "13.0007",
    longitude: "77.5808",
    popularity: 72,
  }),

  // --- Parks ---
  p({
    slug: "blr-lalbagh",
    name: "Lalbagh Botanical Garden",
    city: BLR,
    kind: "park",
    category: "nature",
    area: "Mavalli",
    shortDescription: "240-acre 18th-century garden with the glass house, Kempegowda tower and a 3000-year-old rock.",
    description:
      "Started by Hyder Ali in 1760 and expanded by Tipu Sultan. The Glass House (modelled on London's Crystal Palace) hosts biannual flower shows in January and August. The Kempegowda watchtower sits on a 3000-million-year-old Peninsular Gneiss outcrop.",
    entryFeePerPerson: 50,
    idealMinutesAtPlace: 120,
    openTime: "06:00",
    closeTime: "19:00",
    openDays: "All",
    tags: "park,botanical,heritage,morning-walk",
    latitude: "12.9507",
    longitude: "77.5848",
    popularity: 95,
  }),
  p({
    slug: "blr-cubbon-park",
    name: "Cubbon Park (Sri Chamarajendra Park)",
    city: BLR,
    kind: "park",
    category: "nature",
    area: "Central Bangalore",
    shortDescription: "300-acre lung of central Bangalore — bamboo grove, bandstand, statue of Queen Victoria.",
    description:
      "Designed in 1870, the park ribbons through the city centre between Vidhana Soudha and the High Court. The Sunday vehicle-free morning is a local institution — joggers, skaters and book-clubs take over the avenues.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 90,
    openTime: "06:00",
    closeTime: "20:00",
    openDays: "All",
    tags: "park,morning-walk,sunday-cycling,free",
    latitude: "12.9763",
    longitude: "77.5929",
    popularity: 96,
  }),
  p({
    slug: "blr-jp-park",
    name: "JP Park (Jayaprakash Narayan Biodiversity Park)",
    city: BLR,
    kind: "park",
    category: "nature",
    area: "Mathikere",
    shortDescription: "85-acre rolling park with three lakes and a children's adventure trail.",
    description:
      "Three lakes, an island, a 25 m tower viewpoint, paddle boats and a long jogging track. Less crowded than Lalbagh; bring a picnic.",
    entryFeePerPerson: 30,
    idealMinutesAtPlace: 90,
    openTime: "06:00",
    closeTime: "19:00",
    openDays: "All",
    tags: "park,lake,boating,family",
    latitude: "13.0418",
    longitude: "77.5564",
    popularity: 78,
  }),
  p({
    slug: "blr-freedom-park",
    name: "Freedom Park",
    city: BLR,
    kind: "park",
    category: "nature",
    area: "Gandhinagar",
    shortDescription: "Restored Central Jail, now an open public square for protests, art and music.",
    description:
      "Bengaluru's central jail (1866) was converted into a park in 2008. Original watchtowers, the warden's office and a section of the cell block survive as installations. Hosts Sunday flea markets, music gigs and political rallies.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 45,
    openTime: "07:00",
    closeTime: "20:00",
    openDays: "All",
    tags: "park,heritage,public-space,free",
    latitude: "12.9799",
    longitude: "77.5854",
    popularity: 72,
  }),
  p({
    slug: "blr-bugle-rock",
    name: "Bugle Rock Park",
    city: BLR,
    kind: "park",
    category: "nature",
    area: "Basavanagudi",
    shortDescription: "3000-million-year-old granite outcrop where Kempegowda's lookouts blew the warning bugle.",
    description:
      "The 'bugle rock' is a Peninsular Gneiss outcrop — one of the planet's oldest rocks. Watchmen once blew bugles from here to warn of approaching enemies. Adjoining the Bull Temple, with a free observatory tower at the top.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 30,
    openTime: "06:00",
    closeTime: "20:00",
    openDays: "All",
    tags: "park,geology,kempegowda,free,sunset",
    latitude: "12.9410",
    longitude: "77.5664",
    popularity: 74,
  }),
  p({
    slug: "blr-sankey-tank",
    name: "Sankey Tank",
    city: BLR,
    kind: "lake",
    category: "nature",
    area: "Sadashivanagar / Malleshwaram",
    shortDescription: "Tree-lined reservoir with a 3 km walking loop and weekend boating.",
    description:
      "Commissioned in 1882. A favourite morning walk for the Malleshwaram and Sadashivanagar crowd. Paddle and rowing boats from the boat house on the eastern shore.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 60,
    openTime: "05:30",
    closeTime: "20:00",
    openDays: "All",
    tags: "lake,walk,boating,free",
    latitude: "13.0067",
    longitude: "77.5705",
    popularity: 80,
  }),
  p({
    slug: "blr-lumbini-gardens",
    name: "Lumbini Gardens",
    city: BLR,
    kind: "park",
    category: "nature",
    area: "Nagawara",
    shortDescription: "Lakeside park with boating, a small water park and an artificial sandy beach.",
    description:
      "Sits on the Nagawara lake. Pedal boats, motor boats, a children's water park and a fake sandy beach. Best for families with small kids.",
    entryFeePerPerson: 40,
    idealMinutesAtPlace: 120,
    openTime: "10:00",
    closeTime: "20:00",
    openDays: "All",
    tags: "park,lake,boating,family",
    latitude: "13.0594",
    longitude: "77.6047",
    popularity: 70,
  }),
  p({
    slug: "blr-mn-krishna-rao-park",
    name: "MN Krishna Rao Park",
    city: BLR,
    kind: "park",
    category: "nature",
    area: "Basavanagudi",
    shortDescription: "Old-Bangalore neighbourhood park beloved for early-morning yoga and laughter clubs.",
    description:
      "A leafy 5-acre park surrounded by 1920s-era bungalows. Walking track, kids' play area, an outdoor stage that hosts neighbourhood plays.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 30,
    openTime: "05:00",
    closeTime: "21:00",
    openDays: "All",
    tags: "park,morning-walk,free",
    latitude: "12.9419",
    longitude: "77.5790",
    popularity: 60,
  }),
  p({
    slug: "blr-turahalli-forest",
    name: "Turahalli Forest",
    city: BLR,
    kind: "park",
    category: "nature",
    area: "South Bangalore (Kanakapura Road)",
    shortDescription: "City's last remaining minor reserve forest — short MTB and rock-scrambling trails.",
    description:
      "About 600 acres of dry deciduous scrub on a low rocky hill. Mountain-bikers and weekend trekkers love it; carry water and don't go alone after dark.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 90,
    openTime: "06:00",
    closeTime: "18:00",
    openDays: "All",
    tags: "forest,trek,mtb,nature,free",
    latitude: "12.8769",
    longitude: "77.5402",
    popularity: 68,
  }),

  // --- Lakes ---
  p({
    slug: "blr-ulsoor-lake",
    name: "Ulsoor Lake",
    city: BLR,
    kind: "lake",
    category: "nature",
    area: "Halasuru",
    shortDescription: "Kempegowda-era lake near MG Road with rowing club and pedal boats.",
    description:
      "A 50-hectare lake constructed under Kempegowda II. The boating section is run by the Karnataka Rowing Association. The southern bank is a popular evening promenade.",
    entryFeePerPerson: 10,
    idealMinutesAtPlace: 60,
    openTime: "06:00",
    closeTime: "18:00",
    openDays: "All",
    tags: "lake,boating,kempegowda,central",
    latitude: "12.9817",
    longitude: "77.6175",
    popularity: 84,
  }),
  p({
    slug: "blr-madiwala-lake",
    name: "Madiwala Lake",
    city: BLR,
    kind: "lake",
    category: "nature",
    area: "BTM Layout",
    shortDescription: "120-hectare lake popular for birdwatching and weekend boat rides.",
    description:
      "South Bangalore's largest urban lake. Pelican, painted stork and spot-billed pelican are common sightings between October and February. Walk the western bund at sunrise.",
    entryFeePerPerson: 10,
    idealMinutesAtPlace: 60,
    openTime: "06:00",
    closeTime: "18:00",
    openDays: "All",
    tags: "lake,birds,boating",
    latitude: "12.9223",
    longitude: "77.6203",
    popularity: 78,
  }),
  p({
    slug: "blr-hebbal-lake",
    name: "Hebbal Lake",
    city: BLR,
    kind: "lake",
    category: "nature",
    area: "Hebbal",
    shortDescription: "North-Bangalore lake with a 4 km boardwalk and rare flamingo sightings.",
    description:
      "Commissioned by Kempegowda. The recent restoration added an island, a walking loop and gazebos. Migratory birds (gadwall, garganey, occasional flamingo) winter here.",
    entryFeePerPerson: 30,
    idealMinutesAtPlace: 75,
    openTime: "06:00",
    closeTime: "18:00",
    openDays: "All",
    tags: "lake,birds,kempegowda,walk",
    latitude: "13.0476",
    longitude: "77.5928",
    popularity: 76,
  }),
  p({
    slug: "blr-kaikondrahalli-lake",
    name: "Kaikondrahalli Lake",
    city: BLR,
    kind: "lake",
    category: "nature",
    area: "Sarjapur Road",
    shortDescription: "Citizen-restored lake on Sarjapur — picnic lawns, birdwatching gazebos.",
    description:
      "A model citizen-restoration project from 2010. The walking loop, picnic mounds and three viewing gazebos make it a Sarjapur weekend favourite. Carry binoculars in winter.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 60,
    openTime: "06:00",
    closeTime: "19:00",
    openDays: "All",
    tags: "lake,birds,picnic,free",
    latitude: "12.9079",
    longitude: "77.6878",
    popularity: 70,
  }),

  // --- Amusement ---
  p({
    slug: "blr-wonderla",
    name: "Wonderla Bangalore",
    city: BLR,
    kind: "attraction",
    category: "nature",
    area: "Bidadi (Mysore highway)",
    shortDescription: "60+ rides amusement & water park — the city's biggest day-out.",
    description:
      "Includes high-thrill rides (Recoil, Insanity), water rides (Lazy River, Vertical Fall) and a kids' zone. Open from 11; arrive at opening to ride the popular ones first. Lockers and rental swimwear on site. The ₹1,499 figure is the standard adult ticket; children (86-140 cm) pay a lower rate around ₹1,175-1,275, and booking a few days ahead online usually unlocks a discount over the gate price.",
    entryFeePerPerson: 1499,
    idealMinutesAtPlace: 480,
    openTime: "11:00",
    closeTime: "18:00",
    openDays: "All",
    tags: "amusement,water-park,family,thrill",
    latitude: "12.8434",
    longitude: "77.4338",
    popularity: 92,
  }),
  p({
    slug: "blr-snow-city",
    name: "Snow City",
    city: BLR,
    kind: "attraction",
    category: "nature",
    area: "JC Nagar",
    shortDescription: "Indoor sub-zero snow park kept at -5 °C — sledding, snow play, an ice slide.",
    description:
      "A 12,000 sq ft indoor snow chamber at JC Nagar. Snow jackets and boots provided. Combine with Fun World next door for a full day.",
    entryFeePerPerson: 500,
    idealMinutesAtPlace: 90,
    openTime: "10:00",
    closeTime: "21:00",
    openDays: "All",
    tags: "amusement,snow,indoor,kids",
    latitude: "13.0233",
    longitude: "77.5944",
    popularity: 78,
  }),
  p({
    slug: "blr-innovative-film-city",
    name: "Innovative Film City",
    city: BLR,
    kind: "attraction",
    category: "nature",
    area: "Bidadi",
    shortDescription: "South India's only film-themed amusement park — sets, museums, rides.",
    description:
      "A 58-acre film park with a wax museum, dinosaur park, haunted mansion, miniature city, cartoon city and a working film set you can tour. The ticket covers all 25+ attractions.",
    entryFeePerPerson: 999,
    idealMinutesAtPlace: 360,
    openTime: "10:00",
    closeTime: "18:00",
    openDays: "All",
    tags: "amusement,film,family,kids",
    latitude: "12.7975",
    longitude: "77.3849",
    popularity: 78,
  }),

  // --- Food Streets ---
  p({
    slug: "blr-vv-puram-food-street",
    name: "VV Puram Food Street (Thindi Beedi)",
    city: BLR,
    kind: "market",
    category: "food",
    area: "VV Puram",
    shortDescription: "One street, 60+ stalls — open evenings, Bengaluru's vegetarian street-food temple.",
    description:
      "Operates only in the evening on Sajjan Rao Circle. Iconic dishes: holige, akki rotti, paddu, cheese masala dosa, gobi manchurian. Cash preferred; come hungry.",
    entryFeePerPerson: 0,
    avgCostForTwo: 400,
    idealMinutesAtPlace: 90,
    openTime: "18:00",
    closeTime: "23:30",
    openDays: "All",
    tags: "food-street,veg,evening,iconic,free-entry",
    latitude: "12.9560",
    longitude: "77.5709",
    popularity: 96,
  }),
  p({
    slug: "blr-mosque-road",
    name: "Mosque Road (Frazer Town)",
    city: BLR,
    kind: "market",
    category: "food",
    area: "Frazer Town",
    shortDescription: "Kebab boulevard — peaks during Ramadan with iftar pavement stalls.",
    description:
      "Albert Bakery for sheermal, Empire for kebabs, Hyderabad Biryaani for kachi-style biryani, Hilal Restaurant for paya. Best from 18:00 onwards; Ramadan nights are legendary.",
    entryFeePerPerson: 0,
    avgCostForTwo: 600,
    idealMinutesAtPlace: 90,
    openTime: "11:00",
    closeTime: "23:30",
    openDays: "All",
    tags: "food-street,non-veg,kebabs,ramadan",
    latitude: "13.0024",
    longitude: "77.6118",
    popularity: 92,
  }),
  p({
    slug: "blr-gandhi-bazaar",
    name: "Gandhi Bazaar",
    city: BLR,
    kind: "market",
    category: "food",
    area: "Basavanagudi",
    shortDescription: "Flower market by day, evening Vidyarthi Bhavan dosa queue — old Bangalore at its purest.",
    description:
      "A flower, fruit and snack street in old Basavanagudi. Combine with Vidyarthi Bhavan (benne masala dosa), Subbamma Stores, and the Bull Temple a few minutes away.",
    entryFeePerPerson: 0,
    avgCostForTwo: 300,
    idealMinutesAtPlace: 60,
    openTime: "06:00",
    closeTime: "22:00",
    openDays: "All",
    tags: "market,flowers,food,old-bangalore,free",
    latitude: "12.9418",
    longitude: "77.5683",
    popularity: 86,
  }),
  p({
    slug: "blr-kr-market",
    name: "Krishna Rajendra Market (KR Market)",
    city: BLR,
    kind: "market",
    category: "shopping",
    area: "KR Market",
    shortDescription: "Asia's largest flower market — best between 4 and 6 am.",
    description:
      "Around the 1928 KR Market building. Roses, jasmine, marigold, lotus by the lorry-load. The morning wholesale rush, the flower auctions and the surrounding bazaar make it Bangalore's most photographic spot.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 60,
    openTime: "04:00",
    closeTime: "20:00",
    openDays: "All",
    tags: "market,flowers,photography,early-morning,free",
    latitude: "12.9620",
    longitude: "77.5764",
    popularity: 88,
  }),
  p({
    slug: "blr-russell-market",
    name: "Russell Market",
    city: BLR,
    kind: "market",
    category: "shopping",
    area: "Shivajinagar",
    shortDescription: "1927 covered market — fresh seafood, beef, cheese, exotic vegetables.",
    description:
      "A British-era covered market still going strong. Aisles dedicated to flowers, fish, mutton, butchered chicken, exotic veg and fruit. Mosque Road is a 5-minute walk for the post-shop meal.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 45,
    openTime: "06:00",
    closeTime: "20:00",
    openDays: "Mon-Sat",
    tags: "market,meat,fish,heritage,free",
    latitude: "12.9831",
    longitude: "77.6044",
    popularity: 82,
  }),

  // --- Restaurants ---
  p({
    slug: "blr-mtr-lalbagh",
    name: "Mavalli Tiffin Room (MTR)",
    city: BLR,
    kind: "restaurant",
    category: "food",
    area: "Lalbagh Road",
    shortDescription: "Since 1924 — rava idli, filter coffee, the iconic Bombay-style chandrahara.",
    description:
      "Bangalore's most famous breakfast institution. No phone bookings — the queue starts forming by 7. Order the breakfast set (idli + vada + chow chow bath) and end with filter coffee.",
    entryFeePerPerson: 0,
    avgCostForTwo: 400,
    idealMinutesAtPlace: 60,
    openTime: "06:30",
    closeTime: "21:00",
    openDays: "Tue-Sun",
    tags: "restaurant,veg,iconic,breakfast,filter-coffee",
    latitude: "12.9509",
    longitude: "77.5847",
    popularity: 95,
  }),
  p({
    slug: "blr-vidyarthi-bhavan",
    name: "Vidyarthi Bhavan",
    city: BLR,
    kind: "restaurant",
    category: "food",
    area: "Gandhi Bazaar",
    shortDescription: "Benne masala dosa to a queue that never ends — since 1943.",
    description:
      "Famous for its butter-soaked masala dosa. Shared tables, hectic service, cash only. The walls are lined with caricatures of regulars. Closed Wednesdays.",
    entryFeePerPerson: 0,
    avgCostForTwo: 250,
    idealMinutesAtPlace: 45,
    openTime: "06:30",
    closeTime: "11:30",
    openDays: "Thu-Tue",
    tags: "restaurant,veg,dosa,iconic,cash-only",
    latitude: "12.9418",
    longitude: "77.5694",
    popularity: 93,
  }),
  p({
    slug: "blr-ctr-shri-sagar",
    name: "Central Tiffin Room (Shri Sagar)",
    city: BLR,
    kind: "restaurant",
    category: "food",
    area: "Malleshwaram 7th Cross",
    shortDescription: "Crisp benne dosa rival to Vidyarthi Bhavan — and most locals will pick this side.",
    description:
      "The Malleshwaram favourite for benne dosa, idli-vada and khali dosa. Coffee is excellent. Tight seating, fast turnover — expect a 20-30 min weekend wait.",
    entryFeePerPerson: 0,
    avgCostForTwo: 300,
    idealMinutesAtPlace: 45,
    openTime: "07:00",
    closeTime: "12:30",
    openDays: "All",
    tags: "restaurant,veg,dosa,iconic",
    latitude: "13.0078",
    longitude: "77.5715",
    popularity: 91,
  }),
  p({
    slug: "blr-koshys",
    name: "Koshy's",
    city: BLR,
    kind: "restaurant",
    category: "food",
    area: "St Mark's Road",
    shortDescription: "1940 colonial-cafe institution — mulligatawny soup, plus authors and politicians.",
    description:
      "An all-day cafe with two halves: family side and the more atmospheric Jewel Box bar. Old-school Anglo-Indian dishes, English breakfasts, fish and chips. Wood-panelled walls and ceiling fans, no music.",
    entryFeePerPerson: 0,
    avgCostForTwo: 900,
    idealMinutesAtPlace: 75,
    openTime: "09:00",
    closeTime: "23:00",
    openDays: "All",
    tags: "restaurant,non-veg,colonial,iconic,bar",
    latitude: "12.9728",
    longitude: "77.5959",
    popularity: 89,
  }),
  p({
    slug: "blr-nagarjuna-residency",
    name: "Nagarjuna Residency Road",
    city: BLR,
    kind: "restaurant",
    category: "food",
    area: "Residency Road",
    shortDescription: "Banana-leaf Andhra meals served family-style — biryani, gongura mutton, ragi sankati.",
    description:
      "Lunchtime queues spill out the door. Order the Andhra meal: rice, four curries, sambar, rasam, papad, pickle, ghee. Mutton biryani is the famous evening order.",
    entryFeePerPerson: 0,
    avgCostForTwo: 700,
    idealMinutesAtPlace: 60,
    openTime: "11:30",
    closeTime: "23:00",
    openDays: "All",
    tags: "restaurant,non-veg,andhra,biryani",
    latitude: "12.9716",
    longitude: "77.6018",
    popularity: 90,
  }),
  p({
    slug: "blr-brahmins-coffee-bar",
    name: "Brahmin's Coffee Bar",
    city: BLR,
    kind: "restaurant",
    category: "food",
    area: "Shankarapuram",
    shortDescription: "Idli, vada, kesari bath and filter coffee — three items, one cult following.",
    description:
      "Tiny standing-only counter. Idli arrives wrapped in banana leaf with coconut chutney; kesari bath is the must-add. Cash only; mornings only.",
    entryFeePerPerson: 0,
    avgCostForTwo: 150,
    idealMinutesAtPlace: 30,
    openTime: "06:30",
    closeTime: "11:30",
    openDays: "All",
    tags: "restaurant,veg,iconic,breakfast,cash-only",
    latitude: "12.9446",
    longitude: "77.5654",
    popularity: 88,
  }),
  p({
    slug: "blr-corner-house-lavelle",
    name: "Corner House Lavelle Road",
    city: BLR,
    kind: "restaurant",
    category: "food",
    area: "Lavelle Road",
    shortDescription: "Death by Chocolate — a Bengaluru rite of passage since 1982.",
    description:
      "The founding outlet of Corner House. The 'Death by Chocolate' (DBC) is brownie + ice-cream + chocolate sauce + nuts. Cold-coffee floats and hot caramel sundae are the runner-ups.",
    entryFeePerPerson: 0,
    avgCostForTwo: 500,
    idealMinutesAtPlace: 45,
    openTime: "11:00",
    closeTime: "23:30",
    openDays: "All",
    tags: "restaurant,dessert,ice-cream,iconic",
    latitude: "12.9716",
    longitude: "77.5972",
    popularity: 92,
  }),
  p({
    slug: "blr-meghana-residency",
    name: "Meghana Foods Residency Road",
    city: BLR,
    kind: "restaurant",
    category: "food",
    area: "Residency Road",
    shortDescription: "Andhra-style boneless chicken biryani — the Bangalore default-order.",
    description:
      "The chain's flagship. Boneless chicken biryani is the bestseller; gongura chicken and ulli karam are the side picks. Pure-veg branches also exist.",
    entryFeePerPerson: 0,
    avgCostForTwo: 800,
    idealMinutesAtPlace: 60,
    openTime: "11:30",
    closeTime: "23:30",
    openDays: "All",
    tags: "restaurant,non-veg,andhra,biryani",
    latitude: "12.9700",
    longitude: "77.6020",
    popularity: 94,
  }),
  p({
    slug: "blr-truffles-koramangala",
    name: "Truffles Koramangala",
    city: BLR,
    kind: "restaurant",
    category: "food",
    area: "Koramangala 7th Block",
    shortDescription: "Burgers, shakes, all-day breakfast — Bengaluru's grown-up diner.",
    description:
      "The bestseller is the Cheese Lover beef-or-mutton burger. Sticky-date pudding, banoffee shake and the chicken steak are the regulars' orders. Long evening waits.",
    entryFeePerPerson: 0,
    avgCostForTwo: 1000,
    idealMinutesAtPlace: 75,
    openTime: "11:30",
    closeTime: "23:00",
    openDays: "All",
    tags: "restaurant,burgers,non-veg,diner",
    latitude: "12.9356",
    longitude: "77.6249",
    popularity: 90,
  }),
  p({
    slug: "blr-karavalli",
    name: "Karavalli",
    city: BLR,
    kind: "restaurant",
    category: "food",
    area: "Vivanta by Taj, Residency Road",
    shortDescription: "Award-winning west-coast Indian cooking — Mangalorean, Goan, Kerala.",
    description:
      "Frequently ranked among India's best restaurants. The 'Karavalli specials' tasting includes meen pollichathu, prawn balchao, kori roti, neer dosa. Open-air seating in a heritage garden.",
    entryFeePerPerson: 0,
    avgCostForTwo: 5000,
    idealMinutesAtPlace: 120,
    openTime: "12:30",
    closeTime: "23:00",
    openDays: "All",
    tags: "restaurant,fine-dining,coastal,iconic",
    latitude: "12.9676",
    longitude: "77.6033",
    popularity: 90,
  }),

  // --- Microbreweries / Nightlife ---
  p({
    slug: "blr-toit-indiranagar",
    name: "Toit Brewpub",
    city: BLR,
    kind: "nightlife",
    category: "nightlife",
    area: "Indiranagar 100 Feet Road",
    shortDescription: "India's first big microbrewery — wood-fired pizzas and 9 house beers.",
    description:
      "Opened 2010 and still the default Bangalore brewpub. Toit Red, Tintin Toit and Basmati Blonde are the regulars; rotating seasonals. Wood-fired pizza, pulled-pork sandwiches, sticky chicken wings. No reservations — queue from 19:00.",
    entryFeePerPerson: 0,
    avgCostForTwo: 2200,
    idealMinutesAtPlace: 150,
    openTime: "11:30",
    closeTime: "23:30",
    openDays: "All",
    tags: "nightlife,brewpub,pizza,non-veg",
    latitude: "12.9783",
    longitude: "77.6408",
    popularity: 95,
  }),
  p({
    slug: "blr-windmills-craftworks",
    name: "Windmills Craftworks",
    city: BLR,
    kind: "nightlife",
    category: "nightlife",
    area: "Whitefield",
    shortDescription: "Brewery + jazz theatre + book bar — Whitefield's most polished night out.",
    description:
      "A two-storey microbrewery with a separate Jazz Theatre upstairs. Live jazz Thu-Sat, comedy nights, an 8000-book library bar. Ten beers on tap; pan-Asian and modern Indian kitchen.",
    entryFeePerPerson: 0,
    avgCostForTwo: 2500,
    idealMinutesAtPlace: 150,
    openTime: "12:00",
    closeTime: "23:30",
    openDays: "All",
    tags: "nightlife,brewpub,jazz,books",
    latitude: "12.9707",
    longitude: "77.7079",
    popularity: 88,
  }),
  p({
    slug: "blr-byg-brewski-hennur",
    name: "Byg Brewski Hennur",
    city: BLR,
    kind: "nightlife",
    category: "nightlife",
    area: "Hennur",
    shortDescription: "60,000 sq ft open-air microbrewery — India's largest, with multiple bars.",
    description:
      "Sprawling outdoor brewpub with three bars, a pond, an indoor lounge and live music nightly. Twelve beers on tap. Best Thursday-Sunday. Long waits on weekends.",
    entryFeePerPerson: 0,
    avgCostForTwo: 2000,
    idealMinutesAtPlace: 180,
    openTime: "12:00",
    closeTime: "23:30",
    openDays: "All",
    tags: "nightlife,brewpub,outdoor,live-music",
    latitude: "13.0540",
    longitude: "77.6553",
    popularity: 90,
  }),
  p({
    slug: "blr-pecos",
    name: "Pecos",
    city: BLR,
    kind: "nightlife",
    category: "nightlife",
    area: "Brigade Road",
    shortDescription: "Since 1989 — three floors of rock-music dive bar; cheap beer, no chairs upstairs.",
    description:
      "Bengaluru's longest-running rock pub. Old vinyl covers on the walls, photos of Floyd, Zeppelin, the Doors. Cash, beer and butter chicken; that's the menu. Smoking deck upstairs.",
    entryFeePerPerson: 0,
    avgCostForTwo: 1200,
    idealMinutesAtPlace: 120,
    openTime: "11:00",
    closeTime: "23:00",
    openDays: "All",
    tags: "nightlife,dive-bar,rock-music,iconic",
    latitude: "12.9716",
    longitude: "77.6049",
    popularity: 85,
  }),
  p({
    slug: "blr-the-biere-club",
    name: "The Biere Club",
    city: BLR,
    kind: "nightlife",
    category: "nightlife",
    area: "Vittal Mallya Road",
    shortDescription: "India's first microbrewery (2011) — minimalist, central, four house lagers.",
    description:
      "Quiet, polished microbrewery on Vittal Mallya. Belgian Witbier, German Hefeweizen, Stout, Lager. Better for a sit-down dinner than a loud night.",
    entryFeePerPerson: 0,
    avgCostForTwo: 2200,
    idealMinutesAtPlace: 150,
    openTime: "12:00",
    closeTime: "23:30",
    openDays: "All",
    tags: "nightlife,brewpub,quiet,european",
    latitude: "12.9716",
    longitude: "77.5956",
    popularity: 82,
  }),
  p({
    slug: "blr-prost-koramangala",
    name: "Prost Brewpub Koramangala",
    city: BLR,
    kind: "nightlife",
    category: "nightlife",
    area: "Koramangala 5th Block",
    shortDescription: "Three-storey open-deck brewpub — Hefeweizen and live cricket on the wall.",
    description:
      "House Hefeweizen, Belgian Tripel, Stout. Sports nights pull a crowd; the rooftop deck fills first. Wood-fired pizzas, German sausages, butter-chicken pasta.",
    entryFeePerPerson: 0,
    avgCostForTwo: 2000,
    idealMinutesAtPlace: 150,
    openTime: "12:00",
    closeTime: "23:30",
    openDays: "All",
    tags: "nightlife,brewpub,rooftop,sports",
    latitude: "12.9356",
    longitude: "77.6243",
    popularity: 84,
  }),

  // --- Malls ---
  p({
    slug: "blr-phoenix-mall-of-asia",
    name: "Phoenix Mall of Asia",
    city: BLR,
    kind: "mall",
    category: "shopping",
    area: "Byatarayanapura",
    shortDescription: "1.4 million sq ft — Bangalore's largest mall, opened 2023.",
    description:
      "Has the city's biggest H&M, a 14-screen PVR ICON, a Lulu Hypermarket and a 22,000 sq ft food court. Skylight atrium with rotating art installations.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 180,
    openTime: "11:00",
    closeTime: "23:00",
    openDays: "All",
    tags: "mall,shopping,movies,food-court,family",
    latitude: "13.0626",
    longitude: "77.5907",
    popularity: 92,
  }),
  p({
    slug: "blr-phoenix-marketcity",
    name: "Phoenix Marketcity Whitefield",
    city: BLR,
    kind: "mall",
    category: "shopping",
    area: "Mahadevapura",
    shortDescription: "1.1 million sq ft mall with a 7-screen PVR and the Phoenix outdoor street.",
    description:
      "East Bangalore's flagship. The outdoor Restaurant Street has Toscano, Smoke House Deli, Punjab Grill. Big-box anchors include Marks & Spencer, Lifestyle, Pantaloons.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 180,
    openTime: "11:00",
    closeTime: "23:00",
    openDays: "All",
    tags: "mall,shopping,family,movies",
    latitude: "12.9959",
    longitude: "77.6967",
    popularity: 90,
  }),
  p({
    slug: "blr-ub-city",
    name: "UB City",
    city: BLR,
    kind: "mall",
    category: "shopping",
    area: "Vittal Mallya Road",
    shortDescription: "Bangalore's first luxury mall — Louis Vuitton, Burberry, Skyye lounge.",
    description:
      "A four-tower commercial complex with India's first Louis Vuitton store, Rolex, Canali, Burberry. The 4th-floor restaurant strip has Toscano, Skyye, Sancho's, Toit's Biere Club.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 120,
    openTime: "11:00",
    closeTime: "23:30",
    openDays: "All",
    tags: "mall,luxury,fine-dining,rooftop",
    latitude: "12.9716",
    longitude: "77.5960",
    popularity: 90,
  }),
  p({
    slug: "blr-orion-mall",
    name: "Orion Mall",
    city: BLR,
    kind: "mall",
    category: "shopping",
    area: "Rajajinagar",
    shortDescription: "West-Bangalore's biggest mall — 200+ stores, the GoSports trampoline park.",
    description:
      "Sits next to the World Trade Center. PVR Director's Cut, Hamleys, Marks & Spencer, Lifestyle. Reasonable food court plus full-service restaurants on the third floor.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 180,
    openTime: "11:00",
    closeTime: "23:00",
    openDays: "All",
    tags: "mall,shopping,family,food-court",
    latitude: "13.0145",
    longitude: "77.5547",
    popularity: 88,
  }),
  p({
    slug: "blr-mantri-square",
    name: "Mantri Square Mall",
    city: BLR,
    kind: "mall",
    category: "shopping",
    area: "Malleshwaram",
    shortDescription: "Central-Bangalore landmark mall, directly on the Sampige Road metro.",
    description:
      "Connected to Sampige Road metro. PVR Cinemas, Lifestyle, Marks & Spencer, Croma. Reliable food court; modest fine-dining options.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 120,
    openTime: "11:00",
    closeTime: "22:30",
    openDays: "All",
    tags: "mall,shopping,metro-connected",
    latitude: "13.0036",
    longitude: "77.5694",
    popularity: 80,
  }),
  p({
    slug: "blr-vr-bengaluru",
    name: "VR Bengaluru",
    city: BLR,
    kind: "mall",
    category: "shopping",
    area: "Whitefield",
    shortDescription: "Mall + open-air Black Box for live music + a hospitality strip.",
    description:
      "Combines a 1.4 million sq ft mall with the Black Box live-music venue and the VR Punch food street. Anchor stores include H&M, Zara, Lifestyle, Sephora.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 180,
    openTime: "11:00",
    closeTime: "23:00",
    openDays: "All",
    tags: "mall,live-music,food,shopping",
    latitude: "12.9889",
    longitude: "77.7163",
    popularity: 86,
  }),
  p({
    slug: "blr-nexus-koramangala",
    name: "Nexus Koramangala (formerly Forum Mall)",
    city: BLR,
    kind: "mall",
    category: "shopping",
    area: "Koramangala 7th Block",
    shortDescription: "South-Bangalore's go-to since 2004 — PVR Gold Class, Landmark, Westside.",
    description:
      "The first big mall in Bangalore, rebranded as Nexus in 2022. PVR Gold Class, Landmark bookstore, Westside, Lifestyle. Surrounded by Koramangala's restaurant strip.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 150,
    openTime: "10:00",
    closeTime: "22:30",
    openDays: "All",
    tags: "mall,shopping,movies,family",
    latitude: "12.9343",
    longitude: "77.6118",
    popularity: 86,
  }),
  p({
    slug: "blr-garuda-mall",
    name: "Garuda Mall",
    city: BLR,
    kind: "mall",
    category: "shopping",
    area: "Magrath Road",
    shortDescription: "Central CBD mall right behind Brigade Road — PVR Gold Class, Levi's, Tommy.",
    description:
      "Central, busy, very close to Brigade Road and MG Road. PVR Gold Class on top, Marks & Spencer, Levi's, Tommy Hilfiger.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 120,
    openTime: "11:00",
    closeTime: "22:30",
    openDays: "All",
    tags: "mall,shopping,central,movies",
    latitude: "12.9692",
    longitude: "77.6068",
    popularity: 78,
  }),
  p({
    slug: "blr-1mg-lido",
    name: "1 MG-Lido Mall",
    city: BLR,
    kind: "mall",
    category: "shopping",
    area: "Trinity Circle",
    shortDescription: "Compact upscale mall with INOX, Apple authorised store, Forest Essentials.",
    description:
      "On the old Lido cinema plot near Trinity Circle. INOX, Apple authorised store, FabIndia, Forest Essentials. Punjab Grill, Glen's Bakehouse on the ground floor.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 90,
    openTime: "11:00",
    closeTime: "22:00",
    openDays: "All",
    tags: "mall,shopping,compact,central",
    latitude: "12.9747",
    longitude: "77.6193",
    popularity: 76,
  }),
  p({
    slug: "blr-inorbit-whitefield",
    name: "Inorbit Mall Whitefield",
    city: BLR,
    kind: "mall",
    category: "shopping",
    area: "Whitefield Main Road",
    shortDescription: "Whitefield mainstay since 2012 — Shoppers Stop, Lifestyle, PVR.",
    description:
      "A regular destination for east Bangalore. Shoppers Stop, Lifestyle, Westside, PVR. Café Coffee Day, Beijing Bites, Mainland China on the food floor.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 120,
    openTime: "11:00",
    closeTime: "22:30",
    openDays: "All",
    tags: "mall,shopping,family,whitefield",
    latitude: "12.9905",
    longitude: "77.7173",
    popularity: 80,
  }),

  // --- Shopping streets ---
  p({
    slug: "blr-commercial-street",
    name: "Commercial Street",
    city: BLR,
    kind: "market",
    category: "shopping",
    area: "Shivajinagar",
    shortDescription: "Pedestrian-only fashion bazaar — sarees, kurtas, costume jewellery, street food.",
    description:
      "A 200-year-old shopping street. Mochi, Indra Nikketan, Cottage Industries Exposition, plus hundreds of small fashion shops. The lanes off Commercial Street hide haggling treasures.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 120,
    openTime: "10:30",
    closeTime: "21:30",
    openDays: "Mon-Sat",
    tags: "shopping,bazaar,sarees,jewellery,free",
    latitude: "12.9831",
    longitude: "77.6053",
    popularity: 88,
  }),
  p({
    slug: "blr-brigade-road",
    name: "Brigade Road",
    city: BLR,
    kind: "market",
    category: "shopping",
    area: "MG Road / Brigade Road",
    shortDescription: "The original Bangalore high street — fashion, bookshops, cafes, Brigade Road shoppers.",
    description:
      "Levi's, Allen Solly, Adidas. The strip is best walked between Forum Rex Walk and Magrath Road. Stop at Blossom Book House on Church Street nearby for second-hand books.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 90,
    openTime: "10:30",
    closeTime: "21:30",
    openDays: "All",
    tags: "shopping,high-street,fashion,free",
    latitude: "12.9744",
    longitude: "77.6079",
    popularity: 88,
  }),
  p({
    slug: "blr-chickpet",
    name: "Chickpet",
    city: BLR,
    kind: "market",
    category: "shopping",
    area: "Chickpet",
    shortDescription: "Wholesale silk-saree, jewellery and textile bazaar — Bangalore's oldest market.",
    description:
      "Dense narrow lanes laid out in the 16th century by Kempegowda. Buy silk sarees at Vimor, gold at Joyalukkas. Walk Avenue Road north for the wholesale book bazaar.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 90,
    openTime: "10:30",
    closeTime: "21:00",
    openDays: "Mon-Sat",
    tags: "market,sarees,wholesale,heritage,free",
    latitude: "12.9667",
    longitude: "77.5783",
    popularity: 80,
  }),
  p({
    slug: "blr-sp-road",
    name: "SP Road (Electronics Market)",
    city: BLR,
    kind: "market",
    category: "shopping",
    area: "Avenue Road",
    shortDescription: "Asia's largest computer-hardware bazaar — chips, drones, motors, you name it.",
    description:
      "Two parallel streets packed with electronics wholesalers. SP Road is the destination for PC builds, RC parts, IoT components, robotics. Cash-and-carry; bargain hard.",
    entryFeePerPerson: 0,
    idealMinutesAtPlace: 60,
    openTime: "10:30",
    closeTime: "20:00",
    openDays: "Mon-Sat",
    tags: "market,electronics,wholesale,free",
    latitude: "12.9667",
    longitude: "77.5797",
    popularity: 70,
  }),

  // --- Neighborhood / walking ---
  p({
    slug: "blr-indiranagar-100ft",
    name: "Indiranagar 100 Feet Road",
    city: BLR,
    kind: "market",
    category: "food",
    area: "Indiranagar",
    shortDescription: "Cafes, brewpubs and boutiques — Bengaluru's most-walked night-out strip.",
    description:
      "Walk from CMH Road to the end of 100 Feet Road. Toit, Truffles, Glen's Bakehouse, Burma Burma. The side-streets hide Magazine Stand, Champaca Bookstore and dozens of boutiques.",
    entryFeePerPerson: 0,
    avgCostForTwo: 1500,
    idealMinutesAtPlace: 150,
    openTime: "10:00",
    closeTime: "23:30",
    openDays: "All",
    tags: "neighborhood,food,nightlife,boutique,free",
    latitude: "12.9783",
    longitude: "77.6408",
    popularity: 95,
  }),
  p({
    slug: "blr-church-street",
    name: "Church Street",
    city: BLR,
    kind: "market",
    category: "food",
    area: "MG Road",
    shortDescription: "Cobbled cafe-and-bookshop street — Koshy's, Blossom Book House, Bourbon Street.",
    description:
      "A short pedestrianised section with cafes, bookstores, art galleries and small bars. Sundays are vehicle-free with street art and music. Don't miss Blossom Book House and Bourbon Street.",
    entryFeePerPerson: 0,
    avgCostForTwo: 1000,
    idealMinutesAtPlace: 120,
    openTime: "08:00",
    closeTime: "23:30",
    openDays: "All",
    tags: "neighborhood,cafes,books,pedestrian,free",
    latitude: "12.9742",
    longitude: "77.6088",
    popularity: 92,
  }),

  // --- Day-trip viewpoints (in-Bangalore prefix to differ from nearby_destinations) ---
  p({
    slug: "blr-nandi-hills-view",
    name: "Nandi Hills viewpoint",
    city: BLR,
    kind: "viewpoint",
    category: "nature",
    area: "Chickballapur",
    shortDescription: "Classic Bangalore sunrise — 60 km / ~1.5 hr drive north.",
    description:
      "Leave by 4:30 am. The walk-up has Tipu's Drop, Nehru Nilaya, and the Bhoga Nandeeshwara base. Sunrise from 6:30 between Nov and Feb. See the day-trip planner for a fuller route.",
    entryFeePerPerson: 30,
    idealMinutesAtPlace: 180,
    openTime: "06:00",
    closeTime: "18:00",
    openDays: "All",
    tags: "viewpoint,sunrise,day-trip",
    latitude: "13.3702",
    longitude: "77.6835",
    popularity: 95,
  }),

  // --- Cultural hubs ---
  p({
    slug: "blr-ranga-shankara",
    name: "Ranga Shankara",
    city: BLR,
    kind: "attraction",
    category: "art",
    area: "JP Nagar 2nd Phase",
    shortDescription: "300-seat repertory theatre — a play every day at 7:30 except Mondays.",
    description:
      "Founded in 2004 by Arundhati Nag. A play almost every evening in Kannada, English, Hindi, Tamil. Tickets are inexpensive (₹150-300) and sell out by mid-afternoon.",
    entryFeePerPerson: 250,
    idealMinutesAtPlace: 120,
    openTime: "10:00",
    closeTime: "22:00",
    openDays: "Tue-Sun",
    tags: "theatre,arts,evening,nightlife",
    latitude: "12.9077",
    longitude: "77.5839",
    popularity: 80,
  }),
  p({
    slug: "blr-chowdiah-memorial-hall",
    name: "Chowdiah Memorial Hall",
    city: BLR,
    kind: "attraction",
    category: "art",
    area: "Malleshwaram (Vyalikaval)",
    shortDescription: "Violin-shaped concert hall — Carnatic, Hindustani, Western classical seasons.",
    description:
      "Built in 1980 in the shape of a seven-stringed violin. Hosts the city's biggest classical concerts. Acoustics are excellent; sit centre-stalls if you can.",
    entryFeePerPerson: 500,
    idealMinutesAtPlace: 150,
    openTime: "10:00",
    closeTime: "22:00",
    openDays: "All",
    tags: "concert-hall,classical,architecture",
    latitude: "13.0007",
    longitude: "77.5793",
    popularity: 76,
  }),

  // --- A few key restaurants used by nearby-restaurant search ---
  p({
    slug: "blr-airlines-hotel",
    name: "Airlines Hotel",
    city: BLR,
    kind: "restaurant",
    category: "food",
    area: "Lavelle Road",
    shortDescription: "Open-air drive-in cafe — masala dosa under tamarind trees since 1972.",
    description:
      "A drive-in plus an open-air seating area shaded by old tamarind trees. Masala dosa, idli-vada, omelettes and the very strong filter coffee.",
    entryFeePerPerson: 0,
    avgCostForTwo: 400,
    idealMinutesAtPlace: 60,
    openTime: "07:00",
    closeTime: "23:00",
    openDays: "All",
    tags: "restaurant,veg,outdoor,iconic",
    latitude: "12.9716",
    longitude: "77.5972",
    popularity: 80,
  }),
  p({
    slug: "blr-janatha-hotel",
    name: "Janatha Hotel",
    city: BLR,
    kind: "restaurant",
    category: "food",
    area: "Malleshwaram 8th Cross",
    shortDescription: "Old-school breakfast room — rava idli, set-dosa, kesari bath.",
    description:
      "Open since 1958. Tiny, hectic, perfect. Order set-dosa with kesari bath and end with a small coffee.",
    entryFeePerPerson: 0,
    avgCostForTwo: 200,
    idealMinutesAtPlace: 30,
    openTime: "06:30",
    closeTime: "12:00",
    openDays: "All",
    tags: "restaurant,veg,breakfast,old-bangalore",
    latitude: "13.0078",
    longitude: "77.5694",
    popularity: 78,
  }),
  p({
    slug: "blr-veena-stores",
    name: "Veena Stores",
    city: BLR,
    kind: "restaurant",
    category: "food",
    area: "Malleshwaram 4th Main",
    shortDescription: "Stand-only counter for soft idli + ghee + chutney — Malleshwaram landmark.",
    description:
      "Walk in, point at the menu, eat standing. Idli-vada, khara bath, kesari bath. Don't skip the buttermilk.",
    entryFeePerPerson: 0,
    avgCostForTwo: 120,
    idealMinutesAtPlace: 30,
    openTime: "06:30",
    closeTime: "12:00",
    openDays: "All",
    tags: "restaurant,veg,iconic,quick,old-bangalore",
    latitude: "13.0061",
    longitude: "77.5705",
    popularity: 80,
  }),
];
