import type { NewCityPlace } from "./schema";

// Additional Bengaluru city places (real coordinates to ~4 decimals).
// kind: attraction | temple | museum | park | lake | restaurant | mall | nightlife | market | viewpoint | church
// category: heritage | spiritual | nature | art | shopping | food | nightlife
type Seed = Omit<NewCityPlace, "id" | "createdAt">;
const BLR = "Bangalore";

export const bangaloreCityPlacesExtra2: Seed[] = [
  {
    slug: "blr-shivoham-shiva-temple",
    name: "Shivoham Shiva Temple (Kemp Fort)",
    city: BLR,
    kind: "temple",
    category: "spiritual",
    area: "Old Airport Road",
    shortDescription: "Landmark temple with a 65 ft seated Shiva statue and a symbolic walk-through cave.",
    description: "The Shivoham Shiva Temple on Old Airport Road is known for its towering 65-foot Lord Shiva statue set against a Himalayan-Kailash backdrop, with a fountain, 12 jyotirlinga shrines and a symbolic cave walk. Especially vibrant on Maha Shivaratri.",
    entryFeePerPerson: 0,
    avgCostForTwo: null,
    idealMinutesAtPlace: 45,
    openTime: "07:00",
    closeTime: "21:00",
    openDays: "All",
    tags: "shiva,statue,landmark,festival",
    latitude: "12.9610",
    longitude: "77.6480",
    popularity: 78,
  },
  {
    slug: "blr-kote-venkataramana-temple",
    name: "Kote Venkataramana Temple",
    city: BLR,
    kind: "temple",
    category: "spiritual",
    area: "City Market",
    shortDescription: "17th-century Vijayanagara-Dravidian temple built by the Wodeyars near Tipu's palace.",
    description: "Kote Venkataramana Temple, beside Tipu Sultan's Summer Palace, was built in the late 17th century under the Wodeyars in a blend of Vijayanagara and Dravidian styles. Dedicated to Lord Venkataramana, it is one of the oldest surviving temples in the old fort area.",
    entryFeePerPerson: 0,
    avgCostForTwo: null,
    idealMinutesAtPlace: 30,
    openTime: "07:00",
    closeTime: "20:00",
    openDays: "All",
    tags: "heritage,wodeyar,venkataramana,fort",
    latitude: "12.9590",
    longitude: "77.5760",
    popularity: 62,
  },
  {
    slug: "blr-gali-anjaneya-temple",
    name: "Gali Anjaneya Temple",
    city: BLR,
    kind: "temple",
    category: "spiritual",
    area: "Mysore Road",
    shortDescription: "Centuries-old Hanuman temple on Mysore Road, popular with travellers seeking safe journeys.",
    description: "The Gali Anjaneya Temple on Mysore Road dates back several centuries and enshrines Lord Hanuman (Anjaneya). The presiding deity faces the wind direction, and devotees, especially those starting long journeys, stop here to seek blessings. It draws large crowds on Saturdays.",
    entryFeePerPerson: 0,
    avgCostForTwo: null,
    idealMinutesAtPlace: 30,
    openTime: "06:00",
    closeTime: "20:30",
    openDays: "All",
    tags: "hanuman,anjaneya,mysore-road,journey",
    latitude: "12.9430",
    longitude: "77.5360",
    popularity: 64,
  },
  {
    slug: "blr-champakadhama-swamy-temple",
    name: "Sri Champakadhama Swamy Temple (Bannerghatta)",
    city: BLR,
    kind: "temple",
    category: "spiritual",
    area: "Bannerghatta",
    shortDescription: "Ancient hill temple of Vishnu at the foot of Champakadhama betta near Bannerghatta.",
    description: "Sri Champakadhama Swamy Temple sits at the base of a hill on the Bannerghatta side of the city, with the deity Lord Vishnu worshipped as Champakadhama. A nearby Narasimha shrine and a hill trek make it a popular weekend pilgrimage and short-hike spot.",
    entryFeePerPerson: 0,
    avgCostForTwo: null,
    idealMinutesAtPlace: 60,
    openTime: "06:30",
    closeTime: "20:00",
    openDays: "All",
    tags: "vishnu,hill,bannerghatta,trek",
    latitude: "12.7990",
    longitude: "77.5770",
    popularity: 58,
  },
  {
    slug: "blr-shani-mahatma-temple-jp-nagar",
    name: "Sri Shani Mahatma Temple (JP Nagar)",
    city: BLR,
    kind: "temple",
    category: "spiritual",
    area: "JP Nagar",
    shortDescription: "Popular Lord Shani temple in JP Nagar, busiest on Saturdays for shani-related rituals.",
    description: "The Sri Shani Mahatma Temple in JP Nagar is dedicated to Lord Shani (Saturn) and is one of the most visited Shani shrines in the city. Devotees offer black sesame oil and perform rituals to ease the effects of Saturn, with Saturdays drawing the largest crowds.",
    entryFeePerPerson: 0,
    avgCostForTwo: null,
    idealMinutesAtPlace: 30,
    openTime: "06:00",
    closeTime: "20:30",
    openDays: "All",
    tags: "shani,saturn,jp-nagar,saturday",
    latitude: "12.9070",
    longitude: "77.5850",
    popularity: 60,
  },
  {
    slug: "blr-st-patricks-church",
    name: "St Patrick's Church",
    city: BLR,
    kind: "church",
    category: "heritage",
    area: "Brigade Road",
    shortDescription: "Historic Catholic church near Brigade Road, one of the oldest in the Cantonment.",
    description: "St Patrick's Church on Brigade Road traces its origins to the early 19th century, founded for Irish soldiers of the British garrison. The present church, with its tall spire and arched interiors, is among the oldest Catholic churches in the Bengaluru Cantonment.",
    entryFeePerPerson: 0,
    avgCostForTwo: null,
    idealMinutesAtPlace: 30,
    openTime: "07:00",
    closeTime: "19:00",
    openDays: "All",
    tags: "church,catholic,cantonment,heritage",
    latitude: "12.9690",
    longitude: "77.6080",
    popularity: 56,
  },
  {
    slug: "blr-holy-trinity-church",
    name: "Holy Trinity Church",
    city: BLR,
    kind: "church",
    category: "heritage",
    area: "MG Road",
    shortDescription: "Largest British-era Anglican church in the Cantonment, on MG Road.",
    description: "Holy Trinity Church on MG Road, consecrated in 1851, was the principal garrison church of the British Cantonment and the largest Anglican church in the region. Its colonial architecture, memorials and stained glass reflect Bengaluru's military past.",
    entryFeePerPerson: 0,
    avgCostForTwo: null,
    idealMinutesAtPlace: 30,
    openTime: "07:00",
    closeTime: "18:30",
    openDays: "All",
    tags: "church,anglican,colonial,mg-road",
    latitude: "12.9740",
    longitude: "77.6170",
    popularity: 54,
  },
  {
    slug: "blr-st-andrews-kirk",
    name: "St Andrew's Church (Kirk)",
    city: BLR,
    kind: "church",
    category: "heritage",
    area: "Cubbon Road",
    shortDescription: "19th-century Scottish Presbyterian kirk with a distinctive steeple near Cubbon Road.",
    description: "St Andrew's Church, a Scottish Presbyterian kirk built in the 1860s, stands near Cubbon Road with a neo-Gothic facade and a tall steeple. Designed for Scottish regiments of the Cantonment, it remains an active and well-preserved colonial-era church.",
    entryFeePerPerson: 0,
    avgCostForTwo: null,
    idealMinutesAtPlace: 25,
    openTime: "08:00",
    closeTime: "18:00",
    openDays: "All",
    tags: "church,presbyterian,kirk,colonial",
    latitude: "12.9840",
    longitude: "77.5970",
    popularity: 50,
  },
  {
    slug: "blr-venkatappa-art-gallery",
    name: "Venkatappa Art Gallery",
    city: BLR,
    kind: "museum",
    category: "art",
    area: "Kasturba Road",
    shortDescription: "State art gallery on Kasturba Road showcasing K Venkatappa's works and changing exhibitions.",
    description: "The Venkatappa Art Gallery, adjoining the Government Museum on Kasturba Road, is named after court artist K Venkatappa. It houses his paintings and plaster works alongside rotating exhibitions of contemporary Indian art, making it a key venue in the city's art scene.",
    entryFeePerPerson: 10,
    avgCostForTwo: null,
    idealMinutesAtPlace: 60,
    openTime: "10:00",
    closeTime: "17:00",
    openDays: "Tue-Sun",
    tags: "art,gallery,paintings,exhibition",
    latitude: "12.9750",
    longitude: "77.5950",
    popularity: 55,
  },
  {
    slug: "blr-bangalore-aquarium",
    name: "Bangalore Aquarium",
    city: BLR,
    kind: "museum",
    category: "nature",
    area: "Cubbon Park",
    shortDescription: "Pagoda-shaped aquarium at Cubbon Park gate, among the oldest in India.",
    description: "The Bangalore Aquarium, housed in a three-storey pagoda-style building at the Cubbon Park entrance, is one of the oldest and largest aquariums in India. It displays a range of freshwater and ornamental fish and is a long-standing family attraction.",
    entryFeePerPerson: 20,
    avgCostForTwo: null,
    idealMinutesAtPlace: 45,
    openTime: "10:00",
    closeTime: "17:30",
    openDays: "Tue-Sun",
    tags: "aquarium,fish,family,cubbon",
    latitude: "12.9760",
    longitude: "77.5930",
    popularity: 57,
  },
  {
    slug: "blr-coles-park",
    name: "Coles Park",
    city: BLR,
    kind: "park",
    category: "nature",
    area: "Frazer Town",
    shortDescription: "Leafy colonial-era park in Frazer Town with old trees and a children's play area.",
    description: "Coles Park in Frazer Town is a green colonial-era garden named after a British Resident, dotted with mature rain trees, walking paths and a children's play area. It is a quiet morning-walk and recreation space in the Cantonment neighbourhood.",
    entryFeePerPerson: 0,
    avgCostForTwo: null,
    idealMinutesAtPlace: 45,
    openTime: "05:30",
    closeTime: "20:00",
    openDays: "All",
    tags: "park,green,frazer-town,walk",
    latitude: "13.0000",
    longitude: "77.6140",
    popularity: 52,
  },
  {
    slug: "blr-agara-lake",
    name: "Agara Lake",
    city: BLR,
    kind: "lake",
    category: "nature",
    area: "HSR Layout",
    shortDescription: "Restored lake between HSR Layout and Sarjapur Road with a walking promenade.",
    description: "Agara Lake, near HSR Layout off Sarjapur Road, is a rejuvenated waterbody with a landscaped walking and jogging promenade. It attracts migratory and resident birds and is a popular spot for morning walks and quiet evenings in southeast Bengaluru.",
    entryFeePerPerson: 0,
    avgCostForTwo: null,
    idealMinutesAtPlace: 60,
    openTime: "05:30",
    closeTime: "19:00",
    openDays: "All",
    tags: "lake,birds,walk,hsr",
    latitude: "12.9220",
    longitude: "77.6420",
    popularity: 56,
  },
  {
    slug: "blr-puttenahalli-lake-jp-nagar",
    name: "Puttenahalli Lake (JP Nagar)",
    city: BLR,
    kind: "lake",
    category: "nature",
    area: "JP Nagar",
    shortDescription: "Community-revived lake in JP Nagar known for birdlife and a citizen-run nature park.",
    description: "Puttenahalli Lake in JP Nagar is a small waterbody famously revived by local residents through a citizen trust. The wetland now supports kingfishers, egrets and other birds, with a walking path making it a beloved green pocket of south Bengaluru.",
    entryFeePerPerson: 0,
    avgCostForTwo: null,
    idealMinutesAtPlace: 45,
    openTime: "06:00",
    closeTime: "18:30",
    openDays: "All",
    tags: "lake,birds,community,jp-nagar",
    latitude: "12.8920",
    longitude: "77.5850",
    popularity: 53,
  },
  {
    slug: "blr-yediyur-lake",
    name: "Yediyur Lake",
    city: BLR,
    kind: "lake",
    category: "nature",
    area: "Jayanagar",
    shortDescription: "Small landscaped lake and park in Jayanagar with musical fountain and walkway.",
    description: "Yediyur Lake in Jayanagar is a compact, well-maintained urban lake surrounded by a landscaped park and walking track. With a musical fountain and boating in parts, it is a favourite evening hangout for families in south Bengaluru.",
    entryFeePerPerson: 0,
    avgCostForTwo: null,
    idealMinutesAtPlace: 45,
    openTime: "05:30",
    closeTime: "20:00",
    openDays: "All",
    tags: "lake,park,jayanagar,fountain",
    latitude: "12.9260",
    longitude: "77.5720",
    popularity: 54,
  },
  {
    slug: "blr-jakkur-lake",
    name: "Jakkur Lake",
    city: BLR,
    kind: "lake",
    category: "nature",
    area: "Jakkur",
    shortDescription: "Large north-Bengaluru lake popular for birdwatching, kayaking and morning walks.",
    description: "Jakkur Lake, near Jakkur Aerodrome in north Bengaluru, is one of the city's larger and better-managed lakes. With a wetland for natural water treatment, it draws pelicans and other birds, and supports kayaking, rowing and a long walking trail.",
    entryFeePerPerson: 0,
    avgCostForTwo: null,
    idealMinutesAtPlace: 75,
    openTime: "05:30",
    closeTime: "19:00",
    openDays: "All",
    tags: "lake,birds,kayaking,jakkur",
    latitude: "13.0750",
    longitude: "77.6010",
    popularity: 58,
  },
  {
    slug: "blr-avenue-road",
    name: "Avenue Road",
    city: BLR,
    kind: "market",
    category: "shopping",
    area: "City Market",
    shortDescription: "Bustling historic trading street near KR Market famed for books, stationery and wholesale shops.",
    description: "Avenue Road, in the heart of old Bengaluru near KR Market, is one of the city's oldest commercial streets. Its dense lanes are packed with bookshops, stationery, jewellery, sweets and wholesale traders, offering a chaotic, atmospheric taste of pete (old town) commerce.",
    entryFeePerPerson: 0,
    avgCostForTwo: null,
    idealMinutesAtPlace: 60,
    openTime: "10:00",
    closeTime: "20:30",
    openDays: "Mon-Sat",
    tags: "market,books,wholesale,old-town",
    latitude: "12.9670",
    longitude: "77.5790",
    popularity: 60,
  },
  {
    slug: "blr-malleshwaram-market",
    name: "Malleshwaram Market",
    city: BLR,
    kind: "market",
    category: "shopping",
    area: "Malleshwaram",
    shortDescription: "Traditional flower, fruit and vegetable market at the heart of old Malleshwaram.",
    description: "Malleshwaram Market, around 8th Cross, is a vibrant traditional bazaar known for fresh flowers, fruit, vegetables and pooja items. Surrounded by old eateries and temples, it is busiest during festivals like Varamahalakshmi and offers a classic neighbourhood-market experience.",
    entryFeePerPerson: 0,
    avgCostForTwo: null,
    idealMinutesAtPlace: 45,
    openTime: "06:00",
    closeTime: "21:00",
    openDays: "All",
    tags: "market,flowers,vegetables,malleshwaram",
    latitude: "13.0030",
    longitude: "77.5700",
    popularity: 57,
  },
  {
    slug: "blr-balepete",
    name: "Balepete",
    city: BLR,
    kind: "market",
    category: "shopping",
    area: "Chickpet",
    shortDescription: "Old-town lane near Chickpet known for musical instruments, bangles and traditional wares.",
    description: "Balepete, one of the historic trade lanes of Bengaluru's pete area near Chickpet, is traditionally associated with bangles and musical instruments. Today its shops sell instruments, wedding goods and assorted wholesale items, preserving the old guild-street character.",
    entryFeePerPerson: 0,
    avgCostForTwo: null,
    idealMinutesAtPlace: 45,
    openTime: "10:30",
    closeTime: "20:30",
    openDays: "Mon-Sat",
    tags: "market,instruments,bangles,old-town",
    latitude: "12.9690",
    longitude: "77.5780",
    popularity: 51,
  },
  {
    slug: "blr-jayanagar-4th-block",
    name: "Jayanagar 4th Block Shopping Complex",
    city: BLR,
    kind: "market",
    category: "shopping",
    area: "Jayanagar",
    shortDescription: "Sprawling shopping hub in Jayanagar with apparel, jewellery, street food and a market.",
    description: "Jayanagar 4th Block is one of south Bengaluru's busiest shopping districts, centred on a large shopping complex and surrounding streets. It offers clothing, footwear, jewellery, household goods and a lively street-food scene, drawing big festival-season crowds.",
    entryFeePerPerson: 0,
    avgCostForTwo: null,
    idealMinutesAtPlace: 75,
    openTime: "10:00",
    closeTime: "21:30",
    openDays: "All",
    tags: "shopping,apparel,street-food,jayanagar",
    latitude: "12.9270",
    longitude: "77.5830",
    popularity: 62,
  },
  {
    slug: "blr-forum-shantiniketan",
    name: "Forum Shantiniketan Mall",
    city: BLR,
    kind: "mall",
    category: "shopping",
    area: "Whitefield",
    shortDescription: "Large Whitefield mall with retail brands, a multiplex and a wide food court.",
    description: "Forum Shantiniketan in Whitefield is a major east-Bengaluru shopping mall with a mix of Indian and international brands, a multiplex, gaming zone and an extensive food court. It is a key weekend destination for the IT belt around Whitefield.",
    entryFeePerPerson: 0,
    avgCostForTwo: null,
    idealMinutesAtPlace: 120,
    openTime: "10:30",
    closeTime: "22:00",
    openDays: "All",
    tags: "mall,shopping,multiplex,whitefield",
    latitude: "12.9950",
    longitude: "77.7280",
    popularity: 64,
  },
  {
    slug: "blr-gt-world-mall",
    name: "GT World Mall",
    city: BLR,
    kind: "mall",
    category: "shopping",
    area: "Magadi Road",
    shortDescription: "Popular west-Bengaluru mall on Magadi Road with retail, food court and a cinema.",
    description: "GT World Mall on Magadi Road serves west Bengaluru with anchor retail stores, fashion brands, a multiplex and a large food court. Well connected to the Metro Green Line, it is a busy shopping and entertainment hub for the area.",
    entryFeePerPerson: 0,
    avgCostForTwo: null,
    idealMinutesAtPlace: 120,
    openTime: "10:30",
    closeTime: "22:00",
    openDays: "All",
    tags: "mall,shopping,cinema,magadi-road",
    latitude: "12.9760",
    longitude: "77.5430",
    popularity: 58,
  },
  {
    slug: "blr-big-pitcher",
    name: "Big Pitcher",
    city: BLR,
    kind: "nightlife",
    category: "nightlife",
    area: "Old Airport Road",
    shortDescription: "Sprawling multi-level brewpub on Old Airport Road known for craft beer and a grand interior.",
    description: "Big Pitcher on Old Airport Road is one of Bengaluru's largest microbreweries, spread over multiple levels with bars, dining areas and an open terrace. It is popular for its house-brewed craft beer, extensive menu and lively weekend ambience.",
    entryFeePerPerson: 0,
    avgCostForTwo: 2200,
    idealMinutesAtPlace: 120,
    openTime: "12:00",
    closeTime: "23:30",
    openDays: "All",
    tags: "brewpub,craft-beer,nightlife,terrace",
    latitude: "12.9580",
    longitude: "77.6520",
    popularity: 66,
  },
  {
    slug: "blr-arbor-brewing-company",
    name: "Arbor Brewing Company",
    city: BLR,
    kind: "nightlife",
    category: "nightlife",
    area: "Magrath Road",
    shortDescription: "American-origin craft brewery off Brigade Road serving small-batch beers and pub food.",
    description: "Arbor Brewing Company, an India outpost of the Michigan brewery, sits off Brigade Road on Magrath Road. It is known for its rotating small-batch craft beers, casual pub atmosphere and trivia and music nights popular with the central-city crowd.",
    entryFeePerPerson: 0,
    avgCostForTwo: 1800,
    idealMinutesAtPlace: 120,
    openTime: "12:00",
    closeTime: "23:30",
    openDays: "All",
    tags: "brewery,craft-beer,nightlife,brigade-road",
    latitude: "12.9680",
    longitude: "77.6110",
    popularity: 63,
  },
  {
    slug: "blr-three-dots-and-a-dash",
    name: "Three Dots & a Dash",
    city: BLR,
    kind: "nightlife",
    category: "nightlife",
    area: "Indiranagar",
    shortDescription: "Popular Indiranagar microbrewery and rooftop bar with craft beer and a buzzing vibe.",
    description: "Three Dots & a Dash on 100 Feet Road, Indiranagar, is a well-known microbrewery and rooftop lounge. With house-brewed beers, cocktails, DJ nights and an energetic crowd, it is a fixture of the Indiranagar nightlife scene.",
    entryFeePerPerson: 0,
    avgCostForTwo: 2000,
    idealMinutesAtPlace: 120,
    openTime: "12:00",
    closeTime: "23:30",
    openDays: "All",
    tags: "brewery,rooftop,nightlife,indiranagar",
    latitude: "12.9710",
    longitude: "77.6410",
    popularity: 65,
  },
  {
    slug: "blr-skyye-lounge",
    name: "Skyye Lounge",
    city: BLR,
    kind: "nightlife",
    category: "nightlife",
    area: "UB City",
    shortDescription: "Rooftop sky bar atop UB City with panoramic skyline views, cocktails and DJ nights.",
    description: "Skyye Lounge sits on the 16th floor of UB City and is one of Bengaluru's iconic rooftop bars. Famous for its open-air deck, city skyline views, cocktails and weekend DJ sets, it is a go-to upscale nightlife spot in the central business district.",
    entryFeePerPerson: 0,
    avgCostForTwo: 3000,
    idealMinutesAtPlace: 120,
    openTime: "12:30",
    closeTime: "23:30",
    openDays: "All",
    tags: "rooftop,skybar,cocktails,ub-city",
    latitude: "12.9716",
    longitude: "77.5960",
    popularity: 67,
  },
  {
    slug: "blr-high-ultra-lounge",
    name: "High Ultra Lounge",
    city: BLR,
    kind: "nightlife",
    category: "nightlife",
    area: "Sankey Road",
    shortDescription: "One of India's highest rooftop lounges, atop World Trade Center on Sankey Road.",
    description: "High Ultra Lounge crowns the World Trade Center near Sankey Road and is among the highest rooftop bars in the country. It offers sweeping 360-degree city views, an indoor lounge and an open-air deck with cocktails, making it a premium nightlife destination.",
    entryFeePerPerson: 0,
    avgCostForTwo: 3200,
    idealMinutesAtPlace: 120,
    openTime: "16:00",
    closeTime: "23:30",
    openDays: "All",
    tags: "rooftop,skybar,views,nightlife",
    latitude: "12.9920",
    longitude: "77.5650",
    popularity: 64,
  },
  {
    slug: "blr-hotel-empire",
    name: "Hotel Empire",
    city: BLR,
    kind: "restaurant",
    category: "food",
    area: "Church Street",
    shortDescription: "Beloved late-night chain famed for kebabs, biryani and butter chicken; busy Church Street branch.",
    description: "Hotel Empire is a much-loved Bengaluru restaurant chain known for its hearty, affordable Mughlai and Indian-Chinese fare. Dishes like kebabs, butter chicken, biryani and rumali roti, served till late, make its Church Street and other outlets perennial favourites.",
    entryFeePerPerson: 0,
    avgCostForTwo: 700,
    idealMinutesAtPlace: 60,
    openTime: "11:00",
    closeTime: "01:00",
    openDays: "All",
    tags: "mughlai,kebab,biryani,late-night",
    latitude: "12.9750",
    longitude: "77.6060",
    popularity: 70,
  },
  {
    slug: "blr-shivaji-military-hotel",
    name: "Shivaji Military Hotel",
    city: BLR,
    kind: "restaurant",
    category: "food",
    area: "Jayanagar",
    shortDescription: "Iconic old-school eatery famous for Bangalore-style mutton donne biryani.",
    description: "Shivaji Military Hotel is a legendary no-frills eatery, originally from the Cottonpet area with a Jayanagar outlet, renowned for its fiery Bangalore-style mutton donne biryani and ragi mudde with curry. It is a must-visit for fans of authentic local non-veg fare.",
    entryFeePerPerson: 0,
    avgCostForTwo: 600,
    idealMinutesAtPlace: 45,
    openTime: "12:00",
    closeTime: "16:00",
    openDays: "All",
    tags: "biryani,mutton,military-hotel,local",
    latitude: "12.9290",
    longitude: "77.5830",
    popularity: 68,
  },
  {
    slug: "blr-taaza-thindi",
    name: "Taaza Thindi",
    city: BLR,
    kind: "restaurant",
    category: "food",
    area: "Jayanagar",
    shortDescription: "Tiny Jayanagar institution loved for fresh, fast idli, vada and dosa at low prices.",
    description: "Taaza Thindi in Jayanagar is a small, hugely popular tiffin joint known for serving piping-hot idli, vada, khara bath and butter-soaked dosa at modest prices. Its quick turnover and consistent quality draw long queues, especially at breakfast.",
    entryFeePerPerson: 0,
    avgCostForTwo: 250,
    idealMinutesAtPlace: 30,
    openTime: "06:30",
    closeTime: "21:00",
    openDays: "All",
    tags: "dosa,idli,breakfast,tiffin",
    latitude: "12.9180",
    longitude: "77.5840",
    popularity: 66,
  },
  {
    slug: "blr-slv-sri-lakshmi-venkateshwara",
    name: "SLV (Sri Lakshmi Venkateshwara)",
    city: BLR,
    kind: "restaurant",
    category: "food",
    area: "Marathahalli",
    shortDescription: "Popular South Indian fast-food chain known for crispy dosas, idli-vada and filter coffee.",
    description: "SLV (Sri Lakshmi Venkateshwara) is a widespread Bengaluru chain of self-service South Indian restaurants serving quick, affordable dosas, idli, vada and filter coffee. Its Marathahalli and other outlets are reliable everyday eateries across the city.",
    entryFeePerPerson: 0,
    avgCostForTwo: 300,
    idealMinutesAtPlace: 30,
    openTime: "07:00",
    closeTime: "22:30",
    openDays: "All",
    tags: "dosa,south-indian,fast-food,coffee",
    latitude: "12.9560",
    longitude: "77.7010",
    popularity: 60,
  },
  {
    slug: "blr-maiyas-jayanagar",
    name: "Maiya's (Jayanagar)",
    city: BLR,
    kind: "restaurant",
    category: "food",
    area: "Jayanagar",
    shortDescription: "Upmarket vegetarian restaurant in Jayanagar known for South Indian thalis and sweets.",
    description: "Maiya's in Jayanagar is a well-regarded vegetarian restaurant and sweet shop, descended from the Mavalli Tiffin lineage. It is known for its spacious dining, South Indian breakfasts, full meals (thalis) and a popular counter of traditional sweets and snacks.",
    entryFeePerPerson: 0,
    avgCostForTwo: 700,
    idealMinutesAtPlace: 60,
    openTime: "07:00",
    closeTime: "22:30",
    openDays: "All",
    tags: "vegetarian,thali,sweets,jayanagar",
    latitude: "12.9300",
    longitude: "77.5820",
    popularity: 62,
  },
  {
    slug: "blr-rameshwaram-cafe",
    name: "The Rameshwaram Cafe",
    city: BLR,
    kind: "restaurant",
    category: "food",
    area: "Indiranagar",
    shortDescription: "Hugely popular fast-service cafe famed for ghee podi idli, filter coffee and quick South Indian tiffin.",
    description: "The Rameshwaram Cafe shot to fame for its high-speed South Indian tiffin service, especially ghee-roast dosa, podi idli and strong filter coffee. Its Indiranagar and other outlets see long queues through the day for fresh, value-for-money food.",
    entryFeePerPerson: 0,
    avgCostForTwo: 400,
    idealMinutesAtPlace: 30,
    openTime: "06:30",
    closeTime: "22:00",
    openDays: "All",
    tags: "dosa,idli,filter-coffee,tiffin",
    latitude: "12.9780",
    longitude: "77.6400",
    popularity: 72,
  },
  {
    slug: "blr-konark-restaurant",
    name: "Konark Restaurant",
    city: BLR,
    kind: "restaurant",
    category: "food",
    area: "Residency Road",
    shortDescription: "Long-standing Residency Road restaurant known for Indian-Chinese and North Indian fare.",
    description: "Konark on Residency Road is a veteran Bengaluru restaurant popular for its North Indian and Indian-Chinese dishes in a comfortable family setting. A central-city dining staple for decades, it is known for generous portions and consistent food.",
    entryFeePerPerson: 0,
    avgCostForTwo: 1100,
    idealMinutesAtPlace: 75,
    openTime: "12:00",
    closeTime: "23:00",
    openDays: "All",
    tags: "north-indian,chinese,family,residency-road",
    latitude: "12.9690",
    longitude: "77.6020",
    popularity: 55,
  },
  {
    slug: "blr-halli-mane",
    name: "Halli Mane",
    city: BLR,
    kind: "restaurant",
    category: "food",
    area: "Malleshwaram",
    shortDescription: "Rustic Malleshwaram eatery serving traditional Karnataka vegetarian dishes and snacks.",
    description: "Halli Mane ('village home') in Malleshwaram recreates a rural Karnataka ambience and serves authentic regional vegetarian fare like ragi rotti, akki rotti, holige and a range of traditional snacks and tiffins. It is a favourite for nostalgic, homestyle food.",
    entryFeePerPerson: 0,
    avgCostForTwo: 450,
    idealMinutesAtPlace: 60,
    openTime: "07:30",
    closeTime: "21:30",
    openDays: "All",
    tags: "karnataka,vegetarian,rotti,traditional",
    latitude: "13.0030",
    longitude: "77.5650",
    popularity: 60,
  },
  {
    slug: "blr-adigas-jayanagar",
    name: "Adigas (Jayanagar)",
    city: BLR,
    kind: "restaurant",
    category: "food",
    area: "Jayanagar",
    shortDescription: "Famous Bengaluru vegetarian chain known for crisp dosas, thatte idli and tiffins.",
    description: "Adigas is a well-known Bengaluru-grown vegetarian restaurant chain, with a flagship presence in Jayanagar. It is popular for South Indian tiffins like thatte idli, masala dosa, vada and filter coffee, as well as North Indian and chaat options.",
    entryFeePerPerson: 0,
    avgCostForTwo: 500,
    idealMinutesAtPlace: 45,
    openTime: "07:00",
    closeTime: "22:30",
    openDays: "All",
    tags: "dosa,idli,vegetarian,tiffin",
    latitude: "12.9250",
    longitude: "77.5830",
    popularity: 61,
  },
  {
    slug: "blr-nandi-hills-viewpoint",
    name: "Ramohalli Big Banyan Tree",
    city: BLR,
    kind: "viewpoint",
    category: "nature",
    area: "Ramohalli",
    shortDescription: "Sprawling 400-year-old banyan tree (Dodda Alada Mara) on the city's western outskirts.",
    description: "The Big Banyan Tree (Dodda Alada Mara) at Ramohalli, off Mysore Road, is a single banyan estimated to be around 400 years old, spreading its aerial roots over nearly three acres. It is a popular short-drive picnic and nature spot from the city.",
    entryFeePerPerson: 0,
    avgCostForTwo: null,
    idealMinutesAtPlace: 60,
    openTime: "06:00",
    closeTime: "18:00",
    openDays: "All",
    tags: "banyan,nature,picnic,ramohalli",
    latitude: "12.9230",
    longitude: "77.4540",
    popularity: 59,
  },
  {
    slug: "blr-shanti-sagar-restaurant",
    name: "Sapphire Skydeck (Vidhana Soudha View Point)",
    city: BLR,
    kind: "viewpoint",
    category: "heritage",
    area: "Cubbon Park",
    shortDescription: "Open vantage near Cubbon Park looking onto Vidhana Soudha and the High Court grounds.",
    description: "The avenue and lawns along Cubbon Park facing Vidhana Soudha offer one of the best open views of the granite legislative building and the red Attara Kacheri (High Court). Especially striking when the buildings are floodlit on weekend evenings.",
    entryFeePerPerson: 0,
    avgCostForTwo: null,
    idealMinutesAtPlace: 30,
    openTime: "06:00",
    closeTime: "20:00",
    openDays: "All",
    tags: "viewpoint,vidhana-soudha,cubbon,photography",
    latitude: "12.9790",
    longitude: "77.5910",
    popularity: 56,
  },
];
