import type { NewNearbyDestination } from "./schema";

// Additional one-day-trip spots from Bangalore (BLR centre 12.9716, 77.5946).
// distanceKm / drivingMinutes are one-way road estimates in normal traffic.
export const bangaloreOneDayTripsExtra: Omit<NewNearbyDestination, "id" | "createdAt">[] = [
  {
    slug: "blr-shravanabelagola",
    name: "Shravanabelagola",
    baseCity: "Bangalore",
    category: "pilgrimage",
    shortDescription: "Jain pilgrimage hill crowned by the 17 m monolithic Gomateshwara (Bahubali) statue.",
    description: "Shravanabelagola is a major Jain centre ~145 km from Bangalore. Climb ~600 rock-cut steps up Vindhyagiri to the colossal 10th-century Gommateshwara monolith; Chandragiri hill opposite has older basadis. The Mahamastakabhisheka is held here every 12 years.",
    distanceKm: 145,
    drivingMinutes: 180,
    entryFeePerPerson: 0,
    idealHoursAtPlace: 3,
    bestStartTime: "06:30",
    highlights: "Gomateshwara monolith,Vindhyagiri climb,Jain basadis",
    latitude: "12.8554",
    longitude: "76.4895",
    popularity: 80,
  },
  {
    slug: "blr-mysore",
    name: "Mysore (Mysuru)",
    baseCity: "Bangalore",
    category: "heritage",
    shortDescription: "Royal city of palaces, the illuminated Amba Vilas (Mysore Palace) and Chamundi Hills.",
    description: "Mysuru, ~145 km from Bangalore on a fast expressway, is doable as a long day trip. See the Indo-Saracenic Mysore Palace, climb Chamundi Hills to the Chamundeshwari temple and Nandi monolith, and stroll the Brindavan-style gardens. The palace is famously lit up on Sunday evenings.",
    distanceKm: 145,
    drivingMinutes: 180,
    entryFeePerPerson: 70,
    idealHoursAtPlace: 6,
    bestStartTime: "06:00",
    highlights: "Mysore Palace,Chamundi Hills,Mysore Zoo",
    latitude: "12.3052",
    longitude: "76.6552",
    popularity: 92,
  },
  {
    slug: "blr-srirangapatna",
    name: "Srirangapatna",
    baseCity: "Bangalore",
    category: "heritage",
    shortDescription: "Island fort-town of Tipu Sultan with Ranganathaswamy temple and Daria Daulat Bagh.",
    description: "Srirangapatna sits on a Cauvery island ~125 km from Bangalore and was Tipu Sultan's capital. Visit the ancient Ranganathaswamy temple, Tipu's summer palace Daria Daulat Bagh, the Gumbaz mausoleum and the river ghats. It is a recognised heritage and birding site.",
    distanceKm: 125,
    drivingMinutes: 165,
    entryFeePerPerson: 25,
    idealHoursAtPlace: 4,
    bestStartTime: "06:30",
    highlights: "Ranganathaswamy temple,Daria Daulat Bagh,Gumbaz",
    latitude: "12.4181",
    longitude: "76.6947",
    popularity: 78,
  },
  {
    slug: "blr-somanathapura",
    name: "Somanathapura Keshava Temple",
    baseCity: "Bangalore",
    category: "heritage",
    shortDescription: "Star-shaped 13th-century Hoysala Chennakeshava temple, a UNESCO World Heritage site.",
    description: "The Chennakeshava (Keshava) temple at Somanathapura, ~140 km from Bangalore, was completed in 1268 CE under the Hoysalas. Its trikuta (three-shrine) layout on a stellate platform is covered in intricate friezes of gods, dancers and mythology. It joined the UNESCO list as part of the Sacred Ensembles of the Hoysalas.",
    distanceKm: 140,
    drivingMinutes: 175,
    entryFeePerPerson: 25,
    idealHoursAtPlace: 2,
    bestStartTime: "07:00",
    highlights: "Hoysala carvings,Star-shaped plan,UNESCO site",
    latitude: "12.2752",
    longitude: "76.8807",
    popularity: 74,
  },
  {
    slug: "blr-melukote",
    name: "Melukote (Melkote)",
    baseCity: "Bangalore",
    category: "pilgrimage",
    shortDescription: "Hilltop Sri Vaishnava temple town with Cheluvanarayana temple and the Yoganarasimha hill shrine.",
    description: "Melukote, ~150 km from Bangalore in Mandya district, is a sacred Sri Vaishnava centre linked to Ramanujacharya. The Cheluvanarayanaswamy temple in town and the Yoganarasimha temple atop the rocky hill draw pilgrims, and the Akka-Thangi Kola tanks add to the scene. It is famous for its Vairamudi festival.",
    distanceKm: 150,
    drivingMinutes: 185,
    entryFeePerPerson: 0,
    idealHoursAtPlace: 3,
    bestStartTime: "06:30",
    highlights: "Cheluvanarayana temple,Yoganarasimha hill,Kalyani tanks",
    latitude: "12.6614",
    longitude: "76.6486",
    popularity: 70,
  },
  {
    slug: "blr-kunti-betta",
    name: "Kunti Betta (Pandavapura)",
    baseCity: "Bangalore",
    category: "adventure",
    shortDescription: "Twin rocky hillock near Pandavapura popular for sunrise treks and a night-trek camp.",
    description: "Kunti Betta near Pandavapura, ~125 km from Bangalore, is a pair of granite hillocks linked in legend to the Pandavas and Kunti. The short but rocky climb rewards trekkers with sunrise views over paddy fields and a lake. It is a favourite for early-morning and full-moon night treks.",
    distanceKm: 125,
    drivingMinutes: 170,
    entryFeePerPerson: 0,
    idealHoursAtPlace: 3,
    bestStartTime: "05:00",
    highlights: "Sunrise trek,Rock climb,Lake views",
    latitude: "12.5028",
    longitude: "76.6772",
    popularity: 68,
  },
  {
    slug: "blr-hogenakkal-falls",
    name: "Hogenakkal Falls",
    baseCity: "Bangalore",
    category: "adventure",
    shortDescription: "Cauvery cascades on the TN border famed for coracle rides through a carbonatite gorge.",
    description: "Hogenakkal, ~130 km from Bangalore on the Karnataka-Tamil Nadu border, is where the Cauvery thunders over rocky drops into a gorge, earning it the 'Niagara of India' nickname. Round coracle (parisal) rides take visitors near the falls, best in the post-monsoon months. Fresh river fish and oil massages are local draws.",
    distanceKm: 130,
    drivingMinutes: 180,
    entryFeePerPerson: 0,
    idealHoursAtPlace: 4,
    bestStartTime: "06:00",
    highlights: "Coracle rides,Cauvery falls,Gorge boating",
    latitude: "12.1170",
    longitude: "77.7780",
    popularity: 82,
  },
  {
    slug: "blr-kotilingeshwara",
    name: "Kotilingeshwara (Kolar)",
    baseCity: "Bangalore",
    category: "pilgrimage",
    shortDescription: "Temple complex near Kolar with lakhs of Shiva lingas and one of India's tallest lingas.",
    description: "Kotilingeshwara at Kammasandra near Kolar, ~95 km from Bangalore, is known for hundreds of thousands of installed Shiva lingas across its grounds. The presiding lingam, ~33 m tall, is among the tallest in the country, paired with a giant Nandi. Devotees donate lingas inscribed with their names.",
    distanceKm: 95,
    drivingMinutes: 130,
    entryFeePerPerson: 0,
    idealHoursAtPlace: 2,
    bestStartTime: "07:00",
    highlights: "Tallest Shiva linga,Lakhs of lingas,Giant Nandi",
    latitude: "12.8689",
    longitude: "78.2880",
    popularity: 66,
  },
  {
    slug: "blr-kurudumale-ganesha",
    name: "Kurudumale Ganesha",
    baseCity: "Bangalore",
    category: "pilgrimage",
    shortDescription: "Ancient ~13 ft monolithic Ganesha idol and a Someshwara temple near Mulbagal.",
    description: "Kurudumale, ~100 km from Bangalore near Mulbagal in Kolar district, houses a striking ~13-foot monolithic Ganesha believed to be over a thousand years old. The nearby Someshwara temple is attributed to Hoysala-Vijayanagara craftsmanship. The temple sits amid open countryside dotted with boulders.",
    distanceKm: 100,
    drivingMinutes: 140,
    entryFeePerPerson: 0,
    idealHoursAtPlace: 2,
    bestStartTime: "07:00",
    highlights: "Monolithic Ganesha,Someshwara temple,Ancient sculpture",
    latitude: "13.1830",
    longitude: "78.3870",
    popularity: 58,
  },
  {
    slug: "blr-kaiwara",
    name: "Kaiwara",
    baseCity: "Bangalore",
    category: "pilgrimage",
    shortDescription: "Hamlet linked to saint Yogi Narayana with temples, an ashram and the Bhima Bakasura cave.",
    description: "Kaiwara, ~70 km from Bangalore in Chikkaballapura district, is the birthplace of the 19th-century mystic-poet Yogi Narayana (Kaivara Tatayya). Pilgrims visit his ashram and the Amaranarayana and Bhimeshwara temples. A short hill trek leads to caves associated with the Pandava Bhima.",
    distanceKm: 70,
    drivingMinutes: 100,
    entryFeePerPerson: 0,
    idealHoursAtPlace: 2,
    bestStartTime: "07:30",
    highlights: "Yogi Narayana ashram,Bhima cave,Ancient temples",
    latitude: "13.3700",
    longitude: "78.2280",
    popularity: 52,
  },
  {
    slug: "blr-mulbagal",
    name: "Mulbagal",
    baseCity: "Bangalore",
    category: "pilgrimage",
    shortDescription: "Historic Kolar town with the Anjaneya and Someshwara temples and Kurudumale nearby.",
    description: "Mulbagal, ~100 km east of Bangalore in Kolar district, is an old temple town once called the 'gateway to the south'. It is known for its Anjaneyaswamy temple consecrated by Vyasaraja and the Someshwara temple. The town is a convenient base for nearby Kurudumale and Avani.",
    distanceKm: 100,
    drivingMinutes: 135,
    entryFeePerPerson: 0,
    idealHoursAtPlace: 2,
    bestStartTime: "07:00",
    highlights: "Anjaneya temple,Someshwara temple,Old town",
    latitude: "13.1640",
    longitude: "78.3930",
    popularity: 50,
  },
  {
    slug: "blr-makalidurga",
    name: "Makalidurga",
    baseCity: "Bangalore",
    category: "adventure",
    shortDescription: "Hill-fort trek beside a railway line with a summit Shiva-Nandi shrine and lake views.",
    description: "Makalidurga, ~60 km north of Bangalore near Doddaballapura, is a popular trek up a granite hill topped by a small fort and a Shiva-Nandi shrine. The trail runs alongside a scenic railway track and curving viaduct, making it a favourite with photographers. Sunrise views over the reservoir are the highlight.",
    distanceKm: 60,
    drivingMinutes: 90,
    entryFeePerPerson: 0,
    idealHoursAtPlace: 3,
    bestStartTime: "05:30",
    highlights: "Hill-fort trek,Railway viaduct,Sunrise views",
    latitude: "13.3650",
    longitude: "77.5750",
    popularity: 64,
  },
  {
    slug: "blr-shivagange",
    name: "Shivagange",
    baseCity: "Bangalore",
    category: "pilgrimage",
    shortDescription: "Cone-shaped pilgrim hill near Tumkur with cave temples and the Gangadhareshwara shrine.",
    description: "Shivagange, ~55 km from Bangalore near Tumakuru, is a distinctive cone-shaped hill regarded as 'Dakshina Kashi'. Pilgrims climb past the Gangadhareshwara cave temple, the Olakal Teertha and a giant Nandi to reach the summit. The hill is famed for a spring whose water is said to behave like ghee on the linga.",
    distanceKm: 55,
    drivingMinutes: 80,
    entryFeePerPerson: 0,
    idealHoursAtPlace: 3,
    bestStartTime: "06:30",
    highlights: "Cave temples,Gangadhareshwara,Hill climb",
    latitude: "13.0590",
    longitude: "77.2270",
    popularity: 67,
  },
  {
    slug: "blr-madhugiri-fort",
    name: "Madhugiri Fort",
    baseCity: "Bangalore",
    category: "adventure",
    shortDescription: "Steep climb up Asia's second-largest monolith hill to a tiered Vijayanagara-era fort.",
    description: "Madhugiri, ~100 km north of Bangalore in Tumakuru district, is built on a single huge granite monolith said to be among Asia's largest. The fortified trail with carved steps and gateways climbs steeply to ruined bastions and a Gopalakrishna temple. The exposed rock face makes the upper section a thrilling scramble.",
    distanceKm: 100,
    drivingMinutes: 140,
    entryFeePerPerson: 0,
    idealHoursAtPlace: 3,
    bestStartTime: "06:00",
    highlights: "Monolith fort climb,Bastions,Panoramic views",
    latitude: "13.6610",
    longitude: "77.2120",
    popularity: 63,
  },
  {
    slug: "blr-siddara-betta",
    name: "Siddara Betta",
    baseCity: "Bangalore",
    category: "adventure",
    shortDescription: "Boulder hill near Koratagere with caves, a Shiva shrine and a perennial spring.",
    description: "Siddara Betta, ~95 km from Bangalore near Koratagere in Tumakuru district, is known as a 'hill of siddhas' once home to sages. The trek weaves through caves and narrow rock passages to a Siddhalingeshwara temple, with a small perennial spring on the way. It is a quieter, adventurous alternative to busier hill treks.",
    distanceKm: 95,
    drivingMinutes: 135,
    entryFeePerPerson: 0,
    idealHoursAtPlace: 3,
    bestStartTime: "06:00",
    highlights: "Cave trek,Rock passages,Hill shrine",
    latitude: "13.5900",
    longitude: "77.1880",
    popularity: 55,
  },
  {
    slug: "blr-namada-chilume",
    name: "Namada Chilume",
    baseCity: "Bangalore",
    category: "wildlife",
    shortDescription: "Deer park and natural spring near Devarayanadurga linked to the Ramayana.",
    description: "Namada Chilume, ~70 km from Bangalore near Devarayanadurga, is a forest spot built around a perennial natural spring said to be created by Rama's arrow. It now houses a deer park and a small wildlife/breeding area amid forest. The site pairs well with a visit to nearby Devarayanadurga temples.",
    distanceKm: 70,
    drivingMinutes: 105,
    entryFeePerPerson: 30,
    idealHoursAtPlace: 2,
    bestStartTime: "07:30",
    highlights: "Deer park,Natural spring,Forest walk",
    latitude: "13.3760",
    longitude: "77.2200",
    popularity: 54,
  },
  {
    slug: "blr-bilikal-rangaswamy-betta",
    name: "Bilikal Rangaswamy Betta",
    baseCity: "Bangalore",
    category: "adventure",
    shortDescription: "Forested hill near Kanakapura with a Ranganatha cave shrine and a giant white boulder.",
    description: "Bilikal Rangaswamy Betta, ~85 km from Bangalore beyond Kanakapura, is one of the highest points in the region, named for its huge white granite rock ('bili kal'). A forest road and trek lead to a Ranganathaswamy cave temple near the summit. Misty mornings and sweeping views reward the climb.",
    distanceKm: 85,
    drivingMinutes: 140,
    entryFeePerPerson: 0,
    idealHoursAtPlace: 3,
    bestStartTime: "06:00",
    highlights: "White boulder,Cave shrine,Forest trek",
    latitude: "12.4350",
    longitude: "77.3850",
    popularity: 56,
  },
  {
    slug: "blr-chunchi-falls",
    name: "Chunchi Falls",
    baseCity: "Bangalore",
    category: "adventure",
    shortDescription: "Arkavathi river waterfall in a rocky gorge beyond Kanakapura.",
    description: "Chunchi Falls, ~90 km from Bangalore past Kanakapura, is where the Arkavathi river drops about 50 feet through a rugged granite gorge. The cascade is fullest after the monsoon and sits in scenic, semi-wild surroundings near the Mekedatu road. Swimming is risky here, so it is best enjoyed as a viewpoint.",
    distanceKm: 90,
    drivingMinutes: 135,
    entryFeePerPerson: 0,
    idealHoursAtPlace: 2,
    bestStartTime: "07:00",
    highlights: "Arkavathi falls,Rocky gorge,Monsoon views",
    latitude: "12.3360",
    longitude: "77.4060",
    popularity: 60,
  },
  {
    slug: "blr-muthathi",
    name: "Muthathi",
    baseCity: "Bangalore",
    category: "adventure",
    shortDescription: "Cauvery riverside getaway in Cauvery Wildlife Sanctuary, great for picnics and birding.",
    description: "Muthathi, ~95 km from Bangalore via Malavalli/Kanakapura, is a forested stretch along the Cauvery within the Cauvery Wildlife Sanctuary. Visitors come for riverside picnics, gentle rapids, coracle rides and a hilltop Anjaneya temple. Elephants and rich birdlife make the surrounding forest a draw.",
    distanceKm: 95,
    drivingMinutes: 150,
    entryFeePerPerson: 0,
    idealHoursAtPlace: 4,
    bestStartTime: "06:30",
    highlights: "Cauvery riverside,Coracle ride,Birding",
    latitude: "12.3060",
    longitude: "77.2640",
    popularity: 62,
  },
  {
    slug: "blr-galibore",
    name: "Galibore",
    baseCity: "Bangalore",
    category: "adventure",
    shortDescription: "Riverside nature camp on the Cauvery known for angling, birding and river dips.",
    description: "Galibore, ~100 km from Bangalore inside the Cauvery Wildlife Sanctuary, is a tranquil fishing and nature spot on the river. It is famed for catch-and-release mahseer angling, quiet riverside camps and excellent birdwatching. The forest around it is part of important elephant and otter habitat.",
    distanceKm: 100,
    drivingMinutes: 165,
    entryFeePerPerson: 0,
    idealHoursAtPlace: 4,
    bestStartTime: "06:30",
    highlights: "Mahseer angling,River camp,Birding",
    latitude: "12.3320",
    longitude: "77.2380",
    popularity: 53,
  },
  {
    slug: "blr-hesaraghatta-nrityagram",
    name: "Hesaraghatta Lake & Nrityagram",
    baseCity: "Bangalore",
    category: "heritage",
    shortDescription: "Grassland lake and the Nrityagram dance village on Bangalore's rural outskirts.",
    description: "Hesaraghatta, ~30 km northwest of Bangalore, pairs a large reservoir-fed grassland (an important birding and open space) with Nrityagram, the renowned dance gurukula founded by Protima Gauri. Nrityagram's rustic architecture and Odissi ensemble draw culture lovers. The open countryside is popular for cycling and weekend drives.",
    distanceKm: 30,
    drivingMinutes: 60,
    entryFeePerPerson: 20,
    idealHoursAtPlace: 3,
    bestStartTime: "07:30",
    highlights: "Nrityagram dance village,Grassland lake,Birding",
    latitude: "13.1390",
    longitude: "77.4760",
    popularity: 57,
  },
  {
    slug: "blr-kabbaladurga",
    name: "Kabbaladurga",
    baseCity: "Bangalore",
    category: "adventure",
    shortDescription: "Challenging granite hill-fort trek near Kanakapura with a summit shrine.",
    description: "Kabbaladurga, ~75 km from Bangalore near Kanakapura, is a steep, rocky hill once fortified by local chieftains. The trek involves boulder scrambles and rock-cut footholds up to ruined fort walls and a small temple. Its airy summit gives wide views and it is best attempted in the cooler early hours.",
    distanceKm: 75,
    drivingMinutes: 120,
    entryFeePerPerson: 0,
    idealHoursAtPlace: 3,
    bestStartTime: "05:30",
    highlights: "Steep fort trek,Boulder scramble,Summit shrine",
    latitude: "12.6300",
    longitude: "77.3600",
    popularity: 51,
  },
  {
    slug: "blr-huliyurdurga",
    name: "Huliyurdurga",
    baseCity: "Bangalore",
    category: "adventure",
    shortDescription: "Conical monolith hill-fort near Kunigal with a steep boulder trek.",
    description: "Huliyurdurga, ~80 km from Bangalore in Tumakuru district near Kunigal, rises as a striking conical granite monolith once crowned by a fort. The trek climbs steep rock with a few exposed sections to reach old fortifications and a small shrine. It is a lesser-known but rewarding adventure outing.",
    distanceKm: 80,
    drivingMinutes: 120,
    entryFeePerPerson: 0,
    idealHoursAtPlace: 3,
    bestStartTime: "05:30",
    highlights: "Monolith trek,Fort ruins,Wide views",
    latitude: "12.9410",
    longitude: "77.0220",
    popularity: 48,
  },
  {
    slug: "blr-kunigal-lake",
    name: "Kunigal Lake",
    baseCity: "Bangalore",
    category: "wildlife",
    shortDescription: "Large bird-rich lake town near Tumkur, an easy relaxed day outing.",
    description: "Kunigal, ~70 km from Bangalore in Tumakuru district, is built around one of the region's biggest tanks, drawing migratory and resident waterbirds. The town also has a historic stud farm legacy and old temples. It makes a calm, scenic stop for birding and lakeside picnics.",
    distanceKm: 70,
    drivingMinutes: 100,
    entryFeePerPerson: 0,
    idealHoursAtPlace: 2,
    bestStartTime: "07:00",
    highlights: "Birding lake,Lakeside picnic,Old temples",
    latitude: "13.0230",
    longitude: "77.0250",
    popularity: 46,
  },
  {
    slug: "blr-gudibande-fort",
    name: "Gudibande Fort",
    baseCity: "Bangalore",
    category: "adventure",
    shortDescription: "Tiered 17th-century hill fort near Chickballapur with stepwells and easy views.",
    description: "Gudibande Fort, ~95 km north of Bangalore in Chikkaballapura district, was built by chieftain Byre Gowda in the 17th century. A relatively gentle stepped climb leads through multiple tiers, stone gateways and rock-cut water cisterns to a small temple and watchtower. The nearby Amani Bhyrasagara reservoir adds to the views.",
    distanceKm: 95,
    drivingMinutes: 130,
    entryFeePerPerson: 0,
    idealHoursAtPlace: 3,
    bestStartTime: "06:30",
    highlights: "Tiered fort,Rock cisterns,Reservoir views",
    latitude: "13.6700",
    longitude: "77.7080",
    popularity: 59,
  },
  {
    slug: "blr-avani",
    name: "Avani",
    baseCity: "Bangalore",
    category: "heritage",
    shortDescription: "Ancient temple cluster near Mulbagal linked to the Ramayana, the 'Gaya of the South'.",
    description: "Avani, ~95 km from Bangalore near Mulbagal in Kolar district, is associated with sage Valmiki and the birth of Lava and Kusha. A fine cluster of Nolamba-Chola-era stone temples (the Rameshwara group) sits at the hill's base, with a Sita temple atop the rocky hill. It is a quiet heritage and pilgrimage spot.",
    distanceKm: 95,
    drivingMinutes: 135,
    entryFeePerPerson: 0,
    idealHoursAtPlace: 2,
    bestStartTime: "07:00",
    highlights: "Ancient stone temples,Sita hill shrine,Ramayana legend",
    latitude: "13.1430",
    longitude: "78.4760",
    popularity: 49,
  },
  {
    slug: "blr-vidurashwatha",
    name: "Vidurashwatha",
    baseCity: "Bangalore",
    category: "heritage",
    shortDescription: "Historic Gowribidanur village, the 'Jallianwala Bagh of the South' freedom memorial.",
    description: "Vidurashwatha, ~80 km from Bangalore near Gowribidanur, is remembered for the 1938 firing on freedom-movement protesters that earned it the name 'Jallianwala Bagh of the South'. A memorial (Veera Soudha) and the ancient Ashwatha Narayana temple stand here. It is a meaningful heritage and pilgrimage stop.",
    distanceKm: 80,
    drivingMinutes: 120,
    entryFeePerPerson: 0,
    idealHoursAtPlace: 2,
    bestStartTime: "07:30",
    highlights: "Freedom memorial,Ashwatha temple,History",
    latitude: "13.6020",
    longitude: "77.5360",
    popularity: 45,
  },
  {
    slug: "blr-tg-halli",
    name: "Thippagondanahalli Reservoir (T.G. Halli)",
    baseCity: "Bangalore",
    category: "wildlife",
    shortDescription: "Scenic reservoir at the Arkavathi-Kumudvathi confluence west of Bangalore, good for birding.",
    description: "Thippagondanahalli Reservoir, ~35 km west of Bangalore near Tavarekere, was built in 1933 at the confluence of the Arkavathi and Kumudvathi rivers as a city water source. Its tree-lined banks and water attract many birds, making it a calm photography and picnic spot. Access can be regulated, so it is best as a scenic drive-and-view outing.",
    distanceKm: 35,
    drivingMinutes: 70,
    entryFeePerPerson: 0,
    idealHoursAtPlace: 2,
    bestStartTime: "07:00",
    highlights: "Reservoir views,Birding,River confluence",
    latitude: "12.9670",
    longitude: "77.3470",
    popularity: 47,
  },
  {
    slug: "blr-horsley-hills",
    name: "Horsley Hills",
    baseCity: "Bangalore",
    category: "hill_station",
    shortDescription: "Cool Andhra hill station near Madanapalle with viewpoints, a giant eucalyptus and zoo.",
    description: "Horsley Hills, ~145 km from Bangalore near Madanapalle in Andhra Pradesh, is a small forested hill station rising to about 1,265 m. Highlights include the Gali Bandalu and Tipperary viewpoints, a 150-year-old 'Kalyani' eucalyptus tree, a mini zoo and breezy walking trails. Its cool climate makes it a pleasant day escape.",
    distanceKm: 145,
    drivingMinutes: 195,
    entryFeePerPerson: 0,
    idealHoursAtPlace: 4,
    bestStartTime: "06:00",
    highlights: "Viewpoints,Giant eucalyptus,Cool climate",
    latitude: "13.6580",
    longitude: "78.4060",
    popularity: 72,
  },
  {
    slug: "blr-markonahalli-dam",
    name: "Markonahalli Dam",
    baseCity: "Bangalore",
    category: "adventure",
    shortDescription: "Heritage siphon-system dam on the Shimsha river near Kunigal, a quiet picnic spot.",
    description: "Markonahalli Dam, ~90 km from Bangalore near Kunigal in Tumakuru district, is a historic dam on the Shimsha river noted for its early automatic siphon spillway system. The wide backwaters and green surroundings make it a peaceful, offbeat picnic and photography spot. It is best visited when the reservoir is full after the rains.",
    distanceKm: 90,
    drivingMinutes: 130,
    entryFeePerPerson: 0,
    idealHoursAtPlace: 2,
    bestStartTime: "07:00",
    highlights: "Siphon dam,Backwaters,Picnic spot",
    latitude: "12.9600",
    longitude: "76.9300",
    popularity: 44,
  },
];
