import type { NewDestination } from "../schema";

// Karnataka — Kittur Karnataka (Belagavi, Dharwad, Gadag, Haveri, Bagalkote, Vijayapura)
export const karnatakaKitturRegion: Omit<NewDestination, "id" | "createdAt">[] = [
  // ===================== VIJAYAPURA (BIJAPUR) =====================
  {
    slug: "gol-gumbaz",
    name: "Gol Gumbaz",
    state: "Karnataka",
    district: "Vijayapura",
    category: "heritage",
    placeType: "Monument",
    shortDescription:
      "Mausoleum of Mohammed Adil Shah crowned by one of the world's largest unsupported domes and a famous whispering gallery.",
    description: "Gol Gumbaz is the tomb of Sultan Mohammed Adil Shah, completed in 1656, and is famed for its enormous hemispherical dome, among the largest single-chamber domes in the world. The encircling Whispering Gallery carries the faintest sound across the hall, and the four seven-storey octagonal minarets offer sweeping views over Vijayapura. The complex includes a gateway, mosque and a museum of Adil Shahi relics. This ASI-protected monument is open 10 AM-5 PM and closed on Fridays; booking online saves a few rupees over the cash counter price.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Gol_Gumbaj2.JPG/1280px-Gol_Gumbaj2.JPG",
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 25,
    entryFeesForeigner: 300,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 90,
    latitude: "16.8300989",
    longitude: "75.73612039999999",
  },
  {
    slug: "ibrahim-rauza",
    name: "Ibrahim Rauza",
    state: "Karnataka",
    district: "Vijayapura",
    category: "heritage",
    placeType: "Tomb Complex",
    shortDescription:
      "Elegant Adil Shahi tomb and mosque garden complex, said to have inspired the design of the Taj Mahal.",
    description:
      "Ibrahim Rauza is the tomb of Ibrahim Adil Shah II and his queen Taj Sultana, set within a walled garden alongside a matching mosque on a raised plinth. Renowned for its finely carved stonework, slender minarets and graceful proportions, it is often called the 'Black Taj' and is believed to have influenced Mughal tomb architecture. The symmetry of the twin structures across an ornamental tank is among Vijayapura's finest sights.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Ibrahim_Roza.jpg/1280px-Ibrahim_Roza.jpg",
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 25,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 80,
    latitude: "16.8270326",
    longitude: "75.7026712",
  },
  {
    slug: "bara-kaman",
    name: "Bara Kaman",
    state: "Karnataka",
    district: "Vijayapura",
    category: "heritage",
    placeType: "Monument",
    shortDescription:
      "Unfinished mausoleum of Ali Adil Shah II, a striking row of soaring arches left incomplete.",
    description:
      "Bara Kaman is the unfinished tomb of Ali Adil Shah II, planned as a grand mausoleum of twelve arches but abandoned after his death. Today its surviving arches rise dramatically against the sky over the graves below, lending the ruin an evocative, melancholy beauty. Legend holds that the monument was deliberately left incomplete so it would not overshadow Gol Gumbaz.",
    imageUrl: null,
    openingTimings: "8:00 AM - 5:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 68,
    latitude: "16.8303151",
    longitude: "75.7182706",
  },
  {
    slug: "jama-masjid-vijayapura",
    name: "Jama Masjid, Vijayapura",
    state: "Karnataka",
    district: "Vijayapura",
    category: "pilgrimage",
    placeType: "Mosque",
    shortDescription:
      "Grand congregational mosque begun by Ali Adil Shah I, among the earliest and largest mosques in the Deccan.",
    description:
      "The Jama Masjid of Vijayapura was begun by Ali Adil Shah I in the 16th century and is one of the first great mosques of the Deccan. Its vast prayer hall is divided into rows of bays beneath an elegant onion dome, and the floor is famously painted with the outlines of hundreds of individual prayer rugs. The arcaded courtyard and restrained ornament make it a landmark of Adil Shahi architecture.",
    imageUrl: null,
    openingTimings: "5:00 AM - 9:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 66,
    latitude: "16.8219818",
    longitude: "75.7285982",
  },
  {
    slug: "malik-e-maidan",
    name: "Malik-e-Maidan",
    state: "Karnataka",
    district: "Vijayapura",
    category: "heritage",
    placeType: "Historic Cannon",
    shortDescription:
      "One of the largest medieval cannons in the world, mounted on the Sherza Burj bastion of Vijayapura fort.",
    description:
      "Malik-e-Maidan, 'Monarch of the Plains', is a colossal bell-metal cannon captured by the Adil Shahis and hauled to Vijayapura by elephants and bullocks. Cast in the 16th century, it is among the largest medieval cannons ever made, its muzzle shaped like a lion's jaws devouring an elephant. It sits atop the Sherza Burj bastion of the city's fortifications.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5b/Malik_E_Maidan.jpg",
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 62,
    latitude: "16.8317487",
    longitude: "75.7089292",
  },
  {
    slug: "upli-buruj",
    name: "Upli Buruj",
    state: "Karnataka",
    district: "Vijayapura",
    category: "heritage",
    placeType: "Watchtower",
    shortDescription:
      "Tall round watchtower on a mound, reached by a spiral external stair, with two huge cannons and city views.",
    description:
      "Upli Buruj is a sturdy cylindrical watchtower built on a raised mound by the Adil Shahi commander Haidar Khan in the late 16th century. A winding external stairway climbs its outer wall to a platform mounting two enormous cannons, from where there are panoramic views across Vijayapura. It was a key observation post in the city's defensive ring.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 52,
    latitude: "16.8312",
    longitude: "75.7170",
  },
  {
    slug: "asar-mahal",
    name: "Asar Mahal",
    state: "Karnataka",
    district: "Vijayapura",
    category: "heritage",
    placeType: "Hall / Monument",
    shortDescription:
      "Adil Shahi hall of justice with a reflecting tank, said to enshrine relics of the Prophet Muhammad.",
    description:
      "Asar Mahal was built by Mohammed Adil Shah around 1646 as a Hall of Justice and later venerated as a shrine said to hold sacred relics, including hairs of the Prophet's beard. The two-storey structure has wooden pillars, fine fresco fragments and an ornamental water tank in front. Women are traditionally not permitted into the inner sanctum.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/GolGumbaz2.jpg/1280px-GolGumbaz2.jpg",
    openingTimings: "6:00 AM - 8:30 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 50,
    latitude: "16.8259949",
    longitude: "75.72238279999999",
  },
  {
    slug: "gagan-mahal-vijayapura",
    name: "Gagan Mahal, Vijayapura",
    state: "Karnataka",
    district: "Vijayapura",
    category: "heritage",
    placeType: "Palace Ruins",
    shortDescription:
      "Ruined Adil Shahi durbar hall and royal palace with a vast central arch facing an open ground.",
    description:
      "Gagan Mahal, 'Sky Palace', was built by Ali Adil Shah I around 1561 as a combined royal residence and durbar hall. Its surviving facade is dominated by a huge central arch flanked by two smaller ones, designed so the public could see the seated sultan. Though largely ruined, the scale of the open audience hall still conveys the grandeur of the Adil Shahi court.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 48,
    latitude: "16.8290",
    longitude: "75.7223",
  },
  {
    slug: "sangameshwara-temple-vijayapura",
    name: "Sangameshwara Temple, Vijayapura",
    state: "Karnataka",
    district: "Vijayapura",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription:
      "Old Chalukya-era Shiva temple near Vijayapura, a quiet site of stone craftsmanship and worship.",
    description:
      "The Sangameshwara Temple is an early stone Shiva shrine of Chalukyan lineage in the Vijayapura region, valued for its restrained carving and continuing worship. Set apart from the city's Islamic monuments, it offers a glimpse of the area's older Hindu heritage. The sanctum enshrines a Shiva linga venerated by local devotees.",
    imageUrl: null,
    openingTimings: "6:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 850,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 42,
    latitude: "16.8200",
    longitude: "75.7100",
  },

  // ===================== BAGALKOTE =====================
  {
    slug: "badami-cave-temples",
    name: "Badami Cave Temples",
    state: "Karnataka",
    district: "Bagalkote",
    category: "heritage",
    placeType: "Rock-cut Caves",
    shortDescription:
      "Four rock-cut Chalukyan cave temples carved into a red sandstone cliff overlooking Agastya Lake.",
    description: "Badami, the former Chalukyan capital Vatapi, is famous for four rock-cut cave temples carved into a sandstone cliff in the 6th-7th centuries. Three are dedicated to Vishnu and Shiva and one to Jain Tirthankaras, with masterful sculpture including the dancing Nataraja and Vishnu seated on the serpent Ananta. The caves overlook the green Agastya Lake, flanked by ancient temples and a hilltop fort. This ASI-protected site is open 9 AM-5:30 PM daily; children under 15 enter free.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 25,
    entryFeesForeigner: 300,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 88,
    latitude: "15.9182858",
    longitude: "75.6841104",
  },
  {
    slug: "agastya-lake-badami",
    name: "Agastya Lake",
    state: "Karnataka",
    district: "Bagalkote",
    category: "adventure",
    placeType: "Lake",
    shortDescription:
      "Ancient man-made lake at Badami ringed by sandstone cliffs, cave temples and the Bhutanatha shrines.",
    description:
      "Agastya Lake is a centuries-old reservoir at the heart of Badami, framed by the red sandstone hills that hold the cave temples. The Bhutanatha group of temples sits at its eastern edge, their reflections forming one of the town's iconic views. The lakeside ghats and surrounding cliffs make it a scenic focal point for visitors exploring the Chalukyan ruins.",
    imageUrl: null,
    openingTimings: "Open 24 hours",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 64,
    latitude: "15.9196902",
    longitude: "75.6866252",
  },
  {
    slug: "aihole",
    name: "Aihole",
    state: "Karnataka",
    district: "Bagalkote",
    category: "heritage",
    placeType: "Temple Complex / Ruins",
    shortDescription:
      "Cradle of Chalukyan temple architecture with over a hundred shrines, including the Durga and Lad Khan temples.",
    description:
      "Aihole is celebrated as a 'cradle of Indian temple architecture', where the Chalukyas experimented with stone temple forms from the 5th to 8th centuries. Among its scores of shrines are the apsidal Durga Temple, the early Lad Khan Temple and the Ravalphadi cave, showing the transition from Buddhist and rock-cut styles to structured Hindu temples. The Meguti Jain temple on the hill bears one of the region's important early inscriptions.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 25,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 80,
    latitude: "16.0200011",
    longitude: "75.8814609",
  },
  {
    slug: "pattadakal",
    name: "Pattadakal",
    state: "Karnataka",
    district: "Bagalkote",
    category: "heritage",
    placeType: "UNESCO World Heritage Site",
    shortDescription:
      "UNESCO-listed group of Chalukyan coronation temples blending northern and southern architectural styles.",
    description:
      "Pattadakal is a UNESCO World Heritage Site where the Chalukyas built a remarkable group of temples, used for royal coronations, that fuse the Nagara (northern) and Dravida (southern) styles. The Virupaksha Temple, raised by Queen Lokamahadevi, and the Mallikarjuna and Sangameshwara temples are richly carved with scenes from the epics. Set on the banks of the Malaprabha, it represents the high point of early Chalukyan architecture.",
    imageUrl: null,
    openingTimings: "9:00 AM - 6:00 PM",
    entryFees: 40,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 85,
    latitude: "15.9495996",
    longitude: "75.81625199999999",
  },
  {
    slug: "banashankari-temple-badami",
    name: "Banashankari Temple",
    state: "Karnataka",
    district: "Bagalkote",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription:
      "Ancient Shakti temple of goddess Banashankari near Badami, famed for its Haridra Tirtha tank and annual fair.",
    description:
      "The Banashankari Amma Temple at Cholachagudd near Badami is dedicated to a fierce form of Parvati and has roots going back to the Chalukyan era, with the present structure rebuilt in later centuries. Devotees throng its large stepped tank, the Haridra Tirtha, and the temple draws huge crowds during the Banashankari Jatre fair in winter. It remains one of the most revered Shakti shrines of north Karnataka.",
    imageUrl: null,
    openingTimings: "6:00 AM - 9:00 PM",
    entryFees: 0,
    budgetPerDay: 850,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 70,
    latitude: "15.887266",
    longitude: "75.704442",
  },
  {
    slug: "mahakuta-temple",
    name: "Mahakuta Temple",
    state: "Karnataka",
    district: "Bagalkote",
    category: "pilgrimage",
    placeType: "Temple Complex",
    shortDescription:
      "Chalukyan Shaiva temple cluster around a perennial spring-fed tank near Badami.",
    description:
      "Mahakuta is a serene group of Chalukyan temples built around a natural spring-fed bathing tank, Vishnu Pushkarni, set in a wooded hollow near Badami. The Mahakuteshwara and Mallikarjuna shrines, dedicated to Shiva, are richly carved and date from the 6th–7th centuries. The constantly flowing tank, considered sacred, makes the complex a tranquil pilgrimage spot.",
    imageUrl: null,
    openingTimings: "6:00 AM - 7:00 PM",
    entryFees: 0,
    budgetPerDay: 850,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 56,
    latitude: "15.9430",
    longitude: "75.7440",
  },
  {
    slug: "kudala-sangama",
    name: "Kudala Sangama",
    state: "Karnataka",
    district: "Bagalkote",
    category: "pilgrimage",
    placeType: "Pilgrimage Site",
    shortDescription:
      "Sacred confluence of the Krishna and Malaprabha rivers and the samadhi of social reformer Basavanna.",
    description:
      "Kudala Sangama lies at the confluence of the Krishna and Malaprabha rivers and is a major Lingayat pilgrimage centre, holding the Aikya Mantapa where the 12th-century reformer-poet Basavanna is believed to have merged with the divine. The site has the ancient Sangameshwara temple and a modern memorial complex. Backwaters of the Almatti dam add to its scenic setting.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Kudalasangama.jpg/1280px-Kudalasangama.jpg",
    openingTimings: "6:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 850,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 64,
    latitude: "16.2071115",
    longitude: "76.0658875",
  },
  {
    slug: "almatti-dam",
    name: "Almatti Dam",
    state: "Karnataka",
    district: "Bagalkote",
    category: "adventure",
    placeType: "Dam / Garden",
    shortDescription:
      "Major dam across the Krishna with a vast reservoir, musical fountain and the Lal Bahadur Shastri gardens.",
    description:
      "The Almatti Dam, part of the Upper Krishna Project, holds back a huge reservoir across the Krishna river and is a popular outing for its landscaped Lal Bahadur Shastri gardens, terraced lawns and rock garden. Evening musical fountain shows and views of the spillway in flood season draw families and tourists. The backwaters support fishing and birdlife.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Almatti_Dam_26.jpg/1280px-Almatti_Dam_26.jpg",
    openingTimings: "9:30 AM - 7:30 PM",
    entryFees: 20,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Aug,Sep,Oct,Nov,Dec,Jan",
    isHidden: false,
    popularity: 62,
    latitude: "16.330476",
    longitude: "75.886512",
  },
  {
    slug: "bagalkot-town",
    name: "Bagalkot",
    state: "Karnataka",
    district: "Bagalkote",
    category: "heritage",
    placeType: "Heritage Town",
    shortDescription:
      "Historic district town on the Ghataprabha, a base for Badami, Aihole and Pattadakal with old temples nearby.",
    description:
      "Bagalkot is the district headquarters set near the Ghataprabha river and serves as the gateway for the Chalukyan heritage triangle of Badami, Aihole and Pattadakal. Parts of the old town were resettled as Navanagar after the Almatti reservoir rose, blending modern planning with older shrines and markets. It is a practical hub for exploring the region's monuments.",
    imageUrl: null,
    openingTimings: "Open 24 hours",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 44,
    latitude: "16.1850",
    longitude: "75.6960",
  },

  // ===================== GADAG =====================
  {
    slug: "trikuteshwara-temple-gadag",
    name: "Trikuteshwara Temple",
    state: "Karnataka",
    district: "Gadag",
    category: "pilgrimage",
    placeType: "Temple Complex",
    shortDescription:
      "Chalukyan temple at Gadag with three lingas in one sanctum and the famed musical Saraswati pillars.",
    description:
      "The Trikuteshwara Temple at Gadag is a Kalyani Chalukyan complex whose main shrine enshrines three Shiva lingas in a single sanctum, giving it its name. Adjoining is the Saraswati shrine, celebrated for its intricately carved, lathe-turned stone pillars and the image of the goddess of learning. The lavish surface ornament makes it one of the finest temples of the region.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Gadag_Trikuteshwara_temple_complex_3.JPG/1280px-Gadag_Trikuteshwara_temple_complex_3.JPG",
    openingTimings: "6:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 850,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 62,
    latitude: "15.4244977",
    longitude: "75.6267457",
  },
  {
    slug: "veeranarayana-temple-gadag",
    name: "Veeranarayana Temple, Gadag",
    state: "Karnataka",
    district: "Gadag",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription:
      "Chalukyan Vishnu temple at Gadag linked to the poet Kumara Vyasa, who composed his Kannada Mahabharata here.",
    description:
      "The Veeranarayana Temple at Gadag is a Chalukyan-era Vishnu shrine renowned in Kannada literary tradition as the place where the medieval poet Kumara Vyasa composed his Gadugina Bharata, the Kannada Mahabharata. The pillared hall and carved pillars retain their old-world atmosphere, and the deity Veeranarayana is worshipped with devotion. It is both a religious and cultural landmark.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Veera_Narayana_Temple%2C_Gadag.jpg",
    openingTimings: "6:30 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 850,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 50,
    latitude: "15.431679",
    longitude: "75.6270108",
  },
  {
    slug: "lakkundi-monuments",
    name: "Lakkundi Monuments",
    state: "Karnataka",
    district: "Gadag",
    category: "heritage",
    placeType: "Temple Town / Ruins",
    shortDescription:
      "Historic temple town with dozens of Chalukyan temples, ornate stepwells (kalyanis) and the Kashivishweshwara shrine.",
    description:
      "Lakkundi is an open-air museum of Kalyani Chalukyan art, dotted with scores of intricately carved temples and stepped wells built in soapstone. The Kashivishweshwara Temple, with its exquisitely sculptured double shrine, and the Brahma Jinalaya, the largest of its Jain basadis, are highlights. The town's ornate kalyanis, such as Musukina Bavi, show the era's mastery of water architecture.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/11th_century_Kasivisvesvara_temple%2C_Lakkundi%2C_Karnataka_India_-_12.jpg/1280px-11th_century_Kasivisvesvara_temple%2C_Lakkundi%2C_Karnataka_India_-_12.jpg",
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 66,
    latitude: "15.3895257",
    longitude: "75.71422419999999",
  },
  {
    slug: "doddabasappa-temple-dambal",
    name: "Doddabasappa Temple, Dambal",
    state: "Karnataka",
    district: "Gadag",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription:
      "Chalukyan Shiva temple at Dambal famous for its unique 24-pointed star-shaped plan and Nandi.",
    description:
      "The Doddabasappa Temple at Dambal is a distinctive Kalyani Chalukyan Shiva shrine built on an unusual 24-pointed stellate (star-shaped) plan, an architectural rarity. Its richly moulded walls, lathe-turned pillars and large Nandi reflect the sophistication of 12th-century craftsmen. Dambal was also an important historic centre with Buddhist and Jain associations.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 850,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 48,
    latitude: "15.3024723",
    longitude: "75.7716868",
  },
  {
    slug: "kappattagudda",
    name: "Kappattagudda Hills",
    state: "Karnataka",
    district: "Gadag",
    category: "hill_station",
    placeType: "Hill Range / Reserve",
    shortDescription:
      "Forested hill range and conservation reserve in Gadag rich in medicinal plants, wildlife and trekking trails.",
    description:
      "Kappattagudda is a low forested hill range in Gadag district, designated a conservation reserve for its biodiversity and rich stock of medicinal herbs. The hills shelter wildlife such as wolves, pangolins and many bird species, and offer trekking trails and the Nandivelaga and Shanteshwara shrines on the heights. It is a green oasis amid the otherwise dry plains of the region.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Aug,Sep,Oct,Nov,Dec,Jan",
    isHidden: true,
    popularity: 52,
    latitude: "15.3500",
    longitude: "75.8000",
  },
  {
    slug: "sudi-temples",
    name: "Sudi Temples",
    state: "Karnataka",
    district: "Gadag",
    category: "heritage",
    placeType: "Temple Ruins",
    shortDescription:
      "Chalukyan twin-towered Mallikarjuna temple and other shrines at the historic village of Sudi.",
    description:
      "Sudi was an important administrative centre under the Kalyani Chalukyas and preserves notable temples, chief among them the Mallikarjuna Temple with its rare twin towers (shikharas). The Naganatha Temple and old inscriptions add to the village's historical significance. The carving and layout illustrate the regional Chalukyan style away from the better-known sites.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 850,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 40,
    latitude: "15.4750",
    longitude: "75.7780",
  },
  {
    slug: "magadi-bird-sanctuary",
    name: "Magadi Bird Sanctuary",
    state: "Karnataka",
    district: "Gadag",
    category: "wildlife",
    placeType: "Bird Sanctuary",
    shortDescription:
      "Wetland near Gadag that hosts thousands of migratory bar-headed geese and other waterbirds in winter.",
    description:
      "Magadi Kere is a man-made tank and conservation reserve near Shirahatti in Gadag district that becomes a major wintering ground for migratory birds. It is especially famous for large flocks of bar-headed geese arriving from Central Asia, alongside painted storks, pelicans and many ducks. Watch-towers and the open water make it a fine birdwatching destination between November and February.",
    imageUrl: null,
    openingTimings: "6:30 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 850,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 50,
    latitude: "15.5180",
    longitude: "75.6840",
  },

  // ===================== HAVERI =====================
  {
    slug: "bankapura-peacock-sanctuary",
    name: "Bankapura Peacock Sanctuary",
    state: "Karnataka",
    district: "Haveri",
    category: "wildlife",
    placeType: "Peacock Sanctuary",
    shortDescription:
      "One of only two peacock-dedicated sanctuaries in India, set within the ruins of Bankapura fort.",
    description:
      "Bankapura Peacock Sanctuary, on the grounds of the historic Bankapura fort, is one of India's only two sanctuaries dedicated to the peacock. Hundreds of Indian peafowl roam the wooded fort enclosure, especially active and displaying during the monsoon. The site also preserves remnants of the old fort and the Nagareshwara temple.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/34/Peacock_sanctuary_in_Bankapur.JPG",
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 850,
    recommendedDays: 1,
    bestMonths: "Jun,Jul,Aug,Sep,Oct",
    isHidden: false,
    popularity: 60,
    latitude: "14.923488",
    longitude: "75.2551397",
  },
  {
    slug: "ranebennur-blackbuck-sanctuary",
    name: "Ranebennur Blackbuck Sanctuary",
    state: "Karnataka",
    district: "Haveri",
    category: "wildlife",
    placeType: "Wildlife Sanctuary",
    shortDescription:
      "Grassland sanctuary near Ranebennur protecting blackbuck and the rare great Indian bustard.",
    description:
      "Ranebennur Blackbuck Sanctuary protects open grassland and scrub habitat that shelters a healthy population of Indian blackbuck antelope. It was also one of the last refuges of the critically endangered great Indian bustard and supports wolves, foxes and many birds. The eucalyptus-fringed plains make for rewarding wildlife drives and photography.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 58,
    latitude: "14.6190",
    longitude: "75.5980",
  },
  {
    slug: "tarakeshwara-temple-hangal",
    name: "Tarakeshwara Temple, Hangal",
    state: "Karnataka",
    district: "Haveri",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription:
      "Grand Kadamba–Chalukyan Shiva temple at Hangal with an ornate domed mantapa and fine stone carving.",
    description:
      "The Tarakeshwara Temple at Hangal is a large Shiva temple built under the Kadambas and later Chalukyas, noted for its magnificent navaranga hall crowned by a beautifully sculpted stone dome. Lathe-turned pillars, carved ceilings and finely worked doorways display the height of regional craftsmanship. Hangal itself was a significant historic capital.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/KITLV_88225_-_Unknown_-_Tarakeshvara_temple_at_Hangal_in_British_India_-_1897.tif/lossy-page1-1280px-KITLV_88225_-_Unknown_-_Tarakeshvara_temple_at_Hangal_in_British_India_-_1897.tif.jpg",
    openingTimings: "8:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 850,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 56,
    latitude: "14.7651605",
    longitude: "75.1238214",
  },
  {
    slug: "galageshwara-temple-galaganatha",
    name: "Galageshwara Temple, Galaganatha",
    state: "Karnataka",
    district: "Haveri",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription:
      "Chalukyan Shiva temple on the banks of the Tungabhadra at Galaganatha, with a tall ornate shikhara.",
    description:
      "The Galageshwara (Galagnatha) Temple stands on the bank of the Tungabhadra river and is a fine Kalyani Chalukyan Shiva shrine distinguished by its tall, intricately carved brick-and-stone tower. Its riverside setting and detailed sculpture make it a tranquil heritage spot. The temple is part of a cluster of old shrines at Galaganatha.",
    imageUrl: null,
    openingTimings: "7:00 AM - 7:00 PM",
    entryFees: 0,
    budgetPerDay: 850,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 44,
    latitude: "14.7430",
    longitude: "75.6890",
  },
  {
    slug: "siddheshwara-temple-haveri",
    name: "Siddheshwara Temple, Haveri",
    state: "Karnataka",
    district: "Haveri",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription:
      "Profusely carved Chalukyan Shiva temple in Haveri town, rich in sculptures of deities and motifs.",
    description:
      "The Siddheshwara Temple in Haveri town is a 12th-century Kalyani Chalukyan Shiva temple celebrated for the density and quality of its exterior sculpture, including images of various gods, dancers and decorative bands. The soapstone carving covers nearly every surface of the walls. It is one of the most ornate temples in the district.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Cardamom_dry.jpg/1280px-Cardamom_dry.jpg",
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 850,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 48,
    latitude: "14.7906412",
    longitude: "75.4106802",
  },
  {
    slug: "utsav-rock-garden",
    name: "Utsav Rock Garden",
    state: "Karnataka",
    district: "Haveri",
    category: "adventure",
    placeType: "Rock Garden / Sculpture Park",
    shortDescription:
      "Sprawling theme park of life-size rural sculptures and rock art depicting North Karnataka village life.",
    description:
      "Utsav Rock Garden, near Gotagodi on the Hubballi–Haveri highway, is a contemporary sculpture park created by artists who fashioned thousands of life-size figures portraying rural North Karnataka life. Tableaux of farmers, folk performers and village scenes are arranged across landscaped grounds with rock formations and water bodies. It is a popular family and school outing.",
    imageUrl: null,
    openingTimings: "9:00 AM - 6:00 PM",
    entryFees: 80,
    budgetPerDay: 950,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 64,
    latitude: "14.9510",
    longitude: "75.3120",
  },
  {
    slug: "kaginele",
    name: "Kaginele",
    state: "Karnataka",
    district: "Haveri",
    category: "pilgrimage",
    placeType: "Temple Town",
    shortDescription:
      "Sacred town linked to the saint-poet Kanaka Dasa, with the Adikeshava temple and a major matha.",
    description:
      "Kaginele is a revered pilgrimage town in Haveri district associated with the 16th-century Dasa saint and Kannada poet Kanaka Dasa, who worshipped the deity Adikeshava here. The Kaginele Kanaka Gurupeetha matha and the Adikeshava temple draw devotees, especially from the Kuruba community. The town is an important cultural and devotional centre of the region.",
    imageUrl: null,
    openingTimings: "6:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 42,
    latitude: "14.5640",
    longitude: "75.6360",
  },

  // ===================== DHARWAD =====================
  {
    slug: "nrupatunga-betta",
    name: "Nrupatunga Betta",
    state: "Karnataka",
    district: "Dharwad",
    category: "hill_station",
    placeType: "Hilltop Viewpoint",
    shortDescription:
      "Popular hillock viewpoint and park in Hubballi offering sweeping views of the twin cities.",
    description:
      "Nrupatunga Betta is a landscaped hilltop on the edge of Hubballi, a favourite spot for sunrise and sunset views over the Hubballi–Dharwad conurbation. The park has walking paths, a children's play area, a watch point and a small shrine, named after the Rashtrakuta king Nrupatunga Amoghavarsha. It is a relaxed urban getaway and evening hangout.",
    imageUrl: null,
    openingTimings: "6:00 AM - 8:00 PM",
    entryFees: 10,
    budgetPerDay: 850,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 58,
    latitude: "15.3758872",
    longitude: "75.129363",
  },
  {
    slug: "unkal-lake",
    name: "Unkal Lake",
    state: "Karnataka",
    district: "Dharwad",
    category: "adventure",
    placeType: "Lake",
    shortDescription:
      "Large scenic lake in Hubballi with boating, a Swami Vivekananda island statue and lakeside gardens.",
    description:
      "Unkal Lake is a sprawling freshwater lake on the outskirts of Hubballi, a favourite recreation spot with boating, musical fountains and well-kept lakeside gardens. A tall statue of Swami Vivekananda stands on an island reached by boat, and the promenade is popular for evening walks. The lake also attracts migratory birds in winter.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Chandramouleshware_Temple.JPG/1280px-Chandramouleshware_Temple.JPG",
    openingTimings: "9:00 AM - 7:00 PM",
    entryFees: 0,
    budgetPerDay: 850,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 60,
    latitude: "15.3782466",
    longitude: "75.1063735",
  },
  {
    slug: "chandramouleshwara-temple-hubballi",
    name: "Chandramouleshwara Temple, Hubballi",
    state: "Karnataka",
    district: "Dharwad",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription:
      "Ancient Kalyani Chalukyan Shiva temple at Unkal, Hubballi, noted for its twin shrines and fine carving.",
    description:
      "The Chandramouleshwara Temple at Unkal in Hubballi is an old Kalyani Chalukyan Shiva temple, distinctive for its two facing sanctums and a central pillared hall. Its star-shaped plinth, carved pillars and decorated ceilings reflect the regional architectural style of around the 11th–12th centuries. It is one of the area's most historic shrines.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 48,
    latitude: "15.3768134",
    longitude: "75.11647119999999",
  },
  {
    slug: "sadhanakeri",
    name: "Sadhanakeri",
    state: "Karnataka",
    district: "Dharwad",
    category: "heritage",
    placeType: "Literary Memorial / Garden",
    shortDescription:
      "Memorial garden in Dharwad honouring the celebrated Kannada poet D. R. Bendre, made famous by his verse.",
    description:
      "Sadhanakeri is a quiet locality and memorial garden in Dharwad immortalised by the Jnanpith-winning Kannada poet D. R. Bendre, who drew inspiration from its surroundings. The site preserves his association with a small lake and greenery and is dear to lovers of Kannada literature. It reflects Dharwad's identity as a city of music, learning and letters.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Sadhankeri_locality.jpg/1280px-Sadhankeri_locality.jpg",
    openingTimings: "6:00 AM - 7:00 PM",
    entryFees: 0,
    budgetPerDay: 800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 44,
    latitude: "15.4640865",
    longitude: "74.99023509999999",
  },
  {
    slug: "navagraha-teertha-hubballi",
    name: "Navagraha Teertha, Hubballi",
    state: "Karnataka",
    district: "Dharwad",
    category: "pilgrimage",
    placeType: "Jain Temple",
    shortDescription:
      "Jain pilgrimage complex at Bhagavan Mahaveer Hill near Hubballi with a towering Parshvanatha idol.",
    description:
      "Navagraha Teertha, at Varur near Hubballi, is a modern Jain pilgrimage centre on Bhagavan Mahaveer Hill, famed for an enormous monolithic statue of Bhagwan Parshvanatha, one of the tallest such idols. Around the main image are shrines representing the nine planetary deities (navagraha) of Jain tradition. The hilltop complex draws pilgrims and visitors from across the region.",
    imageUrl: null,
    openingTimings: "6:00 AM - 7:00 PM",
    entryFees: 0,
    budgetPerDay: 850,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 54,
    latitude: "15.2890",
    longitude: "75.0290",
  },
  {
    slug: "nuggikeri-hanuman-temple-dharwad",
    name: "Nuggikeri Hanuman Temple, Dharwad",
    state: "Karnataka",
    district: "Dharwad",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription:
      "Popular lakeside Hanuman temple in Dharwad, a much-visited local shrine beside the Nuggikeri tank.",
    description:
      "The Nuggikeri Anjaneya (Hanuman) Temple in Dharwad is a well-loved local shrine set beside the Nuggikeri lake, drawing steady streams of devotees, especially on Saturdays. The lakeside setting and the revered Hanuman idol make it a peaceful spot of worship within the city. It is among Dharwad's most frequented temples.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/13/Nuggikeri_Shree_Hanuman_temple%2C_Dharwad.jpg",
    openingTimings: "6:00 AM - 8:30 PM",
    entryFees: 0,
    budgetPerDay: 800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 42,
    latitude: "15.4130864",
    longitude: "75.0054464",
  },

  // ===================== BELAGAVI (BELGAUM) =====================
  {
    slug: "belgaum-fort",
    name: "Belgaum Fort",
    state: "Karnataka",
    district: "Belagavi",
    category: "heritage",
    placeType: "Fort",
    shortDescription:
      "Historic moated fort in Belagavi with old gateways, mosques and the famous Kamala Basadi Jain temple inside.",
    description:
      "Belgaum Fort, originally built in the late 13th century and strengthened by successive rulers, is a sturdy moated fortress that has seen Ratta, Vijayanagara, Adil Shahi, Maratha and British control. Within its walls stand fine structures including the Safa and Jamia mosques and notable Jain basadis. It is a layered monument reflecting the city's long strategic importance.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Suvarna_Vidhana_Soudha.jpg/1280px-Suvarna_Vidhana_Soudha.jpg",
    openingTimings: "5:00 AM - 11:00 PM",
    entryFees: 0,
    budgetPerDay: 950,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 64,
    latitude: "15.8593875",
    longitude: "74.5243594",
  },
  {
    slug: "kamala-basadi",
    name: "Kamala Basadi",
    state: "Karnataka",
    district: "Belagavi",
    category: "pilgrimage",
    placeType: "Jain Temple",
    shortDescription:
      "Exquisite 13th-century Jain temple inside Belgaum Fort, famed for its lotus-carved ceiling and Neminatha idol.",
    description:
      "Kamala Basadi, within Belgaum Fort, is a beautiful Jain temple built by the Rattas around 1204 and dedicated to Tirthankara Neminatha. Its name derives from the magnificent stone lotus carved into the ceiling of the mantapa, a masterpiece of Chalukyan-style craftsmanship. The temple's finely worked pillars and black-stone idol make it a key Jain heritage site.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Old_jain_temple_belgaum_%281%29.jpg/1280px-Old_jain_temple_belgaum_%281%29.jpg",
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 52,
    latitude: "15.8580122",
    longitude: "74.52144539999999",
  },
  {
    slug: "saundatti-yellamma",
    name: "Saundatti Yellamma Temple",
    state: "Karnataka",
    district: "Belagavi",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription:
      "Hilltop temple of goddess Renuka–Yellamma at Saundatti, one of Karnataka's most thronged pilgrimage shrines.",
    description:
      "The Renuka Yellamma Temple atop a hill near Saundatti is among the most popular Shakti shrines in Karnataka, drawing huge crowds especially during full-moon festivals and the Yellamma jatre. The deity Yellamma (Renuka) is venerated across communities, and the hill offers wide views of the surrounding country and the Malaprabha valley. Devotees climb the steps to the ancient sanctum throughout the year.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b7/Savadatti_Renuka_temple.JPG",
    openingTimings: "6:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 850,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 70,
    latitude: "15.7544821",
    longitude: "75.15404649999999",
  },
  {
    slug: "gokak-falls",
    name: "Gokak Falls",
    state: "Karnataka",
    district: "Belagavi",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription:
      "Powerful horseshoe waterfall on the Ghataprabha river, often called the 'Niagara of Karnataka', with a hanging bridge.",
    description:
      "Gokak Falls is a broad horseshoe-shaped cascade where the Ghataprabha river plunges around 52 metres, earning it the nickname 'Mini Niagara of Karnataka'. A century-old hanging suspension bridge spans the gorge, and old Chalukyan temples and a heritage textile mill stand nearby. The falls are at their thundering best during and just after the monsoon.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Gokak_Falls_During_Night.jpg",
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 10,
    budgetPerDay: 950,
    recommendedDays: 1,
    bestMonths: "Jul,Aug,Sep,Oct,Nov",
    isHidden: false,
    popularity: 74,
    latitude: "16.1925858",
    longitude: "74.7770475",
  },
  {
    slug: "godachinmalki-falls",
    name: "Godachinmalki Falls",
    state: "Karnataka",
    district: "Belagavi",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription:
      "Two-tier waterfall on the Markandeya river near Gokak, set in a forested gorge reached by a short trek.",
    description:
      "Godachinmalki Falls, also called Markandeya Falls, is a scenic two-stepped cascade where the Markandeya river drops through a rocky, forested valley near Gokak. A trail and steps lead down to the lower pool, making it a rewarding short trek for nature lovers. The falls are most spectacular in the rainy season.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Godachinmalki_falls.jpg/1280px-Godachinmalki_falls.jpg",
    openingTimings: "8:00 AM - 5:30 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Jul,Aug,Sep,Oct,Nov",
    isHidden: true,
    popularity: 56,
    latitude: "16.1227793",
    longitude: "74.7499895",
  },
  {
    slug: "vajrapoha-falls",
    name: "Vajrapoha Falls",
    state: "Karnataka",
    district: "Belagavi",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription:
      "Remote forest waterfall deep in the Western Ghats of Khanapur taluk, reached by a guided trek.",
    description:
      "Vajrapoha Falls is a secluded waterfall hidden in the dense forests of Khanapur taluk in the Western Ghats of Belagavi district. Surrounded by thick green canopy and accessible only by a guided trek through reserve forest, it rewards adventurous visitors with pristine, untouched scenery. It flows strongest during the monsoon and is best explored with local guides.",
    imageUrl: null,
    openingTimings: "7:00 AM - 5:00 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Jul,Aug,Sep,Oct",
    isHidden: true,
    popularity: 46,
    latitude: "15.5800",
    longitude: "74.4500",
  },
  {
    slug: "sogal-someshwara",
    name: "Sogal Someshwara Temple",
    state: "Karnataka",
    district: "Belagavi",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription:
      "Hillside Shiva temple at Sogal near a seasonal waterfall, a local pilgrimage and picnic spot.",
    description:
      "The Someshwara Temple at Sogal is an old Shiva shrine set against a green hillside in Belagavi district, beside a seasonal waterfall that flows in the monsoon. The combination of the temple, the cascade and the surrounding hills makes it a favourite pilgrimage and picnic destination. An annual fair draws devotees from the region.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Sogal_1.jpg/1280px-Sogal_1.jpg",
    openingTimings: "6:00 AM - 7:00 PM",
    entryFees: 0,
    budgetPerDay: 850,
    recommendedDays: 1,
    bestMonths: "Jul,Aug,Sep,Oct,Nov",
    isHidden: true,
    popularity: 44,
    latitude: "15.9560",
    longitude: "74.7180",
  },
  {
    slug: "kittur-fort",
    name: "Kittur Fort",
    state: "Karnataka",
    district: "Belagavi",
    category: "heritage",
    placeType: "Fort",
    shortDescription:
      "Ruined fort of Rani Chennamma, the queen who led an early armed revolt against the British, with a museum.",
    description:
      "Kittur Fort is celebrated as the seat of Rani Chennamma, the warrior queen who rose against the British East India Company in 1824, years before the great revolt of 1857. Though largely in ruins, the fort grounds preserve the palace remains, a memorial and a museum displaying artefacts and weapons of the period. The site is a symbol of Karnataka's freedom struggle.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/ad/Kittur_Chenamma.jpg",
    openingTimings: "9:00 AM - 5:30 PM",
    entryFees: 10,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 60,
    latitude: "15.6360",
    longitude: "74.7980",
  },
  {
    slug: "hidkal-dam",
    name: "Hidkal Dam",
    state: "Karnataka",
    district: "Belagavi",
    category: "adventure",
    placeType: "Dam / Reservoir",
    shortDescription:
      "Large dam across the Ghataprabha with a scenic reservoir and gardens, a popular outing near Hukkeri.",
    description:
      "Hidkal Dam, also called the Rajarambapu (Ghataprabha) reservoir, impounds the Ghataprabha river and forms a vast lake set among low hills near Hukkeri. Landscaped gardens, the spillway in flood and boating make it a popular spot for families and day-trippers. The reservoir irrigates large tracts of the surrounding districts.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Hidkal_Dam.jpg",
    openingTimings: "9:00 AM - 6:00 PM",
    entryFees: 10,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Aug,Sep,Oct,Nov,Dec,Jan",
    isHidden: true,
    popularity: 50,
    latitude: "16.1462048",
    longitude: "74.642605",
  },
  {
    slug: "rakaskop-dam",
    name: "Rakaskop Dam",
    state: "Karnataka",
    district: "Belagavi",
    category: "adventure",
    placeType: "Dam / Reservoir",
    shortDescription:
      "Scenic old dam on the Markandeya river that supplies Belagavi city, surrounded by green hills and forest.",
    description:
      "Rakaskop Dam is a picturesque reservoir on the Markandeya river that has long supplied drinking water to Belagavi city. Ringed by wooded hills and farmland, it is a quiet getaway for picnics and photography, especially lush in and after the monsoon. The calm waters and greenery make it a refreshing escape from the city.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 850,
    recommendedDays: 1,
    bestMonths: "Jul,Aug,Sep,Oct,Nov",
    isHidden: true,
    popularity: 46,
    latitude: "15.8230",
    longitude: "74.4060",
  },
  {
    slug: "military-mahadeva-temple-belagavi",
    name: "Military Mahadeva Temple, Belagavi",
    state: "Karnataka",
    district: "Belagavi",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription:
      "Well-known Shiva temple in Belagavi's Camp area maintained by the army, popular during Mahashivaratri.",
    description:
      "The Military Mahadeva (Kapileshwar) Temple in the Camp area of Belagavi is a popular Shiva shrine associated with and kept by the local military cantonment. Clean, peaceful grounds and a revered Shiva linga draw steady worshippers, with large gatherings during Mahashivaratri. It is one of the city's better-known temples.",
    imageUrl: null,
    openingTimings: "6:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 44,
    latitude: "15.846171",
    longitude: "74.5047407",
  },
];
