import type { NewDestination } from "../schema";

// Karnataka — Kalyana Karnataka (Kalaburagi, Bidar, Yadgir, Raichur, Koppal, Ballari, Vijayanagara)
export const karnatakaKalyanaRegion: Omit<NewDestination, "id" | "createdAt">[] = [
  // ===================== KALABURAGI (GULBARGA) =====================
  {
    slug: "gulbarga-fort",
    name: "Gulbarga Fort",
    state: "Karnataka",
    district: "Kalaburagi",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Bahmani-era fort with a wide moat housing the grand Jama Masjid, the only mosque in India modelled on Cordoba's mosque.",
    description: "Gulbarga Fort was the first capital citadel of the Bahmani Sultanate, ringed by a deep moat and massive bastions. Within stands the Jama Masjid (1367), famous as the only mosque in India fully covered by domes and arched courtyards, said to be inspired by the Great Mosque of Cordoba. The fort also retains old gun emplacements and ruined palaces.",
    imageUrl: null,
    openingTimings: "9:00 AM - 5:30 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 74,
    latitude: "17.3300",
    longitude: "76.8197",
  },
  {
    slug: "khwaja-bande-nawaz-dargah",
    name: "Khwaja Bande Nawaz Dargah",
    state: "Karnataka",
    district: "Kalaburagi",
    category: "pilgrimage",
    placeType: "Dargah",
    shortDescription: "Revered 14th-century Sufi shrine of Hazrat Khwaja Bande Nawaz Gesu Daraz, a major pilgrimage centre of the Deccan.",
    description: "This dargah enshrines the tomb of the Chishti Sufi saint Hazrat Syed Muhammad Gesu Daraz Bande Nawaz, who settled in Gulbarga in 1397. The complex blends Bahmani and later Indo-Islamic styles with fine painted ceilings and calligraphy. Its annual Urs festival draws lakhs of pilgrims of all faiths.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/70/Portrait_of_Bande_Nawaz%2C_a_Sufi_saint_from_India.jpg",
    openingTimings: "5:00 AM - 10:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 80,
    latitude: "17.3439501",
    longitude: "76.85093979999999",
  },
  {
    slug: "sharana-basaveshwara-temple",
    name: "Sharana Basaveshwara Temple",
    state: "Karnataka",
    district: "Kalaburagi",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Major Lingayat temple dedicated to the 18th-century social reformer and saint Sharana Basaveshwara in the heart of Kalaburagi.",
    description: "The Sharana Basaveshwara Temple honours the saint-philosopher Sharana Basaveshwara, known for his Dasoha (selfless service) tradition. The temple has a large sacred tank and draws huge crowds during its annual jatra. It is one of the most important Veerashaiva-Lingayat pilgrimage sites in the region.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Gettyedu-2008.78.51-Retouched.jpg/1280px-Gettyedu-2008.78.51-Retouched.jpg",
    openingTimings: "6:00 AM - 9:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 72,
    latitude: "17.3362564",
    longitude: "76.82619969999999",
  },
  {
    slug: "buddha-vihar-kalaburagi",
    name: "Buddha Vihar Kalaburagi",
    state: "Karnataka",
    district: "Kalaburagi",
    category: "pilgrimage",
    placeType: "Buddhist Vihara",
    shortDescription: "Grand modern Buddhist monument blending the architecture of Sanchi, Sarnath, Ajanta and Nagpur, set in landscaped grounds.",
    description: "Buddha Vihar is a vast modern complex built by the Siddharth Vihar Trust, drawing design elements from Sanchi's stupa, Sarnath's pillar and Ajanta's caves. It houses a large prayer hall, a meditation centre and a striking dome. It has become a major spiritual and cultural landmark of Kalaburagi.",
    imageUrl: null,
    openingTimings: "9:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 66,
    latitude: "17.3050",
    longitude: "76.8050",
  },
  {
    slug: "sannati-kanaganahalli",
    name: "Sannati & Kanaganahalli",
    state: "Karnataka",
    district: "Kalaburagi",
    category: "heritage",
    placeType: "Archaeological Site",
    shortDescription: "Ancient Buddhist site on the Bhima river with a Mauryan-era Mahastupa and a rare relief portrait of Emperor Ashoka.",
    description: "Sannati and the adjoining mound of Kanaganahalli on the Bhima river preserve the remains of a great Buddhist Mahastupa dating from the Mauryan to Satavahana periods. Excavations revealed inscribed limestone slabs and a unique sculpted portrait panel labelled 'Raya Asoko' — the only known relief depiction of Emperor Ashoka. Sannati is also home to the Chandralamba temple.",
    imageUrl: null,
    openingTimings: "9:00 AM - 5:00 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 52,
    latitude: "16.835271",
    longitude: "76.9308159",
  },
  {
    slug: "haft-gumbaz-kalaburagi",
    name: "Haft Gumbaz",
    state: "Karnataka",
    district: "Kalaburagi",
    category: "heritage",
    placeType: "Tombs",
    shortDescription: "Cluster of seven domed Bahmani royal tombs, including the imposing mausoleum of Sultan Firoz Shah Bahmani.",
    description: "Haft Gumbaz ('seven domes') is a group of Bahmani royal tombs on the eastern edge of Gulbarga. The largest is the twin-domed tomb of Taj-ud-din Firoz Shah, decorated with carved stone and arabesque. The complex is a fine showcase of early Deccani funerary architecture.",
    imageUrl: null,
    openingTimings: "9:00 AM - 5:30 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 50,
    latitude: "17.3421087",
    longitude: "76.844779",
  },

  // ===================== BIDAR =====================
  {
    slug: "bidar-fort",
    name: "Bidar Fort",
    state: "Karnataka",
    district: "Bidar",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Sprawling medieval fort of the Bahmani and Barid Shahi dynasties with palaces, halls and a rock-cut triple moat.",
    description: "Bidar Fort is one of the most formidable forts of the Deccan, built in red laterite on a plateau edge. Inside lie the Rangin Mahal with its mother-of-pearl inlay, the Solah Khamba Mosque, Tarkash Mahal and Gagan Mahal, all ringed by a triple moat carved out of solid rock. It marks the high point of Bahmani-era architecture.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Guru_Nanak_Jhira_Sahib_gurdwara_in_Bidar%2C_Jul_2017.jpg/1280px-Guru_Nanak_Jhira_Sahib_gurdwara_in_Bidar%2C_Jul_2017.jpg",
    openingTimings: "9:00 AM - 5:00 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 80,
    latitude: "17.9210724",
    longitude: "77.53113350000001",
  },
  {
    slug: "mahmud-gawan-madrasa",
    name: "Mahmud Gawan Madrasa",
    state: "Karnataka",
    district: "Bidar",
    category: "heritage",
    placeType: "Madrasa",
    shortDescription: "Ruined 15th-century Islamic college of Persian design, once a leading centre of learning with a tall surviving minaret.",
    description: "Built in 1472 by the Bahmani prime minister Mahmud Gawan, this madrasa was modelled on the Persian colleges of Khorasan and once held a vast library. Though partly ruined by a gunpowder explosion and lightning, its remaining minaret and walls still carry brilliant turquoise, white and green glazed tile mosaics. It is a landmark of Indo-Persian architecture.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Complete_view_of_Mahumad_Gawan.JPG/1280px-Complete_view_of_Mahumad_Gawan.JPG",
    openingTimings: "9:00 AM - 5:30 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 70,
    latitude: "17.9148613",
    longitude: "77.53039369999999",
  },
  {
    slug: "bahmani-tombs-ashtur",
    name: "Bahmani Tombs at Ashtur",
    state: "Karnataka",
    district: "Bidar",
    category: "heritage",
    placeType: "Tombs",
    shortDescription: "Row of grand domed Bahmani royal mausoleums at Ashtur, famed for the vivid painted interior of Ahmad Shah's tomb.",
    description: "At Ashtur, a few kilometres from Bidar, stand twelve large domed tombs of the Bahmani sultans. The tomb of Ahmad Shah Al Wali is celebrated for its richly painted dome interior with Persian calligraphy and floral motifs in gold and colour. The monuments are a striking record of 15th-century Deccani funerary art.",
    imageUrl: null,
    openingTimings: "9:00 AM - 5:30 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 60,
    latitude: "17.9333",
    longitude: "77.5667",
  },
  {
    slug: "guru-nanak-jhira-sahib",
    name: "Guru Nanak Jhira Sahib",
    state: "Karnataka",
    district: "Bidar",
    category: "pilgrimage",
    placeType: "Gurudwara",
    shortDescription: "Major Sikh gurudwara built around a perennial spring said to have appeared at the touch of Guru Nanak Dev.",
    description: "Guru Nanak Jhira Sahib commemorates the visit of Guru Nanak Dev to Bidar, where a freshwater spring (jhira) is believed to have miraculously sprung up to relieve the people's drinking-water shortage. The white marble gurudwara around the spring and sarovar is one of the most important Sikh pilgrimage sites in South India.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Gurdwara_Nanak_Jhira_Sahib.jpg/1280px-Gurdwara_Nanak_Jhira_Sahib.jpg",
    openingTimings: "4:00 AM - 9:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 72,
    latitude: "17.9275296",
    longitude: "77.5079354",
  },
  {
    slug: "narasimha-jharni-bidar",
    name: "Narasimha Jharni",
    state: "Karnataka",
    district: "Bidar",
    category: "pilgrimage",
    placeType: "Cave Temple",
    shortDescription: "Unique cave shrine of Narasimha reached by wading neck-deep through a 300-metre water tunnel inside a hill.",
    description: "Narasimha Jharni (Jharani) is a remarkable cave temple where devotees wade about 300 metres through chest- to neck-deep spring water inside a dark tunnel to reach the Lakshmi Narasimha idol. The cave is believed to be linked to the slaying of the demon Jharasura. It offers an unusual and intense pilgrimage experience.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fc/Narsimha_Jharna_Bidar.jpg",
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 62,
    latitude: "17.9030761",
    longitude: "77.54385309999999",
  },
  {
    slug: "papnash-shiva-temple-bidar",
    name: "Papnash Shiva Temple",
    state: "Karnataka",
    district: "Bidar",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Ancient Shiva temple with a spring-fed tank, its linga said to have been installed by Lord Rama.",
    description: "The Papnash Shiva Temple is among the oldest temples in Bidar, with a Shivalinga traditionally believed to have been installed by Lord Rama. A natural spring feeds the temple tank, where pilgrims bathe to wash away sins (papa-nasha). It is a peaceful and revered local pilgrimage spot.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a4/Papnash_temple_%2C_bidar.jpg",
    openingTimings: "6:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 54,
    latitude: "17.9287456",
    longitude: "77.4917996",
  },
  {
    slug: "chaukhandi-bidar",
    name: "Chaukhandi of Hazrat Khalil Ullah",
    state: "Karnataka",
    district: "Bidar",
    category: "heritage",
    placeType: "Tomb",
    shortDescription: "Octagonal domed tomb of the Sufi saint Hazrat Khalil Ullah, noted for its fine tilework and calligraphy.",
    description: "The Chaukhandi is the octagonal tomb of Hazrat Khalil Ullah, spiritual mentor of the Bahmani court, set on a raised platform near Ashtur. Its arched gateway and dome are decorated with intricate tile mosaics and Quranic inscriptions. It is a graceful example of Bahmani religious architecture.",
    imageUrl: null,
    openingTimings: "9:00 AM - 5:00 PM",
    entryFees: 0,
    budgetPerDay: 800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 44,
    latitude: "17.917616",
    longitude: "77.554276",
  },
  {
    slug: "basavakalyan-fort",
    name: "Basavakalyan Fort",
    state: "Karnataka",
    district: "Bidar",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Historic fort of the Kalyani Chalukya capital and the town where the saint Basavanna founded the Lingayat movement.",
    description: "Basavakalyan, once Kalyani, was the 11th-12th century capital of the Western Chalukyas and the place where Basavanna and the Sharanas led the Lingayat social-religious revolution through the Anubhava Mantapa. The hilltop fort with its bastions and gates overlooks the town, which is dotted with shrines linked to the Vachana saints.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2e/Basava_Gaint_Statue_108_feet%2C_Basava_Kalyana.JPG",
    openingTimings: "9:00 AM - 1:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 52,
    latitude: "17.8843749",
    longitude: "76.9486424",
  },

  // ===================== YADGIR =====================
  {
    slug: "yadgir-fort",
    name: "Yadgir Fort",
    state: "Karnataka",
    district: "Yadgir",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Hill fort with concentric stone walls and bastions overlooking Yadgir town, built across Chalukya and later dynasties.",
    description: "Yadgir Fort rises on a rocky hill above the town, with multiple rings of stone ramparts, bastions and gateways developed under the Chalukyas, Bahmanis and later rulers. It retains old cannons, watchtowers and small shrines, and gives sweeping views over the surrounding plains. It is the chief historic landmark of the district headquarters.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Yadgir_town_view_from_fort.jpg/1280px-Yadgir_town_view_from_fort.jpg",
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 50,
    latitude: "16.7661337",
    longitude: "77.1397131",
  },
  {
    slug: "surapura-fort-palace",
    name: "Surapura (Surpur)",
    state: "Karnataka",
    district: "Yadgir",
    category: "heritage",
    placeType: "Fort Town",
    shortDescription: "Historic former princely capital ringed by hills, known for its fort, palace ruins and Raja Venkatappa Nayaka's legacy.",
    description: "Surapura was the seat of the Nayaka chieftains, most famously Raja Venkatappa Nayaka, who rebelled against the British in 1857. The town nestles in a horseshoe of hills with fort walls, palace remains and old temples. The Meghan Sahib (Philip Meadows Taylor) connection and a small museum add to its heritage interest.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Surapura_Taluk.jpg/1280px-Surapura_Taluk.jpg",
    openingTimings: "9:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 46,
    latitude: "16.5167",
    longitude: "76.7600",
  },
  {
    slug: "tintini-bheemanna-temple",
    name: "Tintini Moni Bheemanna Shrine",
    state: "Karnataka",
    district: "Yadgir",
    category: "pilgrimage",
    placeType: "Shrine",
    shortDescription: "Revered shrine of the silent saint Tintini Moni Bheemanna on the banks of the Krishna river, drawing devotees of all faiths.",
    description: "Tintini, on the Krishna river in Surapura taluk, is famed for the shrine of Moni (silent) Bheemanna, a Sufi-influenced saint venerated by both Hindus and Muslims. The annual fair attracts large crowds, and the riverside setting makes it a peaceful pilgrimage spot. It reflects the syncretic spiritual culture of the region.",
    imageUrl: null,
    openingTimings: "6:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 42,
    latitude: "16.3700",
    longitude: "76.6500",
  },
  {
    slug: "buddha-vihara-yadgir",
    name: "Kanaganahalli Buddha Vihara Yadgir",
    state: "Karnataka",
    district: "Yadgir",
    category: "pilgrimage",
    placeType: "Buddhist Vihara",
    shortDescription: "Modern Buddhist vihara and meditation centre in Yadgir, a quiet spiritual retreat in the district.",
    description: "The Buddha Vihara in Yadgir is a contemporary Buddhist prayer and meditation hall serving the local community and visitors. With a seated Buddha image and calm landscaped surroundings, it offers a tranquil space for reflection. It complements the region's deep ancient Buddhist heritage at nearby Sannati.",
    imageUrl: null,
    openingTimings: "9:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 36,
    latitude: "16.7600",
    longitude: "77.1300",
  },

  // ===================== RAICHUR =====================
  {
    slug: "raichur-fort",
    name: "Raichur Fort",
    state: "Karnataka",
    district: "Raichur",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "14th-century hill fort with massive stone gateways, inscriptions and panoramic views over Raichur city.",
    description: "Raichur Fort was built by the Kakatiyas and strengthened by the Vijayanagara and Bahmani rulers, who long fought over the strategic Raichur Doab. It has imposing gateways such as the Naurangi and Mecca Darwaza, carved bastions, inscriptions and old cannon. A climb to the citadel rewards visitors with wide views over the city.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Lake_Aam_Talab%2C_Raichur.jpg/1280px-Lake_Aam_Talab%2C_Raichur.jpg",
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 60,
    latitude: "16.1994808",
    longitude: "77.34945259999999",
  },
  {
    slug: "mallikarjuna-temple-raichur",
    name: "Mallikarjuna Temple Raichur",
    state: "Karnataka",
    district: "Raichur",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Old Shiva temple in Raichur dedicated to Mallikarjuna, a popular local devotional centre.",
    description: "The Mallikarjuna Temple is one of Raichur's notable Shiva shrines, drawing steady streams of devotees, especially during Shivaratri. Its simple Deccan-style architecture and sacred ambience make it a key religious landmark in the city. It is closely tied to the everyday spiritual life of Raichur.",
    imageUrl: null,
    openingTimings: "6:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 40,
    latitude: "16.2050",
    longitude: "77.3550",
  },
  {
    slug: "maliabad-fort-raichur",
    name: "Maliabad Fort",
    state: "Karnataka",
    district: "Raichur",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Ruined hill fort near Raichur with stone ramparts and bastions, popular for sunset views and short hikes.",
    description: "Maliabad Fort sits on a rocky hill a short drive from Raichur, with surviving stretches of fortification wall, bastions and gateways. The hilltop offers fine views of the surrounding doab plains and is a favourite spot for evening walks and photography. It is an offbeat heritage stop near the city.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 36,
    latitude: "16.1800",
    longitude: "77.2700",
  },
  {
    slug: "jaladurga-fort-falls",
    name: "Jaladurga Fort & Falls",
    state: "Karnataka",
    district: "Raichur",
    category: "adventure",
    placeType: "Island Fort & Waterfall",
    shortDescription: "Scenic island fort on the Krishna river where the water cascades into the rocky Jaladurga gorge.",
    description: "Jaladurga ('water fort') is a fortified rocky island in the Krishna river built by the Adil Shahis of Bijapur, surrounded by water and dramatic black-rock gorges. The river churns and cascades through the rocks here, especially in the monsoon, forming the Jaladurga falls. The remote, picturesque setting makes it a favourite for adventurous travellers and photographers.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Aug,Sep,Oct,Nov,Dec,Jan",
    isHidden: true,
    popularity: 50,
    latitude: "16.2536048",
    longitude: "76.4197045",
  },
  {
    slug: "mudgal-fort",
    name: "Mudgal Fort",
    state: "Karnataka",
    district: "Raichur",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Hilltop fort dating to the Kalyana Chalukyas, later held by the Vijayanagara empire, with bastions, a moat and a mosque.",
    description: "Mudgal Fort, near Lingsugur, traces its origins to the 11th-century Kalyana Chalukyas and was later expanded by the Yadavas and Vijayanagara rulers, becoming a key frontier stronghold. The hilltop enclosure has bastions, watchtowers, a moat, temples and a mosque inside its walls. The town below also has old churches and historic structures.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Mudgal_fort_3.jpg/1280px-Mudgal_fort_3.jpg",
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 46,
    latitude: "16.0087106",
    longitude: "76.43606230000002",
  },
  {
    slug: "ek-minar-ki-masjid-raichur",
    name: "Ek Minar Ki Masjid",
    state: "Karnataka",
    district: "Raichur",
    category: "heritage",
    placeType: "Mosque",
    shortDescription: "Distinctive Bahmani-era mosque inside Raichur Fort known for its single tall cylindrical minaret.",
    description: "The Ek Minar Ki Masjid ('mosque of one minaret') stands within the Raichur Fort complex and is named for its solitary tall, two-storeyed cylindrical minaret, an unusual feature among Deccan mosques. The structure reflects Bahmani architectural style and is a notable heritage landmark of the city.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Ek_Minar_Masjid%2C_Raichur.jpg/1280px-Ek_Minar_Masjid%2C_Raichur.jpg",
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 34,
    latitude: "16.2033613",
    longitude: "77.35274179999999",
  },

  // ===================== KOPPAL =====================
  {
    slug: "koppal-fort",
    name: "Koppal Fort",
    state: "Karnataka",
    district: "Koppal",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Two-tier fort with an upper hill citadel and a lower fort, fortified across Mauryan, Chalukya and later eras.",
    description: "Koppal Fort comprises a lower fort in the town and an upper fort perched on a steep granite hill, with stretches of wall, bastions and gateways from successive dynasties. Once considered nearly impregnable, the upper citadel offers commanding views over the boulder-strewn landscape. It is the principal historic monument of the district.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Koppal_Fort.jpg/1280px-Koppal_Fort.jpg",
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 50,
    latitude: "15.3402272",
    longitude: "76.1485774",
  },
  {
    slug: "anegundi",
    name: "Anegundi",
    state: "Karnataka",
    district: "Koppal",
    category: "heritage",
    placeType: "Heritage Village",
    shortDescription: "Ancient village across the Tungabhadra from Hampi, regarded as part of mythological Kishkindha and the older Vijayanagara core.",
    description: "Anegundi, on the north bank of the Tungabhadra opposite Hampi, is one of the oldest settlements of the region and is identified with the legendary Kishkindha of the Ramayana. It has the older fort, palaces, gateways and temples that predate the rise of Hampi, set amid a dramatic boulder landscape. Coracle rides, Anjanadri hill and rural heritage stays make it a rich cultural base.",
    imageUrl: null,
    openingTimings: "Open 24 hours",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 66,
    latitude: "15.3486",
    longitude: "76.4769",
  },
  {
    slug: "pampa-sarovar-koppal",
    name: "Pampa Sarovar",
    state: "Karnataka",
    district: "Koppal",
    category: "pilgrimage",
    placeType: "Sacred Lake",
    shortDescription: "Sacred lotus-filled lake near Anegundi, revered as one of India's five holy sarovars and linked to the Ramayana.",
    description: "Pampa Sarovar, near Anegundi, is counted among the five sacred lakes (panch sarovar) of Hindu tradition. It is associated with the goddess Pampa's penance and with Shabari, who is believed to have waited here for Lord Rama. A small Lakshmi temple and a cave shrine overlook the lotus-covered waters.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Pampa_Sarovar_from_the_hill.jpg/1280px-Pampa_Sarovar_from_the_hill.jpg",
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 54,
    latitude: "15.3537727",
    longitude: "76.4773651",
  },
  {
    slug: "huligemma-temple-koppal",
    name: "Huligemma Temple Huligi",
    state: "Karnataka",
    district: "Koppal",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Popular goddess temple of Huligemma (Durga) at Huligi on the Tungabhadra, drawing large numbers of devotees.",
    description: "The Huligemma Temple at Huligi is dedicated to the goddess Huligemma, a form of Durga, and is among the busiest pilgrimage centres of Koppal district. Devotees flock here especially during festivals and the annual fair, and the riverside location adds to its appeal. It holds deep regional devotional significance.",
    imageUrl: null,
    openingTimings: "6:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 48,
    latitude: "15.4097",
    longitude: "76.2628",
  },
  {
    slug: "gavi-math-koppal",
    name: "Gavi Math Koppal",
    state: "Karnataka",
    district: "Koppal",
    category: "pilgrimage",
    placeType: "Matha & Cave",
    shortDescription: "Hillside Veerashaiva matha with rock-cut caves and inscriptions, an old seat of learning and worship in Koppal.",
    description: "Gavi Math (Gavimath) is a Veerashaiva monastic centre set against the granite hills of Koppal, with natural and rock-cut caves used for meditation. The site is also significant for Ashokan-era rock edicts found nearby, linking it to ancient Mauryan history. It remains an active spiritual and educational institution.",
    imageUrl: null,
    openingTimings: "6:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 38,
    latitude: "15.3490",
    longitude: "76.1560",
  },
  {
    slug: "kanakagiri-koppal",
    name: "Kanakagiri",
    state: "Karnataka",
    district: "Koppal",
    category: "heritage",
    placeType: "Temple Town",
    shortDescription: "Former Nayaka principality known for the Kanakachalapathi temple and historic palace ruins.",
    description: "Kanakagiri was the capital of a Vijayanagara-era Nayaka chiefdom and is renowned for the Kanakachalapathi (Vishnu) temple with its ornate gopuram, pillared halls and fine sculpture. The town also preserves palace ruins, gateways and other temples. It is an important heritage and pilgrimage stop in Koppal district.",
    imageUrl: null,
    openingTimings: "6:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 44,
    latitude: "15.4133",
    longitude: "76.4150",
  },
  {
    slug: "kinnal-koppal",
    name: "Kinnal (Kinhal)",
    state: "Karnataka",
    district: "Koppal",
    category: "heritage",
    placeType: "Craft Village",
    shortDescription: "Village famed for traditional Kinnal lacquered wooden craft and painted toys, a recognised heritage art form.",
    description: "Kinnal (Kinhal) near Koppal is the home of the centuries-old Kinnal craft, a distinctive style of lightweight lacquered and painted wooden figures, toys and temple art. The craft, traditionally practised by the Chitragar community, has GI recognition. Visitors can see artisans at work and the colourful idols and decorative pieces.",
    imageUrl: null,
    openingTimings: "9:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 34,
    latitude: "15.3800",
    longitude: "76.1900",
  },
  {
    slug: "anjanadri-hill-koppal",
    name: "Anjanadri Hill",
    state: "Karnataka",
    district: "Koppal",
    category: "hill_station",
    placeType: "Hill & Viewpoint",
    shortDescription: "Boulder-strewn hill near Anegundi believed to be the birthplace of Lord Hanuman, reached by a long stairway climb.",
    description: "Anjanadri Hill, near Anegundi, is widely revered as the birthplace of Lord Hanuman (Anjaneya) and is topped by a small Hanuman temple. A climb of several hundred steps leads to sweeping views over paddy fields, the Tungabhadra river and the surrounding Hampi-Kishkindha landscape, especially beautiful at sunrise and sunset. It is both a pilgrimage and a scenic viewpoint.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 64,
    latitude: "15.3548385",
    longitude: "76.469264",
  },

  // ===================== BALLARI (BELLARY) =====================
  {
    slug: "bellary-fort-gudda",
    name: "Bellary Fort (Ballari Gudda)",
    state: "Karnataka",
    district: "Ballari",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Twin-level hill fort atop the Ballari Gudda granite outcrop, expanded by Hyder Ali and a French engineer.",
    description: "Bellary Fort crowns the towering Ballari Gudda rock in the centre of the city, with an upper fort on the summit and a lower fort at its base. Originally Vijayanagara, it was greatly strengthened by Hyder Ali with the help of a French engineer. The steep climb rewards visitors with old gateways, a temple, a mosque and panoramic city views.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 58,
    latitude: "15.1452816",
    longitude: "76.9144831",
  },
  {
    slug: "kumaraswamy-temple-sandur",
    name: "Kumaraswamy Temple Sandur",
    state: "Karnataka",
    district: "Ballari",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Ancient hill temple of Lord Kartikeya at Sandur, believed to be one of his earliest abodes in South India.",
    description: "The Kumaraswamy Temple on Krauncha Giri near Sandur is dedicated to Lord Kartikeya (Murugan) and is held to be among his earliest shrines in South India, dating to around the 8th-10th century. The Chalukya-style temple has finely carved pillars and an adjacent Parvati shrine, set amid the green, ore-rich Sandur hills. It is a serene and scenic pilgrimage spot.",
    imageUrl: null,
    openingTimings: "6:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 54,
    latitude: "15.0689",
    longitude: "76.5489",
  },
  {
    slug: "daroji-sloth-bear-sanctuary",
    name: "Daroji Sloth Bear Sanctuary",
    state: "Karnataka",
    district: "Ballari",
    category: "wildlife",
    placeType: "Wildlife Sanctuary",
    shortDescription: "India's first sloth bear sanctuary, set in boulder hills near Hampi, with reliable evening sightings of wild bears.",
    description: "Daroji Bear Sanctuary, established in 1994, was India's first sanctuary dedicated to the Indian sloth bear, spread across the rocky scrub hills near Hampi-Kamalapur. From the viewpoint, visitors regularly see bears emerge in the late afternoon, along with leopards, wild boar, peacocks and many bird species. It is one of the best places in India to observe sloth bears in the wild.",
    imageUrl: null,
    openingTimings: "1:00 PM - 6:00 PM",
    entryFees: 50,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 64,
    latitude: "15.2861",
    longitude: "76.5750",
  },
  {
    slug: "sandur-hills",
    name: "Sandur Hills",
    state: "Karnataka",
    district: "Ballari",
    category: "hill_station",
    placeType: "Hills & Viewpoint",
    shortDescription: "Green, mineral-rich hill range around Sandur with scenic ghats, viewpoints and a pleasant climate, often called the hill retreat of Ballari.",
    description: "The Sandur Hills are a pocket of greenery and cooler air in the otherwise dry Ballari plains, with forested slopes, waterfalls in the monsoon and winding ghat roads. The area is rich in iron and manganese ore yet retains scenic charm, with the Kumaraswamy temple and old Ghorpade palace nearby. Viewpoints along the ghats are popular for their sweeping vistas.",
    imageUrl: null,
    openingTimings: "Open 24 hours",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Aug,Sep,Oct,Nov,Dec,Jan",
    isHidden: true,
    popularity: 48,
    latitude: "15.0957229",
    longitude: "76.55447029999999",
  },
  {
    slug: "kudligi-fort-ballari",
    name: "Kudligi",
    state: "Karnataka",
    district: "Ballari",
    category: "heritage",
    placeType: "Town & Temples",
    shortDescription: "Historic taluk town in Ballari with old temples and a quiet rural-heritage character.",
    description: "Kudligi is a taluk town in Ballari district known for its old temples and traditional fairs, set in the dry uplands of the region. It serves as a local cultural and trade centre and is dotted with shrines that draw devotees during festivals. It offers a glimpse of small-town heritage in the Kalyana Karnataka belt.",
    imageUrl: null,
    openingTimings: "Open 24 hours",
    entryFees: 0,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 30,
    latitude: "14.9080",
    longitude: "76.3870",
  },

  // ===================== VIJAYANAGARA (HOSPET / HAMPI REGION) =====================
  {
    slug: "tungabhadra-dam",
    name: "Tungabhadra Dam",
    state: "Karnataka",
    district: "Vijayanagara",
    category: "adventure",
    placeType: "Dam & Reservoir",
    shortDescription: "Large masonry-and-earthen dam across the Tungabhadra near Hospet, with a vast reservoir, gardens and musical fountain.",
    description: "The Tungabhadra Dam near Hospet is one of the largest reservoirs in the region, built for irrigation and hydro-power across the Tungabhadra river. Its landscaped Japanese-style gardens, viewpoints over the wide backwaters and an evening musical fountain make it a popular outing. The sight of the gates open in spate during the monsoon is especially dramatic.",
    imageUrl: null,
    openingTimings: "10:00 AM - 6:00 PM",
    entryFees: 15,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Aug,Sep,Oct,Nov,Dec,Jan",
    isHidden: false,
    popularity: 70,
    latitude: "15.2667",
    longitude: "76.3358",
  },
  {
    slug: "virupaksha-temple-hampi",
    name: "Virupaksha Temple Hampi",
    state: "Karnataka",
    district: "Vijayanagara",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Living 7th-century temple of Lord Virupaksha (Shiva) with a towering gopuram, the spiritual heart of Hampi.",
    description: "The Virupaksha Temple at Hampi is dedicated to Lord Virupaksha, a form of Shiva, and is the oldest continuously worshipped temple in the site, with roots going back to the 7th century. Its soaring nine-tiered eastern gopuram, pillared halls and a famous pinhole-camera shadow effect draw devotees and visitors alike. It anchors the sacred Hampi bazaar and riverside complex.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Complex_of_Virupaksha_Temple%2C_Hampi_%2804%29.jpg/1280px-Complex_of_Virupaksha_Temple%2C_Hampi_%2804%29.jpg",
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 2,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 88,
    latitude: "15.3351333",
    longitude: "76.45865289999999",
  },
  {
    slug: "vittala-temple-hampi",
    name: "Vittala Temple Hampi",
    state: "Karnataka",
    district: "Vijayanagara",
    category: "heritage",
    placeType: "Temple Complex",
    shortDescription: "Iconic Vijayanagara temple famed for its stone chariot and musical pillars, the masterpiece of Hampi.",
    description: "The Vittala Temple is the finest example of Vijayanagara architecture, dedicated to Vittala, a form of Vishnu. It is renowned for its ornate stone chariot and the Ranga Mantapa with slender 'musical' pillars that resonate when tapped. Carved gateways, courtyards and pavilions make it the artistic high point of the Hampi ruins.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/View_of_the_Virupaksha_temple_complex_from_Hemakuta_hill.JPG/1280px-View_of_the_Virupaksha_temple_complex_from_Hemakuta_hill.JPG",
    openingTimings: "8:30 AM - 6:00 PM",
    entryFees: 40,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 90,
    latitude: "15.3423049",
    longitude: "76.47519170000001",
  },
  {
    slug: "hampi-royal-enclosure",
    name: "Hampi Royal Enclosure",
    state: "Karnataka",
    district: "Vijayanagara",
    category: "heritage",
    placeType: "Archaeological Complex",
    shortDescription: "Civic and royal core of Vijayanagara with the stepped tank, Mahanavami Dibba platform and underground temple.",
    description: "The Royal Enclosure was the ceremonial and administrative heart of the Vijayanagara capital, containing the grand Mahanavami Dibba ceremonial platform used during Dasara, the beautifully geometric stepped tank (Pushkarani), audience halls and palace basements. Nearby lie the Hazara Rama temple and the underground Virupaksha shrine. It vividly conveys the scale of the lost empire's power.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Wide_angle_of_Galigopuram_of_Virupaksha_Temple%2C_Hampi_%2804%29_%28cropped%29.jpg/1280px-Wide_angle_of_Galigopuram_of_Virupaksha_Temple%2C_Hampi_%2804%29_%28cropped%29.jpg",
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 40,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 76,
    latitude: "15.3350132",
    longitude: "76.46002399999999",
  },
  {
    slug: "lotus-mahal-zenana-hampi",
    name: "Lotus Mahal & Zenana Enclosure",
    state: "Karnataka",
    district: "Vijayanagara",
    category: "heritage",
    placeType: "Palace & Elephant Stables",
    shortDescription: "Indo-Islamic Lotus Mahal pavilion and the grand domed Elephant Stables within the royal women's enclosure.",
    description: "The Zenana Enclosure was the secluded quarter for the royal women of Vijayanagara. It contains the elegant two-storeyed Lotus Mahal, a symmetrical pavilion blending Hindu and Islamic styles, and the impressive row of eleven domed Elephant Stables that once housed the royal elephants. Watchtowers and the Queen's quarters complete the complex.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Flat_elevation_of_Lotus_Mahal%2C_Hampi_%28Closeup%29.jpg/1280px-Flat_elevation_of_Lotus_Mahal%2C_Hampi_%28Closeup%29.jpg",
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 40,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 78,
    latitude: "15.3202851",
    longitude: "76.47132429999999",
  },
  {
    slug: "hampi-hemakuta-hill",
    name: "Hemakuta Hill Temples",
    state: "Karnataka",
    district: "Vijayanagara",
    category: "heritage",
    placeType: "Temple Cluster & Viewpoint",
    shortDescription: "Hill above the Virupaksha temple dotted with pre-Vijayanagara shrines, a famed sunset viewpoint over Hampi.",
    description: "Hemakuta Hill rises just above the Virupaksha Temple and is covered with a cluster of early triple-roofed shrines and gateways, many predating the Vijayanagara empire. The gentle climb leads to wide views over the boulder landscape and temple bazaar, making it the most popular sunset spot in Hampi. Nearby stand the monolithic Sasivekalu and Kadalekalu Ganesha statues.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:30 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 74,
    latitude: "15.3325382",
    longitude: "76.4595622",
  },
  {
    slug: "matanga-hill-hampi",
    name: "Matanga Hill",
    state: "Karnataka",
    district: "Vijayanagara",
    category: "hill_station",
    placeType: "Hill & Sunrise Viewpoint",
    shortDescription: "Highest hill in Hampi crowned by the Veerabhadra temple, the premier sunrise viewpoint over the ruins.",
    description: "Matanga Hill is the highest point in the Hampi landscape and is associated with the sage Matanga of the Ramayana. A rocky trail climbs to the Veerabhadra temple on the summit, from where sunrise and sunset bathe the temple ruins, river and boulder fields in golden light. It is the most rewarding short trek in Hampi.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Enroute_to_Matanga_hills%2C_Hampi.jpg/1280px-Enroute_to_Matanga_hills%2C_Hampi.jpg",
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 68,
    latitude: "15.3316387",
    longitude: "76.4682381",
  },
  {
    slug: "hospet-town",
    name: "Hospet (Hosapete)",
    state: "Karnataka",
    district: "Vijayanagara",
    category: "heritage",
    placeType: "Base Town",
    shortDescription: "Bustling district headquarters and main gateway town for visiting Hampi and the Tungabhadra Dam.",
    description: "Hospet, officially Hosapete, is the largest town and railhead serving the Hampi region, founded by the Vijayanagara king Krishnadevaraya. It functions as the main base for travellers, with hotels, markets and transport links to Hampi, Anegundi and the Tungabhadra Dam. The town also has temples and a lively local bazaar.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Hospet_Cityscape.jpg/1280px-Hospet_Cityscape.jpg",
    openingTimings: "Open 24 hours",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 52,
    latitude: "15.2688542",
    longitude: "76.39092409999999",
  },
  {
    slug: "kamalapur-museum-hampi",
    name: "Hampi Archaeological Museum, Kamalapur",
    state: "Karnataka",
    district: "Vijayanagara",
    category: "heritage",
    placeType: "Museum",
    shortDescription: "ASI museum at Kamalapur displaying Vijayanagara sculpture, coins, arms and a scale model of the Hampi ruins.",
    description: "The Archaeological Survey of India museum at Kamalapur, near Hampi, houses sculptures, hero stones, coins, weapons and inscriptions recovered from the Vijayanagara capital. A highlight is the large scale model laying out the entire ruined city, useful for orienting a Hampi visit. It provides valuable historical context for the monuments.",
    imageUrl: null,
    openingTimings: "10:00 AM - 5:00 PM",
    entryFees: 5,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 46,
    latitude: "15.3073493",
    longitude: "76.4771336",
  },
];
