import type { NewDestination } from "../schema";

// Karnataka — Coastal (Dakshina Kannada, Udupi, Uttara Kannada)
export const karnatakaCoastalRegion: Omit<NewDestination, "id" | "createdAt">[] = [
  // ---------------- Dakshina Kannada (Mangaluru) ----------------
  {
    slug: "panambur-beach",
    name: "Panambur Beach",
    state: "Karnataka",
    district: "Dakshina Kannada",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Mangaluru's flagship beach with golden sand, lifeguards, camel rides and an annual kite festival.",
    description: "Panambur Beach near the New Mangalore Port is one of the most popular and well-maintained beaches on the Karnataka coast. It is known for clean golden sand, water sports, camel and horse rides, and an international kite festival. Lifeguards and food stalls make it family friendly.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/23/Panambur_Beach_Mangalore.jpg",
    openingTimings: "Open 24 hours",
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 85,
    latitude: "12.9371312",
    longitude: "74.8043149",
  },
  {
    slug: "tannirbhavi-beach",
    name: "Tannirbhavi Beach",
    state: "Karnataka",
    district: "Dakshina Kannada",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Quiet Mangaluru beach reached by ferry, known for sunsets, a tree park and casuarina groves.",
    description: "Tannirbhavi Beach lies across the Gurupura river from the city and is reachable by a short ferry ride from Sultan Battery. It offers calm waters, a tree park, and some of the best sunset views in Mangaluru, with fewer crowds than Panambur.",
    imageUrl: null,
    openingTimings: "Open 24 hours",
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 72,
    latitude: "12.8913022",
    longitude: "74.81387409999999",
  },
  {
    slug: "someshwara-beach",
    name: "Someshwara Beach (Ullal)",
    state: "Karnataka",
    district: "Dakshina Kannada",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Rocky-and-sand beach at Ullal beside the Someshwara temple, famous for the Rudra Shile rock formations.",
    description: "Someshwara Beach at Ullal, south of Mangaluru, is named after the ancient Someshwara temple nearby. The shore features dramatic black rock formations known as Rudra Shile where waves crash, making it a scenic and photogenic spot away from the busier city beaches.",
    imageUrl: null,
    openingTimings: "Open 24 hours",
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 64,
    latitude: "12.7862087",
    longitude: "74.8534545",
  },
  {
    slug: "sasihithlu-beach",
    name: "Sasihithlu Beach",
    state: "Karnataka",
    district: "Dakshina Kannada",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Offbeat beach where the Shambhavi and Nandini rivers meet the sea; a major surfing destination.",
    description: "Sasihithlu Beach, north of Mangaluru near Mulki, lies at the confluence of the Shambhavi and Nandini rivers with the Arabian Sea. Its consistent waves have made it Karnataka's premier surfing spot, hosting national and international surfing competitions, yet it remains relatively uncrowded.",
    imageUrl: null,
    openingTimings: "8:00 AM - 7:30 PM",
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 58,
    latitude: "13.0707262",
    longitude: "74.77668349999999",
  },
  {
    slug: "kadri-manjunatha-temple",
    name: "Kadri Manjunatha Temple",
    state: "Karnataka",
    district: "Dakshina Kannada",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Ancient Mangaluru Shiva temple with rare 10th-century bronze idols and natural Gomukha springs.",
    description: "The Kadri Manjunatha Temple in Mangaluru dates to around the 10th–11th century and houses one of the oldest bronze idols in South India, a Lokeshwara figure. The temple complex sits below the Kadri hills with nine sacred tanks (Gomukha) fed by natural springs and the Jogimutt above it.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Kadri_temple_entrance_mangalore.jpg/1280px-Kadri_temple_entrance_mangalore.jpg",
    openingTimings: "6:00 AM - 1:00 PM, 4:00 PM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 70,
    latitude: "12.8857251",
    longitude: "74.85561659999999",
  },
  {
    slug: "mangaladevi-temple",
    name: "Mangaladevi Temple",
    state: "Karnataka",
    district: "Dakshina Kannada",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Historic temple of goddess Mangaladevi that gave the city of Mangaluru its name.",
    description: "The Mangaladevi Temple is dedicated to goddess Mangaladevi, a form of Shakti, and is believed to have given Mangaluru its name. Built in the Kerala architectural style, the temple is especially active during the Navaratri Dasara festival when it draws large crowds.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Mangaladevi_Temple_Mangalore_2.jpg/1280px-Mangaladevi_Temple_Mangalore_2.jpg",
    openingTimings: "6:00 AM - 10:00 AM, 5:00 PM - 8:30 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 66,
    latitude: "12.8479",
    longitude: "74.8430",
  },
  {
    slug: "kudroli-gokarnatha-temple",
    name: "Kudroli Gokarnatha Temple",
    state: "Karnataka",
    district: "Dakshina Kannada",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Ornate Shiva temple in Mangaluru built by Narayana Guru, famous for its grand Dasara celebrations.",
    description: "Kudroli Gokarnanatheshwara Temple was consecrated by the social reformer Narayana Guru in 1912. Renovated with elaborate sculptures and vivid lighting, it is renowned for its spectacular Mangaluru Dasara festival featuring illuminated tableaux of goddesses.",
    imageUrl: null,
    openingTimings: "6:00 AM - 1:00 PM, 4:00 PM - 8:30 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 64,
    latitude: "12.8762183",
    longitude: "74.8317479",
  },
  {
    slug: "st-aloysius-chapel",
    name: "St Aloysius Chapel",
    state: "Karnataka",
    district: "Dakshina Kannada",
    category: "pilgrimage",
    placeType: "Church",
    shortDescription: "Mangaluru chapel covered floor-to-ceiling in 19th-century frescoes by Italian artist Antonio Moscheni.",
    description: "The Chapel of St Aloysius College in Mangaluru, built in 1880, is famed for its interior almost entirely covered with paintings by the Italian Jesuit artist Antonio Moscheni. Often compared to the Sistine Chapel, its richly frescoed walls and ceiling make it a unique heritage attraction.",
    imageUrl: null,
    openingTimings: "9:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 75,
    latitude: "12.873883",
    longitude: "74.8453011",
  },
  {
    slug: "sultan-battery",
    name: "Sultan Battery",
    state: "Karnataka",
    district: "Dakshina Kannada",
    category: "heritage",
    placeType: "Watchtower",
    shortDescription: "18th-century black-stone watchtower built by Tipu Sultan to guard the Gurupura river mouth.",
    description: "Sultan Battery is a small fortified watchtower built around 1784 by Tipu Sultan from black laterite stone to prevent enemy warships from entering the Gurupura river. From its top there are views over the backwaters, and a ferry from here connects to Tannirbhavi Beach.",
    imageUrl: null,
    openingTimings: "9:00 AM - 7:30 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 60,
    latitude: "12.8896981",
    longitude: "74.82109109999999",
  },
  {
    slug: "pilikula-nisargadhama",
    name: "Pilikula Nisargadhama",
    state: "Karnataka",
    district: "Dakshina Kannada",
    category: "wildlife",
    placeType: "Nature Park",
    shortDescription: "Integrated eco park near Mangaluru with a zoo, botanical garden, lake, science centre and heritage village.",
    description: "Pilikula Nisargadhama is a large eco-tourism complex on the outskirts of Mangaluru combining a biological park (zoo), arboretum, boating lake, a regional science centre and planetarium, a Gutthu heritage house, and a water park. It is a popular full-day outing for families.",
    imageUrl: null,
    openingTimings: "9:00 AM - 6:00 PM (closed Mon)",
    entryFees: 70,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 68,
    latitude: "12.9710",
    longitude: "74.8970",
  },
  {
    slug: "dharmasthala-manjunatha",
    name: "Dharmasthala Manjunatha Temple",
    state: "Karnataka",
    district: "Dakshina Kannada",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Major pilgrimage town on the Netravati where Lord Manjunatha (Shiva) is worshipped with free meals for all.",
    description: "Dharmasthala is one of Karnataka's most visited pilgrimage centres, home to the Manjunatha temple administered by the Heggade family for centuries. Unusually, the Shaiva shrine is run by Jain administrators with Vaishnava priests. The town is known for free meals (annadana) to all pilgrims, the giant Bahubali statue at Ratnagiri, and the Manjusha and car museums. General darshan is free; a paid Sannidhana/special darshan (around ₹200) is available for faster access during peak hours.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Dharmasthala_1.jpg/1280px-Dharmasthala_1.jpg",
    openingTimings: "6:30 AM - 2:30 PM, 5:00 PM - 8:30 PM",
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 90,
    latitude: "12.9504257",
    longitude: "75.3808779",
  },
  {
    slug: "kukke-subramanya",
    name: "Kukke Subramanya Temple",
    state: "Karnataka",
    district: "Dakshina Kannada",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Famous serpent (Naga) temple at the foot of Kumara Parvatha, key for Sarpa Dosha and Naga Dosha rituals.",
    description: "Kukke Subramanya is a renowned temple dedicated to Lord Subramanya (Kartikeya), worshipped here as the lord of serpents. Pilgrims come from across India to perform Sarpa Samskara and Naga Dosha rituals. Set on the Kumaradhara river at the base of Kumara Parvatha, it is also a starting point for the Kumara Parvatha trek. General darshan is free; paid special and VIP darshan tickets are available for a quicker queue.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5f/Kukke_Subramanya_Swami.jpg",
    openingTimings: "5:00 AM - 1:00 PM, 4:00 PM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 86,
    latitude: "12.6636928",
    longitude: "75.61597619999999",
  },
  {
    slug: "kumara-parvatha-trek",
    name: "Kumara Parvatha Trek",
    state: "Karnataka",
    district: "Dakshina Kannada",
    category: "adventure",
    placeType: "Trek",
    shortDescription: "One of South India's toughest treks, climbing through forest and grassland from Kukke Subramanya to the peak.",
    description: "Kumara Parvatha (Pushpagiri) at around 1712 m is one of the most challenging treks in the Western Ghats, usually begun from Kukke Subramanya. The demanding multi-hour climb passes through dense Pushpagiri forest, Bhattara Mane and Mantapa before reaching panoramic grassland summit views.",
    imageUrl: null,
    openingTimings: "Trek permits 6:00 AM - 10:00 AM",
    entryFees: 500,
    budgetPerDay: 1500,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 62,
    latitude: "12.6420",
    longitude: "75.6620",
  },
  {
    slug: "kateel-durgaparameshwari-temple",
    name: "Kateel Durgaparameshwari Temple",
    state: "Karnataka",
    district: "Dakshina Kannada",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Temple of goddess Durgaparameshwari on an islet in the middle of the Nandini river near Mangaluru.",
    description: "The Kateel Durgaparameshwari Temple sits on a small island in the midst of the Nandini river, about 25 km from Mangaluru. Dedicated to goddess Durga, it is a revered Shakti shrine and a noted centre for Yakshagana performances dedicated to the deity.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Kateel_Durga_Parameshwari_0145.JPG/1280px-Kateel_Durga_Parameshwari_0145.JPG",
    openingTimings: "4:00 AM - 1:00 PM, 4:00 PM - 9:00 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 70,
    latitude: "13.043881",
    longitude: "74.87008039999999",
  },
  {
    slug: "bantwal-town",
    name: "Bantwal",
    state: "Karnataka",
    district: "Dakshina Kannada",
    category: "heritage",
    placeType: "Town",
    shortDescription: "Historic riverside town on the Netravati, a trading centre with old temples and colonial-era buildings.",
    description: "Bantwal is a taluk town on the banks of the Netravati river, long an important trade and agricultural centre of Dakshina Kannada. Old Bantwal preserves traditional mansions and temples, and the riverfront and surrounding areflooded plains are characteristic of the region's heritage.",
    imageUrl: null,
    openingTimings: "Open 24 hours",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 40,
    latitude: "12.8910",
    longitude: "75.0350",
  },
  {
    slug: "mangaluru-surathkal-beach",
    name: "Surathkal Beach & Lighthouse",
    state: "Karnataka",
    district: "Dakshina Kannada",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Picturesque rocky beach near NITK Surathkal with a hilltop lighthouse and dramatic sunsets.",
    description: "Surathkal Beach, beside the NITK campus north of Mangaluru, is known for its rocky outcrops, a small lighthouse on a mound, and excellent sunset views. The Sadashiva rock temple at the shore and the relatively calm setting make it a favourite local getaway.",
    imageUrl: null,
    openingTimings: "Open 24 hours",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 58,
    latitude: "13.005266",
    longitude: "74.7892912",
  },

  // ---------------- Udupi ----------------
  {
    slug: "udupi-sri-krishna-matha",
    name: "Sri Krishna Matha, Udupi",
    state: "Karnataka",
    district: "Udupi",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Famous 13th-century Krishna temple founded by Madhvacharya, worshipped through the silver Kanakana Kindi window.",
    description: "The Sri Krishna Matha in Udupi was established by the Dvaita philosopher Madhvacharya in the 13th century. Devotees view the idol of baby Krishna through the silver-plated Navagraha Kindi (nine-holed window). The temple is the centre of the biennial Paryaya festival and surrounded by the Ashta Mathas and Anantheshwara and Chandramouleshwara temples. Unlike many major temples, there is no separate paid darshan line here — everyone queues together, and the matha's Anna Brahma kitchen serves free meals to all visitors.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Udupi_Krishna_Temple.jpg/1280px-Udupi_Krishna_Temple.jpg",
    openingTimings: "4:30 AM - 9:30 PM",
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 88,
    latitude: "13.3411662",
    longitude: "74.75204459999999",
  },
  {
    slug: "malpe-beach",
    name: "Malpe Beach",
    state: "Karnataka",
    district: "Udupi",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Lively Udupi beach with white sand, water sports and a fishing harbour; gateway to St Mary's Island.",
    description: "Malpe Beach near Udupi is a clean, popular beach with white sand, beach swings, water sports and a busy fishing harbour. It is the launch point for boat trips to St Mary's Island and is known for its food shacks and sunset crowds.",
    imageUrl: null,
    openingTimings: "6:00 AM - 11:00 PM",
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 84,
    latitude: "13.3613804",
    longitude: "74.6976506",
  },
  {
    slug: "st-marys-island",
    name: "St Mary's Island",
    state: "Karnataka",
    district: "Udupi",
    category: "beach",
    placeType: "Island",
    shortDescription: "Geological wonder off Malpe with hexagonal basaltic columns formed by ancient volcanic activity.",
    description: "St Mary's Island (Coconut Island) off the Malpe coast is a cluster of islands famous for its rare hexagonal columnar basalt rock formations, declared a National Geological Monument. Vasco da Gama is said to have landed here in 1498. Reached by ferry from Malpe, it has crystalline sands and tide pools. There's no separate landing fee — the cost is the round-trip ferry ticket from Malpe jetty, which runs roughly 9:30 AM to 5:30 PM.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/St._Mary%27s_islands%2C_Udupi_1767.jpg/1280px-St._Mary%27s_islands%2C_Udupi_1767.jpg",
    openingTimings: "9:00 AM - 5:00 PM",
    entryFees: 300,
    budgetPerDay: 1400,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 82,
    latitude: "13.3791456",
    longitude: "74.6733896",
  },
  {
    slug: "kaup-beach-lighthouse",
    name: "Kaup Beach & Lighthouse",
    state: "Karnataka",
    district: "Udupi",
    category: "beach",
    placeType: "Lighthouse",
    shortDescription: "Scenic beach crowned by a 100-year-old red-and-white lighthouse with panoramic Arabian Sea views.",
    description: "Kaup (Kapu) Beach lies between Udupi and Mangaluru and is famous for its 1901-built lighthouse standing on a rocky promontory. Climbing the lighthouse rewards visitors with sweeping coastal views, and the rocky-and-sand shore is a celebrated sunset point.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Kapu_Beach_Lighthouse_.jpg/1280px-Kapu_Beach_Lighthouse_.jpg",
    openingTimings: "Lighthouse 4:00 PM - 6:00 PM",
    entryFees: 25,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 74,
    latitude: "13.2222775",
    longitude: "74.73807649999999",
  },
  {
    slug: "kollur-mookambika",
    name: "Kollur Mookambika Temple",
    state: "Karnataka",
    district: "Udupi",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Revered hill-foot temple of goddess Mookambika on the Souparnika river, at the base of Kodachadri.",
    description: "The Kollur Mookambika Temple is a major Shakti pilgrimage centre dedicated to goddess Mookambika, set on the banks of the Souparnika river at the foot of the Kodachadri hills. The deity is worshipped as a Jyotirlinga combining Shiva and Shakti, and the temple draws devotees especially for vidyarambham (initiation into learning). General darshan is free, with paid seva-based special darshan available for a shorter queue.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Kollur_Sri_Mookambika_Temple_%284465798056%29.jpg/1280px-Kollur_Sri_Mookambika_Temple_%284465798056%29.jpg",
    openingTimings: "5:00 AM - 1:30 PM, 3:00 PM - 9:00 PM",
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 84,
    latitude: "13.8637041",
    longitude: "74.81448259999999",
  },
  
  {
    slug: "maravanthe-beach",
    name: "Maravanthe Beach",
    state: "Karnataka",
    district: "Udupi",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Unique stretch where NH-66 runs between the Arabian Sea on one side and the Souparnika river on the other.",
    description: "Maravanthe Beach near Kundapura is famed for the rare sight of National Highway 66 running with the Arabian Sea on one side and the Souparnika river backed by Kodachadri hills on the other. The unbroken golden sands and dramatic dual-water scenery make it one of Karnataka's most photographed coastal stretches.",
    imageUrl: null,
    openingTimings: "Open 24 hours",
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 78,
    latitude: "13.7370",
    longitude: "74.6420",
  },
  {
    slug: "manipal-end-point",
    name: "Manipal End Point",
    state: "Karnataka",
    district: "Udupi",
    category: "hill_station",
    placeType: "Viewpoint",
    shortDescription: "Landscaped cliff-edge park in Manipal overlooking the Swarna river valley and Western Ghats.",
    description: "End Point in Manipal is a popular landscaped garden and viewpoint perched at the edge of a plateau, offering panoramic views of the Swarna (Suvarna) river valley and the distant Western Ghats. With walking paths and sunset views, it is a favourite hangout for students and families.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Night_in_Manipal.jpg/1280px-Night_in_Manipal.jpg",
    openingTimings: "6:00 AM - 7:00 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 60,
    latitude: "13.3460",
    longitude: "74.7920",
  },
  {
    slug: "kundapura-koteshwara",
    name: "Koteshwara Temple, Kundapura",
    state: "Karnataka",
    district: "Udupi",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Ancient Shiva temple near Kundapura, one of the seven sacred Mukti Sthalas of coastal Karnataka.",
    description: "The Koteshwara temple near Kundapura is dedicated to Lord Shiva as Kotilingeshwara and is counted among the seven Mukti Sthalas (Parashurama Kshetras) of the Tulu and coastal region. The temple is an old and revered Shaiva pilgrimage site set close to the backwaters.",
    imageUrl: null,
    openingTimings: "6:00 AM - 12:30 PM, 4:00 PM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 45,
    latitude: "13.6390",
    longitude: "74.6990",
  },
  {
    slug: "anegudde-vinayaka-temple",
    name: "Anegudde Vinayaka Temple",
    state: "Karnataka",
    district: "Udupi",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Hilltop Ganesha temple at Kumbashi, one of the seven Mukti Sthalas, popular for wish fulfilment.",
    description: "The Anegudde Vinayaka Temple at Kumbashi near Kundapura is a famed Ganesha shrine set on a small hill, regarded as one of the seven Mukti Sthalas of the coast. Pilgrims visit to seek the blessings of the deity, who is believed to fulfil wishes and remove obstacles.",
    imageUrl: null,
    openingTimings: "6:00 AM - 1:00 PM, 3:30 PM - 8:30 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 55,
    latitude: "13.6760",
    longitude: "74.7170",
  },
  {
    slug: "kemmannu-hanging-bridge",
    name: "Kemmannu Hanging Bridge",
    state: "Karnataka",
    district: "Udupi",
    category: "adventure",
    placeType: "Suspension Bridge",
    shortDescription: "Scenic pedestrian suspension bridge over a backwater channel near Udupi, with mangrove boardwalks.",
    description: "The Kemmannu hanging bridge is a pedestrian suspension footbridge spanning a backwater channel near Udupi, leading toward a small island. Combined with the nearby mangrove boardwalk and quiet backwaters, it has become a popular offbeat photo and leisure spot.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Tonse_hanging_bridge.jpg/1280px-Tonse_hanging_bridge.jpg",
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 42,
    latitude: "13.4096657",
    longitude: "74.71549329999999",
  },
  {
    slug: "kudlu-theertha-falls",
    name: "Kudlu Theertha Falls",
    state: "Karnataka",
    district: "Udupi",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription: "Powerful 300+ ft waterfall on the Sita river near Hebri, reached by a short forest trek.",
    description: "Kudlu Theertha (Koodlu Teertha) Falls near Hebri in Udupi district plunges over 300 feet on the Sita river into a deep pool. A short trek through forest and a check-post leads to the base, where the roar of the cascade and lush surroundings reward visitors in and after the monsoon.",
    imageUrl: null,
    openingTimings: "8:00 AM - 4:00 PM",
    entryFees: 50,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 50,
    latitude: "13.4900",
    longitude: "74.9530",
  },

  // ---------------- Uttara Kannada (Karwar / Sirsi) ----------------
  {
    slug: "murudeshwara",
    name: "Murudeshwara",
    state: "Karnataka",
    district: "Uttara Kannada",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Coastal temple town with the world's second-tallest Shiva statue overlooking the Arabian Sea.",
    description: "Murudeshwara is famed for its towering ~37 m Shiva statue and the Murudeshwara temple on Kanduka Hill, jutting into the Arabian Sea. A tall 20-storey gopura, the beach, and boat rides to nearby Netrani Island for scuba diving make it a major stop on the coast. Temple entry is free; a small lift ticket (around ₹10-30) takes visitors up the gopura for a panoramic sea view, typically running 7-1 and 3-8.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/dc/Shiva_Statue_Murdeshwara_Temple.jpg",
    openingTimings: "6:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 90,
    latitude: "14.0942",
    longitude: "74.4848",
  },
  {
    slug: "netrani-island",
    name: "Netrani Island",
    state: "Karnataka",
    district: "Uttara Kannada",
    category: "adventure",
    placeType: "Island",
    shortDescription: "Heart-shaped island off Murudeshwara, one of India's best scuba diving and snorkelling sites.",
    description: "Netrani (Pigeon) Island lies about 19 km off Murudeshwara in the Arabian Sea and is celebrated for some of India's clearest waters, coral reefs and marine life. Boat trips from Murudeshwara bring divers and snorkellers to its heart-shaped shores.",
    imageUrl: null,
    openingTimings: "Boat tours 8:00 AM - 4:00 PM",
    entryFees: 0,
    budgetPerDay: 2500,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb,Mar,Apr",
    isHidden: true,
    popularity: 60,
    latitude: "14.0169266",
    longitude: "74.3272202",
  },
  {
    slug: "idagunji-ganapathi-temple",
    name: "Idagunji Mahaganapathi Temple",
    state: "Karnataka",
    district: "Uttara Kannada",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Ancient and richly endowed Ganesha temple near Honnavar, one of South India's most visited Ganapathi shrines.",
    description: "The Idagunji Mahaganapathi Temple near Honnavar is one of the most revered and frequented Ganesha temples in coastal Karnataka, believed to be around 1500 years old. The two-armed standing Ganesha idol draws large numbers of devotees seeking blessings and prosperity.",
    imageUrl: null,
    openingTimings: "6:00 AM - 1:00 PM, 3:00 PM - 8:30 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 66,
    latitude: "14.1830",
    longitude: "74.5290",
  },
  {
    slug: "yana-rocks",
    name: "Yana Rocks",
    state: "Karnataka",
    district: "Uttara Kannada",
    category: "adventure",
    placeType: "Rock Formation",
    shortDescription: "Two towering black crystalline limestone monoliths set in Sahyadri forest, a trek-and-pilgrimage spot.",
    description: "Yana, deep in the Sahyadri forests of Uttara Kannada, is famous for two massive karst rock outcrops — Bhairaveshwara Shikhara and Mohini Shikhara — formed of black crystalline limestone. A forest trail leads to a cave shrine of Shiva beneath the larger rock, blending trekking with pilgrimage.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Yana_Rocks.jpg/1280px-Yana_Rocks.jpg",
    openingTimings: "7:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 68,
    latitude: "14.5900339",
    longitude: "74.566979",
  },
  {
    slug: "apsarakonda-falls",
    name: "Apsarakonda Falls",
    state: "Karnataka",
    district: "Uttara Kannada",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription: "Tiered waterfall near Honnavar with a temple and a cliff-top viewpoint over the Arabian Sea.",
    description: "Apsarakonda Falls near Honnavar is a multi-step waterfall that drops into a pool amid greenery, with a nearby cave and the Ardhanarishwara temple. A short walk leads to a cliff-top viewpoint offering wide views of the Arabian Sea and coastline.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/ApsarakondaTemple.JPG/1280px-ApsarakondaTemple.JPG",
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 52,
    latitude: "14.230505",
    longitude: "74.4464054",
  },
  {
    slug: "magod-falls",
    name: "Magod Falls",
    state: "Karnataka",
    district: "Uttara Kannada",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription: "Two-step waterfall where the Bedti river plunges nearly 200 m into a forested gorge near Yellapur.",
    description: "Magod Falls near Yellapur is a spectacular waterfall where the Bedti (Gangavali) river drops in two leaps totalling around 200 metres into a deep, forested valley. Viewpoints on the rim and the nearby Jenukallu Gudda offer dramatic views of the gorge.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 20,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 58,
    latitude: "14.8648676",
    longitude: "74.7592161",
  },
  {
    slug: "unchalli-falls",
    name: "Unchalli (Lushington) Falls",
    state: "Karnataka",
    district: "Uttara Kannada",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription: "Mist-shrouded ~116 m fall of the Aghanashini river near Siddapur, reached by a forest trek.",
    description: "Unchalli Falls, also called Lushington Falls, is formed by the Aghanashini river plunging around 116 metres into a misty gorge near Siddapur. A trek of a few kilometres through forest leads to a viewpoint where the roaring cascade and rising spray create a striking spectacle.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Unchalli_falls_SIRSI.png/1280px-Unchalli_falls_SIRSI.png",
    openingTimings: "8:00 AM - 5:00 PM",
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 54,
    latitude: "14.4360",
    longitude: "74.7430",
  },
  {
    slug: "sathodi-falls",
    name: "Sathodi Falls",
    state: "Karnataka",
    district: "Uttara Kannada",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription: "Wide horseshoe waterfall in dense forest near Yellapur, fed by streams flowing into the Kali backwaters.",
    description: "Sathodi Falls near Yellapur is a roughly 15 m wide waterfall where forest streams cascade into a pool that flows toward the Kodasalli backwaters of the Kali river. Surrounded by thick Western Ghats forest, it is a refreshing and scenic spot.",
    imageUrl: null,
    openingTimings: "8:00 AM - 5:30 PM",
    entryFees: 20,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 50,
    latitude: "14.8910",
    longitude: "74.6080",
  },
  {
    slug: "sirsi-marikamba-temple",
    name: "Sirsi Marikamba Temple",
    state: "Karnataka",
    district: "Uttara Kannada",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Largest Marikamba (Durga) temple in Karnataka at Sirsi, famed for its grand biennial Marikamba Jatre.",
    description: "The Sri Marikamba Temple at Sirsi, built around 1688, is considered the largest temple of goddess Marikamba (a form of Durga) in Karnataka. It is renowned for the spectacular Marikamba Jatre held every two years, one of the biggest temple fairs in the state.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Marikamba_TempleinSirsi.jpg/1280px-Marikamba_TempleinSirsi.jpg",
    openingTimings: "6:00 AM - 1:00 PM, 4:00 PM - 8:30 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 62,
    latitude: "14.612293",
    longitude: "74.8396078",
  },
  {
    slug: "sahasralinga",
    name: "Sahasralinga",
    state: "Karnataka",
    district: "Uttara Kannada",
    category: "pilgrimage",
    placeType: "Sacred Site",
    shortDescription: "Riverbed near Sirsi carved with a thousand Shiva lingas and Nandi figures on the Shalmala rocks.",
    description: "Sahasralinga, on the Shalmala river near Sirsi, is a sacred site where hundreds of Shiva lingas and accompanying Nandi bulls are carved into the rocks of the riverbed. Most visible when the water is low, the lingas draw large crowds during Maha Shivaratri.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 56,
    latitude: "14.7198621",
    longitude: "74.80743439999999",
  },
  {
    slug: "banavasi-madhukeshwara",
    name: "Banavasi Madhukeshwara Temple",
    state: "Karnataka",
    district: "Uttara Kannada",
    category: "heritage",
    placeType: "Temple",
    shortDescription: "9th-century Kadamba-era Shiva temple at Banavasi, the oldest capital town in Karnataka.",
    description: "Banavasi, the ancient capital of the Kadamba dynasty, is home to the Madhukeshwara Temple dedicated to Shiva, dating to around the 9th century with later additions. The temple's honey-coloured Shivalinga, stone cot and rich Kadamba and Hoysala sculpture make it a key heritage monument, celebrated during the Kadambotsava festival.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Madhukeshwara_Temple%2C_Banavasi.jpg/1280px-Madhukeshwara_Temple%2C_Banavasi.jpg",
    openingTimings: "6:30 AM - 8:30 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 58,
    latitude: "14.5352956",
    longitude: "75.01713400000001",
  },
  {
    slug: "karwar-rabindranath-tagore-beach",
    name: "Rabindranath Tagore Beach, Karwar",
    state: "Karnataka",
    district: "Uttara Kannada",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Karwar's main town beach with a naval museum warship (INS Chapala) and a children's park.",
    description: "Rabindranath Tagore Beach is Karwar's premier town beach, named after the poet who was inspired here. Its promenade features a maritime museum aboard the decommissioned warship INS Chapala, an aquarium, gardens and an island viewpoint, making it a lively family destination.",
    imageUrl: null,
    openingTimings: "Open 24 hours",
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 70,
    latitude: "14.8106995",
    longitude: "74.1265652",
  },
  {
    slug: "devbagh-beach",
    name: "Devbagh Beach",
    state: "Karnataka",
    district: "Uttara Kannada",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Casuarina-fringed island beach near Karwar, a quiet retreat known for water sports and a nature camp.",
    description: "Devbagh Beach lies on an island near Karwar at the mouth of the Kali river, fringed by casuarina and pine forest. Reached by boat, it offers white sand, water sports and a Jungle Lodges nature camp, making it a tranquil getaway off the main coast.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Karwar_Evening.jpg/1280px-Karwar_Evening.jpg",
    openingTimings: "Open 24 hours",
    entryFees: 0,
    budgetPerDay: 1500,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 56,
    latitude: "14.8030",
    longitude: "74.1060",
  },
  {
    slug: "kurumgad-island",
    name: "Kurumgad Island",
    state: "Karnataka",
    district: "Uttara Kannada",
    category: "beach",
    placeType: "Island",
    shortDescription: "Tortoise-shaped island off Karwar with a Narasimha temple, trekking trails and a quiet beach.",
    description: "Kurumgad is a small tortoise-shaped island off the Karwar coast, reachable by boat. It is known for a Narasimha temple visited during an annual festival, short hilltop treks, and secluded beaches, offering a peaceful island escape with sea views.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Karwar_Evening.jpg/1280px-Karwar_Evening.jpg",
    openingTimings: "Boat trips 9:00 AM - 5:00 PM",
    entryFees: 0,
    budgetPerDay: 1500,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 48,
    latitude: "14.7920",
    longitude: "74.1090",
  },
  {
    slug: "dandeli-wildlife",
    name: "Dandeli",
    state: "Karnataka",
    district: "Uttara Kannada",
    category: "wildlife",
    placeType: "Wildlife Sanctuary",
    shortDescription: "Adventure and wildlife hub on the Kali river, famed for white-water rafting, kayaking and birding.",
    description: "Dandeli, set amid the dense forests of the Western Ghats on the Kali river, is one of Karnataka's top adventure destinations. It offers white-water rafting, kayaking, coracle rides, jungle safaris and excellent birdwatching, and forms part of the Dandeli-Anshi (Kali) Tiger Reserve known for hornbills, black panthers and elephants.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 200,
    budgetPerDay: 2500,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 80,
    latitude: "15.2361191",
    longitude: "74.6172819",
  },
  {
    slug: "kali-tiger-reserve",
    name: "Kali Tiger Reserve (Dandeli-Anshi)",
    state: "Karnataka",
    district: "Uttara Kannada",
    category: "wildlife",
    placeType: "Tiger Reserve",
    shortDescription: "Vast tiger reserve in the Western Ghats spanning Anshi and Dandeli forests along the Kali river.",
    description: "The Kali Tiger Reserve, formed from the Anshi National Park and Dandeli Wildlife Sanctuary, protects rich evergreen and moist deciduous forests of Uttara Kannada. Home to tigers, black panthers, elephants, hornbills and the king cobra, it offers jeep safaris from the Anshi and Kulgi ranges.",
    imageUrl: null,
    openingTimings: "Safari 6:00 AM - 9:00 AM, 3:30 PM - 6:00 PM",
    entryFees: 300,
    budgetPerDay: 2500,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 66,
    latitude: "15.0480",
    longitude: "74.4060",
  },
  {
    slug: "syntheri-rocks",
    name: "Syntheri Rocks",
    state: "Karnataka",
    district: "Uttara Kannada",
    category: "adventure",
    placeType: "Rock Formation",
    shortDescription: "Towering monolithic granite rock formation inside Dandeli forest, beside the Kaneri stream.",
    description: "Syntheri Rocks is a single, massive granite monolith rising about 300 feet within the Dandeli forest, carved over time by the Kaneri stream at its base. Honeycombed with rock-bee hives and surrounded by wildlife habitat, it is a striking natural formation reached through the reserve.",
    imageUrl: null,
    openingTimings: "8:00 AM - 5:00 PM",
    entryFees: 50,
    budgetPerDay: 1500,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 50,
    latitude: "15.2640",
    longitude: "74.4760",
  },
  {
    slug: "om-beach",
    name: "Om Beach, Gokarna",
    state: "Karnataka",
    district: "Uttara Kannada",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Iconic Gokarna beach naturally shaped like the Om symbol, popular for swimming and sunsets.",
    description: "Om Beach near Gokarna is named for its distinctive shape resembling the Hindu Om symbol, formed by two joined crescents of sand. A favourite for swimming, sunbathing and water sports, it is also the start of the popular beach trek linking Kudle, Half Moon and Paradise beaches.",
    imageUrl: null,
    openingTimings: "Open 24 hours",
    entryFees: 0,
    budgetPerDay: 1300,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 84,
    latitude: "14.5192405",
    longitude: "74.3230039",
  },
  {
    slug: "kudle-beach",
    name: "Kudle Beach, Gokarna",
    state: "Karnataka",
    district: "Uttara Kannada",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Laid-back crescent beach near Gokarna town lined with cafes and shacks, ideal for sunsets.",
    description: "Kudle Beach is a relaxed, broad crescent of sand near Gokarna town, popular with backpackers for its beach cafes, yoga, and spectacular sunsets. It is the first stop on the classic Gokarna beach trek and offers a calmer alternative to the temple town.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Delight_india.jpg",
    openingTimings: "Open 24 hours",
    entryFees: 0,
    budgetPerDay: 1300,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 76,
    latitude: "14.5437315",
    longitude: "74.3135985",
  },
  {
    slug: "half-moon-beach-gokarna",
    name: "Half Moon Beach, Gokarna",
    state: "Karnataka",
    district: "Uttara Kannada",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Secluded half-moon shaped cove near Gokarna reached only by trek or boat.",
    description: "Half Moon Beach is a small, secluded crescent cove between Om and Paradise beaches near Gokarna, accessible only by a forest trek or a boat ride. Its quiet sands and minimal crowds make it a favourite for those seeking solitude on the coast.",
    imageUrl: null,
    openingTimings: "Open 24 hours",
    entryFees: 0,
    budgetPerDay: 1300,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 58,
    latitude: "14.5180064",
    longitude: "74.3314822",
  },
  {
    slug: "paradise-beach-gokarna",
    name: "Paradise Beach, Gokarna",
    state: "Karnataka",
    district: "Uttara Kannada",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Remote, pristine beach (Full Moon Beach) at the end of the Gokarna trek, reached by boat or hike.",
    description: "Paradise Beach, also called Full Moon Beach, is the most remote of the Gokarna beaches, reached by boat or a longer trek past Half Moon Beach. With clear water and no road access, it offers an unspoilt, off-grid coastal experience.",
    imageUrl: null,
    openingTimings: "Open 24 hours",
    entryFees: 0,
    budgetPerDay: 1300,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 56,
    latitude: "14.5000",
    longitude: "74.3200",
  },
  {
    slug: "gokarna-mahabaleshwara",
    name: "Gokarna Mahabaleshwara Temple",
    state: "Karnataka",
    district: "Uttara Kannada",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Ancient Shiva temple at Gokarna housing the revered Atmalinga, one of coastal Karnataka's holiest shrines.",
    description: "The Mahabaleshwara Temple at Gokarna enshrines the Atmalinga, said to have been brought from Kailasa by Ravana, making it one of the most sacred Shiva shrines on the west coast. Pilgrims bathe at the Koti Teertha tank and the temple is central to Gokarna's status as a major pilgrimage town. Entry is free, but the dress code is strictly enforced: men must remove shirts and wear a dhoti, women must wear a saree or salwar covering the shoulders and knees — jeans, shorts and Bermudas are not allowed inside.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Delight_india.jpg",
    openingTimings: "6:00 AM - 12:30 PM, 5:00 PM - 8:30 PM",
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 82,
    latitude: "14.5435357",
    longitude: "74.31641909999999",
  },
  {
    slug: "gokarna-main-beach",
    name: "Gokarna Beach",
    state: "Karnataka",
    district: "Uttara Kannada",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Wide town beach at Gokarna used for rituals and relaxation, near the Mahabaleshwara temple.",
    description: "Gokarna Beach is the long, broad main town beach beside the temple precinct, used both for religious rituals and casual relaxation. Less commercialised than Om or Kudle, it offers a glimpse of the town's pilgrim life along with open sands and sunset views.",
    imageUrl: null,
    openingTimings: "7:00 AM - 7:00 PM",
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 68,
    latitude: "14.5437352",
    longitude: "74.3136288",
  },
  {
    slug: "mirjan-fort",
    name: "Mirjan Fort",
    state: "Karnataka",
    district: "Uttara Kannada",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Sprawling laterite fort near Kumta on the Aghanashini river, linked to the queen Chennabhairadevi.",
    description: "Mirjan Fort near Kumta is a large laterite stone fort set amid greenery on the banks of the Aghanashini river. Associated with the pepper-trading queen Chennabhairadevi, its high walls, bastions, wells and arched gateways make it one of the best-preserved historic forts on the Karnataka coast.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Mirjan_Fort_02.JPG/1280px-Mirjan_Fort_02.JPG",
    openingTimings: "8:00 AM - 5:30 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 58,
    latitude: "14.4893403",
    longitude: "74.41756459999999",
  },
  {
    slug: "sadashivgad-fort",
    name: "Sadashivgad Fort",
    state: "Karnataka",
    district: "Uttara Kannada",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Hilltop fort ruins above the Kali river mouth near Karwar with a Durga temple and estuary views.",
    description: "Sadashivgad Fort sits on a hill overlooking the mouth of the Kali river near Karwar, built by the Sonda rulers and later contested by the Marathas and British. The hilltop hosts the Durga Devi temple and offers sweeping views of the river estuary, the bridge and the Arabian Sea.",
    imageUrl: null,
    openingTimings: "7:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 44,
    latitude: "14.8350",
    longitude: "74.1300",
  },
  {
    slug: "kali-river-dandeli",
    name: "Kali River",
    state: "Karnataka",
    district: "Uttara Kannada",
    category: "adventure",
    placeType: "River",
    shortDescription: "Western Ghats river through Dandeli offering white-water rafting, kayaking and coracle rides.",
    description: "The Kali river flows through the forests of Uttara Kannada and is the centre of Dandeli's adventure tourism, with rapids suitable for white-water rafting, plus kayaking, coracle rides and riverside camping. Its backwaters and gorges also support rich wildlife and birdlife.",
    imageUrl: null,
    openingTimings: "Rafting 9:00 AM - 4:00 PM",
    entryFees: 0,
    budgetPerDay: 2500,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 64,
    latitude: "15.2230",
    longitude: "74.6100",
  },
  {
    slug: "tadri-beach-kumta",
    name: "Kumta Beaches (Nirvana / Vibhooti)",
    state: "Karnataka",
    district: "Uttara Kannada",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Cluster of quiet, scenic beaches around Kumta including Nirvana Beach and the Vibhooti viewpoint.",
    description: "The Kumta coast features several tranquil beaches such as Nirvana (Kumta) Beach and the nearby Vibhooti area, set between the towns of Gokarna and Honnavar. With clean sands, casuarina cover and far fewer crowds, they are favoured by travellers seeking a peaceful stretch of the Karnataka coast.",
    imageUrl: null,
    openingTimings: "Open 24 hours",
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 46,
    latitude: "14.4180",
    longitude: "74.4030",
  },
];
