import type { NewDestination } from "../schema";

// Karnataka — Malnad / central (Chikkamagaluru, Shivamogga, Davanagere, Chitradurga)
export const karnatakaMalnadRegion: Omit<NewDestination, "id" | "createdAt">[] = [
  // ===================== CHIKKAMAGALURU =====================
  {
    slug: "mullayanagiri",
    name: "Mullayanagiri",
    state: "Karnataka",
    district: "Chikkamagaluru",
    category: "hill_station",
    placeType: "Peak",
    shortDescription: "Karnataka's highest peak (~1,930 m) with a hilltop shrine and sweeping Western Ghats views.",
    description: "Mullayanagiri is the tallest peak in Karnataka, part of the Baba Budan range. A short trek leads to a small temple at the summit, with panoramic views over rolling green hills. It is a favourite for sunrise, mist and monsoon greenery.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1300,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 90,
    latitude: "13.3908855",
    longitude: "75.7213295",
  },
  {
    slug: "baba-budangiri",
    name: "Baba Budangiri",
    state: "Karnataka",
    district: "Chikkamagaluru",
    category: "hill_station",
    placeType: "Mountain Range",
    shortDescription: "Sacred mist-clad range famed for its dargah-shrine, coffee history and the Manikyadhara falls.",
    description: "Baba Budangiri is a revered range named after the Sufi saint Baba Budan, who is said to have introduced coffee to India here. The cave shrine of Dattatreya Peetha draws both Hindu and Muslim pilgrims. The grassy ridges, Manikyadhara waterfall and trekking trails make it a popular Malnad stop.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/A_scenery_from_bababudan_hill.jpg/1280px-A_scenery_from_bababudan_hill.jpg",
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1300,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 82,
    latitude: "13.422865",
    longitude: "75.77038759999999",
  },
  {
    slug: "kemmangundi",
    name: "Kemmangundi",
    state: "Karnataka",
    district: "Chikkamagaluru",
    category: "hill_station",
    placeType: "Hill Station",
    shortDescription: "Terraced gardens, Z-Point view and Raj Bhavan retreat set high in the Baba Budan hills.",
    description: "Kemmangundi, also called Krishnarajendra Hill Station, was the summer retreat of the Mysore Wodeyars. It is known for its ornamental Rock Garden, mountain-top Raj Bhavan, the Z-Point sunset viewpoint and the nearby Hebbe and Kalhatti falls. Cool weather and misty valleys define the experience.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 20,
    budgetPerDay: 1400,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 80,
    latitude: "13.5500",
    longitude: "75.7500",
  },
  {
    slug: "kudremukh",
    name: "Kudremukh",
    state: "Karnataka",
    district: "Chikkamagaluru",
    category: "hill_station",
    placeType: "Peak & National Park",
    shortDescription: "Horse-face peak (~1,894 m) inside a biodiverse national park; one of Karnataka's classic treks.",
    description: "Kudremukh, meaning 'horse face' for its profile, is the third-highest peak in Karnataka and the heart of Kudremukh National Park. The challenging trek crosses grassland-shola hills, streams and rolling meadows. The park shelters tigers, lion-tailed macaques and rich shola-grassland ecosystems.",
    imageUrl: null,
    openingTimings: "6:00 AM - 5:00 PM",
    entryFees: 600,
    budgetPerDay: 1800,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 79,
    latitude: "13.2240",
    longitude: "75.2540",
  },
  {
    slug: "hebbe-falls",
    name: "Hebbe Falls",
    state: "Karnataka",
    district: "Chikkamagaluru",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription: "Two-tier falls (~168 m) reached by a jeep ride and trek through coffee and cardamom estates near Kemmangundi.",
    description: "Hebbe Falls plunges in two stages — Dodda Hebbe (big falls) and Chikka Hebbe (small falls) — deep within forest below Kemmangundi. Reaching it involves a rugged jeep ride and a short trek through coffee and cardamom plantations. The pool at the base is a popular spot for a cold dip.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Hebbe_Falls.JPG/1280px-Hebbe_Falls.JPG",
    openingTimings: "9:00 AM - 5:00 PM",
    entryFees: 50,
    budgetPerDay: 1400,
    recommendedDays: 1,
    bestMonths: "Aug,Sep,Oct,Nov,Dec,Jan",
    isHidden: false,
    popularity: 74,
    latitude: "13.5917",
    longitude: "75.7361",
  },
  {
    slug: "kalhatti-falls",
    name: "Kalhatti Falls",
    state: "Karnataka",
    district: "Chikkamagaluru",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription: "Sacred ~122 m cascade falling beside a Veerabhadra temple near Kemmangundi.",
    description: "Kalhatti Falls drops about 122 metres over a rock face, with the water flowing past the ancient Kalhatteshwara (Veerabhadra) temple built into the rock at its base. The site combines a pilgrimage stop with a scenic monsoon waterfall on the way to Kemmangundi.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Aug,Sep,Oct,Nov,Dec",
    isHidden: false,
    popularity: 66,
    latitude: "13.5167",
    longitude: "75.7167",
  },
  {
    slug: "bhadra-wildlife-sanctuary",
    name: "Bhadra Wildlife Sanctuary",
    state: "Karnataka",
    district: "Chikkamagaluru",
    category: "wildlife",
    placeType: "Tiger Reserve",
    shortDescription: "Project Tiger reserve on the Bhadra river with tigers, elephants and boat safaris around the reservoir.",
    description: "Bhadra Wildlife Sanctuary, a designated Project Tiger reserve, spans dense moist-deciduous forest around the Bhadra reservoir. It is home to tigers, leopards, elephants, gaur and over 250 bird species. Jeep safaris and reservoir boat rides from the Lakkavalli side are the main draws.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/cd/2006-Tigers-and-Gaurs.jpg",
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 400,
    budgetPerDay: 2000,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 72,
    latitude: "13.7000",
    longitude: "75.6333",
  },
  {
    slug: "sringeri-sharada-peetham",
    name: "Sringeri Sharada Peetham",
    state: "Karnataka",
    district: "Chikkamagaluru",
    category: "pilgrimage",
    placeType: "Matha / Peetham",
    shortDescription: "First of Adi Shankaracharya's four mathas, on the Tunga river, with the famed Sharadamba temple.",
    description: "Sringeri is the southern Sharada Peetham, the first matha established by Adi Shankaracharya. The Sharadamba temple honours the goddess of learning, and the nearby Vidyashankara temple is celebrated for its astronomical stone pillars. Tame fish in the Tunga river add to the serene setting. Darshan is free with only voluntary donations for sevas; the temple closes for a few hours in the afternoon.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Sharadamba_Temple.jpg/1280px-Sharadamba_Temple.jpg",
    openingTimings: "6:00 AM - 2:00 PM, 4:00 PM - 9:00 PM",
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 81,
    latitude: "13.4161409",
    longitude: "75.25133869999999",
  },
  {
    slug: "horanadu-annapoorneshwari",
    name: "Horanadu Annapoorneshwari Temple",
    state: "Karnataka",
    district: "Chikkamagaluru",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Riverside temple of Adi Shakti Annapoorneshwari, famed for free meals served to all pilgrims.",
    description: "The Sri Annapoorneshwari temple at Horanadu, on the banks of the Bhadra, enshrines the goddess of food and nourishment. Pilgrims are traditionally served free meals (anna-dasoha) at all hours. The temple is a key stop on the Western Ghats pilgrimage circuit.",
    imageUrl: null,
    openingTimings: "6:00 AM - 9:00 PM",
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 73,
    latitude: "13.2167",
    longitude: "75.1000",
  },
  {
    slug: "belavadi-veeranarayana-temple",
    name: "Belavadi Veeranarayana Temple",
    state: "Karnataka",
    district: "Chikkamagaluru",
    category: "heritage",
    placeType: "Hoysala Temple",
    shortDescription: "Large 13th-century Hoysala trikuta temple at Belavadi with elegant pillared halls.",
    description: "The Veeranarayana temple at Belavadi is one of the largest Hoysala temples, built around 1200 CE. Its trikuta (three-shrine) layout, two pillared mantapas and finely lathe-turned columns showcase Hoysala craftsmanship. Belavadi is linked in legend to the Ekachakranagara of the Mahabharata.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Shri_VeeraNarayana_Temple%2C_Belavadi.jpg/1280px-Shri_VeeraNarayana_Temple%2C_Belavadi.jpg",
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 55,
    latitude: "13.2820298",
    longitude: "75.9956878",
  },
  {
    slug: "amruthapura-amruteshwara-temple",
    name: "Amruthapura Amruteshwara Temple",
    state: "Karnataka",
    district: "Chikkamagaluru",
    category: "heritage",
    placeType: "Hoysala Temple",
    shortDescription: "1196 CE Hoysala temple near Tarikere known for its long sculpted parapet and lathe-turned pillars.",
    description: "The Amruteshwara temple at Amruthapura was built in 1196 CE by Amriteshwara Dandanayaka, a commander under the Hoysala king Veera Ballala II. It is admired for its open mantapa, finely lathe-turned pillars and one of the longest decorated wall friezes among Hoysala temples.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Amrutesvara_temple_at_Amruthapura_in_Chikkamagaluru_district.JPG/1280px-Amrutesvara_temple_at_Amruthapura_in_Chikkamagaluru_district.JPG",
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 50,
    latitude: "13.7418045",
    longitude: "75.8526692",
  },
  {
    slug: "hirekolale-lake",
    name: "Hirekolale Lake",
    state: "Karnataka",
    district: "Chikkamagaluru",
    category: "adventure",
    placeType: "Lake & Viewpoint",
    shortDescription: "Scenic lake near Chikkamagaluru town ringed by the Baba Budan hills, popular for sunsets.",
    description: "Hirekolale Lake is a calm reservoir just outside Chikkamagaluru town, backed by the Mullayanagiri and Baba Budan ranges. Its still waters mirror the hills at dusk, making it a favourite sunset and picnic spot close to the city.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:30 PM",
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 58,
    latitude: "13.3300",
    longitude: "75.7430",
  },
  {
    slug: "ayyanakere-lake",
    name: "Ayyanakere Lake",
    state: "Karnataka",
    district: "Chikkamagaluru",
    category: "adventure",
    placeType: "Lake",
    shortDescription: "One of Karnataka's largest old tanks, set below the Baba Budan hills near Sakharayapatna.",
    description: "Ayyanakere is among the largest ancient irrigation tanks in Karnataka, fed by the Baba Budan range. Built centuries ago, the wide reservoir against a backdrop of green hills is a tranquil spot for birdwatching, photography and quiet evenings.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/A_view_of_Ayyanakere_Lake_from_Southeast..jpg/1280px-A_view_of_Ayyanakere_Lake_from_Southeast..jpg",
    openingTimings: "Open 24 hours",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Aug,Sep,Oct,Nov,Dec,Jan",
    isHidden: true,
    popularity: 48,
    latitude: "13.4432234",
    longitude: "75.8780855",
  },
  {
    slug: "kodandarama-temple-hiremagalur",
    name: "Kodandarama Temple, Hiremagalur",
    state: "Karnataka",
    district: "Chikkamagaluru",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Unusual Rama temple near Chikkamagaluru where Sita stands to Rama's right, with a Parashurama shrine.",
    description: "The Kodandarama temple at Hiremagalur is unusual for depicting Sita on the right of Rama, said to represent their wedding form. The complex also venerates Parashurama and reflects a blend of Vaishnava traditions in a quiet town setting near Chikkamagaluru.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Kothanda_Ramar_temple%2C_Hiremagalur_03.jpg/1280px-Kothanda_Ramar_temple%2C_Hiremagalur_03.jpg",
    openingTimings: "7:00 AM - 12:30 PM, 5:00 PM - 8:30 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 45,
    latitude: "13.3220",
    longitude: "75.7900",
  },
  {
    slug: "manikyadhara-falls",
    name: "Manikyadhara Falls",
    state: "Karnataka",
    district: "Chikkamagaluru",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription: "Sacred spray-falls near the Baba Budangiri dargah, believed to never run dry.",
    description: "Manikyadhara Falls trickles down a cliff near the Baba Budangiri dargah, its fine spray giving the appearance of falling pearls. Considered holy, the perennial stream is part of the pilgrimage to Dattatreya Peetha and offers cool relief amid the hills.",
    imageUrl: null,
    openingTimings: "7:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Aug,Sep,Oct,Nov,Dec",
    isHidden: true,
    popularity: 57,
    latitude: "13.4150",
    longitude: "75.7320",
  },
  {
    slug: "mullayanagiri-coffee-estates",
    name: "Chikkamagaluru Coffee Estates",
    state: "Karnataka",
    district: "Chikkamagaluru",
    category: "hill_station",
    placeType: "Coffee Estate Stay",
    shortDescription: "Sprawling coffee plantations around Chikkamagaluru offering estate stays, walks and bean tours.",
    description: "Chikkamagaluru is the birthplace of Indian coffee, and its rolling estates of Arabica and Robusta define the landscape. Many plantations offer homestays, guided plantation walks, bean-processing tours and birdwatching amid silver-oak shade trees, making it a relaxed base for the region.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Chikmagalur%2C_India._%287793316622%29.jpg/1280px-Chikmagalur%2C_India._%287793316622%29.jpg",
    openingTimings: "6:00 AM - 11:00 PM",
    entryFees: 0,
    budgetPerDay: 2500,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 70,
    latitude: "13.3142764",
    longitude: "75.7710462",
  },
  {
    slug: "z-point-kemmangundi",
    name: "Z Point",
    state: "Karnataka",
    district: "Chikkamagaluru",
    category: "hill_station",
    placeType: "Viewpoint",
    shortDescription: "Cliff-edge sunset viewpoint above Kemmangundi reached by a short forest trek.",
    description: "Z Point is a popular viewpoint near Kemmangundi, reached by a scenic 30-40 minute trek through shola forest and grassland. The cliff offers wide views of layered valleys and is a celebrated spot to watch the sun set behind the Baba Budan hills.",
    imageUrl: null,
    openingTimings: "8:00 AM - 5:30 PM",
    entryFees: 0,
    budgetPerDay: 1300,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 60,
    latitude: "13.5460",
    longitude: "75.7530",
  },

  // ===================== SHIVAMOGGA =====================
  {
    slug: "jog-falls",
    name: "Jog Falls",
    state: "Karnataka",
    district: "Shivamogga",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription: "India's iconic ~253 m plunge of the Sharavathi in four streams — Raja, Rani, Rover and Rocket.",
    description: "Jog Falls is one of India's tallest plunge waterfalls, where the Sharavathi river drops about 253 metres in four distinct streams named Raja, Rani, Rover and Rocket. Spectacular during the monsoon, it is best viewed from the opposite cliff or by descending the long stairway to the base. Entry is around ₹20 for Indian visitors (₹100 for foreign tourists), with separate charges for parking, cameras, and drones.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 20,
    budgetPerDay: 1400,
    recommendedDays: 1,
    bestMonths: "Aug,Sep,Oct,Nov,Dec",
    isHidden: false,
    popularity: 92,
    latitude: "14.2294",
    longitude: "74.8126",
  },
  {
    slug: "kodachadri",
    name: "Kodachadri",
    state: "Karnataka",
    district: "Shivamogga",
    category: "hill_station",
    placeType: "Peak & Trek",
    shortDescription: "UNESCO-listed Western Ghats peak (~1,343 m) with shola forests, the Sarvajna Peetha and jeep treks.",
    description: "Kodachadri is a high peak in the Western Ghats, declared a natural heritage site, rising above dense shola forest. The trek or rugged jeep ride leads to the Sarvajna Peetha shrine linked to Adi Shankaracharya and offers sweeping views toward the Arabian Sea on clear days.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Kodachadri.JPG/1280px-Kodachadri.JPG",
    openingTimings: "6:00 AM - 5:00 PM",
    entryFees: 200,
    budgetPerDay: 1600,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 78,
    latitude: "13.8623079",
    longitude: "74.8752009",
  },
  {
    slug: "agumbe",
    name: "Agumbe",
    state: "Karnataka",
    district: "Shivamogga",
    category: "hill_station",
    placeType: "Rainforest & Sunset Point",
    shortDescription: "The 'Cherrapunji of the South' — rainforest village famed for sunsets and king cobra research.",
    description: "Agumbe is one of the wettest places in South India, cloaked in tropical rainforest and home to the Agumbe Rainforest Research Station known for king cobra studies. Its sunset viewpoint over the Western Ghats, monsoon waterfalls and misty trails draw nature lovers and trekkers.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Agumbe_View_point.jpg/1280px-Agumbe_View_point.jpg",
    openingTimings: "6:00 AM - 6:30 PM",
    entryFees: 0,
    budgetPerDay: 1500,
    recommendedDays: 2,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 77,
    latitude: "13.5026635",
    longitude: "75.0903154",
  },
  {
    slug: "linganamakki-dam",
    name: "Linganamakki Dam",
    state: "Karnataka",
    district: "Shivamogga",
    category: "adventure",
    placeType: "Dam & Reservoir",
    shortDescription: "Massive Sharavathi reservoir near Jog Falls, a vast scenic backwater for boating and photography.",
    description: "Linganamakki Dam impounds the Sharavathi river to form one of Karnataka's largest reservoirs, feeding the hydro-power stations that channel the Jog Falls flow. The expansive backwaters set against forested hills are popular for boating, sunsets and watching the dam release during heavy monsoon.",
    imageUrl: null,
    openingTimings: "9:00 AM - 5:30 PM",
    entryFees: 0,
    budgetPerDay: 1300,
    recommendedDays: 1,
    bestMonths: "Aug,Sep,Oct,Nov,Dec,Jan",
    isHidden: false,
    popularity: 64,
    latitude: "14.1810",
    longitude: "74.8480",
  },
  {
    slug: "sigandur-chowdeshwari-temple",
    name: "Sigandur Chowdeshwari Temple",
    state: "Karnataka",
    district: "Shivamogga",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Powerful Chowdeshwari Devi temple amid the Sharavathi backwaters, reached by ferry and bridge.",
    description: "The Sri Sigandur Chowdeshwari temple sits among the Sharavathi backwaters and is revered as a guardian deity, with devotees seeking justice and protection of property. Long reached only by ferry, the recently opened Sigandur (Sharavathi) bridge now connects it across the reservoir.",
    imageUrl: null,
    openingTimings: "7:00 AM - 7:30 PM",
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 62,
    latitude: "14.1670",
    longitude: "74.7330",
  },
  {
    slug: "honnemaradu",
    name: "Honnemaradu",
    state: "Karnataka",
    district: "Shivamogga",
    category: "adventure",
    placeType: "Backwaters & Watersports",
    shortDescription: "Sharavathi backwater hamlet famed for kayaking, coracle rides and camping by the water.",
    description: "Honnemaradu lies on the Linganamakki backwaters of the Sharavathi and is a hub for water-based adventure — kayaking, canoeing, coracle rides, windsurfing and lakeside camping. Surrounded by forested islands and calm water, it is a favourite for adventure and nature retreats.",
    imageUrl: null,
    openingTimings: "7:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 2200,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 63,
    latitude: "14.1500",
    longitude: "74.8000",
  },
  {
    slug: "sakrebailu-elephant-camp",
    name: "Sakrebailu Elephant Camp",
    state: "Karnataka",
    district: "Shivamogga",
    category: "wildlife",
    placeType: "Elephant Camp",
    shortDescription: "Riverside elephant training and care camp on the Tunga, where visitors watch morning bathing and feeding.",
    description: "Sakrebailu Elephant Camp on the banks of the Tunga river near Shivamogga is a rehabilitation and training centre for elephants. Visitors can watch mahouts bathe, feed and train the herd in the morning, learning about elephant care in a forested riverside setting.",
    imageUrl: null,
    openingTimings: "8:30 AM - 11:00 AM, 4:00 PM - 6:00 PM",
    entryFees: 50,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 66,
    latitude: "13.9170",
    longitude: "75.4500",
  },
  {
    slug: "tyavarekoppa-lion-safari",
    name: "Tyavarekoppa Lion & Tiger Safari",
    state: "Karnataka",
    district: "Shivamogga",
    category: "wildlife",
    placeType: "Safari Park",
    shortDescription: "Lion and tiger safari park near Shivamogga with a small zoo and forested enclosures.",
    description: "Tyavarekoppa Lion and Tiger Safari, on the Shivamogga-Sagar road, lets visitors drive through forested enclosures to view lions and tigers up close. The adjoining zoo houses deer, bears and other wildlife, making it a popular family outing near the city.",
    imageUrl: null,
    openingTimings: "10:00 AM - 5:00 PM (Closed Tue)",
    entryFees: 200,
    budgetPerDay: 1300,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 60,
    latitude: "13.9738036",
    longitude: "75.4937044",
  },
  {
    slug: "keladi-rameshwara-temple",
    name: "Keladi Rameshwara Temple",
    state: "Karnataka",
    district: "Shivamogga",
    category: "heritage",
    placeType: "Heritage Temple",
    shortDescription: "Capital of the Keladi Nayakas with a fine three-shrine temple and a small history museum.",
    description: "Keladi was the first capital of the Keladi (Ikkeri) Nayakas. Its Rameshwara temple complex blends Hoysala, Dravidian and Vijayanagara styles, with carved ceilings and a notable Veerabhadra shrine. A museum nearby preserves coins, palm-leaf manuscripts and artefacts of the dynasty.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Rameshwara_Temple_in_Keladi.jpg/1280px-Rameshwara_Temple_in_Keladi.jpg",
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 54,
    latitude: "14.2241528",
    longitude: "75.0167558",
  },
  {
    slug: "ikkeri-aghoreshwara-temple",
    name: "Ikkeri Aghoreshwara Temple",
    state: "Karnataka",
    district: "Shivamogga",
    category: "heritage",
    placeType: "Heritage Temple",
    shortDescription: "Grand 16th-century Aghoreshwara temple, the architectural highlight of the Keladi Nayaka capital Ikkeri.",
    description: "Ikkeri served as a later capital of the Keladi Nayakas, and its large Aghoreshwara (Shiva) temple is a striking example of late Vijayanagara-Nayaka architecture. The stone temple features a high vimana, ornate carvings and a Nandi pavilion set on a spacious raised platform.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 56,
    latitude: "14.1350784",
    longitude: "75.02261349999999",
  },
  {
    slug: "tunga-river-shivamogga",
    name: "Tunga River Front, Shivamogga",
    state: "Karnataka",
    district: "Shivamogga",
    category: "pilgrimage",
    placeType: "River & Ghats",
    shortDescription: "The Tunga river flowing through Shivamogga city, with riverside ghats, temples and evening walks.",
    description: "The Tunga river gives Shivamogga its name and lifeblood, flowing through the city before joining the Bhadra. The riverfront, with its bathing ghats, bridges and the Sahyadri-fed clear waters, is a relaxed spot for evening strolls and is revered along its course from Sringeri downstream.",
    imageUrl: null,
    openingTimings: "Open 24 hours",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 47,
    latitude: "13.9302504",
    longitude: "75.5869872",
  },
  {
    slug: "kunchikal-falls",
    name: "Kunchikal Falls",
    state: "Karnataka",
    district: "Shivamogga",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription: "One of India's tallest falls on the Varahi river, cascading in tiers near Mastikatte.",
    description: "Kunchikal Falls, formed by the Varahi river, is among the highest waterfalls in India, tumbling in a series of cascades down rocky terrain. Largely controlled by the upstream Mani dam and hydel project, it is most impressive during and just after the monsoon.",
    imageUrl: null,
    openingTimings: "8:00 AM - 5:00 PM",
    entryFees: 0,
    budgetPerDay: 1300,
    recommendedDays: 1,
    bestMonths: "Aug,Sep,Oct,Nov",
    isHidden: true,
    popularity: 58,
    latitude: "13.6750",
    longitude: "75.0080",
  },
  {
    slug: "dabbe-falls",
    name: "Dabbe Falls",
    state: "Karnataka",
    district: "Shivamogga",
    category: "adventure",
    placeType: "Waterfall & Trek",
    shortDescription: "Remote multi-tier falls deep in the Sharavathi forests, reached by a demanding jungle trek from Hosagadde.",
    description: "Dabbe Falls is a spectacular series of cascades hidden within the Sharavathi Valley forests near Sagar. Reaching it requires a steep trek through dense jungle, rewarding adventurers with a powerful curtain of water in an unspoilt rainforest setting.",
    imageUrl: null,
    openingTimings: "7:00 AM - 4:00 PM",
    entryFees: 0,
    budgetPerDay: 1500,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan",
    isHidden: true,
    popularity: 52,
    latitude: "14.1080",
    longitude: "74.7920",
  },
  {
    slug: "sharavathi-valley-wildlife-sanctuary",
    name: "Sharavathi Valley Wildlife Sanctuary",
    state: "Karnataka",
    district: "Shivamogga",
    category: "wildlife",
    placeType: "Wildlife Sanctuary",
    shortDescription: "Lush Western Ghats sanctuary around the Sharavathi gorge, rich in lion-tailed macaques and endemic flora.",
    description: "Sharavathi Valley Wildlife Sanctuary protects the evergreen forests and gorge of the Sharavathi river above and below Jog Falls. It shelters lion-tailed macaques, hornbills, leopards and many endemic Western Ghats species, and forms part of a key biodiversity corridor.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 100,
    budgetPerDay: 1500,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 49,
    latitude: "14.0830",
    longitude: "74.8000",
  },
  {
    slug: "kavaledurga-fort",
    name: "Kavaledurga Fort",
    state: "Karnataka",
    district: "Shivamogga",
    category: "heritage",
    placeType: "Hill Fort",
    shortDescription: "Hilltop Keladi-era fort near Thirthahalli with stone ramparts, temples and forest views.",
    description: "Kavaledurga is a hill fort near Thirthahalli, rebuilt and strengthened under the Keladi Nayakas. A trek up the forested slope passes layered stone fortifications and reaches temples and the ruined palace area, with commanding views over the Malnad landscape.",
    imageUrl: null,
    openingTimings: "8:00 AM - 5:30 PM",
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 46,
    latitude: "13.7610",
    longitude: "75.0190",
  },
  {
    slug: "kuppalli-kuvempu-house",
    name: "Kuppalli (Kuvempu House)",
    state: "Karnataka",
    district: "Shivamogga",
    category: "heritage",
    placeType: "Memorial & Museum",
    shortDescription: "Birthplace and memorial of Jnanpith poet Kuvempu at Kuppalli, with his preserved home and Kavishaila.",
    description: "Kuppalli, near Thirthahalli, is the ancestral home of Kuvempu, the Jnanpith-winning Kannada poet. His restored house is now a museum, and the nearby Kavishaila — a Stonehenge-like rock arrangement where he is memorialised — offers reflective views of the Malnad hills.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/be/Kuvempu.jpg",
    openingTimings: "9:00 AM - 5:30 PM (Closed Mon)",
    entryFees: 30,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 50,
    latitude: "13.7800",
    longitude: "75.1000",
  },
  {
    slug: "gudavi-bird-sanctuary",
    name: "Gudavi Bird Sanctuary",
    state: "Karnataka",
    district: "Shivamogga",
    category: "wildlife",
    placeType: "Bird Sanctuary",
    shortDescription: "Lakeside bird sanctuary near Soraba hosting large nesting colonies of egrets, herons and storks.",
    description: "Gudavi Bird Sanctuary surrounds a freshwater lake near Soraba and is one of Karnataka's notable bird sanctuaries. During the breeding season it teems with egrets, herons, cormorants, ibises and storks, best observed from the lakeside watchtowers and trails.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/GDV1.jpg/1280px-GDV1.jpg",
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 50,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Jul,Aug,Sep,Oct,Nov",
    isHidden: true,
    popularity: 45,
    latitude: "14.4464073",
    longitude: "75.0085399",
  },

  // ===================== DAVANAGERE =====================
  {
    slug: "harihareshwara-temple-harihar",
    name: "Harihareshwara Temple, Harihar",
    state: "Karnataka",
    district: "Davanagere",
    category: "pilgrimage",
    placeType: "Hoysala Temple",
    shortDescription: "13th-century Hoysala temple on the Tungabhadra enshrining Harihara, the fused form of Vishnu and Shiva.",
    description: "The Harihareshwara temple at Harihar, built around 1223 CE by the Hoysalas, is dedicated to Harihara — a deity combining Vishnu and Shiva in one form. Standing on the banks of the Tungabhadra, it features classic Hoysala carvings and is the spiritual heart of the temple town.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Harihareshwara_temple_at_Harihar.JPG/1280px-Harihareshwara_temple_at_Harihar.JPG",
    openingTimings: "6:00 AM - 12:30 PM, 5:00 PM - 8:30 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 60,
    latitude: "14.512348",
    longitude: "75.8020267",
  },
  {
    slug: "kundavada-lake",
    name: "Kundavada Lake",
    state: "Karnataka",
    district: "Davanagere",
    category: "adventure",
    placeType: "Lake",
    shortDescription: "Scenic lake on the edge of Davanagere city, popular for walks, boating and evening relaxation.",
    description: "Kundavada Lake (Kundavada Kere) is a large tank on the outskirts of Davanagere, a favourite spot for morning walks, sunsets and birdwatching. With a temple on its bank and developed walkways, it is the city's main recreational waterside destination.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Kundawada_Kere%28Lake%29_Davanagere.jpg/1280px-Kundawada_Kere%28Lake%29_Davanagere.jpg",
    openingTimings: "6:00 AM - 6:30 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Aug,Sep,Oct,Nov,Dec,Jan",
    isHidden: true,
    popularity: 52,
    latitude: "14.4550295",
    longitude: "75.89260709999999",
  },
  {
    slug: "bathi-gudda",
    name: "Bathi Gudda (Anjaneya Hill)",
    state: "Karnataka",
    district: "Davanagere",
    category: "hill_station",
    placeType: "Hill & Viewpoint",
    shortDescription: "Rocky hill near Davanagere with an Anjaneya temple, windmills and sweeping plateau views.",
    description: "Bathi Gudda, also known for its Anjaneya (Hanuman) temple, is a granite hill near Davanagere offering wide views across the Deccan plateau. Lined with wind turbines and reached by steps or road, it is a popular sunrise, sunset and short-trek spot for locals.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:30 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Aug,Sep,Oct,Nov,Dec,Jan",
    isHidden: true,
    popularity: 50,
    latitude: "14.4170",
    longitude: "76.0170",
  },
  {
    slug: "santhebennur-pushkarni",
    name: "Santhebennur Pushkarni",
    state: "Karnataka",
    district: "Davanagere",
    category: "heritage",
    placeType: "Stepped Tank",
    shortDescription: "Ornate 16th-century stepped temple tank built by a Keladi chieftain at Santhebennur.",
    description: "The Santhebennur Pushkarni is a finely built stepped water tank from the late 16th century, attributed to a local Keladi-era chieftain. Its symmetrical stone steps, central pavilion and arched corner mantapas make it one of Karnataka's most elegant historic kalyanis.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 44,
    latitude: "14.0420",
    longitude: "76.0220",
  },
  {
    slug: "anaji-shanthi-sagara",
    name: "Shanthi Sagara (Sulekere)",
    state: "Karnataka",
    district: "Davanagere",
    category: "adventure",
    placeType: "Lake",
    shortDescription: "One of Asia's largest tanks, a vast ancient lake near Channagiri popular for birdlife and scenery.",
    description: "Shanthi Sagara, also called Sulekere, near Channagiri is among the largest tanks in Asia, built centuries ago for irrigation. The huge expanse of water amid farmland attracts migratory birds and offers expansive, tranquil views, with a temple on its shore.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/View_of_Shanthi_Sagar_%28Soole_Kere%29_%E0%B2%B8%E0%B3%82%E0%B2%B3%E0%B3%86_%E0%B2%95%E0%B3%86%E0%B2%B0%E0%B3%86_near_channagiri%2Cdavengere_karnataka.JPG/1280px-View_of_Shanthi_Sagar_%28Soole_Kere%29_%E0%B2%B8%E0%B3%82%E0%B2%B3%E0%B3%86_%E0%B2%95%E0%B3%86%E0%B2%B0%E0%B3%86_near_channagiri%2Cdavengere_karnataka.JPG",
    openingTimings: "Open 24 hours",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Aug,Sep,Oct,Nov,Dec,Jan",
    isHidden: true,
    popularity: 43,
    latitude: "14.1278877",
    longitude: "75.9056753",
  },
  {
    slug: "kondajji-betta",
    name: "Kondajji",
    state: "Karnataka",
    district: "Davanagere",
    category: "adventure",
    placeType: "Lake & Camp",
    shortDescription: "Forested lake and Scout-Guide camping spot near Davanagere, good for picnics and trekking.",
    description: "Kondajji, near Davanagere, is known for its lake set against low hills and a long-established Bharat Scouts and Guides training campsite. The greenery, water and surrounding trails make it a relaxed picnic and short-trek destination away from the city.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Aug,Sep,Oct,Nov,Dec,Jan",
    isHidden: true,
    popularity: 40,
    latitude: "14.3500",
    longitude: "75.8170",
  },

  // ===================== CHITRADURGA =====================
  {
    slug: "chitradurga-fort",
    name: "Chitradurga Fort (Kallina Kote)",
    state: "Karnataka",
    district: "Chitradurga",
    category: "heritage",
    placeType: "Hill Fort",
    shortDescription: "Vast 'stone fortress' of seven concentric walls across boulder hills, stronghold of the Chitradurga Nayakas.",
    description: "Chitradurga Fort, locally called Kallina Kote (stone fort), sprawls over rocky hills with seven concentric ring walls, numerous gateways, temples and ingenious water tanks. Associated with the brave Onake Obavva who defended a breach with a pestle, it is a remarkable example of military engineering.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/GALIMANTAPA.jpg/1280px-GALIMANTAPA.jpg",
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 25,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 84,
    latitude: "14.2160487",
    longitude: "76.3989134",
  },
  {
    slug: "chandravalli-caves",
    name: "Chandravalli Caves",
    state: "Karnataka",
    district: "Chitradurga",
    category: "adventure",
    placeType: "Caves & Archaeology",
    shortDescription: "Ancient cave complex and excavation site near Chitradurga set amid three hills and a scenic lake.",
    description: "Chandravalli is an archaeological valley near Chitradurga between Chitradurga, Kirabanakallu and Cholagatta hills. It is known for the Ankali Math caves used by ascetics and for excavations yielding coins and pottery from Satavahana and earlier periods, beside the Chandravalli lake.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Pre-_Historic_Site%2CChitradurga.JPG/1280px-Pre-_Historic_Site%2CChitradurga.JPG",
    openingTimings: "8:00 AM - 5:30 PM",
    entryFees: 10,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 55,
    latitude: "14.2053349",
    longitude: "76.3808179",
  },
  {
    slug: "vani-vilas-sagar-dam",
    name: "Vani Vilas Sagar Dam (Marikanive)",
    state: "Karnataka",
    district: "Chitradurga",
    category: "adventure",
    placeType: "Dam & Reservoir",
    shortDescription: "Historic stone dam on the Vedavathi river near Hiriyur, a scenic reservoir built under the Mysore Wodeyars.",
    description: "Vani Vilas Sagar, also called Marikanive, is one of the oldest dams in Karnataka, built across the Vedavathi (Hagari) river in the early 20th century during the Mysore Wodeyar era. Its handsome stone masonry, reservoir and surrounding hills make it a popular outing near Hiriyur.",
    imageUrl: null,
    openingTimings: "9:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Aug,Sep,Oct,Nov,Dec,Jan",
    isHidden: false,
    popularity: 58,
    latitude: "13.8882241",
    longitude: "76.489327",
  },
  {
    slug: "jogimatti",
    name: "Jogimatti",
    state: "Karnataka",
    district: "Chitradurga",
    category: "hill_station",
    placeType: "Hill & Forest",
    shortDescription: "Highest point near Chitradurga, a forested hill retreat with viewpoints and the Jogimatti reserve forest.",
    description: "Jogimatti is the highest point in the Chitradurga area, set within a reserve forest of grassland and scrub. With viewpoints, a small shrine to the saint Jogi, caves and cool air, it is a favourite getaway for trekking, sunsets and escaping the plains heat.",
    imageUrl: null,
    openingTimings: "8:00 AM - 5:30 PM",
    entryFees: 50,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Aug,Sep,Oct,Nov,Dec,Jan",
    isHidden: true,
    popularity: 52,
    latitude: "14.1670",
    longitude: "76.4170",
  },
  {
    slug: "adumalleshwara",
    name: "Adumalleshwara Nature Camp",
    state: "Karnataka",
    district: "Chitradurga",
    category: "wildlife",
    placeType: "Nature Camp & Mini Zoo",
    shortDescription: "Forest nature camp near Chitradurga with a deer park, mini-zoo and a rock-set Mallikarjuna temple.",
    description: "Adumalleshwara, just outside Chitradurga, combines a small wildlife park and deer enclosure with the cave-like Adumalleshwara (Mallikarjuna) temple set among boulders, where a perennial spring feeds a Nandi. The shaded camp is a pleasant nature and picnic spot.",
    imageUrl: null,
    openingTimings: "9:00 AM - 5:30 PM",
    entryFees: 20,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 47,
    latitude: "14.2330",
    longitude: "76.4080",
  },
  {
    slug: "ankali-math",
    name: "Ankali Mutt",
    state: "Karnataka",
    district: "Chitradurga",
    category: "pilgrimage",
    placeType: "Cave Monastery",
    shortDescription: "Ancient cave monastery near Chandravalli where ascetics meditated, with underground rock chambers.",
    description: "Ankali Mutt at Chandravalli is a historic monastery built into natural rock, used for centuries by wandering ascetics for meditation. Its dim underground chambers and passages, linked to samadhis of past seers, make it an atmospheric spiritual and heritage site near Chitradurga.",
    imageUrl: null,
    openingTimings: "8:00 AM - 5:30 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 42,
    latitude: "14.2054402",
    longitude: "76.381047",
  },
  {
    slug: "gayatri-reservoir",
    name: "Gayatri Reservoir",
    state: "Karnataka",
    district: "Chitradurga",
    category: "adventure",
    placeType: "Reservoir",
    shortDescription: "Calm reservoir near Holalkere surrounded by hills, a quiet spot for nature and birdwatching.",
    description: "Gayatri Reservoir, near Holalkere in Chitradurga district, is a tranquil dam-fed lake ringed by low hills and farmland. Away from crowds, it draws birdwatchers and picnickers seeking a peaceful waterside setting in the otherwise dry central plains.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Aug,Sep,Oct,Nov,Dec,Jan",
    isHidden: true,
    popularity: 38,
    latitude: "14.0420",
    longitude: "76.1830",
  },
];
