import type { NewDestination } from "../schema";

// Karnataka — Bengaluru region (Bengaluru Urban/Rural, Ramanagara, Tumakuru, Kolar, Chikkaballapura)
export const karnatakaBengaluruRegion: Omit<NewDestination, "id" | "createdAt">[] = [
  // ===================== Bengaluru Urban =====================
  {
    slug: "bangalore-palace",
    name: "Bangalore Palace",
    state: "Karnataka",
    district: "Bengaluru Urban",
    category: "heritage",
    placeType: "Palace",
    shortDescription: "Tudor-style royal palace of the Wadiyars with grand interiors, courtyards and lush grounds.",
    description: "Built in 1878 by the Wadiyar dynasty, Bangalore Palace is modelled on England's Windsor Castle with Tudor and Gothic architecture. The interiors feature ornate woodwork, paintings, antique furniture and a grand durbar hall. The sprawling grounds host major concerts and events. Carrying a camera or phone inside incurs a separate charge on top of the entry ticket.",
    imageUrl: null,
    openingTimings: "10:00 AM - 5:30 PM",
    entryFees: 230,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 88,
    latitude: "13.0035068",
    longitude: "77.5890953",
  },
  {
    slug: "lalbagh-botanical-garden",
    name: "Lalbagh Botanical Garden",
    state: "Karnataka",
    district: "Bengaluru Urban",
    category: "heritage",
    placeType: "Botanical Garden",
    shortDescription: "Historic 240-acre botanical garden begun by Hyder Ali, famed for its Glass House and flower shows.",
    description: "Lalbagh was commissioned by Hyder Ali in the 1760s and expanded by Tipu Sultan, hosting over 1,000 species of flora. Its iconic Glass House, inspired by London's Crystal Palace, holds biannual flower shows around Republic Day and Independence Day. A 3,000-million-year-old Peninsular Gneiss rock and a large lake add to its appeal. Entry is free during early morning (6-9 AM) and evening (6-7 PM) walking hours; senior citizens enter free at all times.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Glasshouse_and_fountain_at_lalbagh.jpg/1280px-Glasshouse_and_fountain_at_lalbagh.jpg",
    openingTimings: "5:00 AM - 7:00 PM",
    entryFees: 30,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Jan,Feb,Aug,Sep,Oct,Nov,Dec",
    isHidden: false,
    popularity: 87,
    latitude: "12.9494158",
    longitude: "77.58468049999999",
  },
  {
    slug: "cubbon-park",
    name: "Cubbon Park",
    state: "Karnataka",
    district: "Bengaluru Urban",
    category: "heritage",
    placeType: "Park",
    shortDescription: "Sprawling green lung in central Bengaluru with heritage buildings, statues and walking trails.",
    description: "Laid out in 1870, Cubbon Park spans about 300 acres in the city centre and is dotted with bamboo groves, flowering trees and ornamental fountains. It surrounds landmarks like the State Central Library, the High Court (Attara Kacheri) and several museums. It is a beloved spot for morning walkers, cyclists and weekend strollers.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Cubbon_Park_W.jpg/1280px-Cubbon_Park_W.jpg",
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 600,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 84,
    latitude: "12.9752487",
    longitude: "77.5928871",
  },
  {
    slug: "iskcon-bengaluru",
    name: "ISKCON Temple Bengaluru",
    state: "Karnataka",
    district: "Bengaluru Urban",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "One of the world's largest Krishna temples on Hare Krishna Hill with grand gopurams and a gold dome.",
    description: "The ISKCON Sri Radha Krishna Temple at Rajajinagar, opened in 1997, is among the largest Krishna-Balaram temples in the world. Built atop Hare Krishna Hill, it blends modern glass-and-steel design with traditional gopurams and a gilded shikhara. It draws huge crowds during Janmashtami and serves free prasadam. General darshan is free; an optional paid special-entry darshan is available to skip the queue.",
    imageUrl: null,
    openingTimings: "4:15 AM - 8:30 PM",
    entryFees: 0,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Aug,Sep,Oct,Nov,Dec,Jan",
    isHidden: false,
    popularity: 85,
    latitude: "13.0096643",
    longitude: "77.5511344",
  },
  {
    slug: "bull-temple-basavanagudi",
    name: "Bull Temple (Dodda Basavana Gudi)",
    state: "Karnataka",
    district: "Bengaluru Urban",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "16th-century Kempe Gowda temple housing a giant monolithic Nandi bull carved from granite.",
    description: "The Bull Temple in Basavanagudi, built by Kempe Gowda in the 16th century, enshrines a massive monolithic Nandi about 4.5 m tall and 6 m long. The Dravidian-style shrine is one of Bengaluru's oldest temples. The annual Kadalekai Parishe (groundnut fair) draws large crowds each November.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/86/Dodda_Ganeshana_Gudi_Hindu_temple%2C_Basavanagudi%2C_Karnataka%2C_India.jpg",
    openingTimings: "6:30 AM - 8:30 PM",
    entryFees: 0,
    budgetPerDay: 600,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 78,
    latitude: "12.9420315",
    longitude: "77.5681024",
  },
  {
    slug: "tipu-sultan-summer-palace-bengaluru",
    name: "Tipu Sultan's Summer Palace",
    state: "Karnataka",
    district: "Bengaluru Urban",
    category: "heritage",
    placeType: "Palace",
    shortDescription: "Elegant teak summer palace of Tipu Sultan with ornate arches, balconies and frescoes.",
    description: "Completed in 1791, this two-storey palace built largely of teak was Tipu Sultan's summer retreat, which he called the 'abode of happiness'. It features ornate pillars, cusped arches, painted ceilings and floral motifs in Indo-Islamic style. Adjacent stands the Kote Venkataramana Temple within the old fort area.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Tippu_Sultan%27s_Summer_palace.jpg/1280px-Tippu_Sultan%27s_Summer_palace.jpg",
    openingTimings: "8:30 AM - 5:30 PM",
    entryFees: 15,
    budgetPerDay: 600,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 70,
    latitude: "12.9593513",
    longitude: "77.5736415",
  },
  {
    slug: "bangalore-fort",
    name: "Bangalore Fort",
    state: "Karnataka",
    district: "Bengaluru Urban",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Remnant of Kempe Gowda's mud fort rebuilt in stone by Hyder Ali, with the Delhi Gate surviving.",
    description: "Originally a mud fort built by Kempe Gowda in 1537, Bangalore Fort was rebuilt in stone by Hyder Ali around 1761. Only fragments survive today, most notably the Delhi Gate and parts of the ramparts near the City Market. It was the site of fierce fighting during the Anglo-Mysore Wars.",
    imageUrl: null,
    openingTimings: "8:30 AM - 5:30 PM",
    entryFees: 5,
    budgetPerDay: 600,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 58,
    latitude: "12.9628018",
    longitude: "77.5758862",
  },
  {
    slug: "vidhana-soudha",
    name: "Vidhana Soudha",
    state: "Karnataka",
    district: "Bengaluru Urban",
    category: "heritage",
    placeType: "Landmark",
    shortDescription: "Imposing granite seat of Karnataka's legislature, a Neo-Dravidian architectural landmark.",
    description: "Completed in 1956, the Vidhana Soudha is the seat of the Karnataka State Legislature and one of Bengaluru's most photographed landmarks. Built in Neo-Dravidian style with granite, it features a grand entrance, domed pavilions and the motto 'Government Work is God's Work'. The building is dramatically floodlit on Sundays and holidays. Since 2025 the interior is open to the public via free guided tours on Sundays and the 2nd/4th Saturday of each month — book a slot on the Karnataka One app and carry an original Aadhaar card.",
    imageUrl: null,
    openingTimings: "Exterior viewing anytime; free guided interior tours Sun and 2nd/4th Sat, 8 AM-5 PM",
    entryFees: 0,
    budgetPerDay: 600,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 80,
    latitude: "12.9796033",
    longitude: "77.5908529",
  },
  {
    slug: "ulsoor-lake",
    name: "Ulsoor Lake",
    state: "Karnataka",
    district: "Bengaluru Urban",
    category: "heritage",
    placeType: "Lake",
    shortDescription: "Scenic central-city lake with islands and boating, dating to Kempe Gowda's era.",
    description: "Ulsoor Lake (Halasuru) is one of Bengaluru's oldest and largest lakes, spread over about 50 hectares with several small islands. Boating facilities and a lakeside promenade make it a popular evening spot. The nearby Someshwara Temple adds historic character to the area.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Native_Girls%27_School_and_Preaching-Room%2C_Alasoor%2C_Bangalore_%28p.184%2C_December_1865%2C_XXII%29.jpg/1280px-Native_Girls%27_School_and_Preaching-Room%2C_Alasoor%2C_Bangalore_%28p.184%2C_December_1865%2C_XXII%29.jpg",
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 600,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 65,
    latitude: "12.9832468",
    longitude: "77.6199608",
  },
  {
    slug: "bannerghatta-national-park",
    name: "Bannerghatta National Park",
    state: "Karnataka",
    district: "Bengaluru Urban",
    category: "wildlife",
    placeType: "National Park",
    shortDescription: "National park near Bengaluru with a zoo, butterfly park and a popular safari for tigers and lions.",
    description: "Established in 1971, Bannerghatta National Park combines a biological reserve, zoo, butterfly park and a rescue centre across its forested terrain. Its safari offers close views of tigers, lions, leopards, elephants and bears. India's first butterfly conservatory here showcases dozens of native species. The zoo/park entry ticket is separate from the safari, which costs extra and roughly doubles on weekends and government holidays.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Bengal_Tiger_In_Bannerghatta_Bengaluru.jpg/1280px-Bengal_Tiger_In_Bannerghatta_Bengaluru.jpg",
    openingTimings: "9:30 AM - 5:00 PM (closed Tue)",
    entryFees: 100,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 86,
    latitude: "12.8007084",
    longitude: "77.5763941",
  },
  {
    slug: "hesaraghatta-lake",
    name: "Hesaraghatta Lake & Grasslands",
    state: "Karnataka",
    district: "Bengaluru Urban",
    category: "wildlife",
    placeType: "Grassland",
    shortDescription: "Vast lake and grassland on Bengaluru's outskirts, a birding and nature haven near Nrityagram.",
    description: "Created in 1894 across the Arkavathi river, Hesaraghatta Lake and its surrounding grasslands form one of the last open grassland ecosystems near Bengaluru. The area is rich in birdlife, including larks, harriers and the rare lesser florican habitat. Nearby attractions include the Nrityagram dance village and the Government floriculture centre.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/59/BangaloreLake.jpg",
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 55,
    latitude: "13.1390",
    longitude: "77.4790",
  },
  {
    slug: "national-gallery-modern-art-bengaluru",
    name: "National Gallery of Modern Art, Bengaluru",
    state: "Karnataka",
    district: "Bengaluru Urban",
    category: "heritage",
    placeType: "Art Gallery",
    shortDescription: "Premier modern-art museum in the heritage Manikyavelu Mansion with works by Indian masters.",
    description: "Housed in the restored Manikyavelu Mansion on Palace Road, the NGMA Bengaluru displays modern and contemporary Indian art from the 1850s onward. Its collection includes works by Raja Ravi Varma, Amrita Sher-Gil and the Tagores. The leafy grounds and well-curated galleries make it a cultural highlight.",
    imageUrl: null,
    openingTimings: "10:00 AM - 5:00 PM (closed Mon)",
    entryFees: 20,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Jan,Feb,Oct,Nov,Dec",
    isHidden: true,
    popularity: 52,
    latitude: "12.9894116",
    longitude: "77.5880553",
  },
  {
    slug: "gavi-gangadhareshwara-temple",
    name: "Gavi Gangadhareshwara Cave Temple",
    state: "Karnataka",
    district: "Bengaluru Urban",
    category: "pilgrimage",
    placeType: "Cave Temple",
    shortDescription: "Ancient monolithic cave temple famed for sun rays striking the Shiva linga on Makara Sankranti.",
    description: "Carved into a rocky outcrop and attributed to Kempe Gowda in the 16th century, Gavipuram's Gavi Gangadhareshwara Temple is a rare monolithic cave shrine to Shiva. Each Makara Sankranti, the setting sun's rays pass through an arch and a stone window to illuminate the linga. Tall stone discs of the sun and moon stand in the courtyard.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Bengaluru_Fort.jpg/1280px-Bengaluru_Fort.jpg",
    openingTimings: "7:30 AM - 12:30 PM, 5:00 PM - 8:30 PM",
    entryFees: 0,
    budgetPerDay: 600,
    recommendedDays: 1,
    bestMonths: "Jan,Oct,Nov,Dec,Feb",
    isHidden: true,
    popularity: 60,
    latitude: "12.9480823",
    longitude: "77.56286639999999",
  },
  {
    slug: "hal-aerospace-museum",
    name: "HAL Aerospace Museum",
    state: "Karnataka",
    district: "Bengaluru Urban",
    category: "heritage",
    placeType: "Museum",
    shortDescription: "India's first aerospace museum showcasing aircraft, engines and a flight simulator.",
    description: "Run by Hindustan Aeronautics Limited, the HAL Aerospace Museum was India's first dedicated aerospace museum, opened in 2001. Exhibits include vintage and modern fighter jets, helicopters, aero engines and a mock air traffic control tower. Visitors can try a flight simulator and explore the history of Indian aviation.",
    imageUrl: null,
    openingTimings: "9:00 AM - 4:30 PM",
    entryFees: 50,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Jan,Feb,Oct,Nov,Dec",
    isHidden: true,
    popularity: 62,
    latitude: "12.954655",
    longitude: "77.68090579999999",
  },
  {
    slug: "jawaharlal-nehru-planetarium-bengaluru",
    name: "Jawaharlal Nehru Planetarium",
    state: "Karnataka",
    district: "Bengaluru Urban",
    category: "heritage",
    placeType: "Planetarium",
    shortDescription: "Popular science centre with immersive sky shows and astronomy exhibits near Sankey Tank.",
    description: "Opened in 1989 and run by the Bangalore Association for Science Education, the planetarium offers daily dome sky-theatre shows on astronomy. Its science park and interactive exhibits make it a favourite for families and students. It also hosts a public telescope-viewing programme.",
    imageUrl: null,
    openingTimings: "10:00 AM - 5:30 PM (closed Mon)",
    entryFees: 90,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Jan,Feb,Oct,Nov,Dec",
    isHidden: true,
    popularity: 58,
    latitude: "12.9848665",
    longitude: "77.5896341",
  },

  // ===================== Bengaluru Rural =====================
  {
    slug: "ghati-subramanya-temple",
    name: "Ghati Subramanya Temple",
    state: "Karnataka",
    district: "Bengaluru Rural",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Ancient hill temple to Lord Subramanya (Kartikeya) and Lakshmi Narasimha, a noted serpent-worship site.",
    description: "Set amid hills near Doddaballapura, the Ghati Subramanya Temple is dedicated to Lord Subramanya and Lakshmi Narasimha, whose idols face opposite directions in the same sanctum. It is a major pilgrimage centre for those seeking relief from sarpa dosha (serpent affliction). The annual car festival and the surrounding forested setting draw many devotees.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Ghati_Subramanya_Temple.JPG",
    openingTimings: "6:00 AM - 8:30 PM",
    entryFees: 0,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 58,
    latitude: "13.4085317",
    longitude: "77.5282792",
  },
  {
    slug: "shivagange",
    name: "Shivagange",
    state: "Karnataka",
    district: "Bengaluru Rural",
    category: "hill_station",
    placeType: "Hill",
    shortDescription: "Cone-shaped sacred hill near Dobbaspet with cave temples, a trek and the Gangadhareshwara shrine.",
    description: "Shivagange is a striking 1,368 m conical hill revered as a pilgrimage site and popular trekking destination near Tumakuru border. The trail passes the Gangadhareshwara cave temple, the Olakal Teertha spring and a giant Nandi statue, ending at the Shanthala Drop. The peak resembles a Shivalinga from one side and a Ganesha from another.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Shivagange_Basavanna.JPG/1280px-Shivagange_Basavanna.JPG",
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 72,
    latitude: "13.168056",
    longitude: "77.222222",
  },
  {
    slug: "nrityagram",
    name: "Nrityagram Dance Village",
    state: "Karnataka",
    district: "Bengaluru Rural",
    category: "heritage",
    placeType: "Cultural Village",
    shortDescription: "Renowned dance gurukul near Hesaraghatta founded by Protima Gauri, set in rustic eco-architecture.",
    description: "Founded in 1990 by dancer Protima Gauri, Nrityagram is India's first modern gurukul for classical dance, centred on Odissi. Designed by architect Gerard da Cunha, the village uses traditional mud-and-brick eco-architecture. Visitors can watch performances and learn about the residential training of dancers.",
    imageUrl: null,
    openingTimings: "10:00 AM - 5:30 PM (closed Mon)",
    entryFees: 20,
    budgetPerDay: 800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 54,
    latitude: "13.1616539",
    longitude: "77.459435",
  },
  {
    slug: "kanva-reservoir",
    name: "Kanva Reservoir",
    state: "Karnataka",
    district: "Bengaluru Rural",
    category: "adventure",
    placeType: "Reservoir",
    shortDescription: "Tranquil reservoir near Channapatna popular for coracle rides, picnics and weekend getaways.",
    description: "The Kanva Reservoir, built across the Kanva river near Channapatna, offers calm waters framed by low hills and greenery. It is a favourite for coracle rides, fishing and quiet picnics away from city crowds. The scenic setting makes it a popular short getaway from Bengaluru.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Jul,Aug,Sep,Oct,Nov,Dec",
    isHidden: true,
    popularity: 48,
    latitude: "12.6705",
    longitude: "77.1670",
  },

  // ===================== Ramanagara =====================
  {
    slug: "ramadevarabetta-ramanagara",
    name: "Ramadevarabetta Vulture Sanctuary",
    state: "Karnataka",
    district: "Ramanagara",
    category: "adventure",
    placeType: "Rocky Hill",
    shortDescription: "Iconic Sholay-filming rocky hill with a Rama temple and India's only vulture sanctuary.",
    description: "Ramadevarabetta is a dramatic granite hill in Ramanagara famed as a location for the film Sholay and for the hilltop Pattabhi Rama Temple. It is also home to the Ramadevarabetta Vulture Sanctuary, protecting the endangered long-billed and Egyptian vultures. The rugged crags make it a hotspot for trekking and rock climbing.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Ramadevarabetta.jpg/1280px-Ramadevarabetta.jpg",
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 66,
    latitude: "12.7531984",
    longitude: "77.30136739999999",
  },
  {
    slug: "janapada-loka",
    name: "Janapada Loka",
    state: "Karnataka",
    district: "Ramanagara",
    category: "heritage",
    placeType: "Folk Museum",
    shortDescription: "Sprawling folk-culture museum complex on the Mysuru highway preserving Karnataka's rural heritage.",
    description: "Janapada Loka, near Ramanagara on the Bengaluru-Mysuru highway, is a vast open-air museum dedicated to Karnataka's folk arts and rural life. It houses thousands of artefacts, masks, puppets, musical instruments and life-size dioramas across several galleries. Weekend folk performances and a research wing keep village traditions alive.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Yakshagana_artist%27s_mannequin_on_display_in_the_Janapada_Loka_%28Folk_art_museum%29.jpg/1280px-Yakshagana_artist%27s_mannequin_on_display_in_the_Janapada_Loka_%28Folk_art_museum%29.jpg",
    openingTimings: "9:00 AM - 5:30 PM (closed Tue)",
    entryFees: 50,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 64,
    latitude: "12.7005029",
    longitude: "77.2520292",
  },
  {
    slug: "channapatna-toy-town",
    name: "Channapatna (Toy Town)",
    state: "Karnataka",
    district: "Ramanagara",
    category: "heritage",
    placeType: "Craft Town",
    shortDescription: "GI-tagged 'Toy Town' famed for its centuries-old lacquered wooden toys and dolls.",
    description: "Channapatna, nicknamed Gombegala Ooru ('town of toys'), is celebrated for its GI-tagged lacquerware wooden toys, a craft said to have been encouraged by Tipu Sultan. Artisans turn ivory-wood (aale mara) on lathes and colour them with natural vegetable dyes. Visitors can tour workshops and buy toys directly from craft cooperatives.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Wooden_toys.JPG/1280px-Wooden_toys.JPG",
    openingTimings: "9:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 63,
    latitude: "12.6508012",
    longitude: "77.19560109999999",
  },
  {
    slug: "revana-siddeshwara-betta",
    name: "Revana Siddeshwara Betta",
    state: "Karnataka",
    district: "Ramanagara",
    category: "hill_station",
    placeType: "Hill",
    shortDescription: "Sacred hill near Magadi with a Shiva shrine, panoramic views and a moderate trek.",
    description: "Revana Siddeshwara Betta is a rocky hill near Magadi crowned by an ancient Shiva temple linked to the saint Revana Siddeshwara. The climb rewards trekkers with sweeping views of the surrounding plains and reservoirs. It draws both pilgrims and weekend hikers from Bengaluru.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 50,
    latitude: "12.8920",
    longitude: "77.2010",
  },
  {
    slug: "savandurga",
    name: "Savandurga",
    state: "Karnataka",
    district: "Ramanagara",
    category: "adventure",
    placeType: "Monolith",
    shortDescription: "One of Asia's largest monolith hills near Magadi, a thrilling trek with a Veerabhadra temple at base.",
    description: "Savandurga is among the largest single granite monoliths in Asia, rising about 1,226 m near Magadi. The hill has two peaks, Karigudda (black hill) and Biligudda (white hill), with a popular but steep trek to the summit. At its base stand the Savandi Veerabhadreshwara and Narasimha temples beside the Arkavathi river.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Savandurga_Hill_02.jpg/1280px-Savandurga_Hill_02.jpg",
    openingTimings: "6:00 AM - 5:00 PM",
    entryFees: 0,
    budgetPerDay: 800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 70,
    latitude: "12.9205893",
    longitude: "77.2944334",
  },
  {
    slug: "manchanabele-dam",
    name: "Manchanabele Dam",
    state: "Karnataka",
    district: "Ramanagara",
    category: "adventure",
    placeType: "Dam",
    shortDescription: "Scenic dam on the Arkavathi near Magadi, popular for kayaking, water sports and weekend camping.",
    description: "Manchanabele Dam, built across the Arkavathi river near Magadi, sits in a rugged landscape ringed by hills including Savandurga. Its calm backwaters are a hub for kayaking, coracle rides and adventure camping. The remote setting makes it a favourite escape for adventure seekers from Bengaluru.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 800,
    recommendedDays: 1,
    bestMonths: "Jul,Aug,Sep,Oct,Nov,Dec",
    isHidden: true,
    popularity: 52,
    latitude: "12.8748817",
    longitude: "77.336068",
  },
  {
    slug: "mekedatu-sangama",
    name: "Mekedatu & Sangama",
    state: "Karnataka",
    district: "Ramanagara",
    category: "adventure",
    placeType: "River Gorge",
    shortDescription: "Deep gorge where the Cauvery narrows dramatically, near the Sangama confluence with the Arkavathi.",
    description: "At Mekedatu ('goat's leap'), the Cauvery river squeezes through a narrow, deep rocky gorge so tight that a goat could supposedly leap across. Nearby Sangama marks the confluence of the Cauvery and Arkavathi rivers, reached by coracle and a short jeep ride. The dramatic rocks and rushing water make it a popular day trip from Bengaluru.",
    imageUrl: null,
    openingTimings: "8:00 AM - 5:00 PM",
    entryFees: 0,
    budgetPerDay: 800,
    recommendedDays: 1,
    bestMonths: "Aug,Sep,Oct,Nov,Dec,Jan",
    isHidden: false,
    popularity: 68,
    latitude: "12.3170",
    longitude: "77.4470",
  },
  {
    slug: "kabbaladurga",
    name: "Kabbaladurga",
    state: "Karnataka",
    district: "Ramanagara",
    category: "adventure",
    placeType: "Hill Fort",
    shortDescription: "Steep fortified hill near Kanakapura known for a challenging night trek and ruined fortifications.",
    description: "Kabbaladurga is a rocky hill near Kanakapura topped with the ruins of an old fort and a small Shiva temple. The steep, boulder-strewn trail is favoured for adventurous night treks and stargazing. From the summit, trekkers enjoy expansive views over the Cauvery basin.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 47,
    latitude: "12.5430",
    longitude: "77.3960",
  },
  // NOTE: "chunchi-falls" removed — officially closed to visitors (flagged in
  // Book1.xlsx cleanup). Do not re-add.
  {
    slug: "big-banyan-tree",
    name: "Big Banyan Tree (Dodda Aalada Mara)",
    state: "Karnataka",
    district: "Ramanagara",
    category: "heritage",
    placeType: "Natural Landmark",
    shortDescription: "Sprawling 400-year-old banyan tree near Bengaluru spread across nearly three acres.",
    description: "The Dodda Aalada Mara, near Ramohalli on the Bengaluru-Mysuru side, is a single banyan tree estimated to be around 400 years old. Its aerial roots have grown into a forest-like canopy covering close to three acres. A small Muneshwara shrine sits at its centre, and the spot is a relaxed weekend picnic destination.",
    imageUrl: null,
    openingTimings: "8:00 AM - 5:30 PM",
    entryFees: 0,
    budgetPerDay: 600,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 62,
    latitude: "12.909488",
    longitude: "77.39567439999999",
  },

  // ===================== Tumakuru (Tumkur) =====================
  {
    slug: "devarayanadurga",
    name: "Devarayanadurga",
    state: "Karnataka",
    district: "Tumakuru",
    category: "hill_station",
    placeType: "Hill",
    shortDescription: "Forested hill near Tumakuru with the Yoga Narasimha and Bhoga Narasimha temples and viewpoints.",
    description: "Devarayanadurga is a rocky, forested hill rising to about 1,194 m near Tumakuru, dotted with ancient temples. The Bhoga Narasimha temple sits at the base and the Yoga Narasimha temple crowns the summit, both Vaishnavite shrines. The Namada Chilume spring nearby and cool hilltop views make it a popular outing.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Yoga_Narasimha_Temple_Devarayanadurga.JPG/1280px-Yoga_Narasimha_Temple_Devarayanadurga.JPG",
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 800,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 68,
    latitude: "13.3741575",
    longitude: "77.2127134",
  },
  {
    slug: "namada-chilume",
    name: "Namada Chilume",
    state: "Karnataka",
    district: "Tumakuru",
    category: "wildlife",
    placeType: "Spring & Deer Park",
    shortDescription: "Perennial spring and deer park near Devarayanadurga linked to a Ramayana legend.",
    description: "Namada Chilume is a perennial natural spring set within a deer park near Devarayanadurga. Legend holds that Lord Rama struck the rock here to draw water for his tilak (nama), giving the spring its name. The shaded forest, spotted deer and tranquil pool make it a pleasant nature stop.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Namada_Chilume.jpg/1280px-Namada_Chilume.jpg",
    openingTimings: "8:30 AM - 5:30 PM",
    entryFees: 10,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 50,
    latitude: "13.3654657",
    longitude: "77.1922062",
  },
  {
    slug: "siddara-betta",
    name: "Siddara Betta",
    state: "Karnataka",
    district: "Tumakuru",
    category: "adventure",
    placeType: "Hill & Caves",
    shortDescription: "'Hill of Siddhas' near Koratagere with caves, a Shiva shrine and a rugged trek among boulders.",
    description: "Siddara Betta is a boulder-strewn hill near Koratagere, long associated with siddhas (ascetic sages) who meditated in its caves. The trek winds through narrow cave passages and rock formations to a hilltop Shiva temple. Medicinal herbs growing on the slopes add to its mystique among pilgrims and trekkers.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 800,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 52,
    latitude: "13.5260",
    longitude: "77.1620",
  },
  {
    slug: "madhugiri-fort",
    name: "Madhugiri Fort",
    state: "Karnataka",
    district: "Tumakuru",
    category: "adventure",
    placeType: "Hill Fort",
    shortDescription: "Fort on Asia's second-largest monolith, offering a steep, exhilarating trek and panoramic views.",
    description: "Madhugiri Fort climbs one of the largest monolithic hills in Asia, rising to about 1,200 m. Built in the 17th century and later strengthened under Hyder Ali, its layered gateways and fortifications snake up the steep granite face. The challenging trek rewards visitors with sweeping views and the ruins of granaries and watchtowers.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/63/Madhugiri_Fort_1.JPG",
    openingTimings: "6:00 AM - 5:30 PM",
    entryFees: 0,
    budgetPerDay: 800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 64,
    latitude: "13.6515542",
    longitude: "77.2000587",
  },
  {
    slug: "goravanahalli-mahalakshmi-temple",
    name: "Goravanahalli Mahalakshmi Temple",
    state: "Karnataka",
    district: "Tumakuru",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Revered Mahalakshmi temple near Koratagere drawing devotees seeking wealth and prosperity.",
    description: "The Goravanahalli Sri Mahalakshmi Temple near Koratagere is a popular Devi shrine believed to fulfil prayers for prosperity. The self-manifested idol of Mahalakshmi is the focus of intense devotion, especially on Fridays and during the Sravana month. Simple in structure, the temple attracts large crowds from across the region.",
    imageUrl: null,
    openingTimings: "7:00 AM - 1:00 PM, 4:00 PM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Aug,Sep,Oct,Nov,Dec,Jan",
    isHidden: true,
    popularity: 54,
    latitude: "13.5510",
    longitude: "77.2330",
  },
  {
    slug: "sira-fort-town",
    name: "Sira (Fort & Jumma Masjid)",
    state: "Karnataka",
    district: "Tumakuru",
    category: "heritage",
    placeType: "Historic Town",
    shortDescription: "Former Mughal provincial capital with fort ruins, the Jumma Masjid and Malik Rihan's tomb.",
    description: "Sira was once a prominent Mughal subah (province) headquarters and later a centre under the Marathas and Hyder Ali. Surviving monuments include the old fort ruins, the elegant Jumma Masjid and the dargah and tomb of Malik Rihan. The town's Khan Bagh garden is said to have inspired Lalbagh in Bengaluru.",
    imageUrl: null,
    openingTimings: "9:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 44,
    latitude: "13.7434024",
    longitude: "76.9135271",
  },
  {
    slug: "kaidala-chennakeshava-temple",
    name: "Kaidala Chennakeshava Temple",
    state: "Karnataka",
    district: "Tumakuru",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Hoysala-era temple near Tumakuru linked to the legendary sculptor Jakanachari.",
    description: "The Chennakeshava Temple at Kaidala, near Tumakuru, is associated with the famed Hoysala sculptor Amarashilpi Jakanachari, said to have hailed from this village. It enshrines finely carved idols of Chennakeshava and Gangadhareshwara. The site holds an important place in the lore of Karnataka's temple sculptors.",
    imageUrl: null,
    openingTimings: "8:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 600,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 42,
    latitude: "13.3000924",
    longitude: "77.0815871",
  },
  {
    slug: "jayamangali-blackbuck-reserve",
    name: "Jayamangali Blackbuck Reserve (Maidenahalli)",
    state: "Karnataka",
    district: "Tumakuru",
    category: "wildlife",
    placeType: "Wildlife Reserve",
    shortDescription: "Grassland reserve at Maidenahalli protecting a large population of Indian blackbuck.",
    description: "The Jayamangali Blackbuck Conservation Reserve at Maidenahalli, in the Madhugiri taluk near the Andhra border, protects open grasslands home to hundreds of Indian blackbuck. The reserve also shelters foxes, wolves and a variety of grassland birds. Its remote, flat terrain offers excellent wildlife viewing away from crowds.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Black_Bucks.jpg/1280px-Black_Bucks.jpg",
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 50,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 48,
    latitude: "13.7400521",
    longitude: "77.3232365",
  },
  {
    slug: "pavagada-fort",
    name: "Pavagada Fort",
    state: "Karnataka",
    district: "Tumakuru",
    category: "heritage",
    placeType: "Hill Fort",
    shortDescription: "Hilltop fort in Pavagada town near the solar park, with old temples and sweeping plains views.",
    description: "Pavagada Fort sits atop a rocky hill in the town of Pavagada, near the Karnataka-Andhra border. The fort and its hill temples date back several centuries and were contested by various regional powers. The area is now also known for the vast Pavagada Solar Park, one of the world's largest.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 40,
    latitude: "14.1015991",
    longitude: "77.2793059",
  },

  // ===================== Kolar =====================
  {
    slug: "kolar-kotilingeshwara",
    name: "Kotilingeshwara Temple",
    state: "Karnataka",
    district: "Kolar",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Vast temple complex near Kolar with lakhs of Shiva lingas and one of the world's tallest lingas.",
    description: "Kotilingeshwara at Kammasandra, near Kolar, is renowned for its grounds covered with several lakh Shiva lingas installed by devotees. It features a towering Brahma linga about 33 m high alongside a giant Nandi. The temple aims to reach a crore (ten million) lingas over time, drawing pilgrims year-round.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/42/Kotilingeshwara.JPG",
    openingTimings: "6:00 AM - 9:00 PM",
    entryFees: 0,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 70,
    latitude: "12.995146",
    longitude: "78.2959453",
  },
  {
    slug: "antaragange",
    name: "Antara Gange",
    state: "Karnataka",
    district: "Kolar",
    category: "adventure",
    placeType: "Hill & Caves",
    shortDescription: "Volcanic-rock hill near Kolar famed for boulder caves, cave exploration and night treks.",
    description: "Antara Gange ('Ganga from within') is a hill on the Shathashrunga range near Kolar, dotted with caves formed by huge volcanic boulders. A perennial spring feeds a pond at the Kashi Vishweshwara temple, where water flows from a stone bull's mouth. The hill is a top destination for caving, rock climbing and adventure trekking.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Antharagange.JPG/1280px-Antharagange.JPG",
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 68,
    latitude: "13.142425",
    longitude: "78.10056100000001",
  },
  {
    slug: "avani-kolar",
    name: "Avani",
    state: "Karnataka",
    district: "Kolar",
    category: "pilgrimage",
    placeType: "Temple Complex",
    shortDescription: "Ancient 'Gaya of the South' near Mulbagal, linked to Sita and home to Nolamba-era temples.",
    description: "Avani, near Mulbagal, is a revered pilgrimage town often called the Gaya of the South. Legend ties it to Sita's exile and the birth of Lava and Kusha, with the Sitaparvatha hill above. Its cluster of Nolamba and Chola-era stone temples, including the Ramalingeshwara group, showcases fine early Dravidian carving.",
    imageUrl: null,
    openingTimings: "7:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 50,
    latitude: "13.1230",
    longitude: "78.4490",
  },
  {
    slug: "kolaramma-temple",
    name: "Kolaramma Temple",
    state: "Karnataka",
    district: "Kolar",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Chola-era temple in Kolar town dedicated to goddess Kolaramma, the town's namesake deity.",
    description: "The Kolaramma Temple in Kolar is an 11th-century Chola-period shrine dedicated to Shakti as Kolaramma, after whom the town is named. Built in a distinctive L-shaped (Vimana) plan, it carries fine carvings and inscriptions. It remains an active and important temple for the local community.",
    imageUrl: null,
    openingTimings: "6:00 AM - 12:30 PM, 5:00 PM - 8:30 PM",
    entryFees: 0,
    budgetPerDay: 600,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 48,
    latitude: "13.1370",
    longitude: "78.1330",
  },
  {
    slug: "someshwara-temple-kolar",
    name: "Someshwara Temple, Kolar",
    state: "Karnataka",
    district: "Kolar",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Vijayanagara-era Shiva temple in Kolar town noted for its richly carved pillars and gopuram.",
    description: "The Someshwara Temple in Kolar is a 14th-century Vijayanagara-era Shiva temple celebrated for its ornate stone pillars and yali carvings. Its towering gopuram and intricately sculpted mandapas reflect classic Dravidian craftsmanship. It stands among the finest historic temples in the Kolar region.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/20/View_from_the_rear_of_Someshwara_temple_at_Kolar.jpg",
    openingTimings: "6:30 AM - 12:00 PM, 5:00 PM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 600,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 45,
    latitude: "13.1374815",
    longitude: "78.13823",
  },
  {
    slug: "kgf-kolar-gold-fields",
    name: "Kolar Gold Fields (KGF)",
    state: "Karnataka",
    district: "Kolar",
    category: "heritage",
    placeType: "Mining Heritage",
    shortDescription: "Historic gold-mining township once among the world's deepest mines, now a heritage curiosity.",
    description: "Kolar Gold Fields was one of the world's deepest gold mines, operational from the 1880s until 2001 and central to India's early gold output. The colonial-era township, with its bungalows, churches and the eerie disused mine shafts, retains a distinctive heritage character. Surrounding hillocks of mine tailings give the area its unique landscape.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Kolar_Gold_Fields_-_1913.jpg",
    openingTimings: "Township open; mines restricted",
    entryFees: 0,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 56,
    latitude: "12.9585136",
    longitude: "78.2710336",
  },
  {
    slug: "kurudumale-ganesha-temple",
    name: "Kurudumale Ganesha Temple",
    state: "Karnataka",
    district: "Kolar",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Temple near Mulbagal with a towering 13.5-ft monolithic Ganesha and a Vijayanagara Someshwara shrine.",
    description: "Kurudumale, near Mulbagal, is famous for one of the largest monolithic Ganesha idols in the region, standing about 13.5 feet tall. The adjacent Someshwara Temple was built during the Vijayanagara period with finely carved pillars attributed to the sculptor Jakanachari. The site is a revered pilgrimage stop in eastern Karnataka.",
    imageUrl: null,
    openingTimings: "7:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Aug,Sep,Oct,Nov,Dec,Jan",
    isHidden: true,
    popularity: 52,
    latitude: "13.2050",
    longitude: "78.4170",
  },
  {
    slug: "anthargange-mulbagal-anjaneya",
    name: "Mulbagal Anjaneya Temple",
    state: "Karnataka",
    district: "Kolar",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Historic Anjaneya (Hanuman) temple in Mulbagal town, an old pilgrimage centre on the trade route.",
    description: "Mulbagal, an ancient town on the historic Bengaluru-Chennai route, is home to a revered Anjaneya temple and the math of the saint Sripadaraja. The temple and town carry deep Madhwa Vaishnava significance. Mulbagal also serves as a base for visiting Avani and Kurudumale nearby.",
    imageUrl: null,
    openingTimings: "6:30 AM - 12:30 PM, 5:00 PM - 8:30 PM",
    entryFees: 0,
    budgetPerDay: 600,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 40,
    latitude: "13.1661629",
    longitude: "78.3931769",
  },

  // ===================== Chikkaballapura =====================
  {
    slug: "nandi-hills",
    name: "Nandi Hills",
    state: "Karnataka",
    district: "Chikkaballapura",
    category: "hill_station",
    placeType: "Hill Station",
    shortDescription: "Popular sunrise hill fortress near Bengaluru with Tipu's summer retreat and panoramic views.",
    description: "Nandi Hills is an ancient hill fortress rising to about 1,478 m, famous for its early-morning sunrise above the clouds. Highlights include Tipu Sultan's summer residence, Tipu's Drop, the Yoga Nandeeshwara temple and the Amrita Sarovar. It is the source of the Arkavathi and Palar rivers and a favourite weekend escape from Bengaluru. Gate entry is free; a parking charge applies (₹15 for two-wheelers, ₹60 for cars), and a pass system controls the crowds for sunrise visits on weekends.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 92,
    latitude: "13.3702",
    longitude: "77.6835",
  },
  {
    slug: "skandagiri",
    name: "Skandagiri (Kalavara Durga)",
    state: "Karnataka",
    district: "Chikkaballapura",
    category: "adventure",
    placeType: "Trekking Hill",
    shortDescription: "Famous night-trek and sunrise hill near Nandi Hills with fort ruins and views above the clouds.",
    description: "Skandagiri, also called Kalavara Durga, is a popular trekking peak rising to about 1,350 m near Chikkaballapura. The trail to its summit, dotted with the ruins of a Tipu-era fort, is famed for night treks rewarded by a spectacular sunrise above a sea of clouds. Its proximity to Bengaluru makes it a weekend favourite for adventurers.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Skandagiri.jpg/1280px-Skandagiri.jpg",
    openingTimings: "6:00 AM - 5:00 PM",
    entryFees: 250,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 74,
    latitude: "13.426209",
    longitude: "77.6850866",
  },
  {
    slug: "bhoga-nandeeshwara-temple",
    name: "Bhoga Nandeeshwara Temple",
    state: "Karnataka",
    district: "Chikkaballapura",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "One of Karnataka's oldest temples at the foot of Nandi Hills, spanning Nolamba to Vijayanagara eras.",
    description: "Bhoga Nandeeshwara Temple at Nandi village, at the base of Nandi Hills, is among the oldest temples in Karnataka, with parts dating to the 9th-century Nolamba period and later additions by the Chola, Hoysala and Vijayanagara dynasties. Twin shrines to Arunachaleswara and Bhoganandishwara represent the stages of Shiva's life. Its richly carved pillars, the Tulabhara mandapa and a stepped temple tank are key highlights.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Bhoga_Nandeeshwara_Temple_-_North_Side_View.jpg/1280px-Bhoga_Nandeeshwara_Temple_-_North_Side_View.jpg",
    openingTimings: "7:30 AM - 7:30 PM",
    entryFees: 0,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 66,
    latitude: "13.3867627",
    longitude: "77.6980554",
  },
  {
    slug: "gudibande-fort",
    name: "Gudibande Fort",
    state: "Karnataka",
    district: "Chikkaballapura",
    category: "heritage",
    placeType: "Hill Fort",
    shortDescription: "17th-century hill fort built by Byre Gowda with stepped ponds and a short scenic trek.",
    description: "Gudibande Fort is a multi-tiered hill fort built in the 17th century by the chieftain Byre Gowda near Gudibande town. The fort features a series of rock-cut ponds (kalyanis) along its slopes that supplied water within the citadel. A short, rewarding trek leads to the top, offering wide views of the surrounding plains and lakes.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 54,
    latitude: "13.6762111",
    longitude: "77.70080399999999",
  },
  {
    slug: "vidurashwatha",
    name: "Vidurashwatha",
    state: "Karnataka",
    district: "Chikkaballapura",
    category: "pilgrimage",
    placeType: "Memorial & Temple",
    shortDescription: "'Jallianwala Bagh of the South' near Gauribidanur, a freedom-struggle memorial and Ashwatha shrine.",
    description: "Vidurashwatha, near Gauribidanur, is remembered as the 'Jallianwala Bagh of the South' for the 1938 firing on freedom-struggle protesters that killed many satyagrahis. A memorial and Veefor Soudha stand at the site honouring the martyrs. The ancient Ashwatha (peepal) tree and Ashwatha Narayana temple lend it religious significance.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 48,
    latitude: "13.6160",
    longitude: "77.5520",
  },
  {
    slug: "kaiwara-amaranarayana-temple",
    name: "Kaiwara (Amaranarayana Temple & Yogi Nareyana Ashram)",
    state: "Karnataka",
    district: "Chikkaballapura",
    category: "pilgrimage",
    placeType: "Temple & Ashram",
    shortDescription: "Pilgrimage village linked to the Mahabharata and saint Kaivara Tatayya, with hill caves nearby.",
    description: "Kaiwara, near Chintamani, is a revered village associated with the Pandavas' exile and the 19th-century mystic-poet Kaivara Tatayya (Yogi Nareyana). Its Amaranarayana and Bhimalingeshwara temples date to the Vijayanagara period. The nearby Kailasagiri hill holds caves said to have been used by the Pandavas and the saint.",
    imageUrl: null,
    openingTimings: "6:30 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 46,
    latitude: "13.2570",
    longitude: "78.2330",
  },
  {
    slug: "kaivara-kailasagiri",
    name: "Kailasagiri Hill, Kaiwara",
    state: "Karnataka",
    district: "Chikkaballapura",
    category: "adventure",
    placeType: "Hill & Caves",
    shortDescription: "Forested hill near Kaiwara with Pandava-linked caves and a moderate trek to a hill shrine.",
    description: "Kailasagiri, the hill above Kaiwara village, is wrapped in legends of the Pandavas' stay during their exile. A trail past rock caves and a perennial spring leads up to a Shiva shrine on the hill. The green, boulder-strewn slopes make it a quiet trekking and pilgrimage spot near Chintamani.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 42,
    latitude: "13.2620",
    longitude: "78.2410",
  },
  // NOTE: "muddenahalli" removed — flagged as closed in Book1.xlsx cleanup.
  // Do not re-add.
  {
    slug: "vivekananda-falls-nandi",
    name: "Vivekananda Falls, Nandi Hills",
    state: "Karnataka",
    district: "Chikkaballapura",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription: "Seasonal waterfall on the lower slopes of Nandi Hills, a scenic monsoon stop near Chikkaballapura.",
    description: "Vivekananda Falls lies on the lower reaches of the Nandi Hills near Chikkaballapura, flowing best during and after the monsoon. The cascade and its rocky pools are a pleasant nature stop on the way up to Nandi. It is named in honour of Swami Vivekananda, who is said to have visited the area.",
    imageUrl: null,
    openingTimings: "8:00 AM - 5:30 PM",
    entryFees: 0,
    budgetPerDay: 700,
    recommendedDays: 1,
    bestMonths: "Jul,Aug,Sep,Oct,Nov",
    isHidden: true,
    popularity: 44,
    latitude: "13.3580",
    longitude: "77.6790",
  },
  {
    slug: "rangasthala-ranganatha-temple",
    name: "Rangasthala Ranganathaswamy Temple",
    state: "Karnataka",
    district: "Chikkaballapura",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Historic Ranganathaswamy temple near Chikkaballapura, a notable Vaishnava pilgrimage site.",
    description: "The Ranganathaswamy Temple at Rangasthala, near Chikkaballapura, is an old Vaishnava shrine dedicated to Lord Ranganatha. It draws steady streams of pilgrims, especially during Vaikunta Ekadashi. The temple is a respected religious landmark in the district.",
    imageUrl: null,
    openingTimings: "7:00 AM - 12:30 PM, 5:00 PM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 600,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 40,
    latitude: "13.4300",
    longitude: "77.7270",
  },
];
