import type { NewDestination } from "../schema";

// Karnataka — Mysuru region (Mysuru, Mandya, Chamarajanagara, Hassan, Kodagu)
export const karnatakaMysuruRegion: Omit<NewDestination, "id" | "createdAt">[] = [
  // ===================== MYSURU (MYSORE) =====================
  {
    slug: "mysore-palace",
    name: "Mysore Palace",
    state: "Karnataka",
    district: "Mysuru",
    category: "heritage",
    placeType: "Palace",
    shortDescription:
      "The opulent Indo-Saracenic seat of the Wadiyar dynasty, dazzling when lit with ~97,000 bulbs.",
    description: "Mysore Palace (Amba Vilas) is among India's most visited monuments, seat of the Wadiyar dynasty; the present Indo-Saracenic structure was rebuilt after an 1897 fire destroyed the earlier wooden palace. Its ornate Durbar Hall, Kalyana Mantapa and jewelled Golden Howdah are highlights. The palace is illuminated with roughly 97,000 bulbs on Sunday evenings, public holidays and nightly through the ten-day Dasara festival, when it also hosts the royal procession. A separate evening sound-and-light show ticket covers the palace's 400-year history.",
    imageUrl: null,
    openingTimings: "10:00 AM - 5:30 PM",
    entryFees: 100,
    budgetPerDay: 1500,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 97,
    latitude: "12.3052",
    longitude: "76.6552",
  },
  {
    slug: "chamundi-hills",
    name: "Chamundi Hills",
    state: "Karnataka",
    district: "Mysuru",
    category: "hill_station",
    placeType: "Hill & Temple",
    shortDescription:
      "Sacred hill overlooking Mysuru, crowned by the Chamundeshwari Temple and a giant Nandi monolith.",
    description: "Rising about 1,000 m above Mysuru, Chamundi Hills is topped by the Chamundeshwari Temple dedicated to the goddess Durga, slayer of the demon Mahishasura. A massive monolithic Nandi bull and panoramic city views are highlights of the climb or drive up. General darshan is free; the temple closes midday (2-3:30 PM) for cleaning, and paid special/VIP darshan tickets are available for quicker access.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/J.C.Nagar_Welcome_Board_to_Chamundi_Hills.jpg/1280px-J.C.Nagar_Welcome_Board_to_Chamundi_Hills.jpg",
    openingTimings: "7:30 AM - 9:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 90,
    latitude: "12.2731672",
    longitude: "76.6707435",
  },
  {
    slug: "brindavan-gardens",
    name: "Brindavan Gardens (KRS)",
    state: "Karnataka",
    district: "Mysuru",
    category: "heritage",
    placeType: "Garden",
    shortDescription:
      "Terraced ornamental gardens below KRS Dam, famous for the evening musical fountain show.",
    description: "Laid out below the Krishnaraja Sagar (KRS) Dam across the Cauvery, Brindavan Gardens is a symmetrical terraced garden with fountains, lawns and flower beds. The illuminated musical fountain show each evening is its biggest draw, near Mysuru. Entry is inexpensive (around ₹15 for adults); pedal and motor boat rides and vehicle parking are charged separately.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Brindavan_Gardens.JPG/1280px-Brindavan_Gardens.JPG",
    openingTimings: "6:00 AM - 8:00 PM",
    entryFees: 15,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Jul,Aug,Sep,Oct,Nov,Dec,Jan",
    isHidden: false,
    popularity: 88,
    latitude: "12.4232732",
    longitude: "76.5745085",
  },
  {
    slug: "st-philomenas-church",
    name: "St Philomena's Church",
    state: "Karnataka",
    district: "Mysuru",
    category: "pilgrimage",
    placeType: "Church",
    shortDescription:
      "One of India's tallest churches, a Neo-Gothic cathedral with soaring twin spires in Mysuru.",
    description: "St Philomena's Cathedral is a Neo-Gothic church inspired by Cologne Cathedral, with twin spires rising about 53 m. A relic of St Philomena rests in the catacomb beneath the altar. It is one of the largest churches in India. Entry is free; visit in the evening to see the cathedral illuminated after dark.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/India_-_St._Philomena%27s_Church_02.jpg/1280px-India_-_St._Philomena%27s_Church_02.jpg",
    openingTimings: "6:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 80,
    latitude: "12.3210417",
    longitude: "76.65826349999999",
  },
  {
    slug: "mysore-zoo",
    name: "Mysore Zoo",
    state: "Karnataka",
    district: "Mysuru",
    category: "wildlife",
    placeType: "Zoo",
    shortDescription:
      "Sri Chamarajendra Zoological Gardens, one of the oldest and best-maintained zoos in India.",
    description: "Established in 1892, Mysore Zoo (Sri Chamarajendra Zoological Gardens) is among the oldest zoos in India and is renowned for its naturalistic enclosures and breeding programmes. It houses a wide range of mammals, birds and reptiles from across the world. The zoo is closed on Tuesdays; a combo ticket with nearby Karanji Lake is also available.",
    imageUrl: null,
    openingTimings: "8:30 AM - 5:30 PM (closed Tue)",
    entryFees: 120,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 84,
    latitude: "12.3024092",
    longitude: "76.6638194",
  },
  {
    slug: "karanji-lake",
    name: "Karanji Lake",
    state: "Karnataka",
    district: "Mysuru",
    category: "wildlife",
    placeType: "Lake & Aviary",
    shortDescription:
      "Lake at the foot of Chamundi Hills with a butterfly park and one of India's largest walk-through aviaries.",
    description:
      "Karanji Lake is a nature park beside Mysore Zoo featuring a large walk-through aviary, a butterfly park and a boating area. The wetland attracts many resident and migratory birds, making it a peaceful birdwatching spot.",
    imageUrl: null,
    openingTimings: "8:30 AM - 5:30 PM (closed Mon)",
    entryFees: 20,
    budgetPerDay: 800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 62,
    latitude: "12.302778",
    longitude: "76.673611",
  },
  {
    slug: "jaganmohan-palace",
    name: "Jaganmohan Palace",
    state: "Karnataka",
    district: "Mysuru",
    category: "heritage",
    placeType: "Palace & Art Gallery",
    shortDescription:
      "Wadiyar-era palace housing the Sri Jayachamarajendra Art Gallery and Raja Ravi Varma paintings.",
    description:
      "Built in 1861, Jaganmohan Palace served as a royal residence and venue for important events before the main palace was completed. It now houses the Sri Jayachamarajendra Art Gallery with a celebrated collection of Raja Ravi Varma paintings and antiques.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Mysore_Palace_Morning.jpg/1280px-Mysore_Palace_Morning.jpg",
    openingTimings: "8:30 AM - 5:00 PM",
    entryFees: 60,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 58,
    latitude: "12.3068216",
    longitude: "76.6497928",
  },
  {
    slug: "mysore-rail-museum",
    name: "Mysore Rail Museum",
    state: "Karnataka",
    district: "Mysuru",
    category: "heritage",
    placeType: "Museum",
    shortDescription:
      "Open-air railway museum displaying vintage locomotives and the Maharani's royal saloon carriage.",
    description:
      "The Mysore Rail Museum, the second railway museum in India, showcases vintage steam locomotives, royal coaches including the Maharani's saloon carriage, and railway memorabilia. A toy train ride adds to the appeal for families.",
    imageUrl: null,
    openingTimings: "9:30 AM - 6:30 PM (closed Mon)",
    entryFees: 30,
    budgetPerDay: 800,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 52,
    latitude: "12.3163393",
    longitude: "76.643323",
  },
  {
    slug: "lalitha-mahal-palace",
    name: "Lalitha Mahal Palace",
    state: "Karnataka",
    district: "Mysuru",
    category: "heritage",
    placeType: "Palace",
    shortDescription:
      "Gleaming white Italianate palace built for the Viceroy, now a heritage hotel below Chamundi Hills.",
    description:
      "Lalitha Mahal is a grand white palace built in 1921 to host the Viceroy of India, designed in an Italianate style inspired by St Paul's Cathedral. Set at the foot of Chamundi Hills, it now operates as a heritage hotel.",
    imageUrl: null,
    openingTimings: "Open (hotel premises)",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 55,
    latitude: "12.2982956",
    longitude: "76.6926105",
  },

  // ===================== SRIRANGAPATNA (MANDYA) =====================
  {
    slug: "ranganathaswamy-temple-srirangapatna",
    name: "Ranganathaswamy Temple, Srirangapatna",
    state: "Karnataka",
    district: "Mandya",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription:
      "Ancient island temple to Lord Ranganatha, the first of the three sacred Ranga Kshetras on the Cauvery.",
    description:
      "The Sri Ranganathaswamy Temple at Srirangapatna is dedicated to a reclining form of Vishnu and is the Adi Ranga, the first of the three island shrines along the Cauvery. Originally Hoysala and expanded by the Vijayanagara and later rulers, it is a major Vaishnava pilgrimage site.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Sri_Ranganathaswami_Temple%2C_Srirangaptna.jpg/1280px-Sri_Ranganathaswami_Temple%2C_Srirangaptna.jpg",
    openingTimings: "7:30 AM - 1:00 PM, 4:00 PM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 78,
    latitude: "12.4248989",
    longitude: "76.67906839999999",
  },
  {
    slug: "daria-daulat-bagh",
    name: "Daria Daulat Bagh (Tipu's Summer Palace)",
    state: "Karnataka",
    district: "Mandya",
    category: "heritage",
    placeType: "Palace & Museum",
    shortDescription:
      "Tipu Sultan's teak summer palace set in gardens, covered in vivid frescoes and murals.",
    description:
      "Daria Daulat Bagh was the summer palace of Tipu Sultan at Srirangapatna, built in 1784 largely of teak in Indo-Saracenic style. Its walls are adorned with frescoes depicting Tipu's battles, and it now functions as a museum of Tipu-era relics.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Gumbaj_containing_tomb_of_Tipu_Sultan.jpg/1280px-Gumbaj_containing_tomb_of_Tipu_Sultan.jpg",
    openingTimings: "9:00 AM - 5:00 PM",
    entryFees: 25,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 74,
    latitude: "12.4183707",
    longitude: "76.69671",
  },
  {
    slug: "gumbaz-srirangapatna",
    name: "Gumbaz, Srirangapatna",
    state: "Karnataka",
    district: "Mandya",
    category: "heritage",
    placeType: "Mausoleum",
    shortDescription:
      "Domed mausoleum holding the tombs of Tipu Sultan, Hyder Ali and their family.",
    description:
      "The Gumbaz is an elegant Indo-Islamic mausoleum at Srirangapatna housing the tombs of Tipu Sultan, his father Hyder Ali and his mother. Built by Tipu, it features ebony doors inlaid with ivory and tiger-stripe motifs set in a quiet garden.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Gopuram_of_the_Ranganathaswamy_Temple%2C_Srirangapatna_Karnataka_India.jpg/1280px-Gopuram_of_the_Ranganathaswamy_Temple%2C_Srirangapatna_Karnataka_India.jpg",
    openingTimings: "8:00 AM - 6:30 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 70,
    latitude: "12.4100205",
    longitude: "76.7138937",
  },
  {
    slug: "srirangapatna-fort",
    name: "Srirangapatna Fort",
    state: "Karnataka",
    district: "Mandya",
    category: "heritage",
    placeType: "Fort",
    shortDescription:
      "Island fortress of Tipu Sultan where the decisive 1799 Anglo-Mysore battle was fought.",
    description:
      "Srirangapatna Fort, encircled by the Cauvery, was the island capital of Hyder Ali and Tipu Sultan. The site of Tipu's last stand against the British in 1799, it preserves ramparts, dungeons, the Water Gate and the spot where Tipu fell.",
    imageUrl: null,
    openingTimings: "8:30 AM - 5:30 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 65,
    latitude: "12.421644",
    longitude: "76.6905037",
  },
  {
    slug: "nimishamba-temple",
    name: "Nimishamba Temple",
    state: "Karnataka",
    district: "Mandya",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription:
      "Riverside Shakti temple near Srirangapatna where the goddess is believed to grant wishes in a minute.",
    description:
      "The Nimishamba Temple sits on the banks of the Cauvery near Srirangapatna and is dedicated to a form of Parvati. Devotees believe the goddess fulfils prayers within a 'nimisha' (minute), and the Sri Chakra installed here draws steady crowds.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Nimishamba_temple.jpg/1280px-Nimishamba_temple.jpg",
    openingTimings: "6:30 AM - 8:30 PM",
    entryFees: 0,
    budgetPerDay: 800,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 60,
    latitude: "12.4187565",
    longitude: "76.710678",
  },
  {
    slug: "ranganathittu-bird-sanctuary",
    name: "Ranganathittu Bird Sanctuary",
    state: "Karnataka",
    district: "Mandya",
    category: "wildlife",
    placeType: "Bird Sanctuary",
    shortDescription:
      "Karnataka's largest bird sanctuary, a cluster of Cauvery islets teeming with nesting waterbirds and crocodiles.",
    description: "Ranganathittu is a group of riverine islets on the Cauvery near Srirangapatna and is Karnataka's largest bird sanctuary. Boat rides bring visitors close to nesting pelicans, storks, herons, cormorants and basking mugger crocodiles, especially during the breeding season. Entry is separate from the shared boat ride, which costs extra per person (a private boat can also be hired).",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Spot-billed_Pelican_Rising_Flight_Ranganathittu_Feb24_D72_26266.jpg/1280px-Spot-billed_Pelican_Rising_Flight_Ranganathittu_Feb24_D72_26266.jpg",
    openingTimings: "6:00 AM - 5:30 PM",
    entryFees: 75,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Dec,Jan,Feb,Mar,Apr,May,Jun",
    isHidden: false,
    popularity: 80,
    latitude: "12.4243603",
    longitude: "76.6563492",
  },

  // ===================== MANDYA / MYSURU BORDER =====================
  {
    slug: "somanathapura-keshava-temple",
    name: "Somanathapura Keshava Temple",
    state: "Karnataka",
    district: "Mysuru",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription:
      "Star-shaped 13th-century Hoysala masterpiece, a UNESCO World Heritage trikuta temple of intricate carving.",
    description:
      "The Chennakeshava (Keshava) Temple at Somanathapura, built in 1268, is the finest surviving Hoysala temple, with a star-shaped plan and three sanctums on a raised platform. Its friezes and ceiling carvings are exquisitely detailed, and it is inscribed as a UNESCO World Heritage Site.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Le_temple_de_Chennakesava_%28Somanathapura%2C_Inde%29_%2814465165685%29.jpg/1280px-Le_temple_de_Chennakesava_%28Somanathapura%2C_Inde%29_%2814465165685%29.jpg",
    openingTimings: "8:30 AM - 5:30 PM",
    entryFees: 25,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 79,
    latitude: "12.2757964",
    longitude: "76.8815048",
  },
  {
    slug: "talakadu",
    name: "Talakadu",
    state: "Karnataka",
    district: "Mysuru",
    category: "heritage",
    placeType: "Temple Town & Sand Dunes",
    shortDescription:
      "Buried temple town on the Cauvery, where ancient shrines emerge from shifting sand dunes.",
    description:
      "Talakadu is a historic town on the Cauvery once boasting dozens of temples, now famously covered by sand dunes attributed to a legendary curse. Excavated Pancha Linga shrines such as Vaidyanatheshwara and Pathaleshwara, and the Pancha Linga Darshana festival, draw pilgrims and history lovers.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 68,
    latitude: "12.1900",
    longitude: "77.0300",
  },

  // ===================== MELUKOTE (MANDYA) =====================
  {
    slug: "melukote",
    name: "Melukote (Cheluvanarayana Swamy Temple)",
    state: "Karnataka",
    district: "Mandya",
    category: "pilgrimage",
    placeType: "Temple Town",
    shortDescription:
      "Hilltop Vaishnava pilgrimage town linked to Ramanujacharya, with the Cheluvanarayana temple and Yoga Narasimha shrine.",
    description:
      "Melukote (Melkote) is a sacred Sri Vaishnava centre associated with the saint Ramanujacharya. The Cheluvanarayana Swamy Temple in the town and the hilltop Yoga Narasimha Temple, reached by a long flight of steps, overlook the Kalyani tank and rocky hills. The Vairamudi festival is its grandest event.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Cheluvanarayana_Swamy_Temple_BNC.jpg/1280px-Cheluvanarayana_Swamy_Temple_BNC.jpg",
    openingTimings: "7:30 AM - 1:00 PM, 4:00 PM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 67,
    latitude: "12.6602119",
    longitude: "76.6476455",
  },

  // ===================== SHIVANASAMUDRA / CAUVERY (MANDYA-CHAMARAJANAGAR) =====================
  {
    slug: "shivanasamudra-falls",
    name: "Shivanasamudra Falls (Gaganachukki & Bharachukki)",
    state: "Karnataka",
    district: "Mandya",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription:
      "Twin segmented falls on the Cauvery, splitting around an island into Gaganachukki and Bharachukki cascades.",
    description:
      "At Shivanasamudra the Cauvery splits around an island and plunges in two grand cascades, Gaganachukki and Bharachukki, among India's most powerful waterfalls in the monsoon. Asia's first hydroelectric power station was set up here in 1902.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Gagana_Chukki_%281%29.jpg/1280px-Gagana_Chukki_%281%29.jpg",
    openingTimings: "9:00 AM - 5:00 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Jul,Aug,Sep,Oct,Nov",
    isHidden: false,
    popularity: 82,
    latitude: "12.2878258",
    longitude: "77.18366750000001",
  },
  

  // ===================== CHAMARAJANAGARA =====================
  {
    slug: "biligiriranga-hills-br-hills",
    name: "Biligiriranga Hills (BR Hills)",
    state: "Karnataka",
    district: "Chamarajanagara",
    category: "wildlife",
    placeType: "Tiger Reserve & Hills",
    shortDescription:
      "Forested hill range and tiger reserve bridging the Western and Eastern Ghats, with a hilltop Rangaswamy temple.",
    description:
      "The Biligiri Rangana Hills form a biodiverse range linking the Western and Eastern Ghats and are protected as the BRT Tiger Reserve. The hilltop Biligiri Ranganathaswamy Temple, the Soliga tribal community and rich wildlife including tigers and elephants make it a unique destination.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1800,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 74,
    latitude: "11.9667",
    longitude: "77.1333",
  },
  {
    slug: "male-mahadeshwara-hills",
    name: "Male Mahadeshwara Hills (MM Hills)",
    state: "Karnataka",
    district: "Chamarajanagara",
    category: "pilgrimage",
    placeType: "Temple Town",
    shortDescription:
      "Hilltop pilgrimage town in seven hills, centred on the Sri Male Mahadeshwara Swamy (Shiva) temple.",
    description:
      "Male Mahadeshwara Hills is a major Shaivite pilgrimage town set among seven hills in Hanur taluk. The Sri Male Mahadeshwara Swamy Temple, dedicated to a self-manifested Shiva linga, is steeped in the folk legends of the saint Madappa and draws lakhs of devotees.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/90/Male_Mahadeswara_temple.jpg",
    openingTimings: "6:00 AM - 9:00 PM",
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 66,
    latitude: "12.0444",
    longitude: "77.5944",
  },
  {
    slug: "bandipur-national-park",
    name: "Bandipur National Park",
    state: "Karnataka",
    district: "Chamarajanagara",
    category: "wildlife",
    placeType: "National Park",
    shortDescription:
      "Premier tiger reserve in the Nilgiri Biosphere, famed for tigers, elephants and gaur on safari.",
    description: "Bandipur National Park, a former Mysore royal hunting ground, is one of India's best-known tiger reserves and part of the Nilgiri Biosphere Reserve. Jeep and bus safaris offer chances to see tigers, leopards, elephants, gaur, dhole and abundant deer and birdlife. Park entry is separate from the safari itself — bus safaris run roughly ₹300-450 per person while a private jeep (up to six people) costs several thousand rupees; safaris run in early morning and late afternoon slots only.",
    imageUrl: null,
    openingTimings: "6:00 AM - 9:00 AM, 3:30 PM - 6:00 PM",
    entryFees: 250,
    budgetPerDay: 2200,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar,Apr",
    isHidden: false,
    popularity: 88,
    latitude: "11.6700",
    longitude: "76.6300",
  },
  {
    slug: "gopalaswamy-betta",
    name: "Himavad Gopalaswamy Betta",
    state: "Karnataka",
    district: "Chamarajanagara",
    category: "hill_station",
    placeType: "Hill & Temple",
    shortDescription:
      "Highest peak in Bandipur, often wrapped in mist, crowned by the Venugopalaswamy temple.",
    description:
      "Himavad Gopalaswamy Betta is the tallest peak within the Bandipur reserve, frequently shrouded in mist ('hima') even in summer. The hilltop Venugopalaswamy Temple, a Hoysala-era shrine to Krishna, and sweeping views of forested valleys reward the climb.",
    imageUrl: null,
    openingTimings: "8:30 AM - 4:30 PM",
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 58,
    latitude: "11.7986",
    longitude: "76.5142",
  },

  // ===================== HASSAN =====================
  {
    slug: "belur-chennakeshava-temple",
    name: "Chennakeshava Temple, Belur",
    state: "Karnataka",
    district: "Hassan",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription:
      "Hoysala-era Vishnu temple at Belur with breathtaking sculpted bracket figures, a UNESCO World Heritage Site.",
    description: "The Chennakeshava Temple at Belur, commissioned by Hoysala king Vishnuvardhana in 1117, took over a century to complete and is celebrated for its filigree-like soapstone carving and madanika bracket figures. It is part of the UNESCO-listed Sacred Ensembles of the Hoysalas. This ASI-protected monument charges a modest entry fee for Indian visitors; carry a photo ID.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/The_Courtyard_of_Chennakesava_Temple_-_Belur.jpg/1280px-The_Courtyard_of_Chennakesava_Temple_-_Belur.jpg",
    openingTimings: "7:30 AM - 7:30 PM",
    entryFees: 20,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 82,
    latitude: "13.1629637",
    longitude: "75.860315",
  },
  {
    slug: "halebidu-hoysaleswara-temple",
    name: "Hoysaleswara Temple, Halebidu",
    state: "Karnataka",
    district: "Hassan",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription:
      "Twin-shrine Shiva temple at the old Hoysala capital, covered in thousands of intricate stone carvings.",
    description: "The Hoysaleswara Temple at Halebidu, the former Hoysala capital Dwarasamudra, is a twin-shrine temple to Shiva built in the 12th century. Its walls are densely carved with friezes of elephants, deities, dancers and mythological scenes, forming part of the UNESCO Sacred Ensembles of the Hoysalas. This ASI-protected monument is open sunrise to sunset; children under 12 enter free.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Hoysaleshwara_temple_in_Monsoon.JPG/1280px-Hoysaleshwara_temple_in_Monsoon.JPG",
    openingTimings: "6:30 AM - 6:30 PM",
    entryFees: 25,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 80,
    latitude: "13.2125039",
    longitude: "75.9941821",
  },
  {
    slug: "shravanabelagola",
    name: "Shravanabelagola (Gomateshwara)",
    state: "Karnataka",
    district: "Hassan",
    category: "pilgrimage",
    placeType: "Jain Pilgrimage",
    shortDescription:
      "Hilltop site of the 57-ft Gomateshwara (Bahubali) monolith, a major Jain pilgrimage centre.",
    description:
      "Shravanabelagola is one of the most important Jain pilgrimage centres, dominated by the colossal 57-foot monolithic statue of Bahubali (Gomateshwara) atop Vindyagiri hill, carved around 981 CE. Every twelve years the grand Mahamastakabhisheka anointing ceremony is held here.",
    imageUrl: null,
    openingTimings: "6:30 AM - 6:30 PM",
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 81,
    latitude: "12.8539875",
    longitude: "76.48470309999999",
  },
  {
    slug: "hasanamba-temple-hassan",
    name: "Hasanamba Temple, Hassan",
    state: "Karnataka",
    district: "Hassan",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription:
      "Goddess temple that gives Hassan its name, opened to devotees only once a year during Deepavali.",
    description:
      "The Hasanamba Temple, dedicated to the goddess after whom Hassan town is named, is unusual for opening its sanctum just once a year, for about a week around Deepavali. Legends of a lamp and flowers remaining undisturbed for a year draw huge crowds during the opening.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Hassan._court_-1.jpg/1280px-Hassan._court_-1.jpg",
    openingTimings: "Open ~1 week/year (Deepavali)",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov",
    isHidden: true,
    popularity: 56,
    latitude: "13.0026637",
    longitude: "76.0944116",
  },

  // ===================== KODAGU (COORG) =====================
  {
    slug: "madikeri",
    name: "Madikeri",
    state: "Karnataka",
    district: "Kodagu",
    category: "hill_station",
    placeType: "Hill Station",
    shortDescription:
      "Misty hill-station capital of Coorg, base for coffee estates, forts and scenic viewpoints.",
    description:
      "Madikeri is the headquarters of Kodagu (Coorg) and the gateway to its coffee country. Set amid the Western Ghats, the town has the Madikeri Fort, the Omkareshwara Temple, the Raja's Tombs and easy access to surrounding waterfalls and viewpoints.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Raja%27s_Seat_View_Point.jpg/1280px-Raja%27s_Seat_View_Point.jpg",
    openingTimings: "Open all day",
    entryFees: 0,
    budgetPerDay: 2000,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 85,
    latitude: "12.4209",
    longitude: "75.7397",
  },
  {
    slug: "abbey-falls",
    name: "Abbey Falls",
    state: "Karnataka",
    district: "Kodagu",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription:
      "Picturesque Coorg waterfall set among coffee and spice plantations, viewed from a hanging bridge.",
    description:
      "Abbey (Abbi) Falls is a popular cascade near Madikeri, plunging through coffee estates and spice plantations into a rocky pool. A short trail and a hanging bridge offer a close view, with the falls at their fullest during and after the monsoon.",
    imageUrl: null,
    openingTimings: "9:00 AM - 5:00 PM",
    entryFees: 20,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Jul,Aug,Sep,Oct,Nov,Dec",
    isHidden: false,
    popularity: 78,
    latitude: "12.4578946",
    longitude: "75.7164803",
  },
  {
    slug: "rajas-seat",
    name: "Raja's Seat",
    state: "Karnataka",
    district: "Kodagu",
    category: "hill_station",
    placeType: "Viewpoint & Garden",
    shortDescription:
      "Garden viewpoint in Madikeri once favoured by Coorg kings for its spectacular sunset over the hills.",
    description:
      "Raja's Seat is a seasonal flower garden and viewpoint in Madikeri where the rulers of Coorg are said to have relaxed and watched the sunset. It offers sweeping views of mist-laden valleys and a small toy train for visitors.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c6/Raja_seat_madikeri.JPG",
    openingTimings: "9:00 AM - 8:00 PM",
    entryFees: 20,
    budgetPerDay: 1700,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 75,
    latitude: "12.4144899",
    longitude: "75.7368986",
  },
  {
    slug: "talacauvery",
    name: "Talacauvery",
    state: "Karnataka",
    district: "Kodagu",
    category: "pilgrimage",
    placeType: "Temple & River Source",
    shortDescription:
      "Sacred source of the Cauvery on Brahmagiri Hill, with a kundike tank and panoramic Western Ghats views.",
    description:
      "Talacauvery, on the Brahmagiri Hills near Bhagamandala, is the revered origin of the Cauvery river. Pilgrims bathe in the Triveni and visit the small temple tank (kundike) where the goddess Cauvery is believed to well up, especially during the Tula Sankramana festival.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Thalakkaveri_Temple%2C_Karnataka.jpg/1280px-Thalakkaveri_Temple%2C_Karnataka.jpg",
    openingTimings: "6:00 AM - 8:30 PM",
    entryFees: 0,
    budgetPerDay: 1700,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 72,
    latitude: "12.3858741",
    longitude: "75.4947431",
  },
  {
    slug: "bhagamandala",
    name: "Bhagamandala (Triveni Sangama)",
    state: "Karnataka",
    district: "Kodagu",
    category: "pilgrimage",
    placeType: "Temple & Confluence",
    shortDescription:
      "Sacred confluence of three rivers near Talacauvery, with the Bhagandeshwara temple complex.",
    description:
      "Bhagamandala is the Triveni Sangama where the Cauvery, Kannike and the mythical Sujyoti rivers meet. Pilgrims perform rituals at the confluence before continuing to Talacauvery, and the Bhagandeshwara temple complex in Kerala-influenced style is the town's centrepiece.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Bhagamandala_Birdseye_View_Coorg_Feb24_A7C_09524.jpg/1280px-Bhagamandala_Birdseye_View_Coorg_Feb24_A7C_09524.jpg",
    openingTimings: "6:30 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 1700,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 60,
    latitude: "12.3844311",
    longitude: "75.53308340000001",
  },
  {
    slug: "dubare-elephant-camp",
    name: "Dubare Elephant Camp",
    state: "Karnataka",
    district: "Kodagu",
    category: "wildlife",
    placeType: "Elephant Camp",
    shortDescription:
      "Riverside elephant camp on the Cauvery where visitors can feed, bathe and learn about trained elephants.",
    description:
      "Dubare Elephant Camp on the banks of the Cauvery is a forest department camp where trained elephants are cared for. Visitors can watch and assist with feeding and bathing the elephants, take coracle rides and enjoy the riverine forest setting.",
    imageUrl: null,
    openingTimings: "8:30 AM - 11:00 AM, 4:30 PM - 5:30 PM",
    entryFees: 50,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 76,
    latitude: "12.3705082",
    longitude: "75.9059901",
  },
  {
    slug: "namdroling-monastery-bylakuppe",
    name: "Namdroling Monastery (Golden Temple), Bylakuppe",
    state: "Karnataka",
    district: "Kodagu",
    category: "pilgrimage",
    placeType: "Monastery",
    shortDescription:
      "The 'Golden Temple' of Bylakuppe, the largest Nyingma Tibetan Buddhist monastery in the world.",
    description:
      "Namdroling Monastery at Bylakuppe, India's largest Tibetan settlement, is the biggest teaching centre of the Nyingma school of Tibetan Buddhism. Its golden temple houses towering gilded statues of Buddha, Padmasambhava and Amitayus amid vivid murals, with thousands of resident monks and nuns.",
    imageUrl: null,
    openingTimings: "9:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1500,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 79,
    latitude: "12.430628",
    longitude: "75.9669536",
  },
  {
    slug: "iruppu-falls",
    name: "Iruppu Falls",
    state: "Karnataka",
    district: "Kodagu",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription:
      "Sacred Coorg waterfall on the Brahmagiri range, gateway to the Brahmagiri trek and the Rameshwara temple.",
    description:
      "Iruppu (Irpu) Falls is a freshwater cascade on the Lakshmana Tirtha river in the Brahmagiri range of South Kodagu. Considered sacred and linked to the Ramayana, it adjoins the Rameshwara Temple and marks the start of the Brahmagiri wildlife trek.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Iruppu_Falls_%2849099719332%29.jpg/1280px-Iruppu_Falls_%2849099719332%29.jpg",
    openingTimings: "8:00 AM - 5:30 PM",
    entryFees: 20,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Jul,Aug,Sep,Oct,Nov,Dec",
    isHidden: false,
    popularity: 68,
    latitude: "11.9661026",
    longitude: "75.9833292",
  },
  {
    slug: "mandalpatti",
    name: "Mandalpatti",
    state: "Karnataka",
    district: "Kodagu",
    category: "hill_station",
    placeType: "Viewpoint & Trek",
    shortDescription:
      "High Coorg viewpoint reached by jeep or trek, offering 360-degree views over a sea of misty hills.",
    description:
      "Mandalpatti is a scenic peak within the Pushpagiri reserve near Madikeri, popular for its bumpy jeep ride and short trek to a viewpoint. At sunrise and after rain, clouds drift across the surrounding ridges, creating a sea-of-clouds panorama.",
    imageUrl: null,
    openingTimings: "6:00 AM - 5:00 PM",
    entryFees: 50,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 64,
    latitude: "12.4030",
    longitude: "75.6760",
  },
  {
    slug: "nisargadhama",
    name: "Nisargadhama",
    state: "Karnataka",
    district: "Kodagu",
    category: "wildlife",
    placeType: "Nature Park",
    shortDescription:
      "River island nature park near Kushalnagar with bamboo groves, a deer park and hanging bridge.",
    description:
      "Nisargadhama is a forested island on the Cauvery near Kushalnagar, reached by a hanging rope bridge. The park features bamboo and sandalwood groves, a deer enclosure, a small elephant area, treehouse cottages and boating, making it a relaxed family stop.",
    imageUrl: null,
    openingTimings: "9:00 AM - 6:00 PM",
    entryFees: 20,
    budgetPerDay: 1600,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 63,
    latitude: "12.4480",
    longitude: "75.9560",
  },
  {
    slug: "harangi-dam",
    name: "Harangi Dam",
    state: "Karnataka",
    district: "Kodagu",
    category: "heritage",
    placeType: "Dam",
    shortDescription:
      "Earthen dam on the Harangi river near Kushalnagar with a garden and reservoir views.",
    description:
      "Harangi Dam is built across the Harangi, a tributary of the Cauvery, near Kushalnagar in Kodagu. The dam, its reservoir and a small ornamental garden make it a quiet picnic and viewpoint spot, especially scenic when the gates are opened in the monsoon.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Harangi_Reservoir%2C_Coorg.jpg/1280px-Harangi_Reservoir%2C_Coorg.jpg",
    openingTimings: "9:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1500,
    recommendedDays: 1,
    bestMonths: "Jul,Aug,Sep,Oct,Nov",
    isHidden: true,
    popularity: 50,
    latitude: "12.491667",
    longitude: "75.90555599999999",
  },
  {
    slug: "tadiandamol-peak",
    name: "Tadiandamol Peak",
    state: "Karnataka",
    district: "Kodagu",
    category: "adventure",
    placeType: "Trek & Peak",
    shortDescription:
      "Highest peak in Coorg and a classic trek through shola forests and rolling grasslands.",
    description:
      "Tadiandamol is the tallest peak in Kodagu at about 1,748 m and the third highest in Karnataka. The trek from Nalknad Palace passes through shola forests and open grassland to a summit with sweeping views of the Western Ghats, popular with hikers.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Tadiandamol_Trek_25Aug_Pic_3_View_From_Top.jpg/1280px-Tadiandamol_Trek_25Aug_Pic_3_View_From_Top.jpg",
    openingTimings: "6:00 AM - 5:00 PM",
    entryFees: 0,
    budgetPerDay: 1900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 62,
    latitude: "12.2175976",
    longitude: "75.6091118",
  },

  // ===================== NAGARHOLE (KODAGU / MYSURU) =====================
  {
    slug: "nagarhole-national-park",
    name: "Nagarhole National Park (Rajiv Gandhi NP)",
    state: "Karnataka",
    district: "Kodagu",
    category: "wildlife",
    placeType: "National Park",
    shortDescription:
      "Lush tiger reserve in the Nilgiri Biosphere, rich in elephants, tigers, leopards and birdlife.",
    description: "Nagarhole (Rajiv Gandhi) National Park lies between Kodagu and Mysuru and forms part of the Nilgiri Biosphere Reserve. Its moist deciduous forests, streams and the Kabini backwaters support large herds of elephants, tigers, leopards, gaur and dhole, with excellent safari and boat-based wildlife viewing. Park entry is separate from the jeep or bus safari, which costs extra and runs only in the early-morning and late-afternoon slots.",
    imageUrl: null,
    openingTimings: "6:00 AM - 9:00 AM, 3:00 PM - 6:00 PM",
    entryFees: 250,
    budgetPerDay: 2400,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar,Apr",
    isHidden: false,
    popularity: 84,
    latitude: "12.0000",
    longitude: "76.1300",
  },
];
