import type { NewDestination } from "../schema";

// Central & East-Central India — Madhya Pradesh, Chhattisgarh, Bihar, Jharkhand
export const centralIndiaDestinations: Omit<NewDestination, "id" | "createdAt">[] = [
  // ─────────────────────────── MADHYA PRADESH ───────────────────────────
  {
    slug: "sanchi-stupa",
    name: "Sanchi Stupa",
    state: "Madhya Pradesh",
    district: "Raisen",
    category: "heritage",
    placeType: "Buddhist Monument",
    shortDescription: "Great Stupa commissioned by Ashoka, India's oldest stone structure and a UNESCO World Heritage Site.",
    description: "The Great Stupa at Sanchi, begun by Emperor Ashoka in the 3rd century BCE, is India's oldest surviving stone structure. Famous for its ornately carved toranas (gateways) depicting the life of the Buddha, the hilltop complex also holds monasteries, pillars and smaller stupas. Visit the on-site museum housing the Ashokan lion capital.",
    imageUrl: null,
    openingTimings: "6:30 AM - 6:00 PM",
    entryFees: 40,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 78,
    latitude: "23.4795",
    longitude: "77.7397",
  },
  {
    slug: "khajuraho-western-group-temples",
    name: "Khajuraho Western Group of Temples",
    state: "Madhya Pradesh",
    district: "Chhatarpur",
    category: "heritage",
    placeType: "Temple Complex",
    shortDescription: "UNESCO-listed Chandela temples renowned for their intricate erotic and celestial sculpture, led by Kandariya Mahadev.",
    description: "The Western Group is the largest and finest cluster of Khajuraho's Nagara-style sandstone temples, built by the Chandela dynasty between 950 and 1050 CE. The towering Kandariya Mahadev, Lakshmana and Vishwanath temples are covered in exquisite carvings of deities, dancers, musicians and famous erotic panels. An evening sound-and-light show narrates the site's history.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 40,
    budgetPerDay: 1600,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 90,
    latitude: "24.8518",
    longitude: "79.9199",
  },
  {
    slug: "raneh-falls-canyon",
    name: "Raneh Falls Canyon",
    state: "Madhya Pradesh",
    district: "Chhatarpur",
    category: "adventure",
    placeType: "Waterfall & Canyon",
    shortDescription: "A colourful crystalline granite canyon on the Ken river with seasonal falls, near Khajuraho and Panna reserve.",
    description: "Raneh Falls is a five-kilometre gorge carved by the Ken river through pink, red and grey crystalline granite. During and after the monsoon a series of waterfalls thunder through the canyon, while the surrounding forest is home to gharial and crocodiles. It makes an easy half-day trip from Khajuraho combined with the Ken Gharial Sanctuary.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 15,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Aug,Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 55,
    latitude: "24.9333",
    longitude: "80.0167",
  },
  {
    slug: "gwalior-fort",
    name: "Gwalior Fort",
    state: "Madhya Pradesh",
    district: "Gwalior",
    category: "heritage",
    placeType: "Hill Fort",
    shortDescription: "A towering hilltop fort with the Man Singh Palace, Teli-ka-Mandir and India's oldest recorded use of zero.",
    description: "Perched on a sheer sandstone hill, Gwalior Fort has been called the 'pearl among fortresses of Hind'. Highlights include the tiled Man Singh Palace, the tall Teli-ka-Mandir, the Sas-Bahu temples, Gujari Mahal and rock-cut Jain colossi. A small inscription at the Chaturbhuj temple here contains one of the world's oldest records of the numeral zero.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 75,
    budgetPerDay: 1500,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 82,
    latitude: "26.2299",
    longitude: "78.1691",
  },
  {
    slug: "jai-vilas-palace-gwalior",
    name: "Jai Vilas Palace & Scindia Museum",
    state: "Madhya Pradesh",
    district: "Gwalior",
    category: "heritage",
    placeType: "Palace Museum",
    shortDescription: "Opulent 19th-century Scindia palace famed for its Durbar Hall chandeliers and silver toy-train that served after-dinner brandy.",
    description: "Built in 1874 by Maharaja Jayajirao Scindia, this European-styled palace mixes Tuscan, Italian and Corinthian architecture. The Durbar Hall dazzles with gold furnishings and two of the world's largest chandeliers, while the museum preserves royal artefacts, weaponry and a silver miniature train that carried drinks around the dining table.",
    imageUrl: null,
    openingTimings: "10:00 AM - 5:00 PM",
    entryFees: 150,
    budgetPerDay: 1500,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 68,
    latitude: "26.2007",
    longitude: "78.1583",
  },
  {
    slug: "orchha-fort-complex",
    name: "Orchha Fort Complex",
    state: "Madhya Pradesh",
    district: "Niwari",
    category: "heritage",
    placeType: "Fort & Palaces",
    shortDescription: "Bundela riverside fort with the grand Jehangir Mahal and Raja Mahal overlooking the Betwa river.",
    description: "The 16th-century citadel of the Bundela rulers of Orchha centres on the multi-tiered Jehangir Mahal, built to honour a Mughal emperor's visit, and the frescoed Raja Mahal. Set beside the Betwa river, the complex includes the Rai Praveen Mahal and camel stables, and rewards visitors with sweeping views from its domed pavilions.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 40,
    budgetPerDay: 1400,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 76,
    latitude: "25.3518",
    longitude: "78.6420",
  },
  {
    slug: "ram-raja-temple-orchha",
    name: "Ram Raja Temple, Orchha",
    state: "Madhya Pradesh",
    district: "Niwari",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "The only shrine where Rama is worshipped as a king, housed in a former palace at Orchha.",
    description: "Legend says an idol of Rama installed here overnight could not be moved, so the queen's palace became a temple. Uniquely, Rama is venerated as a reigning king and given a daily armed guard of honour by state police. The pink-and-yellow palatial structure draws large crowds during Ram Navami and evening aarti.",
    imageUrl: null,
    openingTimings: "8:00 AM - 12:30 PM, 7:00 PM - 10:30 PM",
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 70,
    latitude: "25.3520",
    longitude: "78.6413",
  },
  {
    slug: "orchha-chhatris-cenotaphs",
    name: "Orchha Cenotaphs (Chhatris)",
    state: "Madhya Pradesh",
    district: "Niwari",
    category: "heritage",
    placeType: "Royal Cenotaphs",
    shortDescription: "Fourteen towering Bundela royal cenotaphs lined along the Betwa river, glowing at sunset.",
    description: "The Kanchana Ghat cenotaphs are a row of fourteen memorial chhatris built for the Bundela kings of Orchha. Their domed sandstone spires reflect beautifully in the Betwa at dawn and dusk, and the site is a favourite for photographers and a nesting ground for vultures.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 20,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 58,
    latitude: "25.3486",
    longitude: "78.6398",
  },
  {
    slug: "upper-lake-bhopal",
    name: "Upper Lake (Bhojtal), Bhopal",
    state: "Madhya Pradesh",
    district: "Bhopal",
    category: "heritage",
    placeType: "Lake",
    shortDescription: "The 11th-century man-made Bhojtal lake that earns Bhopal its title of 'City of Lakes'.",
    description: "Believed to have been created by Raja Bhoj in the 11th century, the Upper Lake is one of India's oldest man-made lakes and Bhopal's main source of water. The waterfront Boat Club offers cruises and kayaking, while the adjoining VIP road and Kamla Park are popular for evening strolls and sunset views.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1300,
    recommendedDays: 1,
    bestMonths: "Jul,Aug,Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 66,
    latitude: "23.2560",
    longitude: "77.3690",
  },
  {
    slug: "taj-ul-masajid-bhopal",
    name: "Taj-ul-Masajid, Bhopal",
    state: "Madhya Pradesh",
    district: "Bhopal",
    category: "pilgrimage",
    placeType: "Mosque",
    shortDescription: "One of Asia's largest mosques, a pink-domed 19th-century masterpiece begun by the Begums of Bhopal.",
    description: "Taj-ul-Masajid, meaning 'Crown of Mosques', is among the largest mosques in Asia, with a vast marble-floored courtyard, two soaring minarets and imposing pink facade with white domes. Begun under Shah Jahan Begum in the 1870s, it was completed only in the 20th century and remains an active place of worship and Islamic seminary.",
    imageUrl: null,
    openingTimings: "5:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 64,
    latitude: "23.2637",
    longitude: "77.3910",
  },
  {
    slug: "van-vihar-national-park-bhopal",
    name: "Van Vihar National Park, Bhopal",
    state: "Madhya Pradesh",
    district: "Bhopal",
    category: "wildlife",
    placeType: "National Park",
    shortDescription: "A drive-through urban national park beside Upper Lake sheltering tigers, lions, leopards and crocodiles.",
    description: "Van Vihar is an unusual national park run partly as a zoological garden on the edge of Bhopal's Upper Lake. Animals live in near-natural open enclosures, and visitors can drive or cycle through to see tigers, lions, leopards, sloth bears, hyenas and gharials, with birdlife along the lakeside.",
    imageUrl: null,
    openingTimings: "7:00 AM - 6:00 PM (closed Tue)",
    entryFees: 30,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 62,
    latitude: "23.2350",
    longitude: "77.3620",
  },
  {
    slug: "bhimbetka-rock-shelters",
    name: "Bhimbetka Rock Shelters",
    state: "Madhya Pradesh",
    district: "Raisen",
    category: "heritage",
    placeType: "Prehistoric Rock Art",
    shortDescription: "UNESCO-listed sandstone caves with prehistoric paintings up to 30,000 years old, among Asia's oldest.",
    description: "The rock shelters of Bhimbetka preserve one of the world's largest concentrations of prehistoric cave art, painted in natural ochres over tens of thousands of years. Trails wind past shelters depicting hunting scenes, dancers, animals and later historic figures, set among dramatic wind-sculpted Vindhyan sandstone formations.",
    imageUrl: null,
    openingTimings: "7:00 AM - 6:00 PM",
    entryFees: 25,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 72,
    latitude: "22.9385",
    longitude: "77.6132",
  },
  {
    slug: "bhojpur-shiva-temple",
    name: "Bhojeshwar Temple, Bhojpur",
    state: "Madhya Pradesh",
    district: "Raisen",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "An unfinished 11th-century Shiva temple housing one of India's largest monolithic lingams.",
    description: "Built by Raja Bhoj in the 11th century, the Bhojeshwar Temple enshrines a colossal 2.3-metre stone Shiva lingam carved from a single rock. Though never completed, its huge sanctum, unfinished dome and the earthen ramp used to raise the stones make it a remarkable window into medieval temple engineering.",
    imageUrl: null,
    openingTimings: "7:00 AM - 7:00 PM",
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 52,
    latitude: "23.1063",
    longitude: "77.5893",
  },
  {
    slug: "ujjain-mahakaleshwar-temple",
    name: "Mahakaleshwar Jyotirlinga, Ujjain",
    state: "Madhya Pradesh",
    district: "Ujjain",
    category: "pilgrimage",
    placeType: "Jyotirlinga Temple",
    shortDescription: "One of twelve Jyotirlingas of Shiva, famous for the daily pre-dawn Bhasma Aarti in Ujjain.",
    description: "Mahakaleshwar is among the holiest Shaivite shrines, its south-facing lingam considered swayambhu (self-manifested). The temple is renowned for the Bhasma Aarti performed before dawn using sacred ash, and Ujjain itself is one of the four cities that host the Simhastha Kumbh Mela on the banks of the Shipra river.",
    imageUrl: null,
    openingTimings: "3:00 AM - 11:00 PM",
    entryFees: 0,
    budgetPerDay: 1300,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 85,
    latitude: "23.1828",
    longitude: "75.7683",
  },
  {
    slug: "kal-bhairav-temple-ujjain",
    name: "Kal Bhairav Temple, Ujjain",
    state: "Madhya Pradesh",
    district: "Ujjain",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Ancient Ujjain shrine where the deity Kal Bhairav is offered liquor as prasad.",
    description: "Dedicated to Kal Bhairav, the fierce guardian form of Shiva, this Tantric temple is famous for its unusual ritual in which liquor is poured to the idol as an offering and appears to vanish. It is one of the eight Bhairava shrines traditionally associated with Ujjain's spiritual geography.",
    imageUrl: null,
    openingTimings: "6:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 60,
    latitude: "23.2000",
    longitude: "75.7660",
  },
  {
    slug: "mandu-jahaz-mahal",
    name: "Mandu (Jahaz Mahal & Rupmati Pavilion)",
    state: "Madhya Pradesh",
    district: "Dhar",
    category: "heritage",
    placeType: "Fortified City",
    shortDescription: "Afghan-era hilltop city of romance, with the ship-shaped Jahaz Mahal and Rani Rupmati's cliff-top pavilion.",
    description: "The ruined city of Mandu spreads across a Vindhya plateau and is celebrated for its Afghan architecture and the legend of Baz Bahadur and Rani Rupmati. Highlights include the ship-like Jahaz Mahal set between two lakes, the swinging Hindola Mahal, Rupmati's Pavilion overlooking the Narmada valley, and the marble Hoshang Shah's tomb.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 40,
    budgetPerDay: 1400,
    recommendedDays: 2,
    bestMonths: "Jul,Aug,Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 74,
    latitude: "22.3441",
    longitude: "75.3760",
  },
  {
    slug: "kanha-national-park",
    name: "Kanha National Park",
    state: "Madhya Pradesh",
    district: "Mandla",
    category: "wildlife",
    placeType: "Tiger Reserve",
    shortDescription: "Sprawling sal-forest tiger reserve that inspired Kipling's Jungle Book and saved the barasingha deer.",
    description: "One of India's finest tiger reserves, Kanha spreads across meadows and sal forests in the Maikal hills and is credited with rescuing the hard-ground barasingha from extinction. Jeep safaris offer chances to spot tigers, leopards, gaur, dhole and abundant birdlife, and the landscape is said to have inspired Rudyard Kipling's Jungle Book.",
    imageUrl: null,
    openingTimings: "Safari: 6:00 AM - 11:00 AM, 3:00 PM - 6:00 PM (closed Jul-Sep)",
    entryFees: 250,
    budgetPerDay: 2400,
    recommendedDays: 3,
    bestMonths: "Nov,Dec,Jan,Feb,Mar,Apr",
    isHidden: false,
    popularity: 84,
    latitude: "22.3345",
    longitude: "80.6115",
  },
  {
    slug: "bandhavgarh-national-park",
    name: "Bandhavgarh National Park",
    state: "Madhya Pradesh",
    district: "Umaria",
    category: "wildlife",
    placeType: "Tiger Reserve",
    shortDescription: "Reserve with one of India's highest tiger densities, crowned by an ancient hilltop fort.",
    description: "Bandhavgarh boasts among the highest densities of Bengal tigers in India, giving excellent sighting chances on its jeep safaris. Beyond big cats it shelters leopards, sloth bears and deer, while the ancient Bandhavgarh Fort, reclining Vishnu sculptures and cave shrines add a layer of history to the wilderness.",
    imageUrl: null,
    openingTimings: "Safari: 6:00 AM - 11:00 AM, 3:00 PM - 6:00 PM (closed Jul-Sep)",
    entryFees: 250,
    budgetPerDay: 2500,
    recommendedDays: 3,
    bestMonths: "Nov,Dec,Jan,Feb,Mar,Apr",
    isHidden: false,
    popularity: 86,
    latitude: "23.7135",
    longitude: "81.0326",
  },
  {
    slug: "pench-national-park-mp",
    name: "Pench National Park (Madhya Pradesh)",
    state: "Madhya Pradesh",
    district: "Seoni",
    category: "wildlife",
    placeType: "Tiger Reserve",
    shortDescription: "Teak-forested tiger reserve straddling the Pench river, another landscape behind Kipling's Jungle Book.",
    description: "Named for the Pench river that bisects it, this reserve of teak forest and grassland supports tigers, leopards, wild dogs, gaur and huge herds of deer, along with rich birdlife. Its 'Mowgli-land' setting is often linked to Kipling's stories. Jeep safaris depart from the Turia and Karmajhiri gates.",
    imageUrl: null,
    openingTimings: "Safari: 6:00 AM - 11:00 AM, 3:00 PM - 6:00 PM (closed Jul-Sep)",
    entryFees: 250,
    budgetPerDay: 2300,
    recommendedDays: 2,
    bestMonths: "Nov,Dec,Jan,Feb,Mar,Apr",
    isHidden: false,
    popularity: 76,
    latitude: "21.7500",
    longitude: "79.2960",
  },
  {
    slug: "panna-national-park",
    name: "Panna National Park",
    state: "Madhya Pradesh",
    district: "Panna",
    category: "wildlife",
    placeType: "Tiger Reserve",
    shortDescription: "Ken-river tiger reserve famed for its successful tiger reintroduction, gorges and boat safaris.",
    description: "Panna is celebrated as a conservation success story, having rebuilt its tiger population after local extinction. Set among plateaus, gorges and the Ken river, it offers jeep and boat safaris to spot tigers, crocodiles, vultures and gharials. It combines easily with nearby Khajuraho and Raneh Falls.",
    imageUrl: null,
    openingTimings: "Safari: 6:00 AM - 11:00 AM, 3:00 PM - 6:00 PM (closed Jul-Sep)",
    entryFees: 250,
    budgetPerDay: 2200,
    recommendedDays: 2,
    bestMonths: "Nov,Dec,Jan,Feb,Mar,Apr",
    isHidden: false,
    popularity: 68,
    latitude: "24.7180",
    longitude: "80.0080",
  },
  {
    slug: "pachmarhi-hill-station",
    name: "Pachmarhi Hill Station",
    state: "Madhya Pradesh",
    district: "Narmadapuram",
    category: "hill_station",
    placeType: "Hill Station",
    shortDescription: "Madhya Pradesh's only hill station, 'Satpura ki Rani', with waterfalls, caves and the state's highest peak.",
    description: "Nestled in the Satpura range at over 1,000 metres, Pachmarhi is Madhya Pradesh's sole hill station. Its forests hide the Pandava Caves, Bee Falls, Apsara Vihar pools and ancient rock paintings, while Dhupgarh, the state's highest point, offers spectacular sunsets over the hills.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1600,
    recommendedDays: 3,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar,Apr",
    isHidden: false,
    popularity: 74,
    latitude: "22.4675",
    longitude: "78.4336",
  },
  {
    slug: "satpura-national-park",
    name: "Satpura National Park",
    state: "Madhya Pradesh",
    district: "Narmadapuram",
    category: "wildlife",
    placeType: "Tiger Reserve",
    shortDescription: "Rugged reserve near Pachmarhi renowned for walking safaris, canoeing and sloth-bear sightings.",
    description: "Part of the larger Satpura Tiger Reserve, this park stands out for permitting walking safaris, canoe rides on the Denwa backwaters and night drives that few Indian parks allow. Its hills and ravines shelter tigers, leopards, sloth bears, Indian giant squirrels and rich birdlife in a wonderfully wild landscape.",
    imageUrl: null,
    openingTimings: "Safari: 6:30 AM - 11:00 AM, 3:00 PM - 5:30 PM (closed Jul-Sep)",
    entryFees: 250,
    budgetPerDay: 2400,
    recommendedDays: 2,
    bestMonths: "Nov,Dec,Jan,Feb,Mar,Apr",
    isHidden: true,
    popularity: 66,
    latitude: "22.5200",
    longitude: "78.2700",
  },
  {
    slug: "omkareshwar-jyotirlinga",
    name: "Omkareshwar Jyotirlinga",
    state: "Madhya Pradesh",
    district: "Khandwa",
    category: "pilgrimage",
    placeType: "Jyotirlinga Temple",
    shortDescription: "Om-shaped island shrine on the Narmada, one of the twelve sacred Jyotirlingas of Shiva.",
    description: "Omkareshwar sits on Mandhata, an island in the Narmada shaped like the sacred 'Om' symbol. The temple is one of Shiva's twelve Jyotirlingas and is reached by boat or a footbridge, with pilgrims performing a parikrama of the island. The riverfront ghats and the nearby Mamleshwar temple add to its spiritual draw.",
    imageUrl: null,
    openingTimings: "5:00 AM - 10:00 PM",
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 78,
    latitude: "22.2450",
    longitude: "76.1510",
  },
  {
    slug: "maheshwar-ghats-fort",
    name: "Maheshwar Ghats & Fort",
    state: "Madhya Pradesh",
    district: "Khargone",
    category: "heritage",
    placeType: "Riverfront Town",
    shortDescription: "Ahilya Bai Holkar's serene temple town on the Narmada, famed for its ghats and Maheshwari saris.",
    description: "The historic capital of the Holkar queen Ahilya Bai, Maheshwar charms with its riverfront fort, carved temples and stepped ghats descending to the Narmada. Boat rides at sunset reveal the town's silhouette, while local weavers still produce the celebrated Maheshwari handloom saris.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1300,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 66,
    latitude: "22.1770",
    longitude: "75.5850",
  },
  {
    slug: "rajwada-palace-indore",
    name: "Rajwada Palace, Indore",
    state: "Madhya Pradesh",
    district: "Indore",
    category: "heritage",
    placeType: "Palace",
    shortDescription: "Seven-storey Holkar palace blending Maratha, Mughal and French styles in the heart of Indore.",
    description: "Rajwada is the historic seven-storeyed palace of the Holkar dynasty, its lower floors in stone and upper floors in wood, mixing Maratha, Mughal and French influences. Overlooking a lively bazaar and the Krishnapura Chhatris, it lights up beautifully in the evenings and anchors old Indore's heritage circuit.",
    imageUrl: null,
    openingTimings: "10:00 AM - 6:00 PM (closed Mon)",
    entryFees: 20,
    budgetPerDay: 1500,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 64,
    latitude: "22.7177",
    longitude: "75.8545",
  },
  {
    slug: "lal-bagh-palace-indore",
    name: "Lal Bagh Palace, Indore",
    state: "Madhya Pradesh",
    district: "Indore",
    category: "heritage",
    placeType: "Palace Museum",
    shortDescription: "Grand European-style Holkar palace with a replica of Buckingham Palace's gates and ornate interiors.",
    description: "Lal Bagh Palace was the residence of the Holkar rulers and reflects their fascination with European royalty, from Baroque and Rococo interiors to entrance gates modelled on Buckingham Palace. Now a museum, it displays coins, weaponry, regal furniture and a grand ballroom with a spring-mounted dance floor.",
    imageUrl: null,
    openingTimings: "10:00 AM - 5:00 PM (closed Mon)",
    entryFees: 10,
    budgetPerDay: 1500,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 60,
    latitude: "22.6960",
    longitude: "75.8480",
  },
  {
    slug: "bhedaghat-marble-rocks",
    name: "Bhedaghat Marble Rocks & Dhuandhar Falls",
    state: "Madhya Pradesh",
    district: "Jabalpur",
    category: "adventure",
    placeType: "River Gorge & Waterfall",
    shortDescription: "Gleaming white marble cliffs along the Narmada with the roaring Dhuandhar waterfall and boat rides.",
    description: "At Bhedaghat the Narmada carves a gorge between towering white and pastel marble cliffs that shimmer under moonlight. Boat rides glide through the canyon, while nearby the river narrows and plunges as the thundering, mist-shrouded Dhuandhar ('smoke cascade') Falls. A cable car offers aerial views of both.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1300,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 72,
    latitude: "23.1290",
    longitude: "79.8000",
  },
  {
    slug: "amarkantak-narmada-source",
    name: "Amarkantak (Narmada Source)",
    state: "Madhya Pradesh",
    district: "Anuppur",
    category: "pilgrimage",
    placeType: "Pilgrimage Town",
    shortDescription: "Sacred Maikal-hills pilgrimage town at the source of the Narmada and Son rivers.",
    description: "Amarkantak, revered as 'Teerthraj' (king of pilgrimages), lies where the Maikal, Vindhya and Satpura ranges meet and is the source of the holy Narmada and Son rivers. The Narmada Kund temples, Kapildhara and Dugdhdhara waterfalls and cool forested surroundings make it both a spiritual and scenic retreat.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 2,
    bestMonths: "Jul,Aug,Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 58,
    latitude: "22.6720",
    longitude: "81.7550",
  },
  {
    slug: "datia-palace",
    name: "Datia Palace (Bir Singh Palace)",
    state: "Madhya Pradesh",
    district: "Datia",
    category: "heritage",
    placeType: "Palace",
    shortDescription: "A seven-storey Bundela palace built entirely without iron or wood, a masterpiece of Indo-Mughal design.",
    description: "Also called Satkhanda Palace, this seven-storeyed structure was raised by Raja Bir Singh Deo in the early 17th century using only stone and brick, without any iron or timber. Though never permanently occupied, its symmetrical halls, arches and rooftop pavilions are considered among the finest surviving Bundela buildings.",
    imageUrl: null,
    openingTimings: "9:00 AM - 5:00 PM",
    entryFees: 25,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 48,
    latitude: "25.6660",
    longitude: "78.4620",
  },
  {
    slug: "chanderi-fort-town",
    name: "Chanderi",
    state: "Madhya Pradesh",
    district: "Ashoknagar",
    category: "heritage",
    placeType: "Historic Town",
    shortDescription: "Hilltop fort town of Bundelkhand famed for its Sultanate monuments and gossamer Chanderi saris.",
    description: "Set among the Vindhya hills, Chanderi is a historic town dotted with the Koshak Mahal, Badal Mahal gate, Jama Masjid and the imposing Chanderi Fort. Long a centre of the handloom trade, it is equally renowned for its lightweight silk-and-cotton Chanderi saris still woven in the old quarters.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 25,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 50,
    latitude: "24.7130",
    longitude: "78.1370",
  },
  {
    slug: "chitrakoot-mp",
    name: "Chitrakoot (Madhya Pradesh)",
    state: "Madhya Pradesh",
    district: "Satna",
    category: "pilgrimage",
    placeType: "Pilgrimage Town",
    shortDescription: "Forest pilgrimage town on the Mandakini where Rama is believed to have spent much of his exile.",
    description: "Straddling the Madhya Pradesh–Uttar Pradesh border, Chitrakoot is sacred as the place where Rama, Sita and Lakshmana spent years of their exile. Ramghat aartis on the Mandakini, the Kamadgiri parikrama, Gupt Godavari caves and Sati Anusuya ashram draw pilgrims through its wooded, temple-strewn landscape.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 62,
    latitude: "25.2000",
    longitude: "80.8600",
  },
  {
    slug: "ghughua-fossil-park",
    name: "Ghughua Fossil National Park",
    state: "Madhya Pradesh",
    district: "Dindori",
    category: "heritage",
    placeType: "Fossil Park",
    shortDescription: "Open-air park preserving plant fossils around 65 million years old from the age of the dinosaurs.",
    description: "Ghughua Fossil Park protects a remarkable spread of petrified plant remains dating back some 65 million years, including fossilised palms, ferns and fruit. Walking trails and a small museum explain how this now-dry plateau once supported lush tropical forests, making it a rare geological attraction.",
    imageUrl: null,
    openingTimings: "9:00 AM - 5:00 PM",
    entryFees: 15,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 40,
    latitude: "22.9330",
    longitude: "80.7830",
  },

  // ─────────────────────────── CHHATTISGARH ───────────────────────────
  {
    slug: "chitrakote-falls",
    name: "Chitrakote Falls",
    state: "Chhattisgarh",
    district: "Bastar",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription: "The horseshoe-shaped 'Niagara of India' on the Indravati river, India's widest waterfall.",
    description: "Chitrakote is India's broadest waterfall, where the Indravati river plunges nearly 30 metres over a horseshoe cliff, roaring in the monsoon and fanning into gentler streams in winter. Boat rides approach the base of the falls, and evening lighting adds to the spectacle in this scenic corner of Bastar.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 10,
    budgetPerDay: 1400,
    recommendedDays: 1,
    bestMonths: "Aug,Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 74,
    latitude: "19.2010",
    longitude: "81.6980",
  },
  {
    slug: "tirathgarh-falls",
    name: "Tirathgarh Falls",
    state: "Chhattisgarh",
    district: "Bastar",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription: "A tiered milky-white cascade tumbling in steps within Kanger Valley National Park.",
    description: "Tirathgarh Falls drops in a series of milky-white cascades over roughly 90 metres of rock steps inside Kanger Valley National Park. Steps lead down to pools at various levels, and a small island shrine sits amid the streams, making it one of Bastar's most photogenic natural spots.",
    imageUrl: null,
    openingTimings: "8:00 AM - 5:00 PM",
    entryFees: 25,
    budgetPerDay: 1300,
    recommendedDays: 1,
    bestMonths: "Aug,Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 58,
    latitude: "18.8330",
    longitude: "81.9160",
  },
  {
    slug: "kanger-valley-national-park",
    name: "Kanger Valley National Park",
    state: "Chhattisgarh",
    district: "Bastar",
    category: "wildlife",
    placeType: "National Park",
    shortDescription: "Biodiverse Bastar park famed for the Kutumsar limestone caves and the Kailash cave formations.",
    description: "Kanger Valley protects dense tropical forest along the Kanger river and is prized for its underground wonders — the long, dark Kutumsar Cave and the stalactite-filled Kailash and Dandak caves. Above ground it shelters the state bird Bastar hill myna, along with tigers, leopards and rich birdlife, plus Tirathgarh Falls.",
    imageUrl: null,
    openingTimings: "8:00 AM - 5:00 PM (closed monsoon)",
    entryFees: 100,
    budgetPerDay: 1500,
    recommendedDays: 2,
    bestMonths: "Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 56,
    latitude: "18.8500",
    longitude: "81.9500",
  },
  {
    slug: "barnawapara-wildlife-sanctuary",
    name: "Barnawapara Wildlife Sanctuary",
    state: "Chhattisgarh",
    district: "Baloda Bazar",
    category: "wildlife",
    placeType: "Wildlife Sanctuary",
    shortDescription: "Central Chhattisgarh sanctuary of teak and bamboo forest with bison, leopards and sloth bears.",
    description: "Barnawapara is an accessible sanctuary set amid teak, sal and bamboo forest, offering jeep safaris to spot gaur (bison), leopards, sloth bears, wild dogs, deer and abundant birdlife. Its gentle terrain and eco-lodges make it a good introduction to Chhattisgarh's wilderness.",
    imageUrl: null,
    openingTimings: "Safari: 6:00 AM - 10:00 AM, 3:00 PM - 6:00 PM (closed Jul-Oct)",
    entryFees: 100,
    budgetPerDay: 1700,
    recommendedDays: 2,
    bestMonths: "Nov,Dec,Jan,Feb,Mar,Apr",
    isHidden: true,
    popularity: 48,
    latitude: "21.3660",
    longitude: "82.3660",
  },
  {
    slug: "sirpur-heritage-site",
    name: "Sirpur Archaeological Site",
    state: "Chhattisgarh",
    district: "Mahasamund",
    category: "heritage",
    placeType: "Archaeological Site",
    shortDescription: "Ancient capital on the Mahanadi with the brick Laxman Temple and Buddhist-Hindu-Jain ruins.",
    description: "Once a flourishing capital of the Sarabhapuriya and Panduvamshi kings, Sirpur preserves a wealth of 6th–8th century monuments on the banks of the Mahanadi. The finely carved brick Laxman Temple is its jewel, surrounded by excavated Buddhist viharas, Hindu shrines and Jain relics that reveal a great early trading and monastic town.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 25,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 46,
    latitude: "21.3400",
    longitude: "82.1830",
  },
  {
    slug: "mahant-ghasidas-museum-raipur",
    name: "Mahant Ghasidas Memorial Museum, Raipur",
    state: "Chhattisgarh",
    district: "Raipur",
    category: "heritage",
    placeType: "Museum",
    shortDescription: "Chhattisgarh's oldest museum, rich in tribal art, sculptures, coins and natural-history exhibits.",
    description: "Established in 1875, the Mahant Ghasidas Memorial Museum in Raipur is the state's oldest and displays archaeological sculptures, inscriptions, coins and an especially strong collection of Bastar tribal art, crafts and ethnographic material. It offers a fine introduction to Chhattisgarh's culture before exploring the interior.",
    imageUrl: null,
    openingTimings: "10:00 AM - 5:00 PM (closed Mon)",
    entryFees: 10,
    budgetPerDay: 1300,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 42,
    latitude: "21.2360",
    longitude: "81.6330",
  },
  {
    slug: "bhoramdeo-temple",
    name: "Bhoramdeo Temple",
    state: "Chhattisgarh",
    district: "Kabirdham",
    category: "heritage",
    placeType: "Temple",
    shortDescription: "An 11th-century Nagara temple of erotic and celestial carvings, dubbed the 'Khajuraho of Chhattisgarh'.",
    description: "Built by the Nagvanshi kings around the 11th century, the Bhoramdeo temple is a sandstone Shiva shrine covered in intricate sculptures of deities, dancers and amorous couples, earning it the nickname 'Khajuraho of Chhattisgarh'. It sits picturesquely at the foot of the Maikal hills near a lake and older brick and stone temples.",
    imageUrl: null,
    openingTimings: "6:00 AM - 7:00 PM",
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 52,
    latitude: "22.0450",
    longitude: "81.1830",
  },
  {
    slug: "danteshwari-temple-dantewada",
    name: "Danteshwari Temple, Dantewada",
    state: "Chhattisgarh",
    district: "Dantewada",
    category: "pilgrimage",
    placeType: "Shakti Peeth",
    shortDescription: "One of the 52 Shakti Peethas and the presiding deity of the Bastar royal family.",
    description: "The Danteshwari Temple at Dantewada is revered as one of the 52 Shakti Peethas and as the tutelary goddess of Bastar's former rulers. Built in the 14th century where two rivers meet, it is the spiritual heart of the region and the focus of Bastar's famous 75-day Dussehra festivities.",
    imageUrl: null,
    openingTimings: "6:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 50,
    latitude: "18.8990",
    longitude: "81.3510",
  },
  {
    slug: "rajim-kuleshwar-temple",
    name: "Rajim (Kuleshwar Mahadev Temple)",
    state: "Chhattisgarh",
    district: "Gariaband",
    category: "pilgrimage",
    placeType: "Pilgrimage Town",
    shortDescription: "Riverside pilgrimage town at a triple-river confluence, called the 'Prayag of Chhattisgarh'.",
    description: "Rajim stands at the confluence of the Mahanadi, Pairi and Sondur rivers and is known as the 'Prayag of Chhattisgarh'. The island Kuleshwar Mahadev temple, the ornate Rajivlochan Vishnu temple and the annual Rajim Kumbh Kalpa fair make it an important religious and cultural centre.",
    imageUrl: null,
    openingTimings: "6:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 44,
    latitude: "20.9660",
    longitude: "81.8760",
  },
  {
    slug: "mainpat-hill-station",
    name: "Mainpat Hill Station",
    state: "Chhattisgarh",
    district: "Surguja",
    category: "hill_station",
    placeType: "Hill Station",
    shortDescription: "Plateau retreat known as the 'Shimla of Chhattisgarh', with a Tibetan settlement and quicksand meadows.",
    description: "Mainpat is a cool, forested plateau in northern Chhattisgarh often called the 'Shimla of Chhattisgarh'. It is home to a resettled Tibetan community with colourful monasteries, along with the curious 'Ulta Pani' where water seems to flow uphill, jaljali quicksand meadows, and waterfalls set among rolling grasslands.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1300,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 46,
    latitude: "22.9500",
    longitude: "83.3660",
  },
  {
    slug: "achanakmar-tiger-reserve",
    name: "Achanakmar Tiger Reserve",
    state: "Chhattisgarh",
    district: "Mungeli",
    category: "wildlife",
    placeType: "Tiger Reserve",
    shortDescription: "Maikal-hills tiger reserve of dense sal forest, part of the Achanakmar-Amarkantak biosphere.",
    description: "Achanakmar lies in the Maikal range as part of a biosphere reserve linking it with Amarkantak. Its thick sal and bamboo forests along the Maniyari river shelter tigers, leopards, bison, wild dogs and flying squirrels, and its remote, hilly terrain makes for an off-beat safari experience.",
    imageUrl: null,
    openingTimings: "Safari: 6:00 AM - 11:00 AM, 3:00 PM - 6:00 PM (closed Jul-Sep)",
    entryFees: 150,
    budgetPerDay: 1800,
    recommendedDays: 2,
    bestMonths: "Nov,Dec,Jan,Feb,Mar,Apr",
    isHidden: true,
    popularity: 44,
    latitude: "22.4500",
    longitude: "81.7500",
  },
  {
    slug: "ratanpur-mahamaya-temple",
    name: "Mahamaya Temple, Ratanpur",
    state: "Chhattisgarh",
    district: "Bilaspur",
    category: "pilgrimage",
    placeType: "Shakti Peeth",
    shortDescription: "Ancient Shakti temple in the historic Kalchuri capital of Ratanpur, a revered Shakti Peeth.",
    description: "Ratanpur, once the capital of the Kalchuri kings, is famed for the Mahamaya Devi temple, counted among Chhattisgarh's most sacred Shakti shrines. The temple town also preserves old forts, tanks and temples, and comes alive during Navratri with thousands of pilgrims.",
    imageUrl: null,
    openingTimings: "5:00 AM - 9:00 PM",
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 42,
    latitude: "22.2900",
    longitude: "82.1660",
  },
  {
    slug: "dongargarh-bamleshwari-temple",
    name: "Maa Bamleshwari Temple, Dongargarh",
    state: "Chhattisgarh",
    district: "Rajnandgaon",
    category: "pilgrimage",
    placeType: "Hilltop Temple",
    shortDescription: "Hilltop goddess temple reached by ropeway or a long climb, a major Chhattisgarh pilgrimage.",
    description: "The Bamleshwari temple crowns a hill about 1,600 steps above Dongargarh town, though a ropeway now eases the ascent. Dedicated to the goddess Bamleshwari, it draws huge crowds during Navratri and offers panoramic views over the surrounding plains, with a second 'Chhoti Bamleshwari' shrine at the base.",
    imageUrl: null,
    openingTimings: "5:00 AM - 9:00 PM",
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 48,
    latitude: "21.1830",
    longitude: "80.7500",
  },

  // ─────────────────────────── BIHAR ───────────────────────────
  {
    slug: "nalanda-mahavihara-ruins",
    name: "Nalanda Mahavihara Ruins",
    state: "Bihar",
    district: "Nalanda",
    category: "heritage",
    placeType: "Ancient University",
    shortDescription: "UNESCO-listed ruins of the world's first great residential university, a Buddhist centre of learning.",
    description: "Nalanda was one of the world's earliest and greatest residential universities, flourishing from the 5th to 12th centuries and drawing scholars from across Asia. Its excavated red-brick monasteries, temples and the towering Sariputra Stupa spread over a vast complex, with the on-site museum displaying sculptures and relics recovered from the site.",
    imageUrl: null,
    openingTimings: "9:00 AM - 5:00 PM",
    entryFees: 25,
    budgetPerDay: 1300,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 82,
    latitude: "25.1360",
    longitude: "85.4436",
  },
  {
    slug: "rajgir-vishwa-shanti-stupa",
    name: "Rajgir (Vishwa Shanti Stupa & Ropeway)",
    state: "Bihar",
    district: "Nalanda",
    category: "pilgrimage",
    placeType: "Buddhist & Jain Site",
    shortDescription: "Hill-ringed ancient capital with a white peace pagoda, hot springs and Buddha's Gridhakuta hill.",
    description: "Rajgir, the first capital of the Magadha kingdom, is sacred to Buddhists and Jains alike. A chairlift ropeway climbs to the gleaming Vishwa Shanti Stupa on Ratnagiri hill, near the Gridhakuta peak where the Buddha preached. The town also has the warm Brahmakund springs, ancient cyclopean walls and the Son Bhandar caves.",
    imageUrl: null,
    openingTimings: "8:00 AM - 5:00 PM",
    entryFees: 0,
    budgetPerDay: 1400,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 74,
    latitude: "25.0270",
    longitude: "85.4200",
  },
  {
    slug: "nalanda-glory-of-hindu-university",
    name: "Nalanda Multimedia Museum & Hiuen Tsang Memorial",
    state: "Bihar",
    district: "Nalanda",
    category: "heritage",
    placeType: "Memorial & Museum",
    shortDescription: "Memorial hall honouring the Chinese pilgrim Xuanzang who studied at Nalanda, with relics and murals.",
    description: "The Xuanzang (Hiuen Tsang) Memorial Hall near the Nalanda ruins commemorates the 7th-century Chinese monk-scholar who studied and taught here for years and later documented the university. The pagoda-style hall displays a relic, murals of his journey and offers a quiet, reflective counterpoint to the excavations nearby.",
    imageUrl: null,
    openingTimings: "9:00 AM - 5:00 PM",
    entryFees: 20,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 48,
    latitude: "25.1400",
    longitude: "85.4470",
  },
  {
    slug: "vaishali-ashokan-pillar",
    name: "Vaishali (Ashokan Pillar & Relic Stupa)",
    state: "Bihar",
    district: "Vaishali",
    category: "heritage",
    placeType: "Ancient City",
    shortDescription: "Cradle of one of the world's first republics, with a complete Ashokan lion pillar and Buddha relic stupa.",
    description: "Vaishali is celebrated as the seat of one of the earliest republican assemblies and as the birthplace of Lord Mahavira. Its highlights include a well-preserved Ashokan pillar topped by a single lion, the Buddha relic stupa, the Kutagarasala Vihara and the modern Vishwa Shanti Stupa, marking sites where the Buddha preached.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 25,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 64,
    latitude: "25.9910",
    longitude: "85.1280",
  },
  {
    slug: "golghar-patna",
    name: "Golghar, Patna",
    state: "Bihar",
    district: "Patna",
    category: "heritage",
    placeType: "Historic Granary",
    shortDescription: "A giant beehive-shaped colonial granary of 1786 with spiral stairs and river views over Patna.",
    description: "Golghar is a huge domed granary built by the British in 1786 to store grain against famine, its 29-metre walls climbed by twin spiral staircases. Never actually filled to capacity, it now serves as a landmark and viewpoint, offering sweeping vistas of Patna and the Ganga from its summit.",
    imageUrl: null,
    openingTimings: "9:00 AM - 5:00 PM (closed Mon)",
    entryFees: 10,
    budgetPerDay: 1300,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 58,
    latitude: "25.6180",
    longitude: "85.1440",
  },
  {
    slug: "patna-museum",
    name: "Patna Museum (Jadu Ghar)",
    state: "Bihar",
    district: "Patna",
    category: "heritage",
    placeType: "Museum",
    shortDescription: "State museum famed for the Didarganj Yakshi and a collection spanning Mauryan art to natural history.",
    description: "The Patna Museum, locally called Jadu Ghar, houses one of India's finest collections of Mauryan and Gupta sculpture, most notably the polished sandstone Didarganj Yakshi. Its galleries range across bronzes, terracottas, coins, Tibetan thangkas, a casket said to hold Buddha relics and even fossils and a whale skeleton.",
    imageUrl: null,
    openingTimings: "10:30 AM - 5:00 PM (closed Mon)",
    entryFees: 15,
    budgetPerDay: 1300,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 56,
    latitude: "25.6130",
    longitude: "85.1420",
  },
  {
    slug: "takht-sri-patna-sahib",
    name: "Takht Sri Patna Sahib",
    state: "Bihar",
    district: "Patna",
    category: "pilgrimage",
    placeType: "Gurudwara",
    shortDescription: "Birthplace of Guru Gobind Singh and one of the five supreme seats of Sikh authority.",
    description: "Takht Sri Harmandir Ji, Patna Sahib, marks the birthplace of the tenth Sikh Guru, Gobind Singh, and is one of the five Takhts, the highest temporal seats of Sikhism. The domed white gurudwara preserves relics of the Guru and draws pilgrims from across the world, especially during Prakash Parv.",
    imageUrl: null,
    openingTimings: "4:00 AM - 9:00 PM",
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 66,
    latitude: "25.5960",
    longitude: "85.2200",
  },
  {
    slug: "mahavir-mandir-patna",
    name: "Mahavir Mandir, Patna",
    state: "Bihar",
    district: "Patna",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "One of India's busiest Hanuman temples, beside Patna Junction and famed for its Naivedyam laddoo.",
    description: "The Mahavir Mandir near Patna Junction is among the most visited Hanuman temples in North India, drawing enormous crowds especially on Tuesdays and during Ram Navami. Its trust runs major charitable hospitals, and the temple's tirupati-style Naivedyam laddoo prasad is famous across Bihar.",
    imageUrl: null,
    openingTimings: "5:00 AM - 10:00 PM",
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 62,
    latitude: "25.6020",
    longitude: "85.1390",
  },
  {
    slug: "vikramshila-ruins",
    name: "Vikramshila University Ruins",
    state: "Bihar",
    district: "Bhagalpur",
    category: "heritage",
    placeType: "Ancient University",
    shortDescription: "Ruins of a great Pala-era Buddhist university, a rival of Nalanda, centred on a cruciform stupa.",
    description: "Founded by the Pala king Dharmapala, Vikramshila was one of ancient India's two premier Buddhist universities alongside Nalanda, renowned for Tantric studies. The excavated site near the Ganga is dominated by a large cruciform brick stupa ringed by monastic cells, with a museum displaying recovered sculptures.",
    imageUrl: null,
    openingTimings: "9:00 AM - 5:00 PM",
    entryFees: 25,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 48,
    latitude: "25.3220",
    longitude: "87.2860",
  },
  {
    slug: "madhubani-mithila-art",
    name: "Madhubani (Mithila Painting Villages)",
    state: "Bihar",
    district: "Madhubani",
    category: "heritage",
    placeType: "Art & Cultural Town",
    shortDescription: "Home of the world-famous Madhubani (Mithila) folk painting tradition and Mithila cultural heritage.",
    description: "Madhubani gives its name to the vibrant Mithila style of folk painting, traditionally created by women on walls and floors and now on paper and cloth. Visiting artist villages such as Ranti and Jitwarpur lets travellers watch painters at work, buy directly, and explore the surrounding temples and ponds of the Mithila region.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 50,
    latitude: "26.3540",
    longitude: "86.0710",
  },
  {
    slug: "great-buddha-statue-bodhgaya",
    name: "Great Buddha Statue, Bodh Gaya",
    state: "Bihar",
    district: "Gaya",
    category: "pilgrimage",
    placeType: "Monument",
    shortDescription: "An 80-foot seated sandstone-and-red-granite Buddha, a serene landmark near the Mahabodhi temple.",
    description: "The Great Buddha Statue in Bodh Gaya rises about 25 metres in a meditative posture and was consecrated by the Dalai Lama in 1989. Built of red granite and sandstone over a hollow core, it is surrounded by gardens and smaller disciple statues, providing a tranquil complement to the many international monasteries nearby.",
    imageUrl: null,
    openingTimings: "7:00 AM - 6:00 PM",
    entryFees: 20,
    budgetPerDay: 1400,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 72,
    latitude: "24.6950",
    longitude: "84.9910",
  },
  {
    slug: "dungeshwari-cave-temples",
    name: "Dungeshwari Cave Temples",
    state: "Bihar",
    district: "Gaya",
    category: "pilgrimage",
    placeType: "Cave Temple",
    shortDescription: "Hillside caves where the Buddha is said to have practised severe austerities before Bodh Gaya.",
    description: "Also called the Mahakala caves, the Dungeshwari cave temples on a rocky hill near Bodh Gaya are believed to be where Prince Siddhartha undertook years of extreme fasting before rejecting austerity for the Middle Way. The caves hold Buddhist and Hindu shrines, including an emaciated Buddha image, amid quiet countryside.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 46,
    latitude: "24.7530",
    longitude: "85.0430",
  },
  {
    slug: "vishnupad-temple-gaya",
    name: "Vishnupad Temple, Gaya",
    state: "Bihar",
    district: "Gaya",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Riverside temple enshrining Vishnu's footprint, the focus of Gaya's ancestral Pitru Paksha rites.",
    description: "The Vishnupad Temple on the Falgu river marks a footprint said to be that of Lord Vishnu, imprinted in rock. Rebuilt by Rani Ahilya Bai Holkar in 1787, its octagonal tower dominates old Gaya. The site is central to Hindu shraddha rituals, drawing vast crowds during the annual Pitru Paksha to offer pind-daan for ancestors.",
    imageUrl: null,
    openingTimings: "6:00 AM - 9:00 PM",
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 60,
    latitude: "24.7770",
    longitude: "85.0010",
  },
  {
    slug: "kesaria-stupa",
    name: "Kesaria Stupa",
    state: "Bihar",
    district: "East Champaran",
    category: "heritage",
    placeType: "Buddhist Stupa",
    shortDescription: "One of the world's tallest and largest Buddhist stupas, marking where the Buddha gave away his begging bowl.",
    description: "The colossal Kesaria Stupa, excavated from a great earthen mound, is among the tallest and broadest Buddhist stupas known, its terraced brick structure rising in receding circular tiers. Tradition holds that the Buddha spent his last days here en route to Kushinagar and gave his alms bowl to the Licchavis of Vaishali.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 48,
    latitude: "26.3340",
    longitude: "84.8560",
  },
  {
    slug: "sher-shah-suri-tomb-sasaram",
    name: "Sher Shah Suri Tomb, Sasaram",
    state: "Bihar",
    district: "Rohtas",
    category: "heritage",
    placeType: "Mausoleum",
    shortDescription: "Majestic Afghan-style tomb of Sher Shah Suri rising from the centre of an artificial lake.",
    description: "The red-sandstone mausoleum of the great 16th-century ruler Sher Shah Suri stands on a stepped plinth in the middle of a large square tank, seeming to float on the water. Its harmonious blend of Afghan and Indian architecture and octagonal domed design make it one of the finest tombs of the pre-Mughal period.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 25,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 52,
    latitude: "24.9490",
    longitude: "84.0300",
  },
  {
    slug: "barabar-caves",
    name: "Barabar Caves",
    state: "Bihar",
    district: "Jehanabad",
    category: "heritage",
    placeType: "Rock-cut Caves",
    shortDescription: "The oldest surviving rock-cut caves in India, mirror-polished granite chambers from the Mauryan era.",
    description: "The Barabar and adjoining Nagarjuni hills hold India's earliest known rock-cut caves, carved from solid granite during Ashoka's reign for Ajivika ascetics. Chambers such as the Lomas Rishi and Sudama caves are famous for their astonishing mirror-like polished interiors and an arched doorway that inspired later cave architecture; the caves also feature in E. M. Forster's writing.",
    imageUrl: null,
    openingTimings: "6:00 AM - 5:00 PM",
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 46,
    latitude: "25.0050",
    longitude: "85.0630",
  },
  {
    slug: "pawapuri-jal-mandir",
    name: "Pawapuri Jal Mandir",
    state: "Bihar",
    district: "Nalanda",
    category: "pilgrimage",
    placeType: "Jain Temple",
    shortDescription: "White marble Jain temple set in a lotus lake, marking the site of Lord Mahavira's final liberation.",
    description: "Pawapuri, or Apapuri, is sacred to Jains as the place where the 24th Tirthankara, Lord Mahavira, attained nirvana and was cremated. The serene Jal Mandir, a marble temple, rises from the centre of a lotus-filled tank and is reached by a long causeway, making it one of the holiest Jain pilgrimage sites in India.",
    imageUrl: null,
    openingTimings: "5:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 50,
    latitude: "25.1650",
    longitude: "85.5030",
  },
  {
    slug: "valmiki-tiger-reserve",
    name: "Valmiki Tiger Reserve",
    state: "Bihar",
    district: "West Champaran",
    category: "wildlife",
    placeType: "Tiger Reserve",
    shortDescription: "Bihar's only tiger reserve, a Himalayan-foothill forest along the Nepal border and Gandak river.",
    description: "Valmiki Tiger Reserve, in the Terai forests of the Himalayan foothills bordering Nepal, is Bihar's sole tiger reserve. Its sal woods, grasslands and the Gandak river shelter tigers, leopards, wild elephants, rhinos on occasion, sloth bears and rich birdlife, with jeep safaris and the scenic Valmikinagar making it a rising eco-destination.",
    imageUrl: null,
    openingTimings: "Safari: 6:00 AM - 10:00 AM, 2:00 PM - 5:00 PM (closed Jul-Sep)",
    entryFees: 150,
    budgetPerDay: 1900,
    recommendedDays: 2,
    bestMonths: "Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 48,
    latitude: "27.3330",
    longitude: "84.1000",
  },
  {
    slug: "mundeshwari-temple",
    name: "Mundeshwari Devi Temple",
    state: "Bihar",
    district: "Kaimur",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Hilltop octagonal shrine often cited as one of India's oldest functioning Hindu temples.",
    description: "Perched on Mundeshwari hill, this octagonal stone temple dedicated to Devi and Shiva is regarded as among the oldest continuously worshipped Hindu temples in India, with inscriptions dating to the early centuries CE. Its unusual four-faced Shiva lingam that appears to change colour and its bloodless animal 'sacrifice' ritual draw devotees and historians alike.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 44,
    latitude: "25.0770",
    longitude: "83.5470",
  },
  {
    slug: "deo-surya-mandir",
    name: "Deo Sun Temple (Surya Mandir)",
    state: "Bihar",
    district: "Aurangabad",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Ancient sun temple and a major Chhath Puja pilgrimage site with unusual west-facing orientation.",
    description: "The Deo Surya Mandir is a centuries-old temple dedicated to the Sun god, distinctive for facing west rather than east. Built in the Nagara style, it becomes one of Bihar's most important pilgrimage centres during the Chhath festival, when hundreds of thousands gather to worship the setting and rising sun.",
    imageUrl: null,
    openingTimings: "5:00 AM - 9:00 PM",
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 42,
    latitude: "24.6580",
    longitude: "84.4340",
  },

  // ─────────────────────────── JHARKHAND ───────────────────────────
  {
    slug: "hundru-falls",
    name: "Hundru Falls",
    state: "Jharkhand",
    district: "Ranchi",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription: "The Subarnarekha river plunging about 98 metres over rocky steps, among Jharkhand's highest falls.",
    description: "Hundru Falls is one of Jharkhand's tallest waterfalls, where the Subarnarekha river drops roughly 98 metres over a series of dark rock ledges, forming pools popular for a dip in winter. A long flight of steps leads to viewpoints, and the surrounding rocky landscape is spectacular after the monsoon.",
    imageUrl: null,
    openingTimings: "8:00 AM - 5:00 PM",
    entryFees: 15,
    budgetPerDay: 1300,
    recommendedDays: 1,
    bestMonths: "Aug,Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 62,
    latitude: "23.4500",
    longitude: "85.6660",
  },
  {
    slug: "dassam-falls",
    name: "Dassam Falls",
    state: "Jharkhand",
    district: "Ranchi",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription: "The Kanchi river cascading in a broad curtain of ten streams near Ranchi.",
    description: "Dassam Falls, also spelt Dasam, is formed by the Kanchi river dropping about 44 metres in a wide sheet often described as ten streams, giving it its name. A scenic picnic spot near Ranchi, it is powerful in the monsoon; visitors are cautioned against swimming due to strong currents at the base.",
    imageUrl: null,
    openingTimings: "8:00 AM - 5:00 PM",
    entryFees: 15,
    budgetPerDay: 1300,
    recommendedDays: 1,
    bestMonths: "Aug,Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 54,
    latitude: "23.1450",
    longitude: "85.4660",
  },
  {
    slug: "jonha-falls",
    name: "Jonha Falls (Gautamdhara)",
    state: "Jharkhand",
    district: "Ranchi",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription: "A picturesque hanging-valley waterfall near Ranchi with a hillside Buddhist shrine.",
    description: "Jonha Falls, also known as Gautamdhara, is a classic hanging-valley cascade where the Raru river leaps some 43 metres into a deep gorge. A long stairway descends to the pool, and a small temple on the hill lends the spot its association with Gautam Buddha, set amid tranquil forest scenery.",
    imageUrl: null,
    openingTimings: "8:00 AM - 5:00 PM",
    entryFees: 15,
    budgetPerDay: 1300,
    recommendedDays: 1,
    bestMonths: "Aug,Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 50,
    latitude: "23.3410",
    longitude: "85.6110",
  },
  {
    slug: "jagannath-temple-ranchi",
    name: "Jagannath Temple, Ranchi",
    state: "Jharkhand",
    district: "Ranchi",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "A 17th-century hilltop temple modelled on Puri's Jagannath shrine, hosting Ranchi's Rath Yatra.",
    description: "Built in 1691 atop a small hill, Ranchi's Jagannath Temple echoes the architecture of the famous Puri temple and offers panoramic views of the city. It is the focus of a colourful annual Rath Yatra chariot festival that draws large crowds, and its calm hilltop setting is popular at sunset.",
    imageUrl: null,
    openingTimings: "5:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 48,
    latitude: "23.3210",
    longitude: "85.2760",
  },
  {
    slug: "baidyanath-dham-deoghar",
    name: "Baidyanath Dham, Deoghar",
    state: "Jharkhand",
    district: "Deoghar",
    category: "pilgrimage",
    placeType: "Jyotirlinga Temple",
    shortDescription: "One of the twelve Jyotirlingas of Shiva and a major Shakti Peeth, thronged during the Shravani Mela.",
    description: "Baba Baidyanath Dham at Deoghar enshrines one of the twelve sacred Jyotirlingas and is also revered as a Shakti Peeth, making it doubly holy. During the month-long Shravani Mela, millions of saffron-clad kanwariyas walk over 100 kilometres from Sultanganj carrying Ganga water to offer at the temple.",
    imageUrl: null,
    openingTimings: "4:00 AM - 9:00 PM",
    entryFees: 0,
    budgetPerDay: 1300,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 78,
    latitude: "24.4920",
    longitude: "86.7000",
  },
  {
    slug: "trikut-pahar-deoghar",
    name: "Trikut Pahar (Trikutachal), Deoghar",
    state: "Jharkhand",
    district: "Deoghar",
    category: "adventure",
    placeType: "Hill & Ropeway",
    shortDescription: "Three-peaked hill near Deoghar with one of India's highest vertical ropeways and a hilltop ashram.",
    description: "Trikut Pahar, named for its three prominent peaks, rises near Deoghar and is famed for its ropeway, among the highest vertical cable cars in India. The hill offers sweeping views, rock-climbing, a Dayanand ashram and the Trikutachal Mahadeva temple, making it a favourite outing from the pilgrimage town.",
    imageUrl: null,
    openingTimings: "8:00 AM - 5:00 PM",
    entryFees: 30,
    budgetPerDay: 1300,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 50,
    latitude: "24.5330",
    longitude: "86.8330",
  },
  {
    slug: "basukinath-temple",
    name: "Basukinath Temple",
    state: "Jharkhand",
    district: "Dumka",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Revered Shiva temple near Deoghar, an essential stop on the Shravani Mela kanwar pilgrimage.",
    description: "Basukinath, about 40 kilometres from Deoghar, is a major Shiva temple where the presiding Basukinath (Nag) and Parvati shrines face each other. Considered the 'court' where devotees' pleas are heard, it is an indispensable part of the Shravani Mela circuit, drawing pilgrims who first visit Baidyanath Dham.",
    imageUrl: null,
    openingTimings: "4:00 AM - 9:00 PM",
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 46,
    latitude: "24.3900",
    longitude: "87.0800",
  },
  {
    slug: "netarhat-hill-station",
    name: "Netarhat Hill Station",
    state: "Jharkhand",
    district: "Latehar",
    category: "hill_station",
    placeType: "Hill Station",
    shortDescription: "The 'Queen of Chotanagpur', a plateau retreat famed for sublime sunrise and sunset viewpoints.",
    description: "Netarhat, the 'Queen of Chotanagpur', is Jharkhand's premier hill station, set on a forested plateau around 1,100 metres high. Visitors gather at the Magnolia Sunset Point and the sunrise point for spectacular views, and explore the nearby Lower and Upper Ghaghri waterfalls and pine-clad ridges in cool, quiet surroundings.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1400,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar,Apr",
    isHidden: false,
    popularity: 60,
    latitude: "23.4720",
    longitude: "84.2660",
  },
  {
    slug: "betla-national-park",
    name: "Betla National Park",
    state: "Jharkhand",
    district: "Latehar",
    category: "wildlife",
    placeType: "Tiger Reserve",
    shortDescription: "Part of Palamu Tiger Reserve, one of India's first tiger reserves, set among sal forests and old forts.",
    description: "Betla, within the Palamu Tiger Reserve, was among the nine original reserves created under Project Tiger and holds the distinction of an early tiger census by pugmark counting. Its sal and bamboo forests shelter elephants, tigers, leopards, gaur and deer, while the crumbling Palamu forts add historic intrigue to jeep safaris.",
    imageUrl: null,
    openingTimings: "Safari: 6:00 AM - 10:00 AM, 3:00 PM - 5:30 PM (closed monsoon)",
    entryFees: 100,
    budgetPerDay: 1800,
    recommendedDays: 2,
    bestMonths: "Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 54,
    latitude: "23.8830",
    longitude: "84.1910",
  },
  {
    slug: "parasnath-hill-shikharji",
    name: "Parasnath Hill (Shikharji)",
    state: "Jharkhand",
    district: "Giridih",
    category: "pilgrimage",
    placeType: "Jain Pilgrimage",
    shortDescription: "Jharkhand's highest peak and the holiest Jain tirtha, where twenty Tirthankaras attained liberation.",
    description: "Parasnath Hill, or Shikharji, rises to about 1,365 metres as the highest point in Jharkhand and the most sacred Jain pilgrimage site, believed to be where twenty of the twenty-four Tirthankaras attained moksha. Devout pilgrims undertake a strenuous circuit of hilltop shrines, often barefoot, through beautiful forested slopes.",
    imageUrl: null,
    openingTimings: "4:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1300,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 64,
    latitude: "23.9630",
    longitude: "86.1330",
  },
  {
    slug: "hazaribagh-wildlife-sanctuary",
    name: "Hazaribagh Wildlife Sanctuary",
    state: "Jharkhand",
    district: "Hazaribagh",
    category: "wildlife",
    placeType: "Wildlife Sanctuary",
    shortDescription: "Plateau sanctuary of forested hills, lakes and grasslands with sambar, nilgai and rich birdlife.",
    description: "Set on the Chotanagpur plateau near the town of Hazaribagh ('a thousand gardens'), this sanctuary of undulating sal forest, meadows and water bodies shelters sambar, nilgai, wild boar, leopards and abundant birds. Nearby Hazaribagh Lake and Canary Hill viewpoint make the cool, scenic area a pleasant getaway.",
    imageUrl: null,
    openingTimings: "6:00 AM - 5:00 PM",
    entryFees: 50,
    budgetPerDay: 1500,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 46,
    latitude: "24.0300",
    longitude: "85.4160",
  },
  {
    slug: "rajrappa-chhinnamasta-temple",
    name: "Rajrappa (Chhinnamasta Temple)",
    state: "Jharkhand",
    district: "Ramgarh",
    category: "pilgrimage",
    placeType: "Shakti Temple",
    shortDescription: "Tantric Shakti temple of the headless goddess Chhinnamasta at the meeting of the Bhairavi and Damodar rivers.",
    description: "Rajrappa is a renowned Tantric shrine dedicated to the fierce goddess Chhinnamasta, depicted holding her own severed head. It stands dramatically where the Bhairavi (Bhera) river tumbles as a small waterfall into the Damodar, and its animal-sacrifice traditions and riverside setting draw pilgrims from across eastern India.",
    imageUrl: null,
    openingTimings: "5:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 48,
    latitude: "23.6330",
    longitude: "85.7160",
  },
  {
    slug: "jubilee-park-jamshedpur",
    name: "Jubilee Park, Jamshedpur",
    state: "Jharkhand",
    district: "East Singhbhum",
    category: "heritage",
    placeType: "Urban Park",
    shortDescription: "Sprawling Mughal-garden-style park gifted to Jamshedpur by Tata Steel, with fountains and a zoo.",
    description: "Jubilee Park is a vast landscaped garden in the planned steel city of Jamshedpur, presented to residents on Tata Steel's golden jubilee. Inspired by Mysore's Brindavan Gardens, it features musical fountains, rose gardens, a lake, an amusement zone and the Tata Zoological Park, lit up spectacularly on Founder's Day.",
    imageUrl: null,
    openingTimings: "5:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 1300,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 52,
    latitude: "22.8000",
    longitude: "86.1830",
  },
  {
    slug: "dalma-wildlife-sanctuary",
    name: "Dalma Wildlife Sanctuary",
    state: "Jharkhand",
    district: "East Singhbhum",
    category: "wildlife",
    placeType: "Wildlife Sanctuary",
    shortDescription: "Elephant sanctuary on forested hills above Jamshedpur, with viewpoints and trekking trails.",
    description: "Dalma Wildlife Sanctuary crowns the Dalma hills overlooking Jamshedpur and is best known as an elephant reserve on a major migration route. Its slopes of dry deciduous forest also shelter sloth bears, barking deer, leopards and porcupines, and a road to the hilltop offers trekking, a Shiva temple and fine views.",
    imageUrl: null,
    openingTimings: "6:00 AM - 5:00 PM",
    entryFees: 50,
    budgetPerDay: 1400,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 46,
    latitude: "22.8660",
    longitude: "86.2160",
  },
  {
    slug: "patratu-valley",
    name: "Patratu Valley",
    state: "Jharkhand",
    district: "Ramgarh",
    category: "adventure",
    placeType: "Scenic Valley",
    shortDescription: "Winding ghat road with hairpin bends overlooking a reservoir, a favourite Ranchi-area drive.",
    description: "Patratu Valley is famed for its serpentine ghat road of dramatic hairpin bends descending toward the Patratu Dam reservoir. The viewpoints along the route offer sweeping vistas of the lake ringed by hills, and the area has developed into a popular weekend destination for drives, boating and lakeside resorts near Ranchi.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1400,
    recommendedDays: 1,
    bestMonths: "Aug,Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 56,
    latitude: "23.6330",
    longitude: "85.2830",
  },
  {
    slug: "maithon-dam",
    name: "Maithon Dam",
    state: "Jharkhand",
    district: "Dhanbad",
    category: "adventure",
    placeType: "Dam & Reservoir",
    shortDescription: "Large Damodar Valley reservoir with boating, an island temple and an underground power station.",
    description: "Maithon Dam on the Barakar river is a major Damodar Valley Corporation reservoir and one of the region's biggest, notable for having Asia's first underground hydel power station. Its expansive lake dotted with islands offers boating and birdwatching, and the Kalyaneshwari temple nearby draws pilgrims.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 10,
    budgetPerDay: 1300,
    recommendedDays: 1,
    bestMonths: "Aug,Sep,Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 44,
    latitude: "23.7830",
    longitude: "86.8160",
  },
  {
    slug: "lodh-falls",
    name: "Lodh Falls (Budha Ghagh)",
    state: "Jharkhand",
    district: "Latehar",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription: "Jharkhand's highest waterfall, where the Burha river plunges about 143 metres in a forest gorge.",
    description: "Lodh Falls, also called Budha Ghagh, is the tallest waterfall in Jharkhand, where the Burha river drops around 143 metres into a mist-filled gorge, its roar audible from a distance. Set in dense forest near Netarhat, it is at its thunderous best during and just after the monsoon.",
    imageUrl: null,
    openingTimings: "8:00 AM - 5:00 PM",
    entryFees: 0,
    budgetPerDay: 1400,
    recommendedDays: 1,
    bestMonths: "Aug,Sep,Oct,Nov,Dec,Jan",
    isHidden: true,
    popularity: 48,
    latitude: "23.4830",
    longitude: "84.0660",
  },
  {
    slug: "mccluskieganj",
    name: "McCluskieganj",
    state: "Jharkhand",
    district: "Ranchi",
    category: "heritage",
    placeType: "Heritage Village",
    shortDescription: "A former Anglo-Indian colony of old bungalows amid forests, a nostalgic offbeat retreat near Ranchi.",
    description: "McCluskieganj was founded in the 1930s as a homeland for the Anglo-Indian community, and its scattered colonial bungalows, churches and cemeteries still evoke that bygone era. Set among sal forests and low hills, the quiet village has become an offbeat getaway, inspiring literature and drawing travellers seeking heritage and calm.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 40,
    latitude: "23.6160",
    longitude: "84.9660",
  },
];
