import type { NewDestination } from "../schema";

// Karnataka — supplementary catalogue (additional places beyond the main 294)
export const karnatakaExtraDestinations: Omit<NewDestination, "id" | "createdAt">[] = [
  // ——— Forts & hill forts ———
  {
    slug: "devanahalli-fort",
    name: "Devanahalli Fort",
    state: "Karnataka",
    district: "Bengaluru Rural",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Oval stone fort near Bengaluru airport, the birthplace of Tipu Sultan, ringed by bastions and old temples.",
    description: "This 16th-century mud-and-stone fort, later strengthened by the Wodeyars and Hyder Ali, is best known as the birthplace of Tipu Sultan. Within its ramparts stand the Venugopalaswamy and Nanjundeshwara temples with fine carvings. The walls, gateways and semicircular bastions can be walked in about an hour.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Devanahalli_fort_entrance_2007.jpg/1280px-Devanahalli_fort_entrance_2007.jpg",
    openingTimings: "9:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 58,
    latitude: "13.2496161",
    longitude: "77.7083876",
  },
  {
    slug: "manjarabad-fort",
    name: "Manjarabad Fort",
    state: "Karnataka",
    district: "Hassan",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Star-shaped hill fort built by Tipu Sultan near Sakleshpur, laid out on a French Vauban plan.",
    description: "Built by Tipu Sultan in 1792, this fort has a distinctive eight-pointed star shape inspired by European Vauban-style military architecture. A short flight of steps leads up to ramparts that command sweeping views of the Western Ghats. There is a central water tank and storerooms once used to hold arms and provisions.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Manjarabad_Fort_2.jpg/1280px-Manjarabad_Fort_2.jpg",
    openingTimings: "9:00 AM - 5:30 PM",
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 62,
    latitude: "12.9556",
    longitude: "75.7361",
  },
  {
    slug: "hutridurga-fort-trek",
    name: "Hutridurga",
    state: "Karnataka",
    district: "Tumakuru",
    category: "adventure",
    placeType: "Hill Fort",
    shortDescription: "One of the Nine Durgas (Navadurga) hill forts near Kunigal, with layered gateways and a Shiva temple at the top.",
    description: "Hutridurga is a granite hill fort of the Kunigal region, one of the Navadurga forts fortified during the Hyder Ali and Tipu Sultan era. The moderate trek climbs past successive fortified gateways to a summit crowned by a Someshwara temple. Boulder-strewn slopes and wide plateau views reward the climb.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 40,
    latitude: "12.9333",
    longitude: "77.1000",
  },
  {
    slug: "huliyurdurga-hill",
    name: "Huliyurdurga",
    state: "Karnataka",
    district: "Tumakuru",
    category: "adventure",
    placeType: "Hill Fort",
    shortDescription: "Steep monolithic hill and old fort near Kunigal with a hilltop temple and panoramic plateau views.",
    description: "Huliyurdurga is a towering monolith topped by remnants of a hill fort and a small temple. The climb involves rock steps and some scrambling before opening to wide views over the surrounding plains. It was a strategic outpost in the region's chain of granite hill forts.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 36,
    latitude: "12.8500",
    longitude: "77.0333",
  },
  {
    slug: "channarayana-durga-fort",
    name: "Channarayana Durga",
    state: "Karnataka",
    district: "Tumakuru",
    category: "adventure",
    placeType: "Hill Fort",
    shortDescription: "Ruined hilltop fortress near Madhugiri with multiple gateways, granaries and temple ruins on a rocky massif.",
    description: "Channarayana Durga is a crumbling hill fort built by the Palegars and later held by Marathas, Hyder Ali and the British. The climb passes several stone doorways, water cisterns and old granaries to reach ruins scattered across the summit. It sees few visitors, making it a quiet spot for history and boulder scenery.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Channarayanadurga1.jpg/1280px-Channarayanadurga1.jpg",
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 34,
    latitude: "13.5500",
    longitude: "77.1667",
  },
  {
    slug: "nagara-bidanur-fort",
    name: "Nagara Fort (Bidanur)",
    state: "Karnataka",
    district: "Shivamogga",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Former Keladi Nayaka capital fort at Nagara near Hosanagara, set amid the Malnad hills.",
    description: "Nagara, once called Bidanur, served as a capital of the Keladi Nayakas before falling to Hyder Ali. The fort retains moats, ramparts, a palace mound and the nearby Neelakanteshwara temple and Devaganga tank. It lies in lush Malnad country close to the Western Ghats.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Nagara_Fort.jpg/1280px-Nagara_Fort.jpg",
    openingTimings: "9:00 AM - 5:30 PM",
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 42,
    latitude: "13.8209168",
    longitude: "75.035713",
  },

  // ——— Hoysala & Chalukyan temples ———
  {
    slug: "doddagaddavalli-lakshmi-temple",
    name: "Doddagaddavalli Lakshmi Devi Temple",
    state: "Karnataka",
    district: "Hassan",
    category: "heritage",
    placeType: "Temple",
    shortDescription: "Early 12th-century Hoysala temple near Hassan, a rare chatushkuta (four-shrine) plan dedicated to Lakshmi.",
    description: "Built around 1114 CE, this is one of the earliest known Hoysala temples, notable for its four shrines opening onto a common hall. The soapstone structure has stark, austere carvings and corner towers, with a small Bhairava shrine guarding a corner. It sits beside a tank in a quiet village setting.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/1113_CE_Lakshmi_Devi_temple%2C_Doddagaddavalli_Karnataka.jpg/1280px-1113_CE_Lakshmi_Devi_temple%2C_Doddagaddavalli_Karnataka.jpg",
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 44,
    latitude: "13.0958987",
    longitude: "76.00405599999999",
  },
  {
    slug: "koravangala-bucheshwara-temple",
    name: "Koravangala Bucheshwara Temple",
    state: "Karnataka",
    district: "Hassan",
    category: "heritage",
    placeType: "Temple",
    shortDescription: "12th-century Hoysala twin-shrine temple near Hassan with finely lathe-turned pillars and star-shaped plan.",
    description: "The Bucheshwara temple at Koravangala, built in 1173 CE, is a dvikuta (two-shrine) Hoysala monument dedicated to Shiva. It features intricately turned pillars, perforated stone screens and detailed wall friezes. It is one of the lesser-visited gems of Hoysala craftsmanship near Hassan.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 38,
    latitude: "13.0167",
    longitude: "76.1833",
  },
  {
    slug: "nuggehalli-lakshminarasimha-temple",
    name: "Nuggehalli Lakshminarasimha Temple",
    state: "Karnataka",
    district: "Hassan",
    category: "heritage",
    placeType: "Temple",
    shortDescription: "13th-century Hoysala trikuta temple at Nuggehalli famed for sculptures by the master Baichoja.",
    description: "Consecrated around 1246 CE, this three-shrine Hoysala temple honours Lakshminarasimha and is celebrated for exquisite images of Vishnu, Venugopala and Yoga-Narasimha. Several figures bear the signature of the sculptor Baichoja. The village also holds a Sadashiva temple of the same period.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Lakshmi_Narasimha_temple_at_Nuggehalli.JPG/1280px-Lakshmi_Narasimha_temple_at_Nuggehalli.JPG",
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 40,
    latitude: "13.0109318",
    longitude: "76.475191",
  },
  {
    slug: "aralaguppe-chennakeshava-temple",
    name: "Aralaguppe Chennakeshava Temple",
    state: "Karnataka",
    district: "Tumakuru",
    category: "heritage",
    placeType: "Temple",
    shortDescription: "Compact Hoysala temple at Aralaguppe on a raised star-shaped platform with an ornate ceiling and Kalleshwara temple nearby.",
    description: "The Chennakeshava temple at Aralaguppe is a small but richly carved Hoysala shrine set on a jagati platform. Its interior boasts a superb domical ceiling and finely detailed deity panels. The same village also has the older Nolamba-period Kalleshwara temple with a striking Nataraja ceiling.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/cf/Chennakeshava_temple_at_Aralaguppe.jpg",
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 37,
    latitude: "13.2516041",
    longitude: "76.6145548",
  },
  {
    slug: "govindanahalli-panchalingeshwara-temple",
    name: "Govindanahalli Panchalingeshwara Temple",
    state: "Karnataka",
    district: "Mandya",
    category: "heritage",
    placeType: "Temple",
    shortDescription: "Rare five-shrine (panchakuta) Hoysala temple near Krishnarajpet, aligned in a row under a single hall.",
    description: "Built around 1238 CE, this unusual Hoysala temple has five Shiva shrines arranged side by side sharing a common pillared hall. The lathe-turned pillars and lintel carvings are typical of the dynasty's fine soapstone work. Its five-shrine layout makes it one of the most distinctive Hoysala plans.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Panchlingeshvara_temple_at_Govindanahalli_-_north_western_view.jpg/1280px-Panchlingeshvara_temple_at_Govindanahalli_-_north_western_view.jpg",
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 35,
    latitude: "12.7739261",
    longitude: "76.3915707",
  },
  {
    slug: "basaralu-mallikarjuna-temple",
    name: "Basaralu Mallikarjuna Temple",
    state: "Karnataka",
    district: "Mandya",
    category: "heritage",
    placeType: "Temple",
    shortDescription: "13th-century Hoysala temple near Nagamangala with a star-shaped plan and dramatic wall sculptures.",
    description: "The Mallikarjuna temple at Basaralu, built around 1234 CE, is an ekakuta Hoysala shrine noted for vivid narrative reliefs, including scenes of Ravana, Bhima and the goddess Durga. Its walls carry rows of finely carved deities beneath a well-preserved tower. It is a compact but rewarding stop for Hoysala art.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Mallikarjuna_Temple_at_Basaral.jpg/1280px-Mallikarjuna_Temple_at_Basaral.jpg",
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 36,
    latitude: "12.7333",
    longitude: "76.7500",
  },
  {
    slug: "turuvekere-chennakeshava-temple",
    name: "Turuvekere Chennakeshava Temple",
    state: "Karnataka",
    district: "Tumakuru",
    category: "heritage",
    placeType: "Temple",
    shortDescription: "Hoysala-era temple town near Tumakuru with the Chennakeshava and Moole Shankareshwara temples and a bronze bell.",
    description: "Turuvekere preserves a cluster of Hoysala temples, chief among them the Chennakeshava shrine with its ornate lathe-turned pillars. The nearby Moole Shankareshwara temple is famous for a large bronze Nandi and a metal bell that rings with a long resonance. The compact town rewards a short heritage walk.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Chennakeshava_temple_at_Turuvekere%2CTumkur_district.JPG/1280px-Chennakeshava_temple_at_Turuvekere%2CTumkur_district.JPG",
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 34,
    latitude: "13.1667",
    longitude: "76.6500",
  },
  {
    slug: "hulikere-kalyani-halebidu",
    name: "Hulikere Kalyani",
    state: "Karnataka",
    district: "Hassan",
    category: "heritage",
    placeType: "Stepwell",
    shortDescription: "Hoysala-era stepped temple tank near Halebidu ringed by dozens of miniature shrines in its recessed walls.",
    description: "Hulikere Kalyani is a beautifully proportioned Hoysala stepwell close to Halebidu, its terraced stone banks lined with rows of small shrine niches. Once serving the temples of the old capital, the tranquil tank reflects the surrounding greenery. It is an atmospheric and uncrowded detour from the main Halebidu circuit.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/cc/Halebidu_monuments_map%2C_1930_survey%2C_the_Dorasamudra_of_Hoysala_dynasty.jpg",
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 41,
    latitude: "13.2000",
    longitude: "75.9833",
  },
  {
    slug: "arasikere-ishwara-temple",
    name: "Arasikere Ishwara Temple",
    state: "Karnataka",
    district: "Hassan",
    category: "heritage",
    placeType: "Temple",
    shortDescription: "Hoysala temple at Arasikere with an unusual 16-pointed star hall and one of the most complex Hoysala vimanas.",
    description: "The Ishwara (Chandramouleshwara) temple at Arasikere, built around 1220 CE, is admired for its intricate stellate mantapa and a highly complex vimana plan. Its ceiling and pillar work are among the finest experiments in Hoysala geometry. The temple stands quietly within the town.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Le_temple_Kalameshwara_%28Arsikere%2C_Inde%29_%2814571148061%29.jpg/1280px-Le_temple_Kalameshwara_%28Arsikere%2C_Inde%29_%2814571148061%29.jpg",
    openingTimings: "7:00 AM - 7:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 37,
    latitude: "13.3184313",
    longitude: "76.2600033",
  },
  {
    slug: "javagal-lakshminarasimha-temple",
    name: "Javagal Lakshminarasimha Temple",
    state: "Karnataka",
    district: "Hassan",
    category: "heritage",
    placeType: "Temple",
    shortDescription: "13th-century Hoysala trikuta temple at Javagal with crisply carved wall images of Vishnu's forms.",
    description: "The Lakshminarasimha temple at Javagal is a three-shrine Hoysala monument with detailed exterior friezes and well-preserved deity sculptures of Vishnu, Narasimha and Venugopala. Its outer walls carry the layered horizontal bands typical of mature Hoysala design. It remains an offbeat stop near Arsikere.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Sri_LakshmiNarasimha_Temple_-_Javagal_West_Side_View.jpg/1280px-Sri_LakshmiNarasimha_Temple_-_Javagal_West_Side_View.jpg",
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 34,
    latitude: "13.3009787",
    longitude: "76.059912",
  },
  {
    slug: "kambadahalli-panchakuta-basadi",
    name: "Kambadahalli Panchakuta Basadi",
    state: "Karnataka",
    district: "Mandya",
    category: "heritage",
    placeType: "Jain Temple",
    shortDescription: "Ganga-period Jain temple complex near Nagamangala with five shrines and a tall monolithic pillar.",
    description: "The Panchakuta Basadi at Kambadahalli is a group of Jain temples from the Western Ganga era dedicated to the Tirthankaras. The complex is noted for its refined dravidian towers and a free-standing brahmadeva pillar. It is one of southern Karnataka's most important early Jain sites.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Panchakuta_Basadi_%2810th_century_AD%29_at_Kambadahalli.JPG/1280px-Panchakuta_Basadi_%2810th_century_AD%29_at_Kambadahalli.JPG",
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 38,
    latitude: "12.8677387",
    longitude: "76.6335998",
  },
  {
    slug: "hosaholalu-lakshminarayana-temple",
    name: "Hosaholalu Lakshminarayana Temple",
    state: "Karnataka",
    district: "Mandya",
    category: "heritage",
    placeType: "Temple",
    shortDescription: "Well-preserved 13th-century Hoysala temple near Krishnarajpet with continuous bands of wall sculpture.",
    description: "The Lakshminarayana temple at Hosaholalu, built around 1250 CE, is prized for its intact star-shaped plan and unbroken rows of finely carved deities and epic scenes along the outer walls. The soapstone friezes are among the best preserved of the late Hoysala style. It is a compact single-shrine gem.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Lakshminayarana_Temple_%2C_Hosaholalu%2C_South_West_View.jpg/1280px-Lakshminayarana_Temple_%2C_Hosaholalu%2C_South_West_View.jpg",
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 39,
    latitude: "12.6424093",
    longitude: "76.4786287",
  },
  {
    slug: "mosale-temples-hassan",
    name: "Mosale Temples",
    state: "Karnataka",
    district: "Hassan",
    category: "heritage",
    placeType: "Temple",
    shortDescription: "Twin Hoysala temples of Nageshwara and Chennakeshava standing side by side in the quiet hamlet of Mosale.",
    description: "Mosale holds a pair of near-identical Hoysala temples, one dedicated to Shiva and the other to Vishnu, built in the early 13th century. Both feature the compact star-shaped plan with delicately carved towers and wall figures. Their pairing and rural calm make them a charming lesser-known stop.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 33,
    latitude: "13.0667",
    longitude: "76.0500",
  },
  {
    slug: "marehalli-lakshminarasimha-temple",
    name: "Marehalli Lakshminarasimha Temple",
    state: "Karnataka",
    district: "Mandya",
    category: "heritage",
    placeType: "Temple",
    shortDescription: "Hoysala-style temple near Malavalli dedicated to Lakshminarasimha with a serene riverside village setting.",
    description: "The Lakshminarasimha temple at Marehalli is a Hoysala-period shrine noted for its carved doorways and pillared hall. It draws pilgrims for its Narasimha deity and hosts a lively local car festival. The quiet setting near Malavalli makes it a peaceful heritage stop.",
    imageUrl: null,
    openingTimings: "7:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 33,
    latitude: "12.3833",
    longitude: "77.0000",
  },
  {
    slug: "ittagi-mahadeva-temple",
    name: "Ittagi Mahadeva Temple",
    state: "Karnataka",
    district: "Koppal",
    category: "heritage",
    placeType: "Temple",
    shortDescription: "Early 12th-century Kalyani Chalukya temple often called the 'Emperor among temples' for its refined carving.",
    description: "The Mahadeva temple at Ittagi, built in 1112 CE by a general of the Western Chalukyas, is celebrated for its superbly ornate pillars, doorframes and lathe-turned columns. An old inscription praises it as the finest of its age. It ranks among the most exquisite Chalukyan monuments in Karnataka.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 43,
    latitude: "15.3000",
    longitude: "76.2333",
  },
  {
    slug: "kukkanoor-navalinga-temples",
    name: "Kukkanoor Navalinga Temples",
    state: "Karnataka",
    district: "Koppal",
    category: "heritage",
    placeType: "Temple",
    shortDescription: "Cluster of Rashtrakuta and Chalukyan-era shrines at Kukkanoor, including the nine-shrine Navalinga group.",
    description: "Kukkanoor preserves a group of early medieval temples, notably the Navalinga complex of interconnected Shiva shrines and the Kalleshwara temple. The stonework shows Rashtrakuta and Chalukyan influences with sturdy pillars and carved ceilings. The site sees few visitors amid the northern Karnataka plains.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 34,
    latitude: "15.4667",
    longitude: "76.1833",
  },
  {
    slug: "annigeri-amruteshwara-temple",
    name: "Annigeri Amruteshwara Temple",
    state: "Karnataka",
    district: "Dharwad",
    category: "heritage",
    placeType: "Temple",
    shortDescription: "1050 CE Chalukyan temple at Annigeri, considered a prototype for later Hoysala soapstone architecture.",
    description: "The Amruteshwara temple at Annigeri, dated to around 1050 CE, is one of the earliest temples built in soapstone and is seen as a forerunner of Hoysala design. It has a pillared hall with finely turned columns and a well-proportioned sanctum. Its historical role in temple evolution makes it notable for enthusiasts.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Amrtesvara_Temple_at_Annigeri.JPG/1280px-Amrtesvara_Temple_at_Annigeri.JPG",
    openingTimings: "6:00 AM - 9:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 34,
    latitude: "15.4236719",
    longitude: "75.432659",
  },

  // ——— Pilgrimage temples ———
  {
    slug: "nanjangud-srikanteshwara-temple",
    name: "Nanjangud Srikanteshwara Temple",
    state: "Karnataka",
    district: "Mysuru",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Large Dravidian temple town on the Kabini river, known as Dakshina Kashi and famed for its towering gopuram.",
    description: "The Srikanteshwara (Nanjundeshwara) temple at Nanjangud is one of Karnataka's largest temples, with a tall carved gopuram and a spacious pillared complex. Revered as a 'Dakshina Kashi', it draws large crowds during its rathotsava car festival. The town sits on the banks of the Kabini river.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Srikanteshvara_Temple%2C_Nanjangud.JPG/1280px-Srikanteshvara_Temple%2C_Nanjangud.JPG",
    openingTimings: "6:00 AM - 8:30 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 66,
    latitude: "12.1188889",
    longitude: "76.6927778",
  },
  {
    slug: "gunja-narasimhaswamy-temple",
    name: "Gunja Narasimhaswamy Temple, T. Narasipura",
    state: "Karnataka",
    district: "Mysuru",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Ancient Narasimha temple at the Triveni Sangama of the Cauvery, Kabini and mythical Spatika Sarovara.",
    description: "Located at T. Narasipura where the Cauvery meets the Kabini, this temple to Gunja Narasimhaswamy is an old pilgrimage centre. The confluence hosts a periodic Kumbha Mela-style gathering for ritual bathing. The temple's name refers to a legend of a balancing gunja seed weighed against the deity.",
    imageUrl: null,
    openingTimings: "6:30 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 40,
    latitude: "12.2167",
    longitude: "76.9000",
  },
  {
    slug: "adichunchanagiri-kalabhairaveshwara",
    name: "Adichunchanagiri",
    state: "Karnataka",
    district: "Mandya",
    category: "pilgrimage",
    placeType: "Temple & Math",
    shortDescription: "Hilltop math and Kalabhairaveshwara temple near Nagamangala, also home to a protected peacock sanctuary.",
    description: "Adichunchanagiri is an important monastic centre of the Vokkaliga community, centred on the ancient Kalabhairaveshwara Swamy temple atop a rocky hill. The site includes the Gangadhareshwara shrine and a hillside peacock sanctuary where the birds roam freely. Pilgrims and nature visitors come alike.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Adichunchanagiri.3.jpg/1280px-Adichunchanagiri.3.jpg",
    openingTimings: "6:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 48,
    latitude: "13.0214665",
    longitude: "76.7383416",
  },
  {
    slug: "karighatta-temple-viewpoint",
    name: "Karighatta Temple",
    state: "Karnataka",
    district: "Mandya",
    category: "pilgrimage",
    placeType: "Hill Temple",
    shortDescription: "Small hill near Srirangapatna crowned by a Srinivasa temple with fine views over the Cauvery and Ranganathittu.",
    description: "Karighatta, meaning 'black hill', rises near Srirangapatna and is topped by the Kariginjaya Srinivasa temple. A short drive and climb lead to the shrine and a panorama over the Cauvery river, paddy fields and the Ranganathittu bird sanctuary. It is a peaceful sunrise and sunset spot.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fb/Karigatte_temple.JPG",
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 42,
    latitude: "12.4251985",
    longitude: "76.720235",
  },
  {
    slug: "bilikal-rangaswamy-betta",
    name: "Bilikal Rangaswamy Betta",
    state: "Karnataka",
    district: "Ramanagara",
    category: "pilgrimage",
    placeType: "Hill Temple",
    shortDescription: "Forested granite hill near Kanakapura with a cave shrine to Ranganatha and sweeping valley views.",
    description: "Bilikal Rangaswamy Betta is a high granite hill in the forests south of Kanakapura, named for a white rock outcrop. A temple to Ranganatha sits near the summit, reached by a scenic climb through woodland. Misty mornings and wide views over the Ghats make it popular with trekkers and pilgrims.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 44,
    latitude: "12.4667",
    longitude: "77.3000",
  },
  {
    slug: "magadi-someshwara-temple",
    name: "Magadi Someshwara Temple",
    state: "Karnataka",
    district: "Ramanagara",
    category: "heritage",
    placeType: "Temple",
    shortDescription: "Vijayanagara-era Someshwara and Ranganatha temples in Magadi, the home region of chieftain Kempe Gowda.",
    description: "Magadi, associated with Kempe Gowda who founded Bengaluru, preserves the old Someshwara and Ranganathaswamy temples built in the Vijayanagara style. The shrines have carved pillars and a spacious mantapa. The town also has a memorial to Kempe Gowda and lies near the Savandurga hills.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Ranganatha_Swamy_Temple_at_Magadi%2C_Karnataka.JPG/1280px-Ranganatha_Swamy_Temple_at_Magadi%2C_Karnataka.JPG",
    openingTimings: "6:30 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 38,
    latitude: "12.9570",
    longitude: "77.2270",
  },
  {
    slug: "kigga-rishyashringeshwara-temple",
    name: "Kigga Rishyashringeshwara Temple",
    state: "Karnataka",
    district: "Chikkamagaluru",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Ancient temple near Sringeri dedicated to sage Rishyashringa, believed to bring timely rains.",
    description: "The Rishyashringeshwara temple at Kigga honours the sage Rishyashringa, associated in legend with rituals for rainfall. Set amid the green Malnad hills near Sringeri, it is a quiet pilgrimage stop with old stone architecture. Nearby lie forest trails and the route toward Kavaledurga.",
    imageUrl: null,
    openingTimings: "6:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 39,
    latitude: "13.4184016",
    longitude: "75.1833833",
  },
  {
    slug: "basavana-bagewadi-temple",
    name: "Basavana Bagewadi Basaveshwara Temple",
    state: "Karnataka",
    district: "Vijayapura",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Birthplace town of the 12th-century social reformer Basavanna, with a temple and museum in his memory.",
    description: "Basavana Bagewadi is revered as the birthplace of Basavanna, the founder of the Lingayat Sharana movement. The town has a Basaveshwara temple and memorial commemorating his life and teachings. It is an important pilgrimage centre for followers across Karnataka.",
    imageUrl: null,
    openingTimings: "5:00 AM - 12:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 40,
    latitude: "16.5728846",
    longitude: "75.9756202",
  },
  {
    slug: "chandragutti-renukamba-temple",
    name: "Chandragutti Renukamba Temple",
    state: "Karnataka",
    district: "Shivamogga",
    category: "pilgrimage",
    placeType: "Hill Temple",
    shortDescription: "Ancient Renukamba temple below a hill fort near Soraba, set in the forested Malnad landscape.",
    description: "Chandragutti is known for the Renukamba (Renuka Devi) temple nestled at the foot of a rocky hill topped by an old fort. The Varada river flows nearby and the surrounding forests add to the setting. It is an old Kadamba-associated pilgrimage site with a large annual fair.",
    imageUrl: null,
    openingTimings: "6:30 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 38,
    latitude: "14.4332325",
    longitude: "74.9512068",
  },
  {
    slug: "humcha-padmavati-jain-temple",
    name: "Humcha Padmavati Jain Temple",
    state: "Karnataka",
    district: "Shivamogga",
    category: "pilgrimage",
    placeType: "Jain Temple",
    shortDescription: "Ancient Jain pilgrimage centre near Hosanagara, famed for the Padmavati Devi temple and Santhinatha basadi.",
    description: "Humcha (Hombuja) was capital of the Santara dynasty and is a major Digambara Jain tirtha. Its Padmavati Devi temple and a cluster of basadis draw pilgrims, and the site holds a revered image and a math. Set in the Malnad hills, it blends devotion with old Jain heritage.",
    imageUrl: null,
    openingTimings: "6:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 41,
    latitude: "13.8833",
    longitude: "75.0500",
  },
  {
    slug: "polali-rajarajeshwari-temple",
    name: "Polali Rajarajeshwari Temple",
    state: "Karnataka",
    district: "Dakshina Kannada",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Coastal temple near Bantwal famed for a tall clay-moulded idol of Rajarajeshwari and its annual football-like fair.",
    description: "The Rajarajeshwari temple at Polali, on the banks of the Phalguni river, houses a striking clay-and-herb sculpted idol said to be centuries old. The temple is known for its month-long festival and a traditional community ball game (Polali Chendu). It is an important Tulunadu shrine near Mangaluru.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/97/Polali_Rajarajeshwari_Temple_festival.jpg",
    openingTimings: "6:00 AM - 8:30 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 42,
    latitude: "12.9339956",
    longitude: "74.95536659999999",
  },
  {
    slug: "southadka-ganapathi-temple",
    name: "Southadka Ganapathi Temple",
    state: "Karnataka",
    district: "Dakshina Kannada",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Unusual open-air Ganesha shrine near Kadaba worshipped in a field with no walls or roof over the deity.",
    description: "Southadka is a distinctive Ganapathi temple where the deity is enshrined in the open with no surrounding walls or sanctum roof. Devotees offer bells and coconuts, and the leafy field setting gives it a serene, rustic feel. It has grown into a popular pilgrimage spot in the Dakshina Kannada hinterland.",
    imageUrl: null,
    openingTimings: "6:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 44,
    latitude: "12.8333",
    longitude: "75.4667",
  },
  {
    slug: "chikka-tirupati-temple",
    name: "Chikka Tirupati",
    state: "Karnataka",
    district: "Bengaluru Rural",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Popular Venkataramana Swamy temple east of Bengaluru, likened to a smaller Tirupati.",
    description: "Chikka Tirupati is a well-known temple to Prasanna Venkataramana Swamy, drawing steady streams of devotees from Bengaluru. Its car festival and weekend crowds give it a lively atmosphere. The temple lies amid the rural countryside near Sarjapur.",
    imageUrl: null,
    openingTimings: "6:30 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 46,
    latitude: "12.8833",
    longitude: "77.8333",
  },
  {
    slug: "honnamana-kere",
    name: "Honnamana Kere",
    state: "Karnataka",
    district: "Kodagu",
    category: "pilgrimage",
    placeType: "Sacred Lake",
    shortDescription: "The largest natural lake in Kodagu near Somwarpet, with a lakeside Honnamma Devi temple and hill backdrop.",
    description: "Honnamana Kere is a serene, forest-fringed lake in the coffee country near Somwarpet, considered sacred to the goddess Honnamma. A small temple by the water hosts an annual festival, and boating is offered on the lake. The green hills and calm setting make it a restful stop.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/91/Honnamana_Kere.jpg",
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 45,
    latitude: "12.6207821",
    longitude: "75.8806269",
  },

  // ——— Jain & coastal heritage ———
  {
    slug: "karkala-gomateshwara-statue",
    name: "Karkala Gomateshwara Statue",
    state: "Karnataka",
    district: "Udupi",
    category: "pilgrimage",
    placeType: "Jain Monument",
    shortDescription: "42-foot monolithic Bahubali statue at Karkala, carved in 1432 and standing atop a rocky hill.",
    description: "The Gomateshwara (Bahubali) statue at Karkala, consecrated in 1432 CE, is a 42-foot monolith of granite standing on a hilltop overlooking the town. The nearby Chaturmukha Basadi and other Jain temples add to Karkala's importance as a heritage centre. Steps lead up to the towering figure and its views.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 58,
    latitude: "13.2167",
    longitude: "74.9833",
  },
  {
    slug: "mudabidri-saavira-kambada-basadi",
    name: "Mudabidri Saavira Kambada Basadi",
    state: "Karnataka",
    district: "Dakshina Kannada",
    category: "heritage",
    placeType: "Jain Temple",
    shortDescription: "15th-century 'Thousand Pillar' Jain temple at Moodbidri, each pillar uniquely carved.",
    description: "The Saavira Kambada Basadi (Tribhuvana Tilaka Chudamani) at Moodbidri is a Jain basadi begun in 1430, famed for its hall of a thousand intricately carved pillars, no two alike. Moodbidri, called the 'Jain Kashi of the South', holds many other basadis and palm-leaf manuscripts. The temple is a masterpiece of coastal Jain art.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 52,
    latitude: "13.0741236",
    longitude: "74.9975011",
  },
  {
    slug: "venur-gomateshwara-statue",
    name: "Venur Gomateshwara",
    state: "Karnataka",
    district: "Dakshina Kannada",
    category: "pilgrimage",
    placeType: "Jain Monument",
    shortDescription: "35-foot Bahubali monolith of 1604 on the banks of the Gurupura river near Belthangady.",
    description: "Venur has a 35-foot monolithic statue of Bahubali erected in 1604 by the Ajila chieftains, one of Karnataka's group of Gomateshwara colossi. The riverside town also has several Jain basadis and a small fort ruin. It is a tranquil, uncrowded heritage stop in the Ghats' foothills.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 40,
    latitude: "12.9667",
    longitude: "75.1000",
  },
  {
    slug: "barkur-heritage-town",
    name: "Barkur Heritage Town",
    state: "Karnataka",
    district: "Udupi",
    category: "heritage",
    placeType: "Heritage Town",
    shortDescription: "Former capital of the Alupa dynasty near Udupi, dotted with dozens of old temples and ruined shrines.",
    description: "Barkur was the medieval capital of the coastal Alupa kingdom and is scattered with old temples, including the Panchalingeshwara and Kachchur Malli complexes. Once said to hold over a hundred temples, its lanes reveal carved shrines and remnants of its former grandeur. It is a rewarding heritage walk near Udupi.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Barkur_main_town..JPG/1280px-Barkur_main_town..JPG",
    openingTimings: "6:00 AM - 7:00 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 38,
    latitude: "13.4718481",
    longitude: "74.75638769999999",
  },
  {
    slug: "halasi-bhuvaraha-narasimha-temple",
    name: "Halasi Bhuvaraha Narasimha Temple",
    state: "Karnataka",
    district: "Belagavi",
    category: "heritage",
    placeType: "Temple",
    shortDescription: "Ancient Kadamba-era temple town near Khanapur with the Bhuvaraha Narasimha temple and old cave shrines.",
    description: "Halasi was a secondary capital of the early Kadambas and preserves the Bhuvaraha Narasimha temple, notable for its combined boar-and-lion image of Vishnu. The compact town also has rock-cut caves and other old shrines set amid greenery. It is a quiet historic pocket in the Belagavi hills.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Halasi_12.jpg/1280px-Halasi_12.jpg",
    openingTimings: "7:00 AM - 7:00 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 35,
    latitude: "15.5408438",
    longitude: "74.5894153",
  },
  {
    slug: "sonda-vadiraja-matha",
    name: "Sonda Vadiraja Matha",
    state: "Karnataka",
    district: "Uttara Kannada",
    category: "pilgrimage",
    placeType: "Math",
    shortDescription: "Historic Madhwa matha and Vrindavana of Sri Vadiraja Tirtha near Sirsi, set in forested surroundings.",
    description: "Sonda (Swadi) near Sirsi is an important Dvaita pilgrimage centre, home to the Vadiraja Matha and the vrindavana of the 16th-century saint Vadiraja Tirtha. The complex includes the Trivikrama and Dhavalagangaa temples and a sacred pond. Old Sonda also has Jain basadis and fort remains nearby.",
    imageUrl: null,
    openingTimings: "6:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 39,
    latitude: "14.7000",
    longitude: "74.8000",
  },
  {
    slug: "bhatkal-khetapai-narayana-temple",
    name: "Bhatkal Khetapai Narayana Temple",
    state: "Karnataka",
    district: "Uttara Kannada",
    category: "heritage",
    placeType: "Temple",
    shortDescription: "16th-century Vijayanagara-era stone temple in coastal Bhatkal with fine lithic carving.",
    description: "The Khetapai Narayana temple at Bhatkal, built in the 16th century, is a finely worked stone temple reflecting Vijayanagara coastal style, with slanted stone roofs suited to heavy monsoon rain. Bhatkal, once a busy port, also has Jain basadis and old mosques. The temple is a highlight of the coastal heritage trail.",
    imageUrl: null,
    openingTimings: "6:30 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 36,
    latitude: "13.9836112",
    longitude: "74.562454",
  },
  {
    slug: "attur-st-lawrence-basilica",
    name: "Attur St. Lawrence Basilica",
    state: "Karnataka",
    district: "Udupi",
    category: "pilgrimage",
    placeType: "Church",
    shortDescription: "Centuries-old pilgrimage church near Karkala dedicated to St. Lawrence, drawing large annual feast crowds.",
    description: "The Shrine Basilica of St. Lawrence at Attur, near Karkala, is a much-visited Catholic pilgrimage centre known for reported miracles. Its annual January feast draws thousands of devotees of many faiths. The peaceful grounds include a holy spring and grotto.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f0/St._Lawrence_Shrine_%28Karkala%29.jpg",
    openingTimings: "6:00 AM - 7:00 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 40,
    latitude: "13.205966",
    longitude: "74.9720868",
  },

  // ——— Waterfalls ———
  {
    slug: "muthyala-maduvu-pearl-valley",
    name: "Muthyala Maduvu (Pearl Valley)",
    state: "Karnataka",
    district: "Bengaluru Rural",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription: "Scenic waterfall and valley near Anekal where a stream cascades over rocks amid greenery.",
    description: "Muthyala Maduvu, literally 'pearl pond', is a waterfall near Anekal where water drops in a fine spray likened to pearls. A short walk through wooded slopes leads to the falls and a small Shiva shrine. The valley viewpoint is a popular easy day trip from Bengaluru.",
    imageUrl: null,
    openingTimings: "9:00 AM - 5:00 PM",
    entryFees: 15,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Jul,Aug,Sep,Oct,Nov",
    isHidden: false,
    popularity: 50,
    latitude: "12.6500",
    longitude: "77.6667",
  },
  {
    slug: "thottikallu-falls-tk-falls",
    name: "Thottikallu Falls",
    state: "Karnataka",
    district: "Bengaluru Urban",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription: "Seasonal waterfall known as TK Falls south of Bengaluru, with a small Muneshwara shrine at its base.",
    description: "Thottikallu Falls, popularly called TK Falls, is a monsoon-fed cascade on the southern outskirts of Bengaluru near Kaggalipura. A short trek leads down to the pool below, where a Muneshwara temple stands. It is a favourite quick nature escape from the city during the rains.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Thottikallu_falls.jpg/1280px-Thottikallu_falls.jpg",
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Jul,Aug,Sep,Oct,Nov",
    isHidden: true,
    popularity: 47,
    latitude: "12.8060797",
    longitude: "77.5386765",
  },
  {
    slug: "chunchanakatte-falls",
    name: "Chunchanakatte Falls",
    state: "Karnataka",
    district: "Mysuru",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription: "Broad Cauvery river waterfall near Krishnarajanagara beside an ancient Kodandarama temple.",
    description: "At Chunchanakatte the Cauvery river spreads and tumbles over rocks in a wide seasonal waterfall. An old Kodandarama temple linked to Ramayana legend stands beside the falls. The setting combines a pilgrimage stop with a scenic riverside outing.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Jul,Aug,Sep,Oct,Nov",
    isHidden: true,
    popularity: 42,
    latitude: "12.5167",
    longitude: "76.3167",
  },
  {
    slug: "balmuri-edmuri-falls",
    name: "Balmuri and Edmuri Falls",
    state: "Karnataka",
    district: "Mysuru",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription: "Low man-made check-dam cascades on the Cauvery near Mysuru, popular for a picnic and shallow water play.",
    description: "Balmuri and Edmuri are twin low weir waterfalls on a Cauvery canal near Srirangapatna, where water sheets gently over broad steps. The shallow, accessible flow makes them a favourite for families and film shoots. A small temple and shaded banks add to the relaxed setting.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Jul,Aug,Sep,Oct,Nov",
    isHidden: false,
    popularity: 52,
    latitude: "12.4333",
    longitude: "76.5667",
  },
  {
    slug: "hanumanagundi-falls",
    name: "Hanumanagundi Falls",
    state: "Karnataka",
    district: "Chikkamagaluru",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription: "Also called Soothanabbi, a stepped waterfall inside Kudremukh National Park reached by a stone stairway.",
    description: "Hanumanagundi (Soothanabbi) Falls plunges around 100 feet within Kudremukh National Park, reached by descending a long flight of stone steps. Fed by natural streams, it flows strongest in the monsoon amid dense shola forest. It is a scenic halt on the Kudremukh road.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Hanumanagundi_Falls.jpg/1280px-Hanumanagundi_Falls.jpg",
    openingTimings: "9:00 AM - 5:00 PM",
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Jul,Aug,Sep,Oct,Nov",
    isHidden: true,
    popularity: 46,
    latitude: "13.2702981",
    longitude: "75.15552339999999",
  },
  {
    slug: "sirimane-falls",
    name: "Sirimane Falls",
    state: "Karnataka",
    district: "Chikkamagaluru",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription: "Pretty cascade near Kigga and Sringeri set amid coffee estates and Malnad greenery.",
    description: "Sirimane Falls is a modest but photogenic waterfall near Kigga, where a stream drops in tiers into a shallow pool safe for wading. Surrounded by coffee and areca plantations, it is a refreshing stop close to Sringeri. Steps and a viewing area make access easy.",
    imageUrl: null,
    openingTimings: "9:00 AM - 5:30 PM",
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Jul,Aug,Sep,Oct,Nov",
    isHidden: true,
    popularity: 45,
    latitude: "13.4667",
    longitude: "75.2167",
  },
  {
    slug: "jomlu-theertha-falls",
    name: "Jomlu Theertha Falls",
    state: "Karnataka",
    district: "Udupi",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription: "Wide, low waterfall on the Sita river near Hebri, spreading across a broad rocky bed.",
    description: "Jomlu Theertha is a broad, relatively low waterfall where the Sita river fans out over a wide expanse of rock near Hebri. Its gentle spread and clear pools make it popular for a dip in season. A short walk from the road leads to the riverside spot.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Jul,Aug,Sep,Oct,Nov",
    isHidden: true,
    popularity: 40,
    latitude: "13.4833",
    longitude: "74.9333",
  },
  {
    slug: "onake-abbi-falls",
    name: "Onake Abbi Falls",
    state: "Karnataka",
    district: "Shivamogga",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription: "Remote waterfall near Agumbe reached by a forest trek, named for its pestle-like shape.",
    description: "Onake Abbi Falls lies deep in the rainforest near Agumbe and is reached by a trek through dense Western Ghats vegetation. The falls plunge in a narrow column said to resemble an 'onake' (grinding pestle). Its seclusion makes it a favourite for adventurous trekkers.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 41,
    latitude: "13.5167",
    longitude: "75.1000",
  },
  {
    slug: "barkana-falls",
    name: "Barkana Falls",
    state: "Karnataka",
    district: "Shivamogga",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription: "One of India's tallest waterfalls, plunging over 850 feet in the Agumbe rainforest.",
    description: "Barkana Falls, fed by the Seetha river, drops over 850 feet in a single high plunge and ranks among the tallest waterfalls in India. It sits within the biodiverse Agumbe rainforest of the Western Ghats. A viewpoint and forest trek offer glimpses of the dramatic cascade, best in the monsoon.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Jul,Aug,Sep,Oct,Nov",
    isHidden: true,
    popularity: 44,
    latitude: "13.4881474",
    longitude: "75.0935483",
  },
  {
    slug: "achakanya-falls",
    name: "Achakanya Falls",
    state: "Karnataka",
    district: "Shivamogga",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription: "Waterfall on the Malapahari river near Thirthahalli, wrapped in local legend.",
    description: "Achakanya Falls, near Thirthahalli, is a forest waterfall on a tributary of the Tunga associated with a local folk legend of three sisters. Set amid thick Malnad greenery, it flows fullest during the rains. It is a quiet, scenic stop off the beaten track.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Jul,Aug,Sep,Oct,Nov",
    isHidden: true,
    popularity: 35,
    latitude: "13.6500",
    longitude: "75.2167",
  },
  {
    slug: "chelavara-falls",
    name: "Chelavara Falls",
    state: "Karnataka",
    district: "Kodagu",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription: "Compact waterfall near Cheyyandane in Kodagu, dropping over a large rock face into a pool.",
    description: "Chelavara Falls, fed by a tributary of the Cauvery, tumbles over a broad boulder face near Virajpet in Kodagu. The rocky perch offers views over coffee country, though the wet rocks demand care. It is an offbeat stop amid the plantations of southern Coorg.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Jul,Aug,Sep,Oct,Nov",
    isHidden: true,
    popularity: 42,
    latitude: "12.3667",
    longitude: "75.7167",
  },
  {
    slug: "hidlumane-falls",
    name: "Hidlumane Falls",
    state: "Karnataka",
    district: "Shivamogga",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription: "Multi-tiered forest waterfall on the trek route to Kodachadri, reached through paddy fields and jungle.",
    description: "Hidlumane Falls is a series of cascades tucked in dense forest on the trekking route to Kodachadri peak. Reaching it involves a walk through paddy fields, streams and slippery rocks. Its wild setting rewards trekkers who make the effort during the post-monsoon months.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 40,
    latitude: "13.8754804",
    longitude: "74.90428659999999",
  },
  {
    slug: "koosalli-falls",
    name: "Koosalli Falls",
    state: "Karnataka",
    district: "Udupi",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription: "Six-tiered waterfall in the Western Ghats near Kundapura, reached by a steep forest descent.",
    description: "Koosalli Falls descends in around six tiers through thick forest in the Ghats east of Kundapura. Reaching the lower pools involves a demanding climb down and back up rocky, root-tangled paths. Its seclusion and multi-step drops make it a prize for adventurous trekkers.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 36,
    latitude: "13.963971",
    longitude: "74.68205209999999",
  },
  {
    slug: "bandaje-arbi-falls",
    name: "Bandaje Falls",
    state: "Karnataka",
    district: "Dakshina Kannada",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription: "High waterfall (Bandaje Arbi) reached by a demanding trek from Ujire near Charmadi in the Western Ghats.",
    description: "Bandaje Falls, known locally as Bandaje Arbi, drops from a high cliff edge and is reached by a strenuous forest trek from Ujire toward the Ballalarayana Durga plateau. The route passes streams, grasslands and ridge views before the falls appear. It is a classic Western Ghats trekking waterfall.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/81/Bandaje_falls.jpg",
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1400,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 41,
    latitude: "13.0000",
    longitude: "75.4667",
  },

  // ——— Dams, lakes & reservoirs ———
  {
    slug: "yagachi-dam",
    name: "Yagachi Dam",
    state: "Karnataka",
    district: "Hassan",
    category: "adventure",
    placeType: "Dam",
    shortDescription: "Reservoir near Hassan on the Yagachi river offering water sports with the backdrop of the Baba Budan hills.",
    description: "Yagachi Dam impounds the Yagachi river near Hassan, forming a broad reservoir set against distant hill ranges. A water-sports centre offers boating, kayaking and jet-ski rides on the calm waters. The green surroundings make it a pleasant half-day outing en route to Belur.",
    imageUrl: null,
    openingTimings: "9:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 44,
    latitude: "13.0000",
    longitude: "75.9333",
  },
  {
    slug: "gorur-dam-hemavathi",
    name: "Gorur Dam (Hemavathi Reservoir)",
    state: "Karnataka",
    district: "Hassan",
    category: "adventure",
    placeType: "Dam",
    shortDescription: "Large earthen dam on the Hemavathi river near Hassan with an island temple and expansive backwaters.",
    description: "Gorur Dam holds back the Hemavathi river to form a vast reservoir near Hassan, dotted with small islands and a river-island temple. The backwaters draw waterbirds and the dam offers sweeping views at sunset. It is a scenic and uncrowded spot in the district.",
    imageUrl: null,
    openingTimings: "9:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 40,
    latitude: "12.8333",
    longitude: "76.0500",
  },
  {
    slug: "kunigal-lake",
    name: "Kunigal Lake",
    state: "Karnataka",
    district: "Tumakuru",
    category: "adventure",
    placeType: "Lake",
    shortDescription: "Large historic tank in Kunigal town, a birdwatching spot near the famed old stud farm.",
    description: "Kunigal Lake is a big centuries-old irrigation tank in the middle of Kunigal town, fringed by greenery and attracting migratory birds in winter. The town is historically linked to Tipu Sultan's horse stud, later a renowned breeding farm. The lakefront makes a calm stop on the Bengaluru–Mangaluru route.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 34,
    latitude: "13.0111585",
    longitude: "77.0262205",
  },
  {
    slug: "thippagondanahalli-reservoir",
    name: "Thippagondanahalli Reservoir",
    state: "Karnataka",
    district: "Bengaluru Rural",
    category: "adventure",
    placeType: "Reservoir",
    shortDescription: "Historic TG Halli reservoir at the confluence of the Arkavathi and Kumudvathi west of Bengaluru.",
    description: "Thippagondanahalli (TG Halli) reservoir was built in 1933 across the Arkavathi river to supply water to Bengaluru. Set where the Arkavathi meets the Kumudvathi, it is fringed by greenery and rocky knolls. The quiet waterside is a scenic day-trip escape from the city.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/TGHallidam.JPG/1280px-TGHallidam.JPG",
    openingTimings: "9:00 AM - 5:30 PM",
    entryFees: 0,
    budgetPerDay: 900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 35,
    latitude: "12.9742475",
    longitude: "77.3475174",
  },

  // ——— Wildlife & nature ———
  {
    slug: "kabini-backwaters",
    name: "Kabini Backwaters",
    state: "Karnataka",
    district: "Mysuru",
    category: "wildlife",
    placeType: "River & Backwaters",
    shortDescription: "Famed wildlife river zone bordering Nagarhole, renowned for elephant herds and black panther sightings.",
    description: "The Kabini backwaters, formed by a dam on the Kabini river along the edge of Nagarhole, are among India's finest wildlife destinations. Boat safaris and jeep drives reveal large elephant congregations in summer, along with tigers, leopards and the elusive black panther. Riverside lodges make it a prime safari base.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 2400,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 72,
    latitude: "11.9833",
    longitude: "76.3500",
  },
  {
    slug: "bheemeshwari-nature-camp",
    name: "Bheemeshwari",
    state: "Karnataka",
    district: "Mandya",
    category: "adventure",
    placeType: "Nature Camp",
    shortDescription: "Riverside adventure and fishing camp on the Cauvery within the Cauvery Wildlife Sanctuary near Malavalli.",
    description: "Bheemeshwari is a well-known nature and adventure camp on the banks of the Cauvery, set within the Cauvery Wildlife Sanctuary. It offers coracle rides, ziplining, trekking and birdwatching, and was famous for mahseer angling. The forested river stretch also shelters otters, crocodiles and grizzled giant squirrels.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 2200,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 55,
    latitude: "12.3167",
    longitude: "77.1000",
  },
  {
    slug: "galibore-nature-camp",
    name: "Galibore",
    state: "Karnataka",
    district: "Ramanagara",
    category: "adventure",
    placeType: "Nature Camp",
    shortDescription: "Secluded fishing and nature camp on the Cauvery downstream of Sangama, rich in riverine birdlife.",
    description: "Galibore is a tranquil riverside camp deep in the Cauvery Wildlife Sanctuary, reached by a rough forest track. Once celebrated for catch-and-release mahseer fishing, it now offers birding, coracle rides and quiet river walks. Its remoteness makes it a peaceful retreat close to Bengaluru.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 2200,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 43,
    latitude: "12.3667",
    longitude: "77.3667",
  },
  {
    slug: "cauvery-wildlife-sanctuary",
    name: "Cauvery Wildlife Sanctuary",
    state: "Karnataka",
    district: "Ramanagara",
    category: "wildlife",
    placeType: "Wildlife Sanctuary",
    shortDescription: "Large sanctuary along the Cauvery gorge, habitat of the grizzled giant squirrel, elephants and mahseer.",
    description: "The Cauvery Wildlife Sanctuary stretches along the deep Cauvery river valley across Ramanagara, Mandya and Chamarajanagar. It protects the grizzled giant squirrel, elephants, leopards, otters and the endangered mahseer fish. Camps at Bheemeshwari, Galibore and Muthathi form access points for wildlife and river activities.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 200,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 46,
    latitude: "12.2833",
    longitude: "77.2500",
  },
  {
    slug: "attiveri-bird-sanctuary",
    name: "Attiveri Bird Sanctuary",
    state: "Karnataka",
    district: "Uttara Kannada",
    category: "wildlife",
    placeType: "Bird Sanctuary",
    shortDescription: "Reservoir-based bird sanctuary near Mundgod, a winter haven for numerous migratory waterbird species.",
    description: "The Attiveri Bird Sanctuary centres on a reservoir near Mundgod and hosts scores of resident and migratory bird species, especially in winter. Egrets, cormorants, storks and migratory ducks gather on the water and islands. Watchtowers and quiet trails make it a rewarding birding stop.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 50,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 37,
    latitude: "15.0667",
    longitude: "75.0000",
  },
  {
    slug: "kokkarebellur-pelican-sanctuary",
    name: "Kokkarebellur Pelican Sanctuary",
    state: "Karnataka",
    district: "Mandya",
    category: "wildlife",
    placeType: "Bird Sanctuary",
    shortDescription: "Village near Maddur where spot-billed pelicans and painted storks nest in trees among the community.",
    description: "Kokkarebellur is a rare village-based bird sanctuary where spot-billed pelicans and painted storks nest on trees within and around homes. The villagers protect the birds, which they treat as auspicious guests, even collecting guano as fertiliser. It is a heart-warming example of community conservation.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c4/Kokkare_Bellur_Pelicans.jpg",
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Dec,Jan,Feb,Mar,Apr",
    isHidden: true,
    popularity: 40,
    latitude: "12.5126074",
    longitude: "77.0928605",
  },
  {
    slug: "arabithittu-wildlife-sanctuary",
    name: "Arabithittu Wildlife Sanctuary",
    state: "Karnataka",
    district: "Mysuru",
    category: "wildlife",
    placeType: "Wildlife Sanctuary",
    shortDescription: "Small deciduous forest sanctuary near Hunsur with a nature camp, watchtower and rich birdlife.",
    description: "Arabithittu is a compact wildlife sanctuary near Hunsur, covered in dry deciduous forest and eucalyptus. It shelters spotted deer, jackals, pangolins and a variety of birds, with a watchtower and eco-camp for visitors. Its calm trails suit birdwatching and short nature walks.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/The_calm_of_river_kali.jpg/1280px-The_calm_of_river_kali.jpg",
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 50,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 34,
    latitude: "12.4667",
    longitude: "76.2667",
  },
  {
    slug: "someshwara-wildlife-sanctuary",
    name: "Someshwara Wildlife Sanctuary",
    state: "Karnataka",
    district: "Udupi",
    category: "wildlife",
    placeType: "Wildlife Sanctuary",
    shortDescription: "Dense rainforest sanctuary near Agumbe and Kollur, home to tigers, lion-tailed macaques and hornbills.",
    description: "The Someshwara Wildlife Sanctuary protects lush Western Ghats rainforest between Agumbe and Kollur, drained by the Sita river. It shelters tigers, leopards, lion-tailed macaques, king cobras and hornbills. The Someshwara temple and the forest rest house lie within its rich, high-rainfall terrain.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 50,
    budgetPerDay: 1400,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 38,
    latitude: "13.4667",
    longitude: "75.0667",
  },
  {
    slug: "bhimgad-wildlife-sanctuary",
    name: "Bhimgad Wildlife Sanctuary",
    state: "Karnataka",
    district: "Belagavi",
    category: "wildlife",
    placeType: "Wildlife Sanctuary",
    shortDescription: "Remote Western Ghats sanctuary near Khanapur, famous for the Barapede caves and Wroughton's free-tailed bat.",
    description: "Bhimgad is a wild, forested sanctuary in the Belagavi Ghats, notable for the Barapede caves, the only known breeding site of the rare Wroughton's free-tailed bat. Its dense forests, streams and the old Bhimgad fort ruins shelter diverse wildlife. Access is difficult, keeping it truly offbeat.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/55/Otomops_wroughtoni.jpg",
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 50,
    budgetPerDay: 1400,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 33,
    latitude: "15.5333",
    longitude: "74.3667",
  },
  {
    slug: "pushpagiri-wildlife-sanctuary",
    name: "Pushpagiri Wildlife Sanctuary",
    state: "Karnataka",
    district: "Kodagu",
    category: "wildlife",
    placeType: "Wildlife Sanctuary",
    shortDescription: "High-rainfall shola-and-grassland sanctuary in northern Kodagu, part of a UNESCO Western Ghats site.",
    description: "The Pushpagiri Wildlife Sanctuary spreads across the northern Kodagu hills with shola forests, grasslands and steep peaks. Part of the Western Ghats World Heritage cluster, it harbours elephants, tigers, Nilgiri langurs and rich birdlife. Its ridges feed several rivers and offer scenic trekking country.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 50,
    budgetPerDay: 1400,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 39,
    latitude: "12.6333",
    longitude: "75.6833",
  },

  // ——— Ghats, treks & viewpoints ———
  {
    slug: "charmadi-ghat",
    name: "Charmadi Ghat",
    state: "Karnataka",
    district: "Chikkamagaluru",
    category: "adventure",
    placeType: "Ghat & Viewpoint",
    shortDescription: "Winding Western Ghats mountain pass linking Mudigere and Dharmasthala, lined with waterfalls and viewpoints.",
    description: "Charmadi Ghat is a scenic ghat road descending from the Chikkamagaluru highlands toward Dakshina Kannada, with hairpin bends, cliffs and seasonal waterfalls. Viewpoints along the route reveal misty valleys and forested peaks like Ballalarayana Durga and Ombattu Gudda. It is a favourite drive and trekking base in the monsoon and winter.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 55,
    latitude: "13.0500",
    longitude: "75.5000",
  },
  {
    slug: "bisle-ghat-viewpoint",
    name: "Bisle Ghat Viewpoint",
    state: "Karnataka",
    district: "Hassan",
    category: "adventure",
    placeType: "Viewpoint",
    shortDescription: "Panoramic Western Ghats viewpoint near Sakleshpur overlooking dense rainforest and distant peaks.",
    description: "The Bisle Ghat viewpoint, on the road between Sakleshpur and Kukke Subramanya, opens onto a vast panorama of unbroken rainforest and the peaks of Pushpagiri, Kumara Parvatha and the Kabbinale range. The Bisle reserve forest below is one of the richest wet-forest tracts in the Ghats. Mornings are often wrapped in mist.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 48,
    latitude: "12.7833",
    longitude: "75.6833",
  },
  {
    slug: "ballalarayana-durga-trek",
    name: "Ballalarayana Durga",
    state: "Karnataka",
    district: "Chikkamagaluru",
    category: "adventure",
    placeType: "Fort Trek",
    shortDescription: "Ruined hill fort on a grassland plateau near Kalasa, a popular trek often paired with Bandaje Falls.",
    description: "Ballalarayana Durga is a Hoysala-era hill fort perched on a green plateau in the Western Ghats near Kalasa. The trek climbs through shola forest and rolling grasslands to fort ruins and sweeping ridge views. It is often combined with the descent to Bandaje Falls toward Ujire.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1400,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 44,
    latitude: "13.1667",
    longitude: "75.4000",
  },
  {
    slug: "ombattu-gudda-trek",
    name: "Ombattu Gudda",
    state: "Karnataka",
    district: "Dakshina Kannada",
    category: "adventure",
    placeType: "Trek",
    shortDescription: "Challenging Western Ghats trek near Charmadi crossing nine hills and countless forest streams.",
    description: "Ombattu Gudda, meaning 'nine hills', is a tough monsoon-season trek through leech-filled rainforest and rolling ridges near Charmadi. The route crosses numerous streams and offers dramatic valley views on clear stretches. It is regarded as one of the more demanding treks in coastal Karnataka.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1400,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 38,
    latitude: "12.8333",
    longitude: "75.5667",
  },
  {
    slug: "ettina-bhuja-trek",
    name: "Ettina Bhuja",
    state: "Karnataka",
    district: "Dakshina Kannada",
    category: "adventure",
    placeType: "Trek",
    shortDescription: "Ox-shoulder shaped peak near Charmadi offering a short but steep climb to a panoramic grassland summit.",
    description: "Ettina Bhuja, named for its resemblance to an ox's shoulder, is a peak near Kokkada below the Charmadi Ghats. A short, steep climb through forest and grassland leads to a summit with commanding views of the surrounding ranges. It has become a favourite one-day trek in the region.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1300,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 42,
    latitude: "12.9667",
    longitude: "75.5167",
  },
  {
    slug: "devaramane-hills",
    name: "Devaramane",
    state: "Karnataka",
    district: "Chikkamagaluru",
    category: "adventure",
    placeType: "Hills & Temple",
    shortDescription: "Scenic grassland hill village near Mudigere with the Bettada Byraveshwara temple and rolling meadow views.",
    description: "Devaramane is a tranquil hill hamlet near Mudigere set amid grassy meadows and forest, with the ancient Bettada Byraveshwara temple at its heart. The rolling greens and Ghat vistas make it popular for easy walks and camping. It offers a quiet alternative to the busier Chikkamagaluru viewpoints.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Temple_of_kalabhairava%2C_skyline_from_Devaramane%2C_Guthi_village%2C_July_5%2C_2011.jpg/1280px-Temple_of_kalabhairava%2C_skyline_from_Devaramane%2C_Guthi_village%2C_July_5%2C_2011.jpg",
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 40,
    latitude: "13.0607031",
    longitude: "75.5387724",
  },
  {
    slug: "avala-betta",
    name: "Avala Betta",
    state: "Karnataka",
    district: "Chikkaballapura",
    category: "adventure",
    placeType: "Hill Viewpoint",
    shortDescription: "Rocky hill near Chikkaballapur with a cave temple and a natural stone arch framing valley views.",
    description: "Avala Betta (Avalabetta) is a granite hill near Chikkaballapur topped by an old fort remnant, a Lakshmi Narasimha cave temple and a striking natural rock arch. A short drive and climb lead to viewpoints over the plains and distant Nandi hills. It is a lesser-known alternative to the crowded Nandi Hills.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 41,
    latitude: "13.5167",
    longitude: "77.8000",
  },

  // ——— Caves ———
  {
    slug: "kavala-caves-dandeli",
    name: "Kavala Caves",
    state: "Karnataka",
    district: "Uttara Kannada",
    category: "adventure",
    placeType: "Cave",
    shortDescription: "Natural limestone cave near Dandeli with a Shivalinga formation reached by a descent through forest.",
    description: "The Kavala Caves lie deep in the forests near Dandeli, reached by a walk and a steep flight of steps into the earth. Inside, a naturally formed Shivalinga draws pilgrims, especially during Shivaratri. The dark, dripping passages and surrounding jungle make the visit an adventure.",
    imageUrl: null,
    openingTimings: "8:00 AM - 5:00 PM",
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 38,
    latitude: "15.1667",
    longitude: "74.6167",
  },

  // ——— Beaches & coastal ———
  {
    slug: "padubidri-beach",
    name: "Padubidri Beach",
    state: "Karnataka",
    district: "Udupi",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Clean Blue Flag-certified beach near Udupi, known for its kite festival and calm, well-kept shoreline.",
    description: "Padubidri Beach is one of India's Blue Flag-certified beaches, maintained for cleanliness and safety near Udupi. Its wide golden sands host an annual international kite festival that fills the sky with colour. Gentle surf and good facilities make it a relaxed family beach.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Padubidri_NH_66_and_State_highway_1_intersection.jpg/1280px-Padubidri_NH_66_and_State_highway_1_intersection.jpg",
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 48,
    latitude: "13.1308865",
    longitude: "74.762509",
  },
  {
    slug: "mattu-beach-udupi",
    name: "Mattu Beach",
    state: "Karnataka",
    district: "Udupi",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Quiet, unspoilt beach near Kaup famed for the local Mattu Gulla brinjal-growing village behind it.",
    description: "Mattu Beach is a serene, less-crowded stretch of sand near Kaup, edged by casuarina groves and fishing hamlets. The village is celebrated for the GI-tagged Mattu Gulla green brinjal grown in its fields. Calm waters and sunsets make it a peaceful coastal escape.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 38,
    latitude: "13.2167",
    longitude: "74.7167",
  },
  {
    slug: "kodi-bengre-beach",
    name: "Kodi Bengre Beach",
    state: "Karnataka",
    district: "Udupi",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Narrow spit near Malpe where the Suvarna river meets the Arabian Sea, with sea on one side and backwaters on the other.",
    description: "Kodi Bengre is a slender sandbar near Malpe where the Suvarna river estuary meets the sea, offering the sea on one flank and calm backwaters on the other. A lighthouse and quiet fishing hamlet add to its charm. Boat rides and sunset views make it a scenic offbeat spot.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 37,
    latitude: "13.4496834",
    longitude: "74.695133",
  },
  {
    slug: "byndoor-ottinene-viewpoint",
    name: "Byndoor Ottinene Viewpoint",
    state: "Karnataka",
    district: "Udupi",
    category: "beach",
    placeType: "Beach & Viewpoint",
    shortDescription: "Hilltop sunset viewpoint at Byndoor overlooking a long crescent of the Arabian Sea coastline.",
    description: "Ottinene is a small hill at Byndoor offering a superb elevated view of the Arabian Sea and a sweeping beach below. It is prized for its sunsets and the sight of waves meeting the shore far beneath. A quiet beach and the Someshwara temple lie nearby.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 39,
    latitude: "13.8667",
    longitude: "74.6333",
  },
  {
    slug: "gangolli-beach-estuary",
    name: "Gangolli Beach",
    state: "Karnataka",
    district: "Udupi",
    category: "beach",
    placeType: "Beach & Estuary",
    shortDescription: "Fishing-port beach near Kundapura where five rivers meet the sea, with a lighthouse and boat rides.",
    description: "Gangolli is a busy fishing harbour town near Kundapura set at the estuary where the Panchagangavali (five rivers) joins the Arabian Sea. The beach, breakwater and river mouth offer boat rides and calm sunset views. A lighthouse and the nearby fort island add interest.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1100,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 36,
    latitude: "13.6500",
    longitude: "74.6833",
  },

  // ——— Museums ———
  {
    slug: "visvesvaraya-industrial-technological-museum",
    name: "Visvesvaraya Industrial and Technological Museum",
    state: "Karnataka",
    district: "Bengaluru Urban",
    category: "heritage",
    placeType: "Museum",
    shortDescription: "Interactive science and technology museum in central Bengaluru with hands-on galleries for all ages.",
    description: "The Visvesvaraya Industrial and Technological Museum, opened in 1965 and named after Sir M. Visvesvaraya, is a leading science museum in Bengaluru. Its galleries on engines, electronics, space and biotechnology feature interactive, hands-on exhibits popular with children. A full-scale aircraft and working models are among the highlights.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/View_from_Visvesvaraya_Industrial_and_Technological_Museum_%282025%29_02.jpg/1280px-View_from_Visvesvaraya_Industrial_and_Technological_Museum_%282025%29_02.jpg",
    openingTimings: "9:30 AM - 6:00 PM",
    entryFees: 90,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Jan,Feb,Jun,Jul,Aug",
    isHidden: false,
    popularity: 55,
    latitude: "12.9751593",
    longitude: "77.59641979999999",
  },
  {
    slug: "regional-natural-history-museum-mysuru",
    name: "Regional Natural History Museum, Mysuru",
    state: "Karnataka",
    district: "Mysuru",
    category: "heritage",
    placeType: "Museum",
    shortDescription: "Museum beside Karanji Lake showcasing the biodiversity, ecology and geology of southern India.",
    description: "The Regional Museum of Natural History in Mysuru, set beside Karanji Lake, presents dioramas and displays on the plants, animals and ecosystems of southern India. Interactive exhibits highlight conservation, evolution and geology for visitors of all ages. It pairs well with the adjoining lake and butterfly park.",
    imageUrl: null,
    openingTimings: "10:00 AM - 5:00 PM",
    entryFees: 20,
    budgetPerDay: 1000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: true,
    popularity: 38,
    latitude: "12.3020",
    longitude: "76.6550",
  },
];
