import type { NewDestination } from "../schema";

// Northwest India — Rajasthan, Punjab, Haryana, Himachal Pradesh, J&K, Ladakh, Chandigarh
export const northwestIndiaDestinations: Omit<NewDestination, "id" | "createdAt">[] = [
  // ───────────────────────── RAJASTHAN ─────────────────────────
  {
    slug: "amber-fort",
    name: "Amber Fort",
    state: "Rajasthan",
    district: "Jaipur",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Hilltop Rajput fort-palace of red sandstone and marble above Maota Lake.",
    description:
      "Amber (Amer) Fort is a magnificent 16th-century fort-palace built by Raja Man Singh, blending Rajput and Mughal architecture. Highlights include the mirrored Sheesh Mahal, Diwan-i-Aam, Ganesh Pol and Sukh Niwas. Visitors can walk or take a jeep up the ramparts and enjoy the evening light-and-sound show.",
    imageUrl: null,
    openingTimings: "7:00 AM - 9:00 PM",
    entryFees: 100,
    budgetPerDay: 2200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 93,
    latitude: "26.9855",
    longitude: "75.8513",
  },
  {
    slug: "nahargarh-fort",
    name: "Nahargarh Fort",
    state: "Rajasthan",
    district: "Jaipur",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Aravalli-crest fort offering sweeping sunset views over the Pink City.",
    description:
      "Nahargarh Fort crowns the Aravalli hills above Jaipur and once formed a defensive ring with Amber and Jaigarh. The Madhavendra Bhawan with its identical suites for the king's queens is a highlight, and the terrace café is famous for panoramic sunset views over the city.",
    imageUrl: null,
    openingTimings: "10:00 AM - 5:30 PM",
    entryFees: 50,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 82,
    latitude: "26.9401659",
    longitude: "75.8170373",
  },
  {
    slug: "jaigarh-fort",
    name: "Jaigarh Fort",
    state: "Rajasthan",
    district: "Jaipur",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Rugged hill fort housing Jaivana, once the world's largest wheeled cannon.",
    description:
      "Jaigarh Fort, the 'Fort of Victory', guarded Amber and its treasury. Its rugged ramparts, water reservoirs and armoury are well preserved, but the star attraction is Jaivana, historically the largest wheeled cannon ever cast. The fort connects to Amber by subterranean passages.",
    imageUrl: null,
    openingTimings: "9:00 AM - 6:30 PM",
    entryFees: 70,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 78,
    latitude: "26.9816052",
    longitude: "75.8447917",
  },
  {
    slug: "hawa-mahal",
    name: "Hawa Mahal",
    state: "Rajasthan",
    district: "Jaipur",
    category: "heritage",
    placeType: "Palace",
    shortDescription: "Iconic five-storey pink 'Palace of Winds' with 953 latticed windows.",
    description:
      "Hawa Mahal, the 'Palace of Winds', was built in 1799 so royal ladies could watch street festivities unseen through its honeycomb of 953 jharokha windows. The pyramidal facade of pink sandstone is Jaipur's most photographed landmark, and a small museum sits within.",
    imageUrl: null,
    openingTimings: "9:00 AM - 7:00 PM",
    entryFees: 50,
    budgetPerDay: 2000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 90,
    latitude: "26.9240458",
    longitude: "75.8267144",
  },
  {
    slug: "city-palace-jaipur",
    name: "City Palace Jaipur",
    state: "Rajasthan",
    district: "Jaipur",
    category: "heritage",
    placeType: "Palace",
    shortDescription: "Sprawling royal palace complex with courtyards, museums and the Chandra Mahal.",
    description:
      "The City Palace is a grand complex of courtyards, gardens and buildings blending Rajput and Mughal styles, still partly home to Jaipur's royal family. Highlights include the Mubarak Mahal museum, the peacock-themed Pritam Niwas Chowk gates and the seven-storey Chandra Mahal.",
    imageUrl: null,
    openingTimings: "9:30 AM - 7:30 PM",
    entryFees: 200,
    budgetPerDay: 2300,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 89,
    latitude: "26.9258",
    longitude: "75.8237",
  },
  {
    slug: "jantar-mantar-jaipur",
    name: "Jantar Mantar Jaipur",
    state: "Rajasthan",
    district: "Jaipur",
    category: "heritage",
    placeType: "Observatory",
    shortDescription: "UNESCO-listed 18th-century observatory with the world's largest stone sundial.",
    description:
      "Built by Maharaja Sawai Jai Singh II, Jantar Mantar is a UNESCO World Heritage collection of nineteen monumental masonry astronomical instruments. The Samrat Yantra sundial stands 27 metres tall and tells time to two-second accuracy; guides explain each instrument's function.",
    imageUrl: null,
    openingTimings: "9:00 AM - 6:30 PM",
    entryFees: 50,
    budgetPerDay: 2000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 80,
    latitude: "26.924762",
    longitude: "75.82455999999999",
  },
  {
    slug: "albert-hall-museum",
    name: "Albert Hall Museum",
    state: "Rajasthan",
    district: "Jaipur",
    category: "heritage",
    placeType: "Museum",
    shortDescription: "Indo-Saracenic state museum in Ram Niwas Garden, floodlit at night.",
    description:
      "The Albert Hall Museum is Rajasthan's oldest museum, housed in a striking Indo-Saracenic building in Ram Niwas Garden. Its galleries display miniature paintings, textiles, arms, an Egyptian mummy and metalware. The facade is beautifully illuminated after dark.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/AMRAPALI_MUSEUM%2C_JAIPUR.jpg/1280px-AMRAPALI_MUSEUM%2C_JAIPUR.jpg",
    openingTimings: "9:00 AM - 8:00 PM",
    entryFees: 40,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 72,
    latitude: "26.9115849",
    longitude: "75.81941200000001",
  },
  {
    slug: "jal-mahal",
    name: "Jal Mahal",
    state: "Rajasthan",
    district: "Jaipur",
    category: "heritage",
    placeType: "Palace",
    shortDescription: "Red-sandstone 'Water Palace' seemingly floating in Man Sagar Lake.",
    description:
      "Jal Mahal appears to float in the middle of Man Sagar Lake, with four of its five storeys submerged. The palace is admired from the lakefront promenade, a popular spot for photography and birdwatching as migratory birds gather on the water against the Aravalli backdrop.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1600,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 79,
    latitude: "26.9534584",
    longitude: "75.84612349999999",
  },
  {
    slug: "galta-ji-monkey-temple",
    name: "Galta Ji (Monkey Temple)",
    state: "Rajasthan",
    district: "Jaipur",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Ancient hillside pilgrimage complex with sacred water tanks and resident monkeys.",
    description:
      "Galta Ji is a historic Hindu pilgrimage site tucked into a rocky Aravalli pass east of Jaipur, with temples, pavilions and natural spring-fed kunds (tanks) where pilgrims bathe. Troops of monkeys give it the nickname Monkey Temple, and the ridge offers fine city views.",
    imageUrl: null,
    openingTimings: "4:00 AM - 9:00 PM",
    entryFees: 0,
    budgetPerDay: 1500,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 68,
    latitude: "26.9170484",
    longitude: "75.8582796",
  },
  {
    slug: "birla-mandir-jaipur",
    name: "Birla Mandir Jaipur",
    state: "Rajasthan",
    district: "Jaipur",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Gleaming white-marble Lakshmi Narayan temple below Moti Dungri hill.",
    description:
      "The Birla Mandir is a modern white-marble temple dedicated to Lakshmi and Narayan, set below Moti Dungri fort. Its carved panels depict figures from Hindu scripture as well as historical thinkers, and it glows beautifully when floodlit in the evening.",
    imageUrl: null,
    openingTimings: "8:00 AM - 12:00 PM, 4:00 PM - 9:00 PM",
    entryFees: 0,
    budgetPerDay: 1500,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 66,
    latitude: "26.8921693",
    longitude: "75.8153093",
  },
  {
    slug: "mehrangarh-fort",
    name: "Mehrangarh Fort",
    state: "Rajasthan",
    district: "Jodhpur",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Towering hilltop fort above Jodhpur's blue city with palatial museum galleries.",
    description:
      "Mehrangarh is one of India's largest and best-preserved forts, rising 120 metres above Jodhpur's blue-painted old city. Its palaces — Moti Mahal, Phool Mahal and Sheesh Mahal — house a superb museum of palanquins, arms and paintings, and a zipline circuits the ramparts.",
    imageUrl: null,
    openingTimings: "9:00 AM - 5:00 PM",
    entryFees: 100,
    budgetPerDay: 2200,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 91,
    latitude: "26.2981883",
    longitude: "73.0186098",
  },
  {
    slug: "umaid-bhawan-palace",
    name: "Umaid Bhawan Palace",
    state: "Rajasthan",
    district: "Jodhpur",
    category: "heritage",
    placeType: "Palace",
    shortDescription: "Grand Art Deco royal palace, part heritage hotel and part museum.",
    description:
      "One of the world's largest private residences, Umaid Bhawan was built in golden-yellow sandstone in the 1930s in a striking Indo-Deco style. Part remains the Jodhpur royal residence, part is a luxury hotel, and a museum displays vintage cars, clocks and royal memorabilia.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/40/Jodhpur_Airport.png",
    openingTimings: "9:00 AM - 5:00 PM",
    entryFees: 30,
    budgetPerDay: 2400,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 80,
    latitude: "26.2810298",
    longitude: "73.04730219999999",
  },
  {
    slug: "jaswant-thada",
    name: "Jaswant Thada",
    state: "Rajasthan",
    district: "Jodhpur",
    category: "heritage",
    placeType: "Cenotaph",
    shortDescription: "Milky-white marble royal cenotaph beside a lake near Mehrangarh.",
    description:
      "Jaswant Thada is an elegant white-marble cenotaph built in 1899 for Maharaja Jaswant Singh II, its thin polished sheets glowing warmly in sunlight. Set beside a small lake near Mehrangarh, its manicured gardens and portrait gallery of Marwar rulers make a tranquil stop.",
    imageUrl: null,
    openingTimings: "9:00 AM - 5:00 PM",
    entryFees: 30,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 74,
    latitude: "26.3040998",
    longitude: "73.0253613",
  },
  {
    slug: "mandore-gardens",
    name: "Mandore Gardens",
    state: "Rajasthan",
    district: "Jodhpur",
    category: "heritage",
    placeType: "Garden",
    shortDescription: "Historic gardens with royal cenotaphs and the Hall of Heroes near Jodhpur.",
    description:
      "Mandore was the old capital of Marwar before Jodhpur. Its shady gardens contain the towering, temple-like cenotaphs of Rathore rulers, the rock-cut Hall of Heroes with painted deities, and the ruins of an old fort, all frequented by resident langurs.",
    imageUrl: null,
    openingTimings: "6:00 AM - 10:00 AM, 4:00 PM - 7:30 PM",
    entryFees: 0,
    budgetPerDay: 1500,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 63,
    latitude: "26.3525047",
    longitude: "73.0353164",
  },
  {
    slug: "jaisalmer-fort",
    name: "Jaisalmer Fort",
    state: "Rajasthan",
    district: "Jaisalmer",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Living golden-sandstone desert fort, a UNESCO 'Sonar Quila' still inhabited.",
    description:
      "Rising from the Thar Desert like a giant sandcastle, Jaisalmer Fort is one of the few 'living forts' where thousands still reside within its walls. Inside its honey-coloured ramparts are Jain temples, palaces, havelis, shops and guesthouses along winding lanes.",
    imageUrl: null,
    openingTimings: "9:00 AM - 6:00 PM",
    entryFees: 50,
    budgetPerDay: 2000,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 88,
    latitude: "26.9124555",
    longitude: "70.9126093",
  },
  {
    slug: "sam-sand-dunes",
    name: "Sam Sand Dunes",
    state: "Rajasthan",
    district: "Jaisalmer",
    category: "adventure",
    placeType: "Desert",
    shortDescription: "Rolling Thar Desert dunes famed for camel safaris and sunset dune camps.",
    description:
      "The Sam Sand Dunes, about 40 km west of Jaisalmer, offer the classic Thar Desert experience of rippling golden sand. Visitors ride camels or jeeps to catch the sunset, then stay in desert camps for folk music, Kalbelia dance and starlit dinners.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2500,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 85,
    latitude: "26.8319",
    longitude: "70.5083",
  },
  {
    slug: "patwon-ki-haveli",
    name: "Patwon ki Haveli",
    state: "Rajasthan",
    district: "Jaisalmer",
    category: "heritage",
    placeType: "Haveli",
    shortDescription: "Cluster of five ornate merchant mansions with intricate sandstone lattice work.",
    description:
      "Patwon ki Haveli is a set of five lavishly carved havelis built by a wealthy brocade-trading family in the early 19th century. Their yellow-sandstone facades, filigree jharokhas and painted interiors make them the grandest of Jaisalmer's mansions, part now a museum.",
    imageUrl: null,
    openingTimings: "9:00 AM - 6:30 PM",
    entryFees: 100,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 72,
    latitude: "26.9163645",
    longitude: "70.9143452",
  },
  {
    slug: "gadisar-lake",
    name: "Gadisar Lake",
    state: "Rajasthan",
    district: "Jaisalmer",
    category: "heritage",
    placeType: "Lake",
    shortDescription: "Man-made desert reservoir ringed by shrines, ghats and the carved Tilon Gate.",
    description:
      "Gadisar Lake was once Jaisalmer's chief water source, built in the 14th century and surrounded by small temples, shrines and bathing ghats. Boating on its calm waters at sunrise, framed by the ornate Tilon Ki Pol gateway, is a peaceful highlight.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1600,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 68,
    latitude: "26.9090162",
    longitude: "70.9210228",
  },
  {
    slug: "kuldhara-abandoned-village",
    name: "Kuldhara Abandoned Village",
    state: "Rajasthan",
    district: "Jaisalmer",
    category: "heritage",
    placeType: "Heritage Village",
    shortDescription: "Eerie ruined desert village abandoned overnight by Paliwal Brahmins, steeped in legend.",
    description:
      "Kuldhara is a deserted village whose Paliwal Brahmin inhabitants are said to have vanished overnight around two centuries ago, cursing the land. Today its restored ruins, empty lanes and a small temple make an atmospheric stop amid the Thar, popular for its ghostly legends.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 30,
    budgetPerDay: 1600,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 62,
    latitude: "26.7789",
    longitude: "70.7100",
  },
  {
    slug: "junagarh-fort-bikaner",
    name: "Junagarh Fort",
    state: "Rajasthan",
    district: "Bikaner",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Rare unconquered plains fort with opulent painted palaces in Bikaner.",
    description:
      "Junagarh Fort, built in 1594, is unusual for standing on flat ground rather than a hill, yet was never conquered. Within its walls are richly decorated palaces such as Anup Mahal, Phool Mahal and Chandra Mahal, plus a museum with royal armoury and a WWI-era biplane.",
    imageUrl: null,
    openingTimings: "10:00 AM - 4:30 PM",
    entryFees: 50,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 76,
    latitude: "28.0219586",
    longitude: "73.3179962",
  },
  {
    slug: "karni-mata-temple",
    name: "Karni Mata Temple (Deshnoke)",
    state: "Rajasthan",
    district: "Bikaner",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Famous 'Rat Temple' at Deshnoke where thousands of sacred rats are revered.",
    description:
      "The Karni Mata Temple in Deshnoke is renowned for the thousands of sacred black rats, called kabbas, that roam its marble halls and are considered holy. Devotees seek out the rare white rats for blessings, and the silver-and-marble facade is finely wrought.",
    imageUrl: null,
    openingTimings: "4:00 AM - 10:00 PM",
    entryFees: 0,
    budgetPerDay: 1500,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 70,
    latitude: "27.7909966",
    longitude: "73.3408206",
  },
  {
    slug: "pushkar-lake",
    name: "Pushkar Lake",
    state: "Rajasthan",
    district: "Ajmer",
    category: "pilgrimage",
    placeType: "Sacred Lake",
    shortDescription: "Sacred Hindu lake ringed by 52 ghats and 500 temples, host of the camel fair.",
    description:
      "Pushkar Lake is one of Hinduism's holiest water bodies, encircled by 52 bathing ghats and hundreds of temples, including the rare Brahma Temple. Pilgrims perform ritual baths, and each November the town hosts the famous Pushkar Camel Fair with trading, races and folk culture.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1600,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 84,
    latitude: "26.4871515",
    longitude: "74.55401770000002",
  },
  {
    slug: "brahma-temple-pushkar",
    name: "Brahma Temple Pushkar",
    state: "Rajasthan",
    district: "Ajmer",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "One of the world's very few temples dedicated to the creator god Brahma.",
    description:
      "The Jagatpita Brahma Mandir at Pushkar is among the only prominent temples in the world dedicated to Lord Brahma. Marked by a red spire and a hamsa (goose) motif, its silver-coin-studded floor and central image draw pilgrims year-round, especially during Kartik Purnima.",
    imageUrl: null,
    openingTimings: "5:30 AM - 1:29 PM, 3:01 PM - 10:00 PM",
    entryFees: 0,
    budgetPerDay: 1500,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 72,
    latitude: "26.4874255",
    longitude: "74.5489438",
  },
  {
    slug: "ajmer-sharif-dargah",
    name: "Ajmer Sharif Dargah",
    state: "Rajasthan",
    district: "Ajmer",
    category: "pilgrimage",
    placeType: "Dargah",
    shortDescription: "Revered Sufi shrine of Khwaja Moinuddin Chishti drawing pilgrims of all faiths.",
    description:
      "The Ajmer Sharif Dargah enshrines the tomb of the 12th-century Sufi saint Khwaja Moinuddin Chishti and is one of South Asia's most important pilgrimage centres. Its marble courtyards, huge offering cauldrons and qawwali music draw millions, peaking during the annual Urs.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Dargah_of_Sufi_saint_Moinuddin_Chishti_Ajmer_India_%285%29.JPG",
    openingTimings: "4:00 AM - 9:00 PM",
    entryFees: 0,
    budgetPerDay: 1600,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 82,
    latitude: "26.456233",
    longitude: "74.628232",
  },
  {
    slug: "chittorgarh-fort",
    name: "Chittorgarh Fort",
    state: "Rajasthan",
    district: "Chittorgarh",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Vast hilltop UNESCO fort symbolising Rajput valour, with towers and palaces.",
    description:
      "Chittorgarh, one of India's largest forts, sprawls across a 180-metre hill and is a UNESCO World Heritage Site emblematic of Rajput sacrifice and jauhar. Its highlights are the nine-storey Vijay Stambha (Victory Tower), Kirti Stambha, Rana Kumbha Palace and Padmini's Palace.",
    imageUrl: null,
    openingTimings: "9:00 AM - 6:00 PM",
    entryFees: 40,
    budgetPerDay: 1700,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 80,
    latitude: "24.8887",
    longitude: "74.6269",
  },
  {
    slug: "kumbhalgarh-fort",
    name: "Kumbhalgarh Fort",
    state: "Rajasthan",
    district: "Rajsamand",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Mewar hill fort with the world's second-longest continuous wall, the 'Great Wall of India'.",
    description:
      "Kumbhalgarh, birthplace of Maharana Pratap, is a UNESCO-listed hill fort whose 36-km perimeter wall is often called the Great Wall of India. Within lie over 360 temples and the Badal Mahal palace on the ridge; the ramparts are stunning at sunset and during the evening light show.",
    imageUrl: null,
    openingTimings: "9:00 AM - 6:00 PM",
    entryFees: 40,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 79,
    latitude: "25.1528239",
    longitude: "73.58699829999999",
  },
  {
    slug: "ranakpur-jain-temple",
    name: "Ranakpur Jain Temple",
    state: "Rajasthan",
    district: "Pali",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Sublime 15th-century marble Jain temple with 1,444 uniquely carved pillars.",
    description:
      "The Ranakpur Jain temple, dedicated to Adinath, is celebrated for its forest of 1,444 intricately carved marble pillars, no two alike. Built in the 15th century in the Aravalli valley, its domed halls, filigree ceilings and serene setting make it a masterpiece of Jain art.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Jain_Temple_Ranakpur.jpg/1280px-Jain_Temple_Ranakpur.jpg",
    openingTimings: "6:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 1700,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 74,
    latitude: "25.115658",
    longitude: "73.47287349999999",
  },
  {
    slug: "mount-abu",
    name: "Mount Abu",
    state: "Rajasthan",
    district: "Sirohi",
    category: "hill_station",
    placeType: "Hill Station",
    shortDescription: "Rajasthan's only hill station, with Nakki Lake and cool Aravalli forests.",
    description:
      "Mount Abu is Rajasthan's sole hill station, a green retreat in the Aravallis at around 1,220 metres. Visitors boat on Nakki Lake, watch sunset from Honeymoon Point, visit the Adhar Devi temple and enjoy the pleasant climate that contrasts with the desert plains below.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1900,
    recommendedDays: 2,
    bestMonths: "Mar,Apr,May,Jun,Sep,Oct,Nov",
    isHidden: false,
    popularity: 78,
    latitude: "24.5936872",
    longitude: "72.71331599999999",
  },
  {
    slug: "dilwara-temples",
    name: "Dilwara Jain Temples",
    state: "Rajasthan",
    district: "Sirohi",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Exquisitely carved marble Jain temples at Mount Abu, famed worldwide for craftsmanship.",
    description:
      "The Dilwara Temples, built between the 11th and 13th centuries near Mount Abu, are among the finest examples of Jain marble carving. The Vimal Vasahi and Luna Vasahi shrines display astonishingly delicate ceilings, lotus pendants and pillars translucent with detail.",
    imageUrl: null,
    openingTimings: "11:00 AM - 5:00 PM",
    entryFees: 0,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Mar,Apr,May,Jun,Sep,Oct,Nov",
    isHidden: false,
    popularity: 73,
    latitude: "24.609382",
    longitude: "72.7229797",
  },
  {
    slug: "bundi-taragarh",
    name: "Taragarh Fort & Bundi Palace",
    state: "Rajasthan",
    district: "Bundi",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Atmospheric hill fort and palace above stepwell-rich Bundi, famed for its murals.",
    description:
      "Overlooking the medieval town of Bundi, Taragarh Fort and the adjoining Garh Palace are prized for their romantic ruins and the exquisite Bundi-school miniature murals of the Chitrashala. Below, ornate stepwells such as Raniji ki Baori add to the town's old-world charm.",
    imageUrl: null,
    openingTimings: "10:00 AM - 5:30 PM",
    entryFees: 100,
    budgetPerDay: 1600,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 62,
    latitude: "25.4506117",
    longitude: "75.6371747",
  },
  {
    slug: "kota-garh-palace",
    name: "Kota Garh (City Palace)",
    state: "Rajasthan",
    district: "Kota",
    category: "heritage",
    placeType: "Palace",
    shortDescription: "Riverside palace complex on the Chambal with the Rao Madho Singh Museum.",
    description:
      "The City Palace of Kota, or Garh, sprawls along the Chambal River with fortified gateways, courtyards and painted halls. The Rao Madho Singh Museum inside displays weapons, miniatures and royal artefacts, and nearby Chambal Garden and river cruises round out a visit.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Jag_Mandir_Kota.jpg/1280px-Jag_Mandir_Kota.jpg",
    openingTimings: "10:00 AM - 5:00 PM",
    entryFees: 100,
    budgetPerDay: 1600,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 58,
    latitude: "25.175408",
    longitude: "75.830517",
  },
  {
    slug: "bhangarh-fort",
    name: "Bhangarh Fort",
    state: "Rajasthan",
    district: "Alwar",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Ruined 17th-century fort town famed as India's most 'haunted' site.",
    description:
      "Bhangarh Fort is a sprawling ruined complex of temples, havelis and bazaars at the foot of the Aravallis, reputedly India's most haunted place with entry barred after dark by official notice. By day its atmospheric ruins and legends draw curious visitors and history buffs.",
    imageUrl: null,
    openingTimings: "9:00 AM - 5:00 PM",
    entryFees: 25,
    budgetPerDay: 1500,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 66,
    latitude: "27.0945913",
    longitude: "76.29129979999999",
  },
  {
    slug: "bala-quila-alwar",
    name: "Bala Quila (Alwar Fort)",
    state: "Rajasthan",
    district: "Alwar",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Long ridge-top fort above Alwar with sweeping views over the Aravallis.",
    description:
      "Bala Quila stretches for several kilometres along a steep Aravalli ridge above Alwar, with massive gates, bastions and old palace remains. The climb rewards visitors with panoramic views of the city and surrounding hills, and the fort dates back over five centuries.",
    imageUrl: null,
    openingTimings: "9:00 AM - 5:00 PM",
    entryFees: 0,
    budgetPerDay: 1500,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 54,
    latitude: "27.5749474",
    longitude: "76.5880856",
  },
  {
    slug: "sariska-tiger-reserve",
    name: "Sariska Tiger Reserve",
    state: "Rajasthan",
    district: "Alwar",
    category: "wildlife",
    placeType: "Tiger Reserve",
    shortDescription: "Aravalli tiger reserve of dry forest, ruins and temples near Alwar.",
    description:
      "Sariska Tiger Reserve spreads across the rugged Aravallis and shelters tigers, leopards, nilgai and rich birdlife amid dry deciduous forest. Jeep safaris also pass ancient sites like the Kankwari Fort and the Neelkanth temples, blending wildlife with heritage.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e5/Sariska_Tiger_Reserve%2C_Alwar.jpg",
    openingTimings: "6:00 AM - 4:30 PM",
    entryFees: 120,
    budgetPerDay: 2400,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 70,
    latitude: "27.3104429",
    longitude: "76.4389167",
  },
  {
    slug: "keoladeo-national-park",
    name: "Keoladeo National Park",
    state: "Rajasthan",
    district: "Bharatpur",
    category: "wildlife",
    placeType: "National Park",
    shortDescription: "UNESCO wetland bird sanctuary at Bharatpur, haven for migratory waterfowl.",
    description:
      "Keoladeo (Bharatpur Bird Sanctuary) is a UNESCO World Heritage wetland and one of Asia's richest bird areas, hosting hundreds of resident and migratory species including painted storks and, historically, the Siberian crane. Cycle-rickshaws and bicycles ply its quiet trails.",
    imageUrl: null,
    openingTimings: "6:00 AM - 5:00 PM",
    entryFees: 75,
    budgetPerDay: 2000,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 76,
    latitude: "27.1596085",
    longitude: "77.5218127",
  },
  {
    slug: "deeg-palace",
    name: "Deeg Palace",
    state: "Rajasthan",
    district: "Bharatpur",
    category: "heritage",
    placeType: "Palace",
    shortDescription: "Jat-era garden palace of pavilions, fountains and monsoon-themed halls.",
    description:
      "The Deeg Palace complex, built by the Jat rulers of Bharatpur, is famed for its symmetrical Mughal-style gardens, hundreds of fountains and elegant bhawans such as Gopal Bhawan overlooking a tank. The Keshav Bhawan's monsoon fountains once mimicked thunder and rain.",
    imageUrl: null,
    openingTimings: "9:30 AM - 5:00 PM",
    entryFees: 25,
    budgetPerDay: 1500,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 52,
    latitude: "27.4722345",
    longitude: "77.32366499999999",
  },
  {
    slug: "osian-temples",
    name: "Osian Temples",
    state: "Rajasthan",
    district: "Jodhpur",
    category: "heritage",
    placeType: "Temple",
    shortDescription: "Ancient desert temple town with 8th-century Hindu and Jain shrines.",
    description:
      "Osian, on the fringe of the Thar, is an ancient temple town with clusters of intricately sculpted 8th- to 12th-century Hindu and Jain temples, notably the Sachiya Mata and Mahavira temples. It also serves as a base for camel safaris into the surrounding dunes.",
    imageUrl: null,
    openingTimings: "6:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 1600,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 54,
    latitude: "26.7260135",
    longitude: "72.9123903",
  },
  {
    slug: "nathdwara-shrinathji",
    name: "Nathdwara (Shrinathji Temple)",
    state: "Rajasthan",
    district: "Rajsamand",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Major Vaishnavite pilgrimage town centred on the Shrinathji (Krishna) temple.",
    description:
      "Nathdwara is a leading centre of the Pushtimarg (Vallabh) sect, home to the revered Shrinathji temple where a black-marble image of the child Krishna is worshipped through elaborate daily darshan rituals. The town is also known for Pichwai devotional paintings.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1600,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 68,
    latitude: "24.9282628",
    longitude: "73.81599",
  },
  {
    slug: "eklingji-temple",
    name: "Eklingji Temple",
    state: "Rajasthan",
    district: "Udaipur",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Ancient Shiva temple complex, the ruling deity of the Mewar dynasty.",
    description:
      "The Eklingji temple complex near Udaipur enshrines a four-faced black-marble Shiva lingam regarded as the ruling deity of Mewar. Built and rebuilt from the 8th century, its 108 shrines, pillared hall and silver doors make it a significant and atmospheric pilgrimage site.",
    imageUrl: null,
    openingTimings: "4:30 AM - 7:00 PM",
    entryFees: 0,
    budgetPerDay: 1600,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 58,
    latitude: "24.7280",
    longitude: "73.7500",
  },
  {
    slug: "mandawa-shekhawati",
    name: "Mandawa (Shekhawati)",
    state: "Rajasthan",
    district: "Jhunjhunu",
    category: "heritage",
    placeType: "Heritage Town",
    shortDescription: "Open-air gallery town of frescoed havelis in the Shekhawati region.",
    description:
      "Mandawa is a highlight of the Shekhawati region, often called an open-air art gallery for its many merchant havelis covered in colourful, richly detailed frescoes. A hilltop fort-hotel and painted mansions such as the Murmuria and Goenka havelis reward wandering the lanes.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1700,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 60,
    latitude: "28.0552478",
    longitude: "75.1497725",
  },
  {
    slug: "fatehsagar-lake-udaipur",
    name: "Fateh Sagar Lake",
    state: "Rajasthan",
    district: "Udaipur",
    category: "heritage",
    placeType: "Lake",
    shortDescription: "Scenic Udaipur lake with island parks and a hilltop solar observatory.",
    description:
      "Fateh Sagar is one of Udaipur's beautiful interconnected lakes, ringed by hills and dotted with islands including Nehru Park and an amusement park. Boating, the lakeside drive and views of the Aravallis and the Moti Magri hill make it a favourite evening spot.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 72,
    latitude: "24.6012962",
    longitude: "73.67967949999999",
  },
  {
    slug: "sajjangarh-monsoon-palace",
    name: "Sajjangarh (Monsoon Palace)",
    state: "Rajasthan",
    district: "Udaipur",
    category: "heritage",
    placeType: "Palace",
    shortDescription: "Hilltop white palace above Udaipur with sweeping sunset lake views.",
    description:
      "The Sajjangarh or Monsoon Palace crowns a hill within a wildlife sanctuary above Udaipur, built to watch the monsoon clouds. Its white ramparts offer some of the finest panoramas of the city's lakes and the Aravalli ranges, especially at sunset.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 100,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Sep,Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 66,
    latitude: "24.5931853",
    longitude: "73.6396056",
  },

  // ───────────────────────── HIMACHAL PRADESH ─────────────────────────
  {
    slug: "shimla-mall-road",
    name: "Shimla Mall Road",
    state: "Himachal Pradesh",
    district: "Shimla",
    category: "hill_station",
    placeType: "Promenade",
    shortDescription: "Bustling colonial-era pedestrian promenade at the heart of Shimla.",
    description:
      "The Mall Road is the lively spine of Shimla, lined with colonial-era buildings, shops, cafés and the Gaiety Theatre. Traffic-free and running along the ridge, it is the town's social hub for evening strolls with views of the surrounding Himalayan foothills.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Kullu_Valley_near_Manali%2C_Himachal_Pradesh%2C_India.jpg/1280px-Kullu_Valley_near_Manali%2C_Himachal_Pradesh%2C_India.jpg",
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2000,
    recommendedDays: 2,
    bestMonths: "Mar,Apr,May,Jun,Sep,Oct,Nov,Dec",
    isHidden: false,
    popularity: 84,
    latitude: "31.1044032",
    longitude: "77.174829",
  },
  {
    slug: "shimla-ridge",
    name: "The Ridge Shimla",
    state: "Himachal Pradesh",
    district: "Shimla",
    category: "hill_station",
    placeType: "Viewpoint",
    shortDescription: "Open ridge-top space with mountain views, Christ Church and colonial landmarks.",
    description:
      "The Ridge is a large open square along the top of Shimla, connecting to the Mall Road and offering sweeping views of snow-capped ranges on clear days. It is flanked by the neo-Gothic Christ Church and the Tudor-style library, and hosts fairs and festivals.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2000,
    recommendedDays: 1,
    bestMonths: "Mar,Apr,May,Jun,Sep,Oct,Nov,Dec",
    isHidden: false,
    popularity: 80,
    latitude: "31.1048001",
    longitude: "77.1746678",
  },
  {
    slug: "jakhoo-temple-shimla",
    name: "Jakhoo Temple",
    state: "Himachal Pradesh",
    district: "Shimla",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Hanuman temple on Shimla's highest peak with a towering idol and city views.",
    description:
      "Jakhoo Temple sits atop Shimla's highest hill, dedicated to Lord Hanuman and marked by one of the world's tallest Hanuman statues at 33 metres. Reached by a forest path or ropeway, it offers commanding views over Shimla, with resident monkeys along the way.",
    imageUrl: null,
    openingTimings: "5:00 AM - 12:00 PM, 4:00 PM - 9:00 PM",
    entryFees: 0,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Mar,Apr,May,Jun,Sep,Oct,Nov,Dec",
    isHidden: false,
    popularity: 70,
    latitude: "31.1011646",
    longitude: "77.1839832",
  },
  {
    slug: "kufri",
    name: "Kufri",
    state: "Himachal Pradesh",
    district: "Shimla",
    category: "hill_station",
    placeType: "Hill Station",
    shortDescription: "Small hill resort near Shimla popular for winter snow and Himalayan views.",
    description:
      "Kufri, about 16 km from Shimla, is a compact hill resort known for its winter snow, pony rides and the Himalayan Nature Park. In season visitors enjoy sledding and tobogganing, while the Mahasu Peak viewpoint gives sweeping vistas of the higher snow ranges.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1900,
    recommendedDays: 1,
    bestMonths: "Mar,Apr,May,Jun,Sep,Oct,Nov,Dec,Jan",
    isHidden: false,
    popularity: 74,
    latitude: "31.0941261",
    longitude: "77.278049",
  },
  {
    slug: "chail",
    name: "Chail",
    state: "Himachal Pradesh",
    district: "Solan",
    category: "hill_station",
    placeType: "Hill Station",
    shortDescription: "Quiet forested hill town with the world's highest cricket ground and a palace.",
    description:
      "Chail is a tranquil, pine-clad hill town built by the Maharaja of Patiala, home to the Chail Palace heritage hotel and the world's highest cricket and polo ground at 2,444 metres. Its wildlife sanctuary and quiet trails make it a peaceful alternative to busier resorts.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1900,
    recommendedDays: 1,
    bestMonths: "Mar,Apr,May,Jun,Sep,Oct,Nov",
    isHidden: true,
    popularity: 62,
    latitude: "30.9736217",
    longitude: "77.19904269999999",
  },
  {
    slug: "kullu-valley",
    name: "Kullu Valley",
    state: "Himachal Pradesh",
    district: "Kullu",
    category: "hill_station",
    placeType: "Valley",
    shortDescription: "Verdant 'Valley of the Gods' along the Beas, famed for Dussehra and river sports.",
    description:
      "The Kullu Valley, the 'Valley of the Gods', stretches along the Beas River amid apple orchards, deodar forests and temples. It is famed for its grand week-long Dussehra festival, river rafting near Babeli, and as the gateway to the higher Himalayan resorts.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2000,
    recommendedDays: 2,
    bestMonths: "Mar,Apr,May,Jun,Sep,Oct,Nov",
    isHidden: false,
    popularity: 78,
    latitude: "31.9645485",
    longitude: "77.1154578",
  },
  {
    slug: "manikaran-sahib",
    name: "Manikaran Sahib",
    state: "Himachal Pradesh",
    district: "Kullu",
    category: "pilgrimage",
    placeType: "Gurudwara",
    shortDescription: "Parvati Valley pilgrimage site with hot springs sacred to Sikhs and Hindus.",
    description:
      "Manikaran, in the Parvati Valley, is revered by both Sikhs and Hindus and is famed for its natural boiling hot springs, in which the gurudwara langar food is cooked. Pilgrims bathe in the sulphurous waters, and the riverside setting beneath steep peaks is dramatic.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1700,
    recommendedDays: 1,
    bestMonths: "Mar,Apr,May,Jun,Sep,Oct,Nov",
    isHidden: false,
    popularity: 70,
    latitude: "32.0270084",
    longitude: "77.3449107",
  },
  {
    slug: "kasol",
    name: "Kasol",
    state: "Himachal Pradesh",
    district: "Kullu",
    category: "hill_station",
    placeType: "Village",
    shortDescription: "Riverside Parvati Valley village popular with trekkers and backpackers.",
    description:
      "Kasol is a laid-back village on the banks of the Parvati River, a hub for backpackers, trekkers and cafés serving Israeli and local food. It is the base for treks to Kheerganga, Malana and Tosh, set amid pine forests and snow-fed streams.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1700,
    recommendedDays: 2,
    bestMonths: "Mar,Apr,May,Jun,Sep,Oct,Nov",
    isHidden: false,
    popularity: 76,
    latitude: "32.009968",
    longitude: "77.3150577",
  },
  {
    slug: "tosh-village",
    name: "Tosh",
    state: "Himachal Pradesh",
    district: "Kullu",
    category: "hill_station",
    placeType: "Village",
    shortDescription: "High Parvati Valley hamlet with snow-peak views and a mellow trekking vibe.",
    description:
      "Tosh is the last motorable village in the upper Parvati Valley, perched above the river with terraced fields and dramatic views of snow peaks. Its cafés and guesthouses draw trekkers and travellers seeking quiet, and it is a springboard for the Kheerganga trail.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1600,
    recommendedDays: 1,
    bestMonths: "Apr,May,Jun,Sep,Oct,Nov",
    isHidden: true,
    popularity: 62,
    latitude: "32.0400",
    longitude: "77.3800",
  },
  {
    slug: "malana-village",
    name: "Malana",
    state: "Himachal Pradesh",
    district: "Kullu",
    category: "hill_station",
    placeType: "Village",
    shortDescription: "Isolated ancient village with a unique culture and its own governance customs.",
    description:
      "Malana is an isolated Himalayan village reached by a trek over a ridge, known for its distinct language, ancient self-governing council and old customs that limit contact with outsiders. Surrounded by high peaks and the Malana Nala, it offers a glimpse of a singular culture.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1600,
    recommendedDays: 1,
    bestMonths: "Apr,May,Jun,Sep,Oct",
    isHidden: true,
    popularity: 58,
    latitude: "32.0570",
    longitude: "77.2600",
  },
  {
    slug: "dharamshala",
    name: "Dharamshala",
    state: "Himachal Pradesh",
    district: "Kangra",
    category: "hill_station",
    placeType: "Hill Station",
    shortDescription: "Kangra Valley hill town backed by the Dhauladhar range, gateway to McLeodganj.",
    description:
      "Dharamshala spreads across the forested slopes of the Kangra Valley beneath the towering Dhauladhar range. Home to a scenic cricket stadium and the gateway to Tibetan McLeodganj above, it blends colonial-era churches, tea gardens and Himalayan views.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2000,
    recommendedDays: 2,
    bestMonths: "Mar,Apr,May,Jun,Sep,Oct,Nov",
    isHidden: false,
    popularity: 82,
    latitude: "32.219042",
    longitude: "76.3234037",
  },
  {
    slug: "mcleodganj",
    name: "McLeodganj",
    state: "Himachal Pradesh",
    district: "Kangra",
    category: "hill_station",
    placeType: "Hill Station",
    shortDescription: "Tibetan hill enclave and seat of the Dalai Lama above Dharamshala.",
    description:
      "McLeodganj, perched above Dharamshala, is the heart of the Tibetan community in exile and home to the Dalai Lama's residence and the Tsuglagkhang complex. Its monasteries, cafés, prayer flags and mountain trails give it a distinctly Tibetan, spiritual atmosphere.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2000,
    recommendedDays: 2,
    bestMonths: "Mar,Apr,May,Jun,Sep,Oct,Nov",
    isHidden: false,
    popularity: 82,
    latitude: "32.2425758",
    longitude: "76.3212781",
  },
  {
    slug: "bhagsu-waterfall",
    name: "Bhagsu Waterfall",
    state: "Himachal Pradesh",
    district: "Kangra",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription: "Popular cascade near McLeodganj beside the ancient Bhagsunag temple.",
    description:
      "Bhagsu Waterfall tumbles down the hillside a short walk from McLeodganj, beside the ancient Bhagsunag Shiva temple. The trail passes cafés and leads up to the falls, which swell impressively during the monsoon and are a favourite easy hike from town.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1700,
    recommendedDays: 1,
    bestMonths: "Mar,Apr,May,Jun,Sep,Oct,Nov",
    isHidden: false,
    popularity: 68,
    latitude: "32.2484815",
    longitude: "76.3396356",
  },
  {
    slug: "triund-trek",
    name: "Triund",
    state: "Himachal Pradesh",
    district: "Kangra",
    category: "adventure",
    placeType: "Trek",
    shortDescription: "Popular short trek to a ridge camp under the Dhauladhar peaks.",
    description:
      "Triund is a hugely popular day or overnight trek from McLeodganj, climbing through oak and rhododendron forest to a grassy ridge at about 2,850 metres. The summit offers a magnificent close-up of the Dhauladhar snow wall on one side and the Kangra Valley on the other.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1700,
    recommendedDays: 1,
    bestMonths: "Mar,Apr,May,Jun,Sep,Oct,Nov",
    isHidden: false,
    popularity: 74,
    latitude: "32.2595821",
    longitude: "76.35649289999999",
  },
  {
    slug: "dalhousie",
    name: "Dalhousie",
    state: "Himachal Pradesh",
    district: "Chamba",
    category: "hill_station",
    placeType: "Hill Station",
    shortDescription: "Colonial hill station spread over five hills with pine forests and old churches.",
    description:
      "Dalhousie is a charming colonial-era hill station built across five hills, retaining Scottish and Victorian architecture, old churches and quiet mall roads. Set amid deodar and pine forests, it offers views of the Pir Panjal snows and easy access to Khajjiar and Chamba.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1900,
    recommendedDays: 2,
    bestMonths: "Mar,Apr,May,Jun,Sep,Oct,Nov",
    isHidden: false,
    popularity: 78,
    latitude: "32.5390",
    longitude: "75.9710",
  },
  {
    slug: "khajjiar",
    name: "Khajjiar",
    state: "Himachal Pradesh",
    district: "Chamba",
    category: "hill_station",
    placeType: "Meadow",
    shortDescription: "Emerald saucer-shaped meadow ringed by deodar forest, the 'Mini Switzerland of India'.",
    description:
      "Khajjiar is a broad, saucer-shaped grassy meadow encircled by dense deodar forest, with a small lake at its centre, earning the nickname 'Mini Switzerland of India'. Zorbing, horse rides and paragliding are on offer, with the Kalatop sanctuary nearby.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Mar,Apr,May,Jun,Sep,Oct,Nov",
    isHidden: false,
    popularity: 76,
    latitude: "32.5454945",
    longitude: "76.0559598",
  },
  {
    slug: "chamba-town",
    name: "Chamba",
    state: "Himachal Pradesh",
    district: "Chamba",
    category: "heritage",
    placeType: "Heritage Town",
    shortDescription: "Ancient Ravi-side town of stone temples, the Chowgan and Bhuri Singh Museum.",
    description:
      "Chamba is an ancient town on the banks of the Ravi, renowned for its cluster of stone shikhara temples such as the Lakshmi Narayan group, the grassy Chowgan promenade, and the Bhuri Singh Museum's Pahari miniature paintings and Chamba rumals.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1600,
    recommendedDays: 1,
    bestMonths: "Mar,Apr,May,Jun,Sep,Oct,Nov",
    isHidden: true,
    popularity: 56,
    latitude: "32.5533633",
    longitude: "76.1258083",
  },
  {
    slug: "kasauli",
    name: "Kasauli",
    state: "Himachal Pradesh",
    district: "Solan",
    category: "hill_station",
    placeType: "Hill Station",
    shortDescription: "Quaint cantonment hill town with colonial charm and forest walks.",
    description:
      "Kasauli is a small, tranquil cantonment hill town retaining Victorian-era buildings, cobbled lanes and pine and cedar forests. Sunset Point, Monkey Point and the Christ Church give gentle sightseeing, and its clean air and slow pace make it a relaxing getaway near Chandigarh.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1900,
    recommendedDays: 1,
    bestMonths: "Mar,Apr,May,Jun,Sep,Oct,Nov",
    isHidden: false,
    popularity: 70,
    latitude: "30.8975",
    longitude: "76.9691667",
  },
  {
    slug: "bir-billing",
    name: "Bir Billing",
    state: "Himachal Pradesh",
    district: "Kangra",
    category: "adventure",
    placeType: "Paragliding Site",
    shortDescription: "India's premier paragliding destination with a Tibetan colony at Bir.",
    description:
      "Bir Billing is regarded as one of the world's top paragliding sites, with take-off at Billing and landing at Bir amid the Kangra Valley. Bir also hosts a Tibetan colony with monasteries and cafés, and serves as a base for meditation retreats and mountain biking.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2100,
    recommendedDays: 2,
    bestMonths: "Mar,Apr,May,Jun,Oct,Nov",
    isHidden: false,
    popularity: 78,
    latitude: "32.0405757",
    longitude: "76.7112169",
  },
  {
    slug: "kalpa-kinnaur",
    name: "Kalpa",
    state: "Himachal Pradesh",
    district: "Kinnaur",
    category: "hill_station",
    placeType: "Village",
    shortDescription: "Kinnaur village facing the sacred Kinnaur Kailash peak amid apple orchards.",
    description:
      "Kalpa is a scenic village in Kinnaur set among apple orchards and pine forests, offering close-up views of the sacred Kinnaur Kailash range across the Sutlej valley. Old wooden temples, Suicide Point and the dramatic sunrise on the snow peaks are its highlights.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1800,
    recommendedDays: 2,
    bestMonths: "Apr,May,Jun,Sep,Oct,Nov",
    isHidden: true,
    popularity: 64,
    latitude: "31.5390",
    longitude: "78.2570",
  },
  {
    slug: "chitkul",
    name: "Chitkul",
    state: "Himachal Pradesh",
    district: "Kinnaur",
    category: "hill_station",
    placeType: "Village",
    shortDescription: "Last inhabited village near the Indo-Tibet border in the Sangla Valley.",
    description:
      "Chitkul is the last inhabited village toward the Indo-Tibet border, set in the upper Baspa (Sangla) Valley at around 3,450 metres. Its wooden houses, the Baspa River, old temple and pristine snow-fed meadows make it one of Himachal's most photogenic frontier hamlets.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "May,Jun,Jul,Aug,Sep,Oct",
    isHidden: true,
    popularity: 66,
    latitude: "31.3507872",
    longitude: "78.4366266",
  },
  {
    slug: "sangla-valley",
    name: "Sangla Valley",
    state: "Himachal Pradesh",
    district: "Kinnaur",
    category: "hill_station",
    placeType: "Valley",
    shortDescription: "Lush Baspa River valley in Kinnaur with orchards, forests and the Kamru Fort.",
    description:
      "The Sangla or Baspa Valley is a green Kinnauri valley of apple and apricot orchards, deodar forests and the fast-flowing Baspa River. The old wooden Kamru Fort-temple, trout streams and views of snow peaks make it a serene base en route to Chitkul.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1800,
    recommendedDays: 2,
    bestMonths: "Apr,May,Jun,Sep,Oct",
    isHidden: true,
    popularity: 62,
    latitude: "31.4254859",
    longitude: "78.26499559999999",
  },
  {
    slug: "naldehra",
    name: "Naldehra",
    state: "Himachal Pradesh",
    district: "Shimla",
    category: "hill_station",
    placeType: "Golf Course",
    shortDescription: "Scenic hill retreat near Shimla with one of India's oldest golf courses.",
    description:
      "Naldehra, about 22 km from Shimla, is a quiet cedar-forested spot famed for one of India's oldest and highest nine-hole golf courses, laid out by Lord Curzon. Horse rides, gentle walks and views over the Sutlej valley make it a relaxed day trip.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Mar,Apr,May,Jun,Sep,Oct,Nov",
    isHidden: true,
    popularity: 56,
    latitude: "31.1660",
    longitude: "77.2100",
  },
  {
    slug: "tattapani",
    name: "Tattapani",
    state: "Himachal Pradesh",
    district: "Mandi",
    category: "adventure",
    placeType: "Hot Springs",
    shortDescription: "Sulphur hot springs on the Sutlej banks, popular for riverside camping.",
    description:
      "Tattapani lies on the banks of the Sutlej River and is known for its natural sulphur hot springs believed to have healing properties. It is a popular spot for riverside camping, river rafting and a short drive to the Shiva caves, set in a warm low-altitude valley.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1700,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar,Apr",
    isHidden: true,
    popularity: 54,
    latitude: "31.2440",
    longitude: "77.0290",
  },
  {
    slug: "rewalsar-lake",
    name: "Rewalsar Lake",
    state: "Himachal Pradesh",
    district: "Mandi",
    category: "pilgrimage",
    placeType: "Sacred Lake",
    shortDescription: "Sacred midland lake holy to Buddhists, Hindus and Sikhs, with a giant Padmasambhava statue.",
    description:
      "Rewalsar (Tso Pema) is a small sacred lake revered by Buddhists, Hindus and Sikhs alike, ringed by monasteries, temples and a gurudwara. A towering statue of Guru Padmasambhava overlooks the water, and floating reed islands add to the site's mystique.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1600,
    recommendedDays: 1,
    bestMonths: "Mar,Apr,May,Jun,Sep,Oct,Nov",
    isHidden: true,
    popularity: 58,
    latitude: "31.6339811",
    longitude: "76.8335347",
  },
  {
    slug: "bilaspur-gobind-sagar",
    name: "Bilaspur (Gobind Sagar Lake)",
    state: "Himachal Pradesh",
    district: "Bilaspur",
    category: "adventure",
    placeType: "Reservoir",
    shortDescription: "Large reservoir behind the Bhakra Dam, offering water sports and boating.",
    description:
      "Gobind Sagar is a vast reservoir formed by the Bhakra Dam on the Sutlej near Bilaspur, ringed by low hills. It supports boating, water sports and seasonal fishing, and the surrounding town of Bilaspur serves as a gateway to Mandi and the higher hills.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1600,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar,Apr",
    isHidden: true,
    popularity: 50,
    latitude: "31.342677",
    longitude: "76.7524339",
  },
  {
    slug: "great-himalayan-national-park",
    name: "Great Himalayan National Park",
    state: "Himachal Pradesh",
    district: "Kullu",
    category: "wildlife",
    placeType: "National Park",
    shortDescription: "UNESCO-listed high-altitude park of alpine meadows, forests and rare Himalayan fauna.",
    description:
      "The Great Himalayan National Park is a UNESCO World Heritage Site protecting a rich swathe of the western Himalayas, from riverine forest to alpine meadow and glacier. It shelters species such as the Himalayan tahr, blue sheep and monal, and offers multi-day treks from Sairopa.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Himalayn_National_Park_01.jpg/1280px-Himalayn_National_Park_01.jpg",
    openingTimings: "6:00 AM - 5:00 PM",
    entryFees: 100,
    budgetPerDay: 2200,
    recommendedDays: 3,
    bestMonths: "Apr,May,Jun,Sep,Oct",
    isHidden: true,
    popularity: 60,
    latitude: "31.7300",
    longitude: "77.5500",
  },

  // ───────────────────────── JAMMU & KASHMIR ─────────────────────────
  {
    slug: "dal-lake",
    name: "Dal Lake",
    state: "Jammu & Kashmir",
    district: "Srinagar",
    category: "hill_station",
    placeType: "Lake",
    shortDescription: "Srinagar's iconic lake of shikaras, houseboats and floating gardens.",
    description:
      "Dal Lake is the shimmering centrepiece of Srinagar, famous for its ornate houseboats, gliding shikara boats, floating vegetable markets and Char Chinar island. Backed by the Zabarwan hills and Mughal gardens, it is the quintessential Kashmir experience.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2200,
    recommendedDays: 2,
    bestMonths: "Apr,May,Jun,Jul,Aug,Sep,Oct",
    isHidden: false,
    popularity: 92,
    latitude: "34.1105857",
    longitude: "74.86825689999999",
  },
  {
    slug: "nishat-bagh",
    name: "Nishat Bagh",
    state: "Jammu & Kashmir",
    district: "Srinagar",
    category: "heritage",
    placeType: "Mughal Garden",
    shortDescription: "Terraced Mughal 'Garden of Joy' descending toward Dal Lake.",
    description:
      "Nishat Bagh, the 'Garden of Joy', is a grand terraced Mughal garden laid out in 1633 on the eastern side of Dal Lake. Its twelve terraces, chinar trees, cascading water channels and fountains frame superb views of the lake and the Pir Panjal beyond.",
    imageUrl: null,
    openingTimings: "9:00 AM - 9:00 PM",
    entryFees: 24,
    budgetPerDay: 2000,
    recommendedDays: 1,
    bestMonths: "Apr,May,Jun,Jul,Aug,Sep,Oct",
    isHidden: false,
    popularity: 78,
    latitude: "34.1229156",
    longitude: "74.8793917",
  },
  {
    slug: "shalimar-bagh",
    name: "Shalimar Bagh",
    state: "Jammu & Kashmir",
    district: "Srinagar",
    category: "heritage",
    placeType: "Mughal Garden",
    shortDescription: "Emperor Jahangir's romantic Mughal garden of terraces and chinar avenues.",
    description:
      "Shalimar Bagh was built by Emperor Jahangir for his wife Nur Jahan in 1619, and remains one of the finest Mughal gardens, with terraced lawns, a central water canal, pavilions and rows of chinar trees. Its evening light show recounts its royal romance.",
    imageUrl: null,
    openingTimings: "9:30 AM - 6:30 PM",
    entryFees: 24,
    budgetPerDay: 2000,
    recommendedDays: 1,
    bestMonths: "Apr,May,Jun,Jul,Aug,Sep,Oct",
    isHidden: false,
    popularity: 80,
    latitude: "34.1495248",
    longitude: "74.87292459999999",
  },
  {
    slug: "chashme-shahi",
    name: "Chashme Shahi",
    state: "Jammu & Kashmir",
    district: "Srinagar",
    category: "heritage",
    placeType: "Mughal Garden",
    shortDescription: "Smallest of Srinagar's Mughal gardens, built around a natural spring.",
    description:
      "Chashme Shahi, the 'Royal Spring', is the smallest and most intimate of Srinagar's Mughal gardens, laid out in 1632 around a fresh mineral spring reputed for its clear water. Its compact terraces and fountains offer lovely elevated views of Dal Lake.",
    imageUrl: null,
    openingTimings: "9:00 AM - 6:00 PM",
    entryFees: 24,
    budgetPerDay: 2000,
    recommendedDays: 1,
    bestMonths: "Apr,May,Jun,Jul,Aug,Sep,Oct",
    isHidden: false,
    popularity: 72,
    latitude: "34.0858864",
    longitude: "74.8869056",
  },
  {
    slug: "shankaracharya-temple",
    name: "Shankaracharya Temple",
    state: "Jammu & Kashmir",
    district: "Srinagar",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Ancient hilltop Shiva temple with panoramic views over Srinagar and Dal Lake.",
    description:
      "The Shankaracharya Temple crowns a hill overlooking Srinagar, an ancient stone Shiva shrine reached by a long stair or road. Believed to date back many centuries, it offers sweeping panoramas of the city, Dal Lake and the encircling mountains.",
    imageUrl: null,
    openingTimings: "7:30 AM - 4:30 PM",
    entryFees: 0,
    budgetPerDay: 1900,
    recommendedDays: 1,
    bestMonths: "Apr,May,Jun,Jul,Aug,Sep,Oct",
    isHidden: false,
    popularity: 70,
    latitude: "34.0789274",
    longitude: "74.8436155",
  },
  {
    slug: "hazratbal-shrine",
    name: "Hazratbal Shrine",
    state: "Jammu & Kashmir",
    district: "Srinagar",
    category: "pilgrimage",
    placeType: "Mosque",
    shortDescription: "White-marble Muslim shrine on Dal Lake housing a relic of the Prophet.",
    description:
      "The Hazratbal Shrine on the northern shore of Dal Lake is Kashmir's holiest Muslim site, enshrining the Moi-e-Muqaddas, a relic believed to be a hair of the Prophet Muhammad. Its gleaming white marble dome reflects beautifully in the lake waters.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/HAZRATBAL_SHRINE_01.JPG/1280px-HAZRATBAL_SHRINE_01.JPG",
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1900,
    recommendedDays: 1,
    bestMonths: "Apr,May,Jun,Jul,Aug,Sep,Oct",
    isHidden: false,
    popularity: 68,
    latitude: "34.12888660000001",
    longitude: "74.8424915",
  },
  {
    slug: "gulmarg",
    name: "Gulmarg",
    state: "Jammu & Kashmir",
    district: "Baramulla",
    category: "hill_station",
    placeType: "Hill Station",
    shortDescription: "Alpine meadow resort famed for skiing and the high Gulmarg Gondola.",
    description:
      "Gulmarg, the 'Meadow of Flowers', is a premier Himalayan resort set at around 2,650 metres, blanketed in wildflowers in summer and snow in winter. Its gondola, one of the world's highest, rises toward Apharwat Peak, making it India's top skiing destination.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2400,
    recommendedDays: 2,
    bestMonths: "Dec,Jan,Feb,Mar,Apr,May,Jun,Sep,Oct",
    isHidden: false,
    popularity: 88,
    latitude: "34.0483704",
    longitude: "74.3804791",
  },
  {
    slug: "pahalgam",
    name: "Pahalgam",
    state: "Jammu & Kashmir",
    district: "Anantnag",
    category: "hill_station",
    placeType: "Hill Station",
    shortDescription: "Lidder Valley resort town, base for Amarnath yatra and river adventures.",
    description:
      "Pahalgam is a picturesque valley town where the Lidder River rushes past pine forests and meadows, and serves as a traditional base for the Amarnath pilgrimage. Nearby Aru and Betaab valleys, trout fishing and pony treks make it a hub for Kashmir's outdoors.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2200,
    recommendedDays: 2,
    bestMonths: "Apr,May,Jun,Jul,Aug,Sep,Oct",
    isHidden: false,
    popularity: 84,
    latitude: "34.0160751",
    longitude: "75.3149796",
  },
  {
    slug: "sonamarg",
    name: "Sonamarg",
    state: "Jammu & Kashmir",
    district: "Ganderbal",
    category: "hill_station",
    placeType: "Hill Station",
    shortDescription: "'Meadow of Gold' gateway to Ladakh, with glaciers and alpine lakes.",
    description:
      "Sonamarg, the 'Meadow of Gold', lies at around 2,800 metres on the road to Ladakh, surrounded by snow peaks and glaciers. Pony rides lead to the Thajiwas Glacier, and it is the trailhead for treks to high-altitude lakes such as Vishansar and Gangabal.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2200,
    recommendedDays: 2,
    bestMonths: "May,Jun,Jul,Aug,Sep,Oct",
    isHidden: false,
    popularity: 80,
    latitude: "34.3031616",
    longitude: "75.293111",
  },
  {
    slug: "betaab-valley",
    name: "Betaab Valley",
    state: "Jammu & Kashmir",
    district: "Anantnag",
    category: "hill_station",
    placeType: "Valley",
    shortDescription: "Lush green valley near Pahalgam ringed by snow peaks and a mountain stream.",
    description:
      "Betaab Valley, named after a Bollywood film shot here, is a verdant meadow near Pahalgam framed by pine-clad slopes and snow peaks, with a clear stream running through. Its lawns and picnic spots make it a favourite short excursion from Pahalgam.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 50,
    budgetPerDay: 2000,
    recommendedDays: 1,
    bestMonths: "Apr,May,Jun,Jul,Aug,Sep,Oct",
    isHidden: false,
    popularity: 72,
    latitude: "34.0290",
    longitude: "75.3480",
  },
  {
    slug: "aru-valley",
    name: "Aru Valley",
    state: "Jammu & Kashmir",
    district: "Anantnag",
    category: "hill_station",
    placeType: "Valley",
    shortDescription: "Quiet meadow village near Pahalgam and a base for high Himalayan treks.",
    description:
      "Aru Valley, about 12 km from Pahalgam, is a tranquil village set amid rolling meadows and the Aru River, far less crowded than the main town. It is a popular base for treks to Kolahoi Glacier and the Tarsar-Marsar lakes, with pony rides and camping.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1900,
    recommendedDays: 1,
    bestMonths: "May,Jun,Jul,Aug,Sep,Oct",
    isHidden: true,
    popularity: 64,
    latitude: "34.0921137",
    longitude: "75.2632113",
  },
  {
    slug: "yusmarg",
    name: "Yusmarg",
    state: "Jammu & Kashmir",
    district: "Budgam",
    category: "hill_station",
    placeType: "Meadow",
    shortDescription: "Offbeat pine-fringed meadow southwest of Srinagar with gentle trails.",
    description:
      "Yusmarg is a serene, less-visited meadow surrounded by pine forests and snow peaks southwest of Srinagar. Its rolling grasslands, the nearby Nilnag Lake and pony rides toward the Doodh Ganga stream make it a peaceful escape from the tourist crowds.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Apr,May,Jun,Jul,Aug,Sep,Oct",
    isHidden: true,
    popularity: 56,
    latitude: "33.8315828",
    longitude: "74.6644026",
  },
  {
    slug: "doodhpathri",
    name: "Doodhpathri",
    state: "Jammu & Kashmir",
    district: "Budgam",
    category: "hill_station",
    placeType: "Meadow",
    shortDescription: "'Valley of Milk' meadow of streams and pastures, an offbeat Kashmir gem.",
    description:
      "Doodhpathri, the 'Valley of Milk', is a broad alpine meadow threaded by frothy streams and carpeted with wildflowers in summer. Relatively untouched by mass tourism, it offers gentle walks, pine forests and views of distant snow peaks about 40 km from Srinagar.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Apr,May,Jun,Jul,Aug,Sep,Oct",
    isHidden: true,
    popularity: 58,
    latitude: "33.8300",
    longitude: "74.8500",
  },
  {
    slug: "vaishno-devi",
    name: "Vaishno Devi",
    state: "Jammu & Kashmir",
    district: "Reasi",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Revered cave shrine of the goddess in the Trikuta hills near Katra.",
    description:
      "The Vaishno Devi shrine is one of India's most visited Hindu pilgrimage sites, set in a cave high in the Trikuta hills. Devotees trek roughly 12 km uphill from Katra to worship the three natural pindis of the goddess, with helicopter and pony options also available.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1900,
    recommendedDays: 2,
    bestMonths: "Mar,Apr,May,Jun,Sep,Oct,Nov",
    isHidden: false,
    popularity: 86,
    latitude: "33.0308295",
    longitude: "74.9490416",
  },
  {
    slug: "patnitop",
    name: "Patnitop",
    state: "Jammu & Kashmir",
    district: "Udhampur",
    category: "hill_station",
    placeType: "Hill Station",
    shortDescription: "Forested hilltop resort on the Jammu-Srinagar highway with meadows and views.",
    description:
      "Patnitop is a popular hill resort perched at around 2,000 metres on the Jammu-Srinagar highway, surrounded by cedar forests and open meadows. It offers gentle walks, paragliding and skiing in winter, and views over the Chenab valley, with Nathatop and Sanasar nearby.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1900,
    recommendedDays: 1,
    bestMonths: "Mar,Apr,May,Jun,Sep,Oct,Nov,Dec",
    isHidden: false,
    popularity: 66,
    latitude: "33.0840",
    longitude: "75.3310",
  },
  {
    slug: "amarnath-cave",
    name: "Amarnath Cave",
    state: "Jammu & Kashmir",
    district: "Anantnag",
    category: "pilgrimage",
    placeType: "Cave Shrine",
    shortDescription: "High-altitude Shiva cave shrine with a natural ice lingam, focus of the Amarnath Yatra.",
    description:
      "The Amarnath Cave, at about 3,888 metres, enshrines a naturally forming ice stalagmite worshipped as a Shiva lingam. Each summer the Amarnath Yatra draws hundreds of thousands of pilgrims who trek from Pahalgam or Baltal through dramatic Himalayan terrain.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Cave_Temple_of_Lord_Amarnath.jpg/1280px-Cave_Temple_of_Lord_Amarnath.jpg",
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2200,
    recommendedDays: 2,
    bestMonths: "Jul,Aug",
    isHidden: false,
    popularity: 74,
    latitude: "34.2156918",
    longitude: "75.5041201",
  },

  // ───────────────────────── LADAKH ─────────────────────────
  {
    slug: "pangong-tso",
    name: "Pangong Tso",
    state: "Ladakh",
    district: "Leh",
    category: "adventure",
    placeType: "Lake",
    shortDescription: "High-altitude endorheic lake famed for its shifting blue hues, spanning India and Tibet.",
    description:
      "Pangong Tso is a spectacular high-altitude lake at around 4,350 metres, its waters shifting through vivid shades of blue against barren mountains. Straddling the India-China border, it is a highlight of any Ladakh trip, popular for lakeside camping and photography.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2600,
    recommendedDays: 2,
    bestMonths: "May,Jun,Jul,Aug,Sep",
    isHidden: false,
    popularity: 90,
    latitude: "33.7595131",
    longitude: "78.66744039999999",
  },
  {
    slug: "nubra-valley-hunder",
    name: "Nubra Valley (Hunder)",
    state: "Ladakh",
    district: "Leh",
    category: "adventure",
    placeType: "Valley",
    shortDescription: "High desert valley with sand dunes, double-humped camels and green oases.",
    description:
      "The Nubra Valley, reached over the high Khardung La pass, is a striking high-altitude cold desert where the Shyok and Nubra rivers meet. At Hunder, white sand dunes host rides on rare double-humped Bactrian camels, set against snow peaks and green villages.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2500,
    recommendedDays: 2,
    bestMonths: "May,Jun,Jul,Aug,Sep",
    isHidden: false,
    popularity: 84,
    latitude: "34.5760",
    longitude: "77.5000",
  },
  {
    slug: "diskit-monastery",
    name: "Diskit Monastery",
    state: "Ladakh",
    district: "Leh",
    category: "pilgrimage",
    placeType: "Monastery",
    shortDescription: "Oldest and largest Nubra Valley gompa, famed for its giant Maitreya Buddha statue.",
    description:
      "Diskit Monastery is the oldest and largest Buddhist gompa in the Nubra Valley, founded in the 14th century. Perched on a hill, it is crowned by a towering 32-metre statue of the Maitreya (Future) Buddha overlooking the Shyok River, with old prayer halls and murals within.",
    imageUrl: null,
    openingTimings: "7:00 AM - 6:00 PM",
    entryFees: 30,
    budgetPerDay: 2200,
    recommendedDays: 1,
    bestMonths: "May,Jun,Jul,Aug,Sep",
    isHidden: false,
    popularity: 74,
    latitude: "34.5412366",
    longitude: "77.5605683",
  },
  {
    slug: "thiksey-monastery",
    name: "Thiksey Monastery",
    state: "Ladakh",
    district: "Leh",
    category: "pilgrimage",
    placeType: "Monastery",
    shortDescription: "Grand hilltop gompa resembling the Potala Palace, with a huge Maitreya Buddha.",
    description:
      "Thiksey Monastery is one of Ladakh's most impressive gompas, its whitewashed buildings rising in tiers up a hill in a form often compared to Lhasa's Potala Palace. It houses a two-storey seated Maitreya Buddha, and its dawn prayer rituals draw many visitors.",
    imageUrl: null,
    openingTimings: "7:00 AM - 7:00 PM",
    entryFees: 30,
    budgetPerDay: 2200,
    recommendedDays: 1,
    bestMonths: "May,Jun,Jul,Aug,Sep,Oct",
    isHidden: false,
    popularity: 80,
    latitude: "34.0559137",
    longitude: "77.6677625",
  },
  {
    slug: "hemis-monastery",
    name: "Hemis Monastery",
    state: "Ladakh",
    district: "Leh",
    category: "pilgrimage",
    placeType: "Monastery",
    shortDescription: "Ladakh's largest and wealthiest gompa, famous for its vibrant masked festival.",
    description:
      "Hemis is the largest and richest monastery in Ladakh, tucked into a side valley south of Leh. Belonging to the Drukpa lineage, it is renowned for its June Hemis Festival with masked cham dances and for periodically unveiling one of the world's largest thangkas.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 100,
    budgetPerDay: 2200,
    recommendedDays: 1,
    bestMonths: "May,Jun,Jul,Aug,Sep",
    isHidden: false,
    popularity: 76,
    latitude: "33.9125964",
    longitude: "77.7029689",
  },
  {
    slug: "shey-monastery",
    name: "Shey Monastery & Palace",
    state: "Ladakh",
    district: "Leh",
    category: "pilgrimage",
    placeType: "Monastery",
    shortDescription: "Former royal summer palace and gompa with a large gilded Buddha near Leh.",
    description:
      "Shey was the ancient capital and summer palace of the kings of Ladakh, its ruined palace and monastery crowning a rocky ridge. The gompa houses a large gilded copper statue of Shakyamuni Buddha, and the surrounding plain is dotted with chortens and mani stones.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 20,
    budgetPerDay: 2100,
    recommendedDays: 1,
    bestMonths: "May,Jun,Jul,Aug,Sep,Oct",
    isHidden: true,
    popularity: 62,
    latitude: "34.071585",
    longitude: "77.6329015",
  },
  {
    slug: "magnetic-hill-ladakh",
    name: "Magnetic Hill",
    state: "Ladakh",
    district: "Leh",
    category: "adventure",
    placeType: "Natural Curiosity",
    shortDescription: "Optical-illusion 'gravity hill' where parked vehicles appear to roll uphill.",
    description:
      "Magnetic Hill on the Leh-Kargil road is a famous optical illusion where the surrounding slope makes vehicles left in neutral seem to roll uphill on their own. A marked spot lets visitors test the effect, set amid stark high-desert scenery near the Indus.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2100,
    recommendedDays: 1,
    bestMonths: "May,Jun,Jul,Aug,Sep",
    isHidden: false,
    popularity: 68,
    latitude: "34.2340",
    longitude: "77.3620",
  },
  {
    slug: "tso-moriri",
    name: "Tso Moriri",
    state: "Ladakh",
    district: "Leh",
    category: "adventure",
    placeType: "Lake",
    shortDescription: "Remote high-altitude Changthang lake and wetland reserve rich in birdlife.",
    description:
      "Tso Moriri is a serene, remote high-altitude lake in the Changthang region at about 4,500 metres, protected as a wetland reserve. Less crowded than Pangong, its still blue waters attract migratory birds like bar-headed geese and are ringed by nomadic Changpa pastures.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2600,
    recommendedDays: 2,
    bestMonths: "May,Jun,Jul,Aug,Sep",
    isHidden: true,
    popularity: 66,
    latitude: "32.9112291",
    longitude: "78.3159411",
  },
  {
    slug: "zanskar-valley",
    name: "Zanskar Valley",
    state: "Ladakh",
    district: "Kargil",
    category: "adventure",
    placeType: "Valley",
    shortDescription: "Remote high-mountain valley famed for the frozen-river Chadar trek and rafting.",
    description:
      "Zanskar is one of the most isolated inhabited valleys in the Himalayas, ringed by high passes and dotted with ancient monasteries like Karsha and Phugtal. It is renowned for river rafting on the Zanskar in summer and the winter Chadar trek over the frozen river.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2600,
    recommendedDays: 3,
    bestMonths: "Jun,Jul,Aug,Sep",
    isHidden: true,
    popularity: 68,
    latitude: "33.5000",
    longitude: "76.9000",
  },
  {
    slug: "lamayuru-monastery",
    name: "Lamayuru Monastery",
    state: "Ladakh",
    district: "Leh",
    category: "pilgrimage",
    placeType: "Monastery",
    shortDescription: "One of Ladakh's oldest gompas set amid eroded 'moonland' landscapes.",
    description:
      "Lamayuru is among the oldest and most spectacularly sited monasteries in Ladakh, perched above a surreal eroded terrain nicknamed 'moonland'. Its ancient prayer halls, cave shrines and annual masked festival, set against the lunar hills, make it unforgettable.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 50,
    budgetPerDay: 2200,
    recommendedDays: 1,
    bestMonths: "May,Jun,Jul,Aug,Sep",
    isHidden: true,
    popularity: 64,
    latitude: "34.2830375",
    longitude: "76.7741094",
  },
  {
    slug: "khardung-la",
    name: "Khardung La",
    state: "Ladakh",
    district: "Leh",
    category: "adventure",
    placeType: "Mountain Pass",
    shortDescription: "One of the world's highest motorable passes, gateway to the Nubra Valley.",
    description:
      "Khardung La is one of the world's highest motorable mountain passes at around 5,359 metres, the gateway from Leh into the Nubra and Shyok valleys. The thin air, prayer flags, snow and dramatic views make reaching the top a bucket-list moment for road trippers and bikers.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2400,
    recommendedDays: 1,
    bestMonths: "May,Jun,Jul,Aug,Sep",
    isHidden: false,
    popularity: 82,
    latitude: "34.2787271",
    longitude: "77.6046756",
  },
  {
    slug: "leh-palace",
    name: "Leh Palace",
    state: "Ladakh",
    district: "Leh",
    category: "heritage",
    placeType: "Palace",
    shortDescription: "Nine-storey 17th-century royal palace towering over Leh's old town.",
    description:
      "Leh Palace is a nine-storey former royal residence built in the 17th century, echoing the design of Lhasa's Potala Palace. Its mud-brick tiers rise above the old town, and the upper terraces offer sweeping views of Leh, the Indus valley and the Stok range.",
    imageUrl: null,
    openingTimings: "7:00 AM - 7:00 PM",
    entryFees: 40,
    budgetPerDay: 2100,
    recommendedDays: 1,
    bestMonths: "May,Jun,Jul,Aug,Sep,Oct",
    isHidden: false,
    popularity: 72,
    latitude: "34.1660308",
    longitude: "77.5871575",
  },
  {
    slug: "shanti-stupa-leh",
    name: "Shanti Stupa",
    state: "Ladakh",
    district: "Leh",
    category: "pilgrimage",
    placeType: "Stupa",
    shortDescription: "White-domed Japanese-built peace stupa with panoramic views over Leh.",
    description:
      "The Shanti Stupa is a gleaming white-domed Buddhist stupa built by Japanese monks in the 1980s to promote world peace, perched on a hill above Leh. Adorned with gilded reliefs of the Buddha, it offers superb sunrise and sunset views over the town and surrounding peaks.",
    imageUrl: null,
    openingTimings: "8:00 AM - 8:00 PM",
    entryFees: 0,
    budgetPerDay: 2000,
    recommendedDays: 1,
    bestMonths: "May,Jun,Jul,Aug,Sep,Oct",
    isHidden: false,
    popularity: 78,
    latitude: "34.17361959999999",
    longitude: "77.5749988",
  },

  // ───────────────────────── PUNJAB ─────────────────────────
  {
    slug: "golden-temple-amritsar",
    name: "Golden Temple (Harmandir Sahib)",
    state: "Punjab",
    district: "Amritsar",
    category: "pilgrimage",
    placeType: "Gurudwara",
    shortDescription: "Sikhism's holiest shrine, a gilded temple set in the sacred Amrit Sarovar.",
    description:
      "The Golden Temple, or Harmandir Sahib, is the holiest gurudwara of Sikhism, its gold-plated sanctum seeming to float in the sacred Amrit Sarovar tank. Pilgrims of all faiths are welcomed, join the world's largest free community kitchen (langar) and circle the marble parikrama.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 95,
    latitude: "31.6200",
    longitude: "74.8765",
  },
  {
    slug: "jallianwala-bagh",
    name: "Jallianwala Bagh",
    state: "Punjab",
    district: "Amritsar",
    category: "heritage",
    placeType: "Memorial",
    shortDescription: "Historic garden memorial to the victims of the 1919 massacre, near the Golden Temple.",
    description:
      "Jallianwala Bagh is a solemn memorial garden marking the site of the 1919 massacre, when British troops opened fire on a peaceful gathering. Preserved bullet marks on the walls, the martyrs' well and a flame-shaped memorial commemorate the tragedy, steps from the Golden Temple.",
    imageUrl: null,
    openingTimings: "9:00 AM - 5:00 PM",
    entryFees: 0,
    budgetPerDay: 1700,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 84,
    latitude: "31.6205869",
    longitude: "74.8802901",
  },
  {
    slug: "wagah-border",
    name: "Wagah Border Ceremony",
    state: "Punjab",
    district: "Amritsar",
    category: "heritage",
    placeType: "Border Ceremony",
    shortDescription: "Daily flag-lowering 'Beating Retreat' ceremony at the India-Pakistan border.",
    description:
      "The Wagah-Attari border, about 30 km from Amritsar, hosts a spirited daily 'Beating Retreat' ceremony in which Indian and Pakistani border forces perform synchronised, high-kicking drills before lowering their flags at sunset, drawing patriotic crowds on both sides.",
    imageUrl: null,
    openingTimings: "Ceremony around 4:15 PM - 5:00 PM",
    entryFees: 0,
    budgetPerDay: 1700,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 84,
    latitude: "31.6048091",
    longitude: "74.5741101",
  },
  {
    slug: "durgiana-temple",
    name: "Durgiana Temple",
    state: "Punjab",
    district: "Amritsar",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Hindu temple in Amritsar echoing the Golden Temple's design, set in a sacred tank.",
    description:
      "The Durgiana Temple, dedicated to Goddess Durga, mirrors the architecture of the Golden Temple with a gilded dome rising from the middle of a holy tank. A major Hindu shrine of Amritsar, it also honours Lakshmi and Narayan and glows attractively when lit at night.",
    imageUrl: null,
    openingTimings: "6:00 AM - 10:00 PM",
    entryFees: 0,
    budgetPerDay: 1600,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 60,
    latitude: "31.6272265",
    longitude: "74.8674364",
  },
  {
    slug: "anandpur-sahib",
    name: "Anandpur Sahib",
    state: "Punjab",
    district: "Rupnagar",
    category: "pilgrimage",
    placeType: "Gurudwara",
    shortDescription: "Sacred Sikh town, birthplace of the Khalsa and host of the Hola Mohalla festival.",
    description:
      "Anandpur Sahib, the 'City of Bliss', is one of Sikhism's holiest towns, where Guru Gobind Singh founded the Khalsa in 1699. Its grand Takht Sri Kesgarh Sahib gurudwara, the Virasat-e-Khalsa museum and the vibrant Hola Mohalla martial festival draw many pilgrims.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1600,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 68,
    latitude: "31.23508859999999",
    longitude: "76.4989336",
  },
  {
    slug: "ranjit-sagar-dam",
    name: "Ranjit Sagar Dam",
    state: "Punjab",
    district: "Pathankot",
    category: "adventure",
    placeType: "Reservoir",
    shortDescription: "Large hydroelectric reservoir on the Ravi with scenic hill-fringed waters.",
    description:
      "The Ranjit Sagar (Thein) Dam is a major hydroelectric project on the Ravi River near Pathankot, its expansive reservoir cradled by low hills at the Punjab-Himachal-J&K junction. The calm waters and surrounding scenery make it a pleasant picnic and viewpoint stop.",
    imageUrl: null,
    openingTimings: "9:00 AM - 5:00 PM",
    entryFees: 0,
    budgetPerDay: 1500,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 48,
    latitude: "32.4160",
    longitude: "75.6250",
  },
  {
    slug: "qila-mubarak-patiala",
    name: "Qila Mubarak (Patiala)",
    state: "Punjab",
    district: "Patiala",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Grand 18th-century royal fort complex in the heart of old Patiala.",
    description:
      "Qila Mubarak is a sprawling 18th-century fortified palace complex at the centre of Patiala, built by the erstwhile Sikh royal house. Its ornate palaces, painted halls, guest house and old bazaar reflect Patiala's regal past, though parts await restoration.",
    imageUrl: null,
    openingTimings: "9:00 AM - 5:00 PM",
    entryFees: 0,
    budgetPerDay: 1500,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: true,
    popularity: 52,
    latitude: "30.3390",
    longitude: "76.3910",
  },

  // ───────────────────────── HARYANA ─────────────────────────
  {
    slug: "brahma-sarovar-kurukshetra",
    name: "Brahma Sarovar (Kurukshetra)",
    state: "Haryana",
    district: "Kurukshetra",
    category: "pilgrimage",
    placeType: "Sacred Tank",
    shortDescription: "Vast sacred water tank at Kurukshetra, focal point of Gita-linked pilgrimage.",
    description:
      "The Brahma Sarovar is a huge sacred tank at Kurukshetra, the land linked to the Mahabharata and the Bhagavad Gita. Pilgrims bathe here especially during solar eclipses and the Gita Mahotsav, when the ghats, temples and evening aarti draw large gatherings.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1500,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 62,
    latitude: "29.9613554",
    longitude: "76.8285533",
  },
  {
    slug: "sultanpur-bird-sanctuary",
    name: "Sultanpur National Park",
    state: "Haryana",
    district: "Gurugram",
    category: "wildlife",
    placeType: "Bird Sanctuary",
    shortDescription: "Wetland bird sanctuary near Gurugram, a haven for migratory waterbirds.",
    description:
      "Sultanpur National Park is a compact wetland reserve near Gurugram that attracts numerous resident and migratory birds in winter, including flamingos, storks, herons and cranes. A raised walking trail and watchtowers make it a popular birdwatching escape from Delhi.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Sultanpur_Bird_Sanctuary%2C_Gurgaon.jpg/1280px-Sultanpur_Bird_Sanctuary%2C_Gurgaon.jpg",
    openingTimings: "7:00 AM - 4:30 PM",
    entryFees: 5,
    budgetPerDay: 1500,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 58,
    latitude: "28.4677325",
    longitude: "76.8920211",
  },
  {
    slug: "morni-hills",
    name: "Morni Hills",
    state: "Haryana",
    district: "Panchkula",
    category: "hill_station",
    placeType: "Hill Station",
    shortDescription: "Haryana's only hill station, a forested Shivalik retreat with twin lakes.",
    description:
      "Morni Hills is Haryana's only hill station, a low Shivalik range of pine and oak forests near Panchkula. Its twin Tikkar Tal lakes, an old fort, birdlife and gentle trails offer a cool, quiet getaway close to Chandigarh, with adventure and nature activities.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Mornihills.jpg/1280px-Mornihills.jpg",
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1600,
    recommendedDays: 1,
    bestMonths: "Feb,Mar,Apr,Sep,Oct,Nov",
    isHidden: true,
    popularity: 52,
    latitude: "30.6872672",
    longitude: "77.08774369999999",
  },
  {
    slug: "pinjore-gardens",
    name: "Pinjore Gardens (Yadavindra Gardens)",
    state: "Haryana",
    district: "Panchkula",
    category: "heritage",
    placeType: "Mughal Garden",
    shortDescription: "Terraced 17th-century Mughal garden of fountains, pavilions and lawns near Chandigarh.",
    description:
      "The Pinjore or Yadavindra Gardens are a beautifully preserved seven-terrace Mughal garden laid out in the 17th century, with water channels, fountains, fruit orchards and palace pavilions like Sheesh Mahal and Rang Mahal. Illuminated evenings and an annual festival add to its appeal.",
    imageUrl: null,
    openingTimings: "7:00 AM - 10:00 PM",
    entryFees: 30,
    budgetPerDay: 1600,
    recommendedDays: 1,
    bestMonths: "Feb,Mar,Apr,Sep,Oct,Nov",
    isHidden: false,
    popularity: 60,
    latitude: "30.7940877",
    longitude: "76.9147109",
  },
  {
    slug: "surajkund",
    name: "Surajkund",
    state: "Haryana",
    district: "Faridabad",
    category: "heritage",
    placeType: "Heritage Reservoir",
    shortDescription: "Ancient sun-shaped reservoir near Delhi, home to the famous crafts mela.",
    description:
      "Surajkund is a 10th-century amphitheatre-shaped reservoir built by the Tomar dynasty near Faridabad. It is best known today for hosting the vibrant Surajkund International Crafts Mela each February, a huge showcase of Indian handicrafts, folk arts and regional cuisines.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Suraj_Kund.jpg/1280px-Suraj_Kund.jpg",
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1600,
    recommendedDays: 1,
    bestMonths: "Feb,Oct,Nov,Dec,Jan",
    isHidden: true,
    popularity: 56,
    latitude: "28.4560",
    longitude: "77.2860",
  },

  // ───────────────────────── CHANDIGARH ─────────────────────────
  {
    slug: "rock-garden-chandigarh",
    name: "Rock Garden of Chandigarh",
    state: "Chandigarh",
    district: "Chandigarh",
    category: "heritage",
    placeType: "Sculpture Garden",
    shortDescription: "Sprawling fantasy garden of sculptures made from recycled waste by Nek Chand.",
    description:
      "The Rock Garden is Nek Chand's extraordinary 40-acre creation, a labyrinth of courtyards, waterfalls and thousands of sculptures fashioned from industrial and household waste like broken tiles, bangles and ceramics. It is one of India's most imaginative public artworks.",
    imageUrl: null,
    openingTimings: "9:00 AM - 6:00 PM",
    entryFees: 30,
    budgetPerDay: 1700,
    recommendedDays: 1,
    bestMonths: "Feb,Mar,Sep,Oct,Nov",
    isHidden: false,
    popularity: 80,
    latitude: "30.7529331",
    longitude: "76.80505409999999",
  },
  {
    slug: "sukhna-lake-chandigarh",
    name: "Sukhna Lake",
    state: "Chandigarh",
    district: "Chandigarh",
    category: "hill_station",
    placeType: "Lake",
    shortDescription: "Scenic man-made lake at the Shivalik foothills, popular for boating and strolls.",
    description:
      "Sukhna Lake is a tranquil rainfed reservoir at the foot of the Shivalik hills, a favourite Chandigarh spot for morning walks, jogging, boating and birdwatching. Its long promenade, gardens and views of distant hills make it especially pleasant at sunrise and sunset.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1700,
    recommendedDays: 1,
    bestMonths: "Feb,Mar,Sep,Oct,Nov,Dec",
    isHidden: false,
    popularity: 74,
    latitude: "30.7447621",
    longitude: "76.8105866",
  },
  {
    slug: "rose-garden-chandigarh",
    name: "Zakir Hussain Rose Garden",
    state: "Chandigarh",
    district: "Chandigarh",
    category: "heritage",
    placeType: "Garden",
    shortDescription: "Asia's largest rose garden with thousands of rose varieties and medicinal plants.",
    description:
      "The Zakir Hussain Rose Garden is said to be Asia's largest rose garden, spread over 30 acres in Sector 16 with thousands of rose bushes across hundreds of varieties, plus medicinal and flowering trees. The annual Rose Festival in spring fills it with colour and crowds.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1600,
    recommendedDays: 1,
    bestMonths: "Feb,Mar,Oct,Nov,Dec",
    isHidden: false,
    popularity: 66,
    latitude: "30.7470353",
    longitude: "76.782881",
  },
];
