import type { NewDestination } from "../schema";

// West India — Gujarat, Maharashtra, Goa, Daman & Diu, Dadra & Nagar Haveli
export const westIndiaDestinations: Omit<NewDestination, "id" | "createdAt">[] = [
  // ===================== GUJARAT =====================
  {
    slug: "statue-of-unity",
    name: "Statue of Unity",
    state: "Gujarat",
    district: "Narmada",
    category: "heritage",
    placeType: "Monument",
    shortDescription: "World's tallest statue (182 m) of Sardar Vallabhbhai Patel beside the Sardar Sarovar Dam on the Narmada.",
    description: "The 182-metre bronze-clad statue of Sardar Vallabhbhai Patel is the tallest in the world, standing on Sadhu Bet island near the Sardar Sarovar Dam. A high-speed lift takes visitors to a viewing gallery at the statue's chest. The complex includes the Valley of Flowers, a jungle safari, laser show and river cruises.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Statue_of_Unity.jpg/1280px-Statue_of_Unity.jpg",
    openingTimings: "8:00 AM - 6:00 PM (closed Mon)",
    entryFees: 150,
    budgetPerDay: 2500,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 92,
    latitude: "21.8384759",
    longitude: "73.719295",
  },
  {
    slug: "somnath-temple",
    name: "Somnath Temple",
    state: "Gujarat",
    district: "Gir Somnath",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "First among the twelve Jyotirlinga shrines of Shiva, rebuilt on the Arabian Sea coast at Prabhas Patan.",
    description: "Somnath is revered as the first of the twelve Jyotirlingas of Lord Shiva and has been rebuilt several times through history. The present Chalukya-style temple stands dramatically on the shore of the Arabian Sea. A nightly sound-and-light show narrates the temple's storied past.",
    imageUrl: null,
    openingTimings: "6:00 AM - 10:00 PM",
    entryFees: 0,
    budgetPerDay: 1600,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 88,
    latitude: "20.8880",
    longitude: "70.4013",
  },
  {
    slug: "dwarka-dwarkadhish",
    name: "Dwarkadhish Temple, Dwarka",
    state: "Gujarat",
    district: "Devbhumi Dwarka",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Char Dham temple of Lord Krishna on the Gomti creek, with a soaring five-storey spire and flag ceremony.",
    description: "The Dwarkadhish Temple, or Jagat Mandir, honours Lord Krishna as the king of Dwarka and is one of the Char Dham pilgrimage sites. Its 78-metre spire flies a large flag changed several times daily. Pilgrims also visit the nearby Gomti Ghat and take a boat to Bet Dwarka.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0c/Dwarakadheesh_Temple%2C_2014.jpg",
    openingTimings: "7:00 AM - 12:30 PM, 5:00 PM - 9:00 PM",
    entryFees: 0,
    budgetPerDay: 1600,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 85,
    latitude: "22.2376811",
    longitude: "68.96735819999999",
  },
  {
    slug: "bet-dwarka",
    name: "Bet Dwarka",
    state: "Gujarat",
    district: "Devbhumi Dwarka",
    category: "pilgrimage",
    placeType: "Island",
    shortDescription: "Sacred island reached by boat from Okha, believed to be Krishna's residence, with temples and quiet beaches.",
    description: "Bet Dwarka is an island off the Okha coast, held to be the place where Lord Krishna lived with his family. A short ferry ride brings pilgrims to the Krishna temple and a cluster of shrines. The island also has undeveloped beaches and dolphin sightings on the crossing.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1500,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 70,
    latitude: "22.4575896",
    longitude: "69.1000033",
  },
  {
    slug: "nageshwar-jyotirlinga",
    name: "Nageshwar Jyotirlinga",
    state: "Gujarat",
    district: "Devbhumi Dwarka",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "One of the twelve Jyotirlingas near Dwarka, marked by a giant seated Shiva statue.",
    description: "Nageshwar is one of the twelve sacred Jyotirlinga shrines of Shiva, set between Dwarka and Bet Dwarka. A towering statue of a seated Shiva marks the temple grounds. It is a common stop on the Dwarka pilgrimage circuit.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Nageshwar.JPG/1280px-Nageshwar.JPG",
    openingTimings: "6:00 AM - 9:00 PM",
    entryFees: 0,
    budgetPerDay: 1400,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 66,
    latitude: "22.3360612",
    longitude: "69.0870145",
  },
  {
    slug: "gir-national-park",
    name: "Gir National Park",
    state: "Gujarat",
    district: "Junagadh",
    category: "wildlife",
    placeType: "National Park",
    shortDescription: "The last natural home of the Asiatic lion, with jeep safaris through dry teak and acacia forest.",
    description: "Gir is the only place on earth where the endangered Asiatic lion survives in the wild, alongside leopards, deer and over 300 bird species. Jeep safaris depart from Sasan Gir into the rugged deciduous forest. The Devalia interpretation zone offers a more assured lion sighting.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/90/Gir_lion-Gir_forest%2Cjunagadh%2Cgujarat%2Cindia.jpeg",
    openingTimings: "6:00 AM - 5:00 PM (closed mid-Jun to mid-Oct)",
    entryFees: 800,
    budgetPerDay: 3000,
    recommendedDays: 2,
    bestMonths: "Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 87,
    latitude: "21.1245",
    longitude: "70.7938",
  },
  {
    slug: "rann-of-kutch-white-desert",
    name: "Rann of Kutch (White Desert)",
    state: "Gujarat",
    district: "Kutch",
    category: "heritage",
    placeType: "Salt Desert",
    shortDescription: "Vast white salt marsh near Dhordo, glowing under the full moon and host to the Rann Utsav festival.",
    description: "The Great Rann of Kutch is a seemingly endless expanse of white salt flats that shimmer under moonlight. The winter Rann Utsav sets up a vibrant tent city near Dhordo with folk music, crafts and camel rides. Sunset and full-moon nights over the salt are the signature experiences.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 100,
    budgetPerDay: 3000,
    recommendedDays: 2,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 90,
    latitude: "23.9822",
    longitude: "69.1330",
  },
  {
    slug: "kalo-dungar-black-hill",
    name: "Kalo Dungar (Black Hill)",
    state: "Gujarat",
    district: "Kutch",
    category: "adventure",
    placeType: "Viewpoint",
    shortDescription: "Highest point in Kutch with panoramic views over the white Rann and a hilltop Dattatreya temple.",
    description: "Kalo Dungar, or Black Hill, is the highest point in Kutch and offers sweeping views across the white salt desert toward the Pakistan border. A 400-year-old Dattatreya temple crowns the hill. The vantage is especially popular at sunset.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Rann_of_Kutch_-_Highest_Point.jpg/1280px-Rann_of_Kutch_-_Highest_Point.jpg",
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2200,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 68,
    latitude: "23.9344982",
    longitude: "69.81448350000001",
  },
  {
    slug: "bhuj-city",
    name: "Bhuj",
    state: "Gujarat",
    district: "Kutch",
    category: "heritage",
    placeType: "Heritage City",
    shortDescription: "Historic capital of Kutch with the Aina Mahal, Prag Mahal palace and colourful craft villages nearby.",
    description: "Bhuj is the gateway city to Kutch, rebuilt after the 2001 earthquake yet retaining royal landmarks like the mirror-walled Aina Mahal and Italian-Gothic Prag Mahal. The Kutch Museum showcases regional crafts and tribal culture. Artisan villages such as Ajrakhpur and Nirona lie a short drive away.",
    imageUrl: null,
    openingTimings: "9:00 AM - 6:00 PM",
    entryFees: 20,
    budgetPerDay: 2000,
    recommendedDays: 2,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 72,
    latitude: "23.2419997",
    longitude: "69.6669324",
  },
  {
    slug: "mandvi-beach-kutch",
    name: "Mandvi Beach",
    state: "Gujarat",
    district: "Kutch",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Clean, wind-swept beach near Mandvi town with the seaside Vijay Vilas Palace and old shipbuilding yards.",
    description: "Mandvi Beach is a broad, breezy stretch of sand on the Kutch coast, popular for camel rides and quiet sunsets. The nearby Vijay Vilas Palace served as a royal summer retreat and film location. Traditional wooden dhow shipbuilding still continues along the Rukmavati river.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/af/Mandvi_Beach.jpg",
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 69,
    latitude: "22.8280",
    longitude: "69.3480",
  },
  {
    slug: "wild-ass-sanctuary-little-rann",
    name: "Wild Ass Sanctuary, Little Rann of Kutch",
    state: "Gujarat",
    district: "Surendranagar",
    category: "wildlife",
    placeType: "Wildlife Sanctuary",
    shortDescription: "Only home of the Indian wild ass, set across the saline flats of the Little Rann with flamingos and blackbuck.",
    description: "The Little Rann of Kutch is the last refuge of the endangered Indian wild ass, which roams the vast saline grassland known as bets. Safaris also reveal blackbuck, nilgai, flamingos and pelicans. The sanctuary is a mosaic of salt pans, marshes and seasonal wetlands.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/33/Asiatic_Wild_Ass.jpeg",
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 250,
    budgetPerDay: 2600,
    recommendedDays: 2,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 62,
    latitude: "23.3167",
    longitude: "71.2333",
  },
  {
    slug: "ahmedabad-heritage-city",
    name: "Ahmedabad Old City (Heritage Walk)",
    state: "Gujarat",
    district: "Ahmedabad",
    category: "heritage",
    placeType: "Heritage City",
    shortDescription: "India's first UNESCO World Heritage City, with carved pols, Jama Masjid and intricate stepwells.",
    description: "The walled old city of Ahmedabad is India's first UNESCO World Heritage City, famed for its dense pols (traditional neighbourhoods), ornate wooden havelis and the 15th-century Jama Masjid. A morning heritage walk winds past bird feeders, secret passages and carved facades. Sabarmati riverfront and street food add to the experience.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2000,
    recommendedDays: 2,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 80,
    latitude: "23.0225",
    longitude: "72.5714",
  },
  {
    slug: "sabarmati-ashram",
    name: "Sabarmati Ashram",
    state: "Gujarat",
    district: "Ahmedabad",
    category: "heritage",
    placeType: "Museum",
    shortDescription: "Mahatma Gandhi's riverside ashram and home during the freedom struggle, now a museum and memorial.",
    description: "Sabarmati Ashram was Mahatma Gandhi's home from 1917 to 1930 and the launch point of the historic Dandi Salt March. The tranquil riverside campus preserves Gandhi's living quarters, letters and spinning wheel. A museum, Hriday Kunj, displays photographs and personal effects.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/GANDHI_ASHRAM_03.jpg/1280px-GANDHI_ASHRAM_03.jpg",
    openingTimings: "10:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 78,
    latitude: "23.0606577",
    longitude: "72.5803299",
  },
  {
    slug: "adalaj-stepwell",
    name: "Adalaj Stepwell",
    state: "Gujarat",
    district: "Gandhinagar",
    category: "heritage",
    placeType: "Stepwell",
    shortDescription: "Five-storey 15th-century stepwell with fusion Hindu-Islamic carvings, cool even in peak summer.",
    description: "The Adalaj Vav is an exquisitely carved five-storey stepwell built in 1498, blending Hindu and Islamic motifs across its octagonal platforms. Descending into it, temperatures drop noticeably below the surface heat. Intricate friezes depict flowers, elephants and everyday life.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Adalaj_ki_Vav_Gujarat_240A1370_72.jpg/1280px-Adalaj_ki_Vav_Gujarat_240A1370_72.jpg",
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 25,
    budgetPerDay: 1600,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 71,
    latitude: "23.1668106",
    longitude: "72.5800895",
  },
  {
    slug: "rani-ki-vav-patan",
    name: "Rani ki Vav, Patan",
    state: "Gujarat",
    district: "Patan",
    category: "heritage",
    placeType: "Stepwell",
    shortDescription: "UNESCO-listed 11th-century queen's stepwell with hundreds of sculptural panels, featured on the ₹100 note.",
    description: "Rani ki Vav is an inverted-temple stepwell built in the 11th century by Queen Udayamati, celebrated for its seven storeys of over 500 principal sculptures. A UNESCO World Heritage Site, it depicts avatars of Vishnu and celestial figures in extraordinary detail. It appears on the reverse of the Indian ₹100 note.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Rani_ki_vav_02.jpg/1280px-Rani_ki_vav_02.jpg",
    openingTimings: "7:00 AM - 6:00 PM",
    entryFees: 40,
    budgetPerDay: 1700,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 79,
    latitude: "23.858924",
    longitude: "72.101933",
  },
  {
    slug: "modhera-sun-temple",
    name: "Modhera Sun Temple",
    state: "Gujarat",
    district: "Mehsana",
    category: "heritage",
    placeType: "Temple",
    shortDescription: "11th-century Solanki-era temple to Surya with a stepped tank, aligned so sunlight lights the sanctum.",
    description: "The Sun Temple at Modhera, built in 1026 under the Solanki dynasty, is dedicated to Surya and famed for its finely carved Surya Kund stepped tank. The complex is oriented so the rising equinox sun illuminates the sanctum. A classical dance festival is held here each January.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Surya_mandhir.jpg/1280px-Surya_mandhir.jpg",
    openingTimings: "7:00 AM - 6:00 PM",
    entryFees: 40,
    budgetPerDay: 1700,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 76,
    latitude: "23.5835889",
    longitude: "72.1329763",
  },
  {
    slug: "champaner-pavagadh",
    name: "Champaner-Pavagadh Archaeological Park",
    state: "Gujarat",
    district: "Panchmahal",
    category: "heritage",
    placeType: "Heritage Site",
    shortDescription: "UNESCO park of medieval mosques, forts and the Kalika Mata hilltop temple on Pavagadh.",
    description: "Champaner-Pavagadh is a UNESCO World Heritage Site combining a sacked medieval city with the sacred Pavagadh hill. Sultanate-era mosques such as the Jama Masjid display superb stone carving. A ropeway carries pilgrims up to the Kalika Mata temple crowning the hill.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/86/Jain_Temple%2C_Pavagadh_%28cropped%29.jpg",
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 40,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 70,
    latitude: "22.4858293",
    longitude: "73.5372445",
  },
  {
    slug: "girnar-hill-junagadh",
    name: "Girnar Hill",
    state: "Gujarat",
    district: "Junagadh",
    category: "pilgrimage",
    placeType: "Sacred Mountain",
    shortDescription: "Sacred mountain above Junagadh with Jain and Hindu temples, reached by ~9,000 steps or a ropeway.",
    description: "Girnar is a revered mountain rising above Junagadh, sacred to both Jains and Hindus, dotted with ancient temples along its climb. Pilgrims ascend roughly 9,000 stone steps, or take the modern ropeway, past Jain shrines to the Ambaji and Dattatreya peaks. It is one of Gujarat's most important pilgrimage climbs.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e1/Girnar_1.jpg",
    openingTimings: "6:30 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1800,
    recommendedDays: 2,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 75,
    latitude: "21.5000",
    longitude: "70.5000",
  },
  {
    slug: "uparkot-fort-junagadh",
    name: "Uparkot Fort, Junagadh",
    state: "Gujarat",
    district: "Junagadh",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Ancient hilltop fort of Junagadh with rock-cut Buddhist caves, stepwells and old cannons.",
    description: "Uparkot Fort has guarded Junagadh for over two millennia and hides Buddhist rock-cut caves, the deep Adi-Kadi Vav and Navghan Kuvo stepwells. Massive gateways and old cannons recall repeated sieges. Recently restored, it offers views over the city toward Girnar.",
    imageUrl: null,
    openingTimings: "8:00 AM - 4:00 PM",
    entryFees: 25,
    budgetPerDay: 1600,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 63,
    latitude: "21.5258099",
    longitude: "70.4704295",
  },
  {
    slug: "palitana-shatrunjaya",
    name: "Palitana Jain Temples (Shatrunjaya)",
    state: "Gujarat",
    district: "Bhavnagar",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Cluster of ~900 marble Jain temples atop Shatrunjaya Hill, one of Jainism's holiest sites.",
    description: "The Shatrunjaya Hill above Palitana holds nearly 900 intricately carved marble Jain temples, making it one of the faith's most sacred pilgrimage summits. Devotees climb around 3,500 steps, ideally by dawn, to reach the temple city. No one is permitted to stay overnight on the sacred hill.",
    imageUrl: null,
    openingTimings: "6:00 AM - 7:00 PM",
    entryFees: 0,
    budgetPerDay: 1600,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 72,
    latitude: "21.4859",
    longitude: "71.9047",
  },
  {
    slug: "saputara-hill-station",
    name: "Saputara",
    state: "Gujarat",
    district: "Dang",
    category: "hill_station",
    placeType: "Hill Station",
    shortDescription: "Gujarat's only hill station in the Sahyadris, with a boating lake, ropeway and tribal culture.",
    description: "Saputara is Gujarat's sole hill station, set amid the forested Sahyadri ranges near the Maharashtra border. Attractions include a boating lake, a ropeway to Sunset Point, a tribal museum and the Gira waterfalls nearby. Cool weather and monsoon greenery make it a favourite weekend escape.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Lake_Saputara.jpg/1280px-Lake_Saputara.jpg",
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2000,
    recommendedDays: 2,
    bestMonths: "Jul,Aug,Sep,Oct,Nov",
    isHidden: false,
    popularity: 70,
    latitude: "20.5796869",
    longitude: "73.7467691",
  },
  {
    slug: "laxmi-vilas-palace-vadodara",
    name: "Laxmi Vilas Palace, Vadodara",
    state: "Gujarat",
    district: "Vadodara",
    category: "heritage",
    placeType: "Palace",
    shortDescription: "Opulent Indo-Saracenic palace of the Gaekwads, reputedly four times the size of Buckingham Palace.",
    description: "Laxmi Vilas Palace, built in 1890 for the Gaekwad rulers of Baroda, is a sprawling Indo-Saracenic mansion still used as a royal residence. Its grand Durbar Hall features Venetian mosaic floors and Belgian stained glass. The grounds hold a museum, a golf course and the Moti Bagh palace.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Lakshmi_Vilas_Palace%2C_Vadodara.jpg/1280px-Lakshmi_Vilas_Palace%2C_Vadodara.jpg",
    openingTimings: "9:30 AM - 5:00 PM (closed Mon)",
    entryFees: 225,
    budgetPerDay: 2000,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 68,
    latitude: "22.2939855",
    longitude: "73.19170079999999",
  },
  {
    slug: "diu-island-note",
    name: "Marine National Park, Gulf of Kutch",
    state: "Gujarat",
    district: "Jamnagar",
    category: "wildlife",
    placeType: "Marine Park",
    shortDescription: "India's first marine national park in the Gulf of Kutch, with coral reefs, mangroves and inter-tidal life.",
    description: "The Marine National Park in the Gulf of Kutch was India's first, protecting a chain of islands, coral reefs and mangroves off Jamnagar. At low tide, walkers explore reefs alive with octopus, sea anemones, starfish and colourful corals. It is also a key wintering ground for migratory birds.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/The_Vast_Expanse_of_Narara_Sea_Bed_during_Low_Tide_of_Narara_Marine_National_Park.jpg/1280px-The_Vast_Expanse_of_Narara_Sea_Bed_during_Low_Tide_of_Narara_Marine_National_Park.jpg",
    openingTimings: "Tide-dependent daylight hours",
    entryFees: 100,
    budgetPerDay: 2200,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 58,
    latitude: "22.4500",
    longitude: "69.8000",
  },
  {
    slug: "polo-forest-vijaynagar",
    name: "Polo Forest (Vijaynagar)",
    state: "Gujarat",
    district: "Sabarkantha",
    category: "adventure",
    placeType: "Forest",
    shortDescription: "Lush Aravalli forest with 15th-century ruined temples, the Harnav river and monsoon greenery.",
    description: "The Polo Forest near Vijaynagar spreads across the Aravalli foothills, hiding ruined Hindu and Jain temples from the 10th to 15th centuries among dense woods. The Harnav river and seasonal waterfalls draw campers and trekkers. It is a rewarding offbeat weekend base for birding and heritage hikes.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1800,
    recommendedDays: 2,
    bestMonths: "Jul,Aug,Sep,Oct,Nov",
    isHidden: false,
    popularity: 55,
    latitude: "23.9330",
    longitude: "73.2500",
  },
  {
    slug: "kankaria-lake-ahmedabad",
    name: "Kankaria Lake",
    state: "Gujarat",
    district: "Ahmedabad",
    category: "heritage",
    placeType: "Lake",
    shortDescription: "Historic 15th-century polygonal lake in Ahmedabad, now a lively lakefront with a zoo and toy train.",
    description: "Kankaria Lake is a large 15th-century artificial lake in southern Ahmedabad, redeveloped into a family lakefront. The promenade features a zoo, balloon rides, a toy train and food stalls, with an island garden at the centre. Evenings draw crowds for the illuminated waterside walk.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Kankaria_Carnival_2_Ahmedabad.JPG/1280px-Kankaria_Carnival_2_Ahmedabad.JPG",
    openingTimings: "9:00 AM - 10:00 PM (closed Mon)",
    entryFees: 25,
    budgetPerDay: 1600,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 66,
    latitude: "23.0062573",
    longitude: "72.60255029999999",
  },
  {
    slug: "velavadar-blackbuck-park",
    name: "Velavadar Blackbuck National Park",
    state: "Gujarat",
    district: "Bhavnagar",
    category: "wildlife",
    placeType: "National Park",
    shortDescription: "Golden grassland park famed for blackbuck herds, wolves and one of the world's largest harrier roosts.",
    description: "Velavadar protects a rare tropical grassland where large herds of graceful blackbuck bound across golden savanna. It is one of the best places in India to see the Indian wolf and hosts a huge winter roost of migratory harriers. The flat plains and big skies make for striking safaris.",
    imageUrl: null,
    openingTimings: "7:00 AM - 6:00 PM",
    entryFees: 250,
    budgetPerDay: 2400,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 60,
    latitude: "22.0439431",
    longitude: "72.0204603",
  },

  // ===================== MAHARASHTRA =====================
  {
    slug: "gateway-of-india",
    name: "Gateway of India",
    state: "Maharashtra",
    district: "Mumbai",
    category: "heritage",
    placeType: "Monument",
    shortDescription: "Iconic basalt arch monument on the Mumbai waterfront overlooking the Arabian Sea.",
    description: "The Gateway of India is a 26-metre basalt triumphal arch built to commemorate the 1911 royal visit of King George V. Standing at Apollo Bunder, it is Mumbai's most recognisable landmark and the departure point for ferries to Elephanta. The waterfront buzzes with vendors, boats and the grand Taj Mahal Palace hotel opposite.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Mumbai_03-2016_30_Gateway_of_India.jpg/1280px-Mumbai_03-2016_30_Gateway_of_India.jpg",
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2500,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 90,
    latitude: "18.9219841",
    longitude: "72.8346543",
  },
  {
    slug: "elephanta-caves",
    name: "Elephanta Caves",
    state: "Maharashtra",
    district: "Mumbai",
    category: "heritage",
    placeType: "Cave",
    shortDescription: "UNESCO rock-cut island caves off Mumbai, famed for the colossal three-faced Trimurti of Shiva.",
    description: "The Elephanta Caves, on an island an hour's ferry from the Gateway of India, are a UNESCO World Heritage Site of rock-cut Hindu temples dating to the 5th-8th centuries. The main cave centres on the magnificent Trimurti, a three-faced sculpture of Shiva. Steep steps and monkeys accompany the climb to the caves.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Elephanta_Caves_Trimurti.jpg/1280px-Elephanta_Caves_Trimurti.jpg",
    openingTimings: "9:00 AM - 5:30 PM (closed Mon)",
    entryFees: 40,
    budgetPerDay: 2400,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 82,
    latitude: "18.9633474",
    longitude: "72.9314864",
  },
  {
    slug: "marine-drive-mumbai",
    name: "Marine Drive",
    state: "Maharashtra",
    district: "Mumbai",
    category: "heritage",
    placeType: "Promenade",
    shortDescription: "Sweeping 3.6 km seafront boulevard in Mumbai, its curved night-lights nicknamed the Queen's Necklace.",
    description: "Marine Drive is a 3.6-kilometre arc of promenade along the Arabian Sea, lined with Art Deco buildings. Its curving string of street lights earns the nickname 'Queen's Necklace' after dark. Locals gather here at sunset and into the night for sea breeze, snacks and city views ending at Chowpatty Beach.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Mumbai_03-2016_27_skyline_at_Marine_Drive.jpg/1280px-Mumbai_03-2016_27_skyline_at_Marine_Drive.jpg",
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2500,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 85,
    latitude: "18.943994",
    longitude: "72.822581",
  },
  {
    slug: "chhatrapati-shivaji-terminus",
    name: "Chhatrapati Shivaji Maharaj Terminus",
    state: "Maharashtra",
    district: "Mumbai",
    category: "heritage",
    placeType: "Monument",
    shortDescription: "UNESCO Victorian-Gothic railway station, Mumbai's ornate 1888 architectural landmark.",
    description: "Chhatrapati Shivaji Maharaj Terminus, formerly Victoria Terminus, is a UNESCO World Heritage Site and one of the finest Victorian-Gothic buildings in India. Completed in 1888, it blends Italianate and traditional Indian design with turrets, gargoyles and a grand central dome. It remains a working railway hub and photographic icon of Mumbai.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Chhatrapati_shivaji_terminus%2C_esterno_01.jpg/1280px-Chhatrapati_shivaji_terminus%2C_esterno_01.jpg",
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2400,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 79,
    latitude: "18.9398446",
    longitude: "72.8354475",
  },
  {
    slug: "juhu-beach-mumbai",
    name: "Juhu Beach",
    state: "Maharashtra",
    district: "Mumbai",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Mumbai's most famous city beach, buzzing with street food, evening crowds and Bollywood mansions nearby.",
    description: "Juhu Beach is Mumbai's best-known urban beach, a long stretch of sand crowded each evening with families, vendors and joggers. It is the home of iconic chaat like pav bhaji and bhel puri sold along the shore. The upscale Juhu neighbourhood behind it is dotted with Bollywood celebrity homes.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Juhu_beach_%28Arial%29.jpg/1280px-Juhu_beach_%28Arial%29.jpg",
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2400,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 74,
    latitude: "19.0968",
    longitude: "72.8267",
  },
  {
    slug: "haji-ali-dargah",
    name: "Haji Ali Dargah",
    state: "Maharashtra",
    district: "Mumbai",
    category: "pilgrimage",
    placeType: "Dargah",
    shortDescription: "Floating white mosque and tomb on an islet off Worli, reached by a causeway open at low tide.",
    description: "Haji Ali Dargah is a striking white mosque and tomb built on an islet in the Arabian Sea, dedicated to the saint Pir Haji Ali Shah Bukhari. A narrow causeway connects it to the mainland, accessible only at low tide. Devotees of all faiths visit, especially on Thursday and Friday evenings.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Mumbai_03-2016_12_Haji_Ali_Dargah.jpg/1280px-Mumbai_03-2016_12_Haji_Ali_Dargah.jpg",
    openingTimings: "5:30 AM - 10:00 PM",
    entryFees: 0,
    budgetPerDay: 2200,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 72,
    latitude: "18.9827935",
    longitude: "72.80900009999999",
  },
  {
    slug: "siddhivinayak-temple-mumbai",
    name: "Siddhivinayak Temple",
    state: "Maharashtra",
    district: "Mumbai",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Mumbai's most revered Ganesha temple at Prabhadevi, drawing huge crowds and celebrity devotees.",
    description: "The Siddhivinayak Temple in Prabhadevi is one of Mumbai's most visited shrines, dedicated to Lord Ganesha. The gold-plated inner sanctum houses a black stone Ganesh idol believed to grant wishes. Tuesdays see especially long queues of devotees, including many public figures.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Shree_Siddhivinayak_Temple_Mumbai.jpg/1280px-Shree_Siddhivinayak_Temple_Mumbai.jpg",
    openingTimings: "7:00 AM - 7:00 PM",
    entryFees: 0,
    budgetPerDay: 2200,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 76,
    latitude: "19.0169538",
    longitude: "72.83039389999999",
  },
  {
    slug: "sanjay-gandhi-national-park",
    name: "Sanjay Gandhi National Park",
    state: "Maharashtra",
    district: "Mumbai Suburban",
    category: "wildlife",
    placeType: "National Park",
    shortDescription: "Forested national park within Mumbai, with leopards, a lion safari and the ancient Kanheri Caves.",
    description: "Sanjay Gandhi National Park is a rare expanse of protected forest inside a megacity, home to leopards, deer, butterflies and rich birdlife. Within it, the 2,000-year-old Kanheri Caves form a Buddhist rock-cut complex carved into a basalt hill. A toy train, lion and tiger safaris and nature trails draw Mumbai's day-trippers.",
    imageUrl: null,
    openingTimings: "7:30 AM - 6:00 PM (closed Mon)",
    entryFees: 85,
    budgetPerDay: 2000,
    recommendedDays: 1,
    bestMonths: "Jul,Aug,Sep,Oct,Nov,Dec",
    isHidden: false,
    popularity: 68,
    latitude: "19.2204535",
    longitude: "72.9128422",
  },
  {
    slug: "ajanta-caves",
    name: "Ajanta Caves",
    state: "Maharashtra",
    district: "Chhatrapati Sambhajinagar",
    category: "heritage",
    placeType: "Cave",
    shortDescription: "UNESCO Buddhist rock-cut caves famed for exquisite 2nd-century BCE murals and sculpture.",
    description: "The Ajanta Caves are 30 rock-cut Buddhist monuments carved into a horseshoe cliff, dating from the 2nd century BCE to about 480 CE. They are renowned worldwide for their vivid murals depicting the life of the Buddha and Jataka tales. A UNESCO World Heritage Site, the caves were rediscovered by chance in 1819.",
    imageUrl: null,
    openingTimings: "9:00 AM - 5:30 PM (closed Mon)",
    entryFees: 40,
    budgetPerDay: 2200,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 86,
    latitude: "20.5519",
    longitude: "75.7033",
  },
  {
    slug: "ellora-caves",
    name: "Ellora Caves",
    state: "Maharashtra",
    district: "Chhatrapati Sambhajinagar",
    category: "heritage",
    placeType: "Cave",
    shortDescription: "UNESCO caves blending Buddhist, Hindu and Jain art, crowned by the monolithic Kailasa temple.",
    description: "Ellora is a UNESCO World Heritage complex of 34 rock-cut Buddhist, Hindu and Jain caves carved over five centuries. Its centrepiece, the Kailasa Temple, is the world's largest monolithic rock excavation, chiselled top-down from a single basalt cliff. The site embodies remarkable religious harmony and engineering ambition.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM (closed Tue)",
    entryFees: 40,
    budgetPerDay: 2200,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 87,
    latitude: "20.0267844",
    longitude: "75.17708689999999",
  },
  {
    slug: "bibi-ka-maqbara",
    name: "Bibi Ka Maqbara",
    state: "Maharashtra",
    district: "Chhatrapati Sambhajinagar",
    category: "heritage",
    placeType: "Monument",
    shortDescription: "Mughal mausoleum resembling the Taj Mahal, built for Aurangzeb's wife in Aurangabad.",
    description: "Bibi Ka Maqbara is a 17th-century Mughal mausoleum built by Aurangzeb's son in memory of his mother, closely modelled on the Taj Mahal. Its white-plastered dome and minarets have earned it the nickname 'Taj of the Deccan'. Set in Mughal-style gardens, it is Aurangabad's signature monument.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/The_Tomb_of_Dilras_Banu_Begum.jpg/1280px-The_Tomb_of_Dilras_Banu_Begum.jpg",
    openingTimings: "7:00 AM - 10:00 PM",
    entryFees: 25,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 66,
    latitude: "19.9013998",
    longitude: "75.3202657",
  },
  {
    slug: "daulatabad-fort",
    name: "Daulatabad Fort",
    state: "Maharashtra",
    district: "Chhatrapati Sambhajinagar",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Formidable medieval hill fort near Aurangabad, famed for its ingenious labyrinth of defensive tunnels.",
    description: "Daulatabad, once called Devagiri, is a near-impregnable 12th-century hill fort rising on a conical rock. Its defences include a moat, spiked gates and a dark, twisting tunnel designed to trap invaders. A steep climb rewards visitors with sweeping views and the tall Chand Minar tower.",
    imageUrl: null,
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 40,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 64,
    latitude: "19.9436929",
    longitude: "75.2205449",
  },
  {
    slug: "lonavala-hill-station",
    name: "Lonavala",
    state: "Maharashtra",
    district: "Pune",
    category: "hill_station",
    placeType: "Hill Station",
    shortDescription: "Popular Sahyadri hill station between Mumbai and Pune, with misty ghats, waterfalls and chikki.",
    description: "Lonavala is a much-loved hill station in the Sahyadri range, especially magical during the monsoon when its valleys mist over and waterfalls roar. Highlights include Tiger's Leap viewpoint, Bhushi Dam, Lonavala Lake and the nearby Karla and Bhaja caves. It is famous for its brittle-sweet chikki.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5d/Mumbai_Pune_Expressway2.jpg",
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2400,
    recommendedDays: 2,
    bestMonths: "Jul,Aug,Sep,Oct",
    isHidden: false,
    popularity: 82,
    latitude: "18.7546",
    longitude: "73.4062",
  },
  {
    slug: "khandala",
    name: "Khandala",
    state: "Maharashtra",
    district: "Pune",
    category: "hill_station",
    placeType: "Hill Station",
    shortDescription: "Twin hill town to Lonavala at the head of the Bhor Ghat, known for green valleys and monsoon views.",
    description: "Khandala sits at the crest of the Bhor Ghat, a short hop from Lonavala, offering lush valley panoramas and cool breezes. Popular stops include Duke's Nose cliff, Amrutanjan Point and Kune Falls. It is a quick, scenic getaway on the Mumbai-Pune route.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2300,
    recommendedDays: 1,
    bestMonths: "Jul,Aug,Sep,Oct",
    isHidden: false,
    popularity: 70,
    latitude: "18.7645",
    longitude: "73.3752",
  },
  {
    slug: "matheran-hill-station",
    name: "Matheran",
    state: "Maharashtra",
    district: "Raigad",
    category: "hill_station",
    placeType: "Hill Station",
    shortDescription: "Asia's only vehicle-free hill station, reached by a heritage toy train, with red-earth forest trails.",
    description: "Matheran is a compact hill station where motor vehicles are banned, so visitors explore its red-earth paths on foot, horseback or hand-pulled rickshaw. A narrow-gauge toy train winds up from Neral through forest to the town. Dozens of viewpoints such as Panorama and Louisa Point look out over the Sahyadris.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Matheran_In_Clouds.jpg/1280px-Matheran_In_Clouds.jpg",
    openingTimings: null,
    entryFees: 50,
    budgetPerDay: 2200,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 74,
    latitude: "18.9889971",
    longitude: "73.27065069999999",
  },
  {
    slug: "lavasa-city",
    name: "Lavasa",
    state: "Maharashtra",
    district: "Pune",
    category: "hill_station",
    placeType: "Planned Town",
    shortDescription: "Italian-inspired planned lakeside town in the hills near Pune, with promenades and watersports.",
    description: "Lavasa is a privately planned hill town styled on the Italian town of Portofino, set beside the Warasgaon reservoir. Its colourful lakeside promenade offers cafes, cycling, watersports and boat rides. The scenic drive through the ghats is part of the appeal.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/60/Lavasahills.jpg",
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2600,
    recommendedDays: 2,
    bestMonths: "Jul,Aug,Sep,Oct,Nov",
    isHidden: false,
    popularity: 62,
    latitude: "18.4096269",
    longitude: "73.5066488",
  },
  {
    slug: "shaniwar-wada-pune",
    name: "Shaniwar Wada",
    state: "Maharashtra",
    district: "Pune",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Ruined 18th-century Peshwa palace-fort in Pune, known for its grand gateway and sound-and-light show.",
    description: "Shaniwar Wada was the fortified seat of the Peshwa rulers of the Maratha Empire, built in 1732. Though a fire destroyed much of the wooden palace, its massive stone ramparts and the studded Delhi Gate survive. An evening sound-and-light show recounts its dramatic history.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Front_view_of_Shaniwar_Wada_illuminated.jpg/1280px-Front_view_of_Shaniwar_Wada_illuminated.jpg",
    openingTimings: "9:00 AM - 5:30 PM",
    entryFees: 25,
    budgetPerDay: 1900,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 67,
    latitude: "18.5195841",
    longitude: "73.85542079999999",
  },
  {
    slug: "aga-khan-palace-pune",
    name: "Aga Khan Palace",
    state: "Maharashtra",
    district: "Pune",
    category: "heritage",
    placeType: "Palace",
    shortDescription: "Elegant palace in Pune where Gandhi was interned; now a memorial and Gandhi museum.",
    description: "The Aga Khan Palace, built in 1892, served as a prison for Mahatma Gandhi, his wife Kasturba and secretary Mahadev Desai during the Quit India Movement. Kasturba and Desai died here and their memorials stand in the gardens. The graceful Italianate arches now house a Gandhi museum.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Pune_Palace.jpg/1280px-Pune_Palace.jpg",
    openingTimings: "9:00 AM - 5:30 PM",
    entryFees: 25,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 60,
    latitude: "18.5525887",
    longitude: "73.9015388",
  },
  {
    slug: "sinhagad-fort-pune",
    name: "Sinhagad Fort",
    state: "Maharashtra",
    district: "Pune",
    category: "adventure",
    placeType: "Fort",
    shortDescription: "Hilltop Maratha fort near Pune, a favourite trek with valley views, monsoon mist and local snacks.",
    description: "Sinhagad, the 'Lion Fort', crowns a hill southwest of Pune and is tied to the heroic 1670 battle led by Tanaji Malusare. A popular half-day trek or drive leads to its ramparts, gates and memorials. In monsoon it fills with mist, and stalls sell hot pithla-bhakri and buttermilk.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Sinhagad.jpg/1280px-Sinhagad.jpg",
    openingTimings: "6:00 AM - 6:00 PM",
    entryFees: 20,
    budgetPerDay: 1600,
    recommendedDays: 1,
    bestMonths: "Jul,Aug,Sep,Oct,Nov",
    isHidden: false,
    popularity: 69,
    latitude: "18.366277",
    longitude: "73.7558777",
  },
  {
    slug: "raigad-fort",
    name: "Raigad Fort",
    state: "Maharashtra",
    district: "Raigad",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Hilltop capital of Chhatrapati Shivaji's Maratha empire, reached by a steep climb or ropeway.",
    description: "Raigad Fort was the mountain capital from which Chhatrapati Shivaji Maharaj was crowned in 1674, perched high in the Sahyadris. Visitors ascend around 1,700 steps or take a ropeway to reach ruins of the royal court, market street and Shivaji's memorial. Commanding views and deep history make it a Maratha pilgrimage.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Nagarkhana%2C_Raigad_Fort%2C_India.jpg/1280px-Nagarkhana%2C_Raigad_Fort%2C_India.jpg",
    openingTimings: "8:00 AM - 5:00 PM",
    entryFees: 40,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 71,
    latitude: "18.2334679",
    longitude: "73.4406903",
  },
  {
    slug: "nashik-trimbakeshwar",
    name: "Trimbakeshwar Temple, Nashik",
    state: "Maharashtra",
    district: "Nashik",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Jyotirlinga temple at the source of the Godavari near Nashik, a major Kumbh Mela pilgrimage centre.",
    description: "Trimbakeshwar is one of the twelve sacred Jyotirlinga shrines of Shiva, set at the foothills of Brahmagiri where the Godavari river rises. Its black-stone Nagara temple is a focus of major rituals and the Nashik Kumbh Mela. The nearby Kushavarta kund is where pilgrims bathe.",
    imageUrl: null,
    openingTimings: "6:00 AM - 9:00 PM",
    entryFees: 0,
    budgetPerDay: 1700,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 72,
    latitude: "19.9321592",
    longitude: "73.5307823",
  },
  {
    slug: "sula-vineyards-nashik",
    name: "Sula Vineyards, Nashik",
    state: "Maharashtra",
    district: "Nashik",
    category: "heritage",
    placeType: "Vineyard",
    shortDescription: "India's best-known winery near Nashik, offering tastings, tours and a rolling vineyard-country setting.",
    description: "Sula Vineyards helped make Nashik the wine capital of India, spreading across sun-soaked slopes near Gangapur Dam. Guided tours explain the winemaking process and end with tastings overlooking the vines. A resort, restaurants and the annual SulaFest music festival round out the experience.",
    imageUrl: null,
    openingTimings: "11:00 AM - 9:00 PM",
    entryFees: 400,
    budgetPerDay: 2600,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 65,
    latitude: "20.00532",
    longitude: "73.68844659999999",
  },
  {
    slug: "panchgani-hill-station",
    name: "Panchgani",
    state: "Maharashtra",
    district: "Satara",
    category: "hill_station",
    placeType: "Hill Station",
    shortDescription: "Sahyadri hill town near Mahabaleshwar known for the flat Table Land plateau and strawberry farms.",
    description: "Panchgani, named for the five hills that surround it, is a serene hill station on the Deccan plateau. Its highlight is Table Land, one of Asia's largest mountain plateaus, ideal for horse rides and views. The area is dotted with strawberry farms, boarding schools and colonial-era bungalows.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Panchghani_Hill.jpg",
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2400,
    recommendedDays: 2,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 73,
    latitude: "17.9247",
    longitude: "73.8003",
  },
  {
    slug: "bhandardara",
    name: "Bhandardara",
    state: "Maharashtra",
    district: "Ahmednagar",
    category: "hill_station",
    placeType: "Hill Station",
    shortDescription: "Tranquil lakeside hill retreat below Mount Kalsubai, famed for the Arthur Lake and fireflies.",
    description: "Bhandardara is a quiet hill and lake destination in the Sahyadris, centred on the Arthur Lake and Wilson Dam with the tiered Umbrella Falls. It sits below Kalsubai, Maharashtra's highest peak and a popular trek. In pre-monsoon nights the surrounding forests glitter with fireflies.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2200,
    recommendedDays: 2,
    bestMonths: "Jun,Jul,Aug,Sep,Oct",
    isHidden: false,
    popularity: 64,
    latitude: "19.5400",
    longitude: "73.7500",
  },
  {
    slug: "kolhapur-mahalaxmi",
    name: "Mahalaxmi Temple, Kolhapur",
    state: "Maharashtra",
    district: "Kolhapur",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Ancient Shakti Peeth temple of Goddess Ambabai in Kolhapur, a major western Maharashtra pilgrimage.",
    description: "The Mahalaxmi (Ambabai) Temple in Kolhapur is one of the revered Shakti Peethas, dating back to the 7th century Chalukya era. Its black-stone idol of the goddess and finely carved spires draw pilgrims year-round. Twice a year, sunlight aligns to illuminate the deity in the Kirnotsav festival.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Mahalaxmi_Temple%2C_Kolhapur.jpg/1280px-Mahalaxmi_Temple%2C_Kolhapur.jpg",
    openingTimings: "5:00 AM - 10:00 PM",
    entryFees: 0,
    budgetPerDay: 1700,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 68,
    latitude: "16.6948109",
    longitude: "74.2228275",
  },
  {
    slug: "new-palace-kolhapur",
    name: "New Palace, Kolhapur",
    state: "Maharashtra",
    district: "Kolhapur",
    category: "heritage",
    placeType: "Palace",
    shortDescription: "Indo-Saracenic royal palace of the Kolhapur Chhatrapatis, housing a museum of arms and heirlooms.",
    description: "The New Palace of Kolhapur, built in 1877 for Chhatrapati Shahaji, is a striking Indo-Saracenic mansion set in landscaped grounds with a lake. Its museum displays royal weaponry, costumes, hunting trophies and memorabilia of the Kolhapur dynasty. The black-stone facade and clock tower are architectural highlights.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Kolhapur_New_Palace.jpg/1280px-Kolhapur_New_Palace.jpg",
    openingTimings: "9:00 AM - 6:00 PM",
    entryFees: 100,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 58,
    latitude: "16.7193627",
    longitude: "74.231735",
  },
  {
    slug: "tarkarli-beach",
    name: "Tarkarli Beach",
    state: "Maharashtra",
    district: "Sindhudurg",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Clear-water Konkan beach near Malvan, prized for scuba diving, snorkelling and backwater houseboats.",
    description: "Tarkarli, on the Sindhudurg coast, is famed for some of the clearest water in Maharashtra, making it the state's top spot for scuba diving and snorkelling. White sand fringed by casuarina and swaying palms lines the shore. Backwater houseboats, dolphin trips and fresh Malvani seafood complete the coastal escape.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2400,
    recommendedDays: 2,
    bestMonths: "Nov,Dec,Jan,Feb,Mar",
    isHidden: false,
    popularity: 72,
    latitude: "16.0300",
    longitude: "73.4700",
  },
  {
    slug: "sindhudurg-fort",
    name: "Sindhudurg Fort",
    state: "Maharashtra",
    district: "Sindhudurg",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Sea fort built by Shivaji on a rocky island off Malvan, reached by boat, with a rare Shivaji temple.",
    description: "Sindhudurg is a formidable 17th-century sea fort built by Chhatrapati Shivaji Maharaj on a rocky islet off Malvan. Its curving ramparts rise straight from the Arabian Sea and enclose freshwater wells and a rare temple dedicated to Shivaji himself. A short boat ride from Malvan carries visitors across.",
    imageUrl: null,
    openingTimings: "8:00 AM - 5:30 PM",
    entryFees: 50,
    budgetPerDay: 2200,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 66,
    latitude: "16.0433863",
    longitude: "73.4609954",
  },
  {
    slug: "ganpatipule-beach",
    name: "Ganpatipule",
    state: "Maharashtra",
    district: "Ratnagiri",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Serene Konkan beach town centred on a seaside Swayambhu Ganesh temple set against white sand.",
    description: "Ganpatipule pairs a clean, palm-lined Konkan beach with a revered 400-year-old Swayambhu (self-manifested) Ganesh temple right by the shore. Pilgrims circumambulate the small hill behind the temple. Calm waters, seafood shacks and nearby mango orchards make it a relaxed coastal retreat.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/A_Beach_at_GanapatiPule.jpg/1280px-A_Beach_at_GanapatiPule.jpg",
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2200,
    recommendedDays: 2,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 68,
    latitude: "17.1450",
    longitude: "73.2680",
  },
  {
    slug: "alibaug-beach",
    name: "Alibaug",
    state: "Maharashtra",
    district: "Raigad",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Coastal weekend town near Mumbai with black-sand beaches and the sea-girt Kolaba Fort.",
    description: "Alibaug is a favourite coastal getaway from Mumbai, reachable by road or ferry, dotted with laid-back beaches and weekend villas. The black-sand Alibaug Beach leads out at low tide to the 17th-century Kolaba Fort, a Maratha sea fort. Nearby Nagaon, Kihim and Akshi beaches offer quieter sands.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1d/Alibag_Sea_beach_3%2C_Maharashtra.JPG",
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2400,
    recommendedDays: 2,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 70,
    latitude: "18.6438187",
    longitude: "72.8737017",
  },
  {
    slug: "tadoba-andhari-tiger-reserve",
    name: "Tadoba-Andhari Tiger Reserve",
    state: "Maharashtra",
    district: "Chandrapur",
    category: "wildlife",
    placeType: "Tiger Reserve",
    shortDescription: "Maharashtra's oldest and largest tiger reserve, among India's best for reliable wild tiger sightings.",
    description: "Tadoba-Andhari is Maharashtra's oldest and largest national park, renowned as one of India's finest reserves for spotting wild tigers. Jeep safaris through teak forest and around Tadoba Lake also reveal leopards, sloth bears, dhole and marsh crocodiles. Its dense population and open terrain make sightings frequent.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Panthera_tigris_tigris_Tidoba_20150306.jpg/1280px-Panthera_tigris_tigris_Tidoba_20150306.jpg",
    openingTimings: "6:00 AM - 6:00 PM (closed Tue)",
    entryFees: 400,
    budgetPerDay: 3200,
    recommendedDays: 2,
    bestMonths: "Nov,Dec,Jan,Feb,Mar,Apr",
    isHidden: false,
    popularity: 78,
    latitude: "20.2717885",
    longitude: "79.38757059999999",
  },
  {
    slug: "lonar-crater-lake",
    name: "Lonar Crater Lake",
    state: "Maharashtra",
    district: "Buldhana",
    category: "adventure",
    placeType: "Crater Lake",
    shortDescription: "Rare saline lake formed by a meteorite impact in basalt, ringed by forest and ancient temples.",
    description: "Lonar Lake fills a crater created around 50,000 years ago by a meteorite striking the Deccan basalt, one of very few such impact lakes in the world. Its green, alkaline-saline water is fringed by forest and dotted with ruined medieval temples. Scientists and birdwatchers alike are drawn to its unusual ecology.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Lonar_Crater_Lake.jpg/1280px-Lonar_Crater_Lake.jpg",
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 60,
    latitude: "19.9757827",
    longitude: "76.50691069999999",
  },
  {
    slug: "harihareshwar-beach",
    name: "Harihareshwar",
    state: "Maharashtra",
    district: "Raigad",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Peaceful Konkan pilgrimage-beach town with a Shiva temple flanked by hills and the Savitri estuary.",
    description: "Harihareshwar is a calm Konkan coastal town where a hillside Shiva temple, known as the Kashi of the South, meets a quiet beach. A rocky pradakshina path circles the headland at the sea's edge. The nearby Savitri river estuary and Bagmandala ferry add to its serene charm.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Harihareshwar_beach.jpg/1280px-Harihareshwar_beach.jpg",
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2000,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 57,
    latitude: "17.9970",
    longitude: "73.0180",
  },
  {
    slug: "pratapgad-fort",
    name: "Pratapgad Fort",
    state: "Maharashtra",
    district: "Satara",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Mountain fort near Mahabaleshwar tied to Shivaji's famous 1659 victory, with valley-edge ramparts.",
    description: "Pratapgad is a well-preserved hill fort near Mahabaleshwar, the site of Chhatrapati Shivaji's decisive 1659 encounter with Afzal Khan. Its upper and lower fortifications, temples and a large Shivaji statue crown a ridge with dramatic Sahyadri views. The winding ghat drive to reach it is scenic in itself.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Pratapgad_The_Fort_of_Valour.jpg/1280px-Pratapgad_The_Fort_of_Valour.jpg",
    openingTimings: "6:00 AM - 7:00 PM",
    entryFees: 0,
    budgetPerDay: 1900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 62,
    latitude: "17.9371187",
    longitude: "73.57820079999999",
  },
  {
    slug: "shirdi-note-different",
    name: "Shani Shingnapur",
    state: "Maharashtra",
    district: "Ahmednagar",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "Village temple to Lord Shani famed for homes without doors, near the Shirdi pilgrimage circuit.",
    description: "Shani Shingnapur is a village revered for its open-air shrine to Lord Shani, the deity of Saturn, marked by a self-manifested black stone. Legend holds that the god protects the village, so traditionally homes here were built without doors or locks. It is a popular add-on to the nearby Shirdi pilgrimage.",
    imageUrl: null,
    openingTimings: "5:00 AM - 10:00 PM",
    entryFees: 0,
    budgetPerDay: 1600,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 63,
    latitude: "19.3560",
    longitude: "74.9250",
  },
  {
    slug: "karla-caves",
    name: "Karla Caves",
    state: "Maharashtra",
    district: "Pune",
    category: "heritage",
    placeType: "Cave",
    shortDescription: "Ancient rock-cut Buddhist chaitya near Lonavala with India's largest surviving early prayer hall.",
    description: "The Karla Caves, dating to around the 2nd century BCE, house one of the largest and best-preserved early Buddhist chaitya (prayer) halls in India. A rock-cut horseshoe arch, carved pillars topped with elephants, and an original wooden ceiling distinguish the main cave. It sits on a hill near Lonavala beside a Ekvira Devi temple.",
    imageUrl: null,
    openingTimings: "9:00 AM - 5:00 PM",
    entryFees: 25,
    budgetPerDay: 1700,
    recommendedDays: 1,
    bestMonths: "Jul,Aug,Sep,Oct,Nov",
    isHidden: false,
    popularity: 58,
    latitude: "18.7832875",
    longitude: "73.4704531",
  },

  // ===================== GOA =====================
  {
    slug: "goa-north-beaches-belt",
    name: "Baga Beach",
    state: "Goa",
    district: "North Goa",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Lively North Goa beach famed for water sports, beach shacks and Goa's most energetic nightlife.",
    description: "Baga Beach is the buzzing heart of North Goa's party scene, packed with beach shacks, water sports and famous nightclubs like Tito's Lane. Days are filled with parasailing, banana-boat rides and dolphin-spotting trips. The golden sands connect to neighbouring Calangute and Anjuna.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Baga_Beach%2C_Calangute%2C_Goa.jpg/1280px-Baga_Beach%2C_Calangute%2C_Goa.jpg",
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2800,
    recommendedDays: 2,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 84,
    latitude: "15.5556",
    longitude: "73.7517",
  },
  {
    slug: "calangute-beach",
    name: "Calangute Beach",
    state: "Goa",
    district: "North Goa",
    category: "beach",
    placeType: "Beach",
    shortDescription: "The 'Queen of Beaches', Goa's largest and busiest stretch of sand with shacks and water sports.",
    description: "Calangute is the largest and most popular beach in North Goa, nicknamed the 'Queen of Beaches'. Its broad sands host water sports, souvenir markets and a long line of shacks serving seafood and cocktails. It stays lively from morning swims to sunset crowds.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2700,
    recommendedDays: 2,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 80,
    latitude: "15.549441",
    longitude: "73.7534857",
  },
  {
    slug: "anjuna-beach",
    name: "Anjuna Beach",
    state: "Goa",
    district: "North Goa",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Bohemian North Goa beach known for its Wednesday flea market, trance parties and rocky sunsets.",
    description: "Anjuna is a hippie-era icon of Goa, ringed by red-rock outcrops and famous for its sprawling Wednesday flea market. It remains a hub of trance and full-moon parties, alongside laid-back cafes and yoga retreats. The rocky southern end offers dramatic sunset viewpoints.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Anjuna_Beach%2C_Goa%2C_India%2C_Legendary_Curlies_beach_shack.jpg/1280px-Anjuna_Beach%2C_Goa%2C_India%2C_Legendary_Curlies_beach_shack.jpg",
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2600,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 76,
    latitude: "15.5733497",
    longitude: "73.74097809999999",
  },
  {
    slug: "vagator-beach",
    name: "Vagator Beach",
    state: "Goa",
    district: "North Goa",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Scenic North Goa beach with red cliffs, the Chapora Fort backdrop and cliff-top party venues.",
    description: "Vagator is a striking North Goa beach split by rocky headlands, backed by red laterite cliffs and the ruined Chapora Fort. Its two coves, Big and Little Vagator, offer calmer sands and photogenic sunsets. Cliff-top clubs and cafes keep it popular with a younger crowd.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2600,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 72,
    latitude: "15.5980",
    longitude: "73.7440",
  },
  {
    slug: "chapora-fort",
    name: "Chapora Fort",
    state: "Goa",
    district: "North Goa",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Hilltop Portuguese-era fort above Vagator, famed for river-mouth views and its Bollywood fame.",
    description: "Chapora Fort is a ruined 17th-century Portuguese bastion perched on a headland where the Chapora river meets the sea. Its weathered red-laterite walls offer sweeping views over Vagator and the coastline. Popularly called 'Dil Chahta Hai Fort' after the film, it draws crowds at sunset.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Fort_Chapora_26012016.jpg/1280px-Fort_Chapora_26012016.jpg",
    openingTimings: "10:00 AM - 5:00 PM",
    entryFees: 0,
    budgetPerDay: 2400,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 68,
    latitude: "15.6046375",
    longitude: "73.7369631",
  },
  {
    slug: "aguada-fort",
    name: "Fort Aguada",
    state: "Goa",
    district: "North Goa",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Well-preserved 17th-century Portuguese fort and lighthouse guarding the Mandovi rivermouth.",
    description: "Fort Aguada is a large, well-preserved Portuguese fortress built in 1612 to guard the mouth of the Mandovi river against invaders. It features a four-storey lighthouse, a huge freshwater cistern and commanding sea views. The complex overlooks Sinquerim Beach and once housed a colonial-era jail.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/ad/Fort_aguada.jpg",
    openingTimings: "9:30 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 2400,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 71,
    latitude: "15.4922519",
    longitude: "73.77374619999999",
  },
  {
    slug: "old-goa-basilica-bom-jesus",
    name: "Basilica of Bom Jesus, Old Goa",
    state: "Goa",
    district: "North Goa",
    category: "heritage",
    placeType: "Church",
    shortDescription: "UNESCO baroque church in Old Goa holding the mortal remains of St Francis Xavier.",
    description: "The Basilica of Bom Jesus, consecrated in 1605, is a UNESCO World Heritage church and one of Goa's most sacred Christian sites. It enshrines the incorrupt body of St Francis Xavier in an ornate silver casket. Its bare-laterite baroque facade and gilded interior make it an architectural landmark of Old Goa.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Front_Elevation_of_Basilica_of_Bom_Jesus.jpg/1280px-Front_Elevation_of_Basilica_of_Bom_Jesus.jpg",
    openingTimings: "9:00 AM - 6:30 PM",
    entryFees: 0,
    budgetPerDay: 2200,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 79,
    latitude: "15.5008238",
    longitude: "73.9114061",
  },
  {
    slug: "se-cathedral-old-goa",
    name: "Sé Cathedral, Old Goa",
    state: "Goa",
    district: "North Goa",
    category: "heritage",
    placeType: "Church",
    shortDescription: "One of Asia's largest churches, a UNESCO landmark in Old Goa famed for its Golden Bell.",
    description: "The Sé Cathedral is among the largest churches in Asia, built by the Portuguese over some 80 years and dedicated to St Catherine. Its Tuscan exterior and vast barrel-vaulted interior house gilded altars and the celebrated 'Golden Bell'. It stands at the heart of the UNESCO-listed Old Goa monuments.",
    imageUrl: null,
    openingTimings: "7:30 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 2200,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 70,
    latitude: "15.5038077",
    longitude: "73.9121499",
  },
  {
    slug: "panaji-fontainhas",
    name: "Fontainhas, Panaji",
    state: "Goa",
    district: "North Goa",
    category: "heritage",
    placeType: "Heritage Quarter",
    shortDescription: "Goa's colourful Latin Quarter in Panaji, with narrow lanes of Portuguese-era pastel houses.",
    description: "Fontainhas is Panaji's old Latin Quarter, a UNESCO-recognised heritage zone of winding lanes lined with vividly painted Portuguese-era homes. Ochre, blue and green facades, tiled roofs and tiny chapels give it a distinctly Mediterranean feel. Art galleries, cafes and homestays make it ideal for a leisurely walk.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Panaji_City.JPG/1280px-Panaji_City.JPG",
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2400,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 67,
    latitude: "15.4980",
    longitude: "73.8320",
  },
  {
    slug: "dudhsagar-falls",
    name: "Dudhsagar Falls",
    state: "Goa",
    district: "South Goa",
    category: "adventure",
    placeType: "Waterfall",
    shortDescription: "One of India's tallest waterfalls, a milky four-tier cascade on the Goa-Karnataka border in Bhagwan Mahaveer sanctuary.",
    description: "Dudhsagar, meaning 'sea of milk', is a spectacular four-tiered waterfall plunging about 310 metres down a forested mountainside on the Goa-Karnataka border. Reached by jeep safari through Bhagwan Mahaveer Sanctuary or a scenic train route, it is most thunderous just after the monsoon. A railway bridge crosses its base for iconic views.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Doodhsagar_Fall.jpg/1280px-Doodhsagar_Fall.jpg",
    openingTimings: "6:00 AM - 5:00 PM",
    entryFees: 30,
    budgetPerDay: 2600,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan",
    isHidden: false,
    popularity: 82,
    latitude: "15.3144375",
    longitude: "74.3143073",
  },
  {
    slug: "palolem-beach",
    name: "Palolem Beach",
    state: "Goa",
    district: "South Goa",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Crescent-shaped palm-fringed beach in South Goa, known for calm swimming and silent discos.",
    description: "Palolem is South Goa's most beloved beach, a picture-perfect crescent of soft sand framed by swaying coconut palms. Its calm, shallow waters are ideal for swimming and kayaking, while colourful shacks and beach huts line the bay. It is also famous for headphone-based 'silent disco' nights.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Palolem_Beach%2C_South_Goa.jpg/1280px-Palolem_Beach%2C_South_Goa.jpg",
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2500,
    recommendedDays: 2,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 80,
    latitude: "15.0099648",
    longitude: "74.02321859999999",
  },
  {
    slug: "colva-beach",
    name: "Colva Beach",
    state: "Goa",
    district: "South Goa",
    category: "beach",
    placeType: "Beach",
    shortDescription: "One of South Goa's oldest and longest beaches, with white sand, shacks and a historic church nearby.",
    description: "Colva is one of the oldest and longest beaches in South Goa, stretching along soft white sand backed by a lively strip of shacks and stalls. Calmer and more family-oriented than the north, it is popular for gentle swims and sunset walks. The nearby Our Lady of Mercy Church adds a heritage touch.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/06/Colv%C3%A1_beach.jpg",
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2400,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 71,
    latitude: "15.2805316",
    longitude: "73.91199449999999",
  },
  {
    slug: "agonda-beach",
    name: "Agonda Beach",
    state: "Goa",
    district: "South Goa",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Tranquil, unspoilt South Goa beach ideal for relaxation, turtle nesting and quiet beach huts.",
    description: "Agonda is a serene, laid-back beach in South Goa, prized for its clean sands, low crowds and gentle pace. Backed by palms and eco-friendly huts, it is a favourite for those seeking calm over nightlife. Olive Ridley turtles nest along a protected stretch of its shore.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2400,
    recommendedDays: 2,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 66,
    latitude: "15.0450",
    longitude: "74.0230",
  },
  {
    slug: "benaulim-beach",
    name: "Benaulim Beach",
    state: "Goa",
    district: "South Goa",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Quiet fishing-village beach in South Goa with calm waters, dolphin trips and a relaxed vibe.",
    description: "Benaulim is a peaceful South Goa beach rooted in a traditional fishing village, just south of Colva. Its calm, clean waters and gentle slope suit swimming and long strolls, while local outrigger boats offer dolphin-spotting trips. Fresh seafood shacks and a slow, unhurried atmosphere define it.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/20191211_Benaulim_4885.jpg/1280px-20191211_Benaulim_4885.jpg",
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2300,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 60,
    latitude: "15.2507866",
    longitude: "73.9201835",
  },
  {
    slug: "cabo-de-rama-fort",
    name: "Cabo de Rama Fort",
    state: "Goa",
    district: "South Goa",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Ancient clifftop fort in South Goa with dramatic Arabian Sea views and a small chapel within.",
    description: "Cabo de Rama is one of Goa's oldest forts, set on a rugged headland high above the Arabian Sea in the south. Though largely in ruins, its ramparts, cannons and a still-active chapel remain. The clifftop viewpoints over crashing surf make it a quiet, atmospheric stop.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Cabo_de_Rama_Entrance.jpg/1280px-Cabo_de_Rama_Entrance.jpg",
    openingTimings: "9:30 AM - 5:30 PM",
    entryFees: 0,
    budgetPerDay: 2200,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 55,
    latitude: "15.0887849",
    longitude: "73.9215933",
  },
  {
    slug: "mangeshi-temple-goa",
    name: "Shri Mangeshi Temple",
    state: "Goa",
    district: "North Goa",
    category: "pilgrimage",
    placeType: "Temple",
    shortDescription: "One of Goa's largest and most visited Hindu temples, dedicated to Lord Manguesh (Shiva).",
    description: "The Shri Mangeshi Temple at Ponda is among Goa's most important and elegant Hindu shrines, dedicated to Lord Manguesh, a form of Shiva. Its whitewashed tower, seven-storey lamp tower (deepstambha) and serene tank reflect distinctive Goan temple architecture. It draws steady streams of pilgrims and visitors.",
    imageUrl: null,
    openingTimings: "5:30 AM - 9:30 PM",
    entryFees: 0,
    budgetPerDay: 2000,
    recommendedDays: 1,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 62,
    latitude: "15.4449051",
    longitude: "73.9663825",
  },
  {
    slug: "arambol-beach",
    name: "Arambol Beach",
    state: "Goa",
    district: "North Goa",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Far-north Goa beach with a bohemian vibe, freshwater lake, drum circles and paragliding.",
    description: "Arambol is the northernmost of Goa's popular beaches, long favoured by a bohemian, backpacker crowd. A short walk over the rocks leads to a sweet-water lake set behind the sand, ringed by forest. Sunset drum circles, live music, yoga and paragliding define its free-spirited character.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2400,
    recommendedDays: 2,
    bestMonths: "Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 69,
    latitude: "15.6870",
    longitude: "73.7040",
  },

  // ===================== DAMAN & DIU / DADRA & NAGAR HAVELI =====================
  {
    slug: "diu-fort",
    name: "Diu Fort",
    state: "Daman and Diu",
    district: "Diu",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Massive Portuguese sea fort on Diu island, with old cannons, a lighthouse and ocean-battered walls.",
    description: "Diu Fort is a grand 16th-century Portuguese fortress ringing the eastern tip of Diu island, its ramparts rising straight from the sea. Rows of antique cannons, a lighthouse and a chapel remain within the weathered walls. Waves crash against the bastions, and views stretch across the Arabian Sea and old jail island.",
    imageUrl: null,
    openingTimings: "7:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 2000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 68,
    latitude: "20.7130",
    longitude: "70.9420",
  },
  {
    slug: "nagoa-beach-diu",
    name: "Nagoa Beach, Diu",
    state: "Daman and Diu",
    district: "Diu",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Diu's most popular horseshoe beach, lined with Hoka palms and safe for swimming and water sports.",
    description: "Nagoa Beach is Diu's most famous stretch, a curving horseshoe bay fringed by distinctive branching Hoka palm trees found almost nowhere else in India. Its calm, shallow waters are well suited to swimming, and operators offer jet-skiing, parasailing and banana-boat rides. Sunbeds and shacks make it a relaxed day out.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 2000,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 70,
    latitude: "20.7055733",
    longitude: "70.9156624",
  },
  {
    slug: "ghoghla-beach-diu",
    name: "Ghoghla Beach, Diu",
    state: "Daman and Diu",
    district: "Diu",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Diu's longest and cleanest beach, quieter than Nagoa, good for swimming and water sports.",
    description: "Ghoghla Beach, on the mainland side of Diu, is the island's longest and one of its cleanest, with wide open sands and gentle surf. Less crowded than Nagoa, it is popular for swimming, sunbathing and water sports. Its calm setting suits families and relaxed evenings.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1900,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 58,
    latitude: "20.7250",
    longitude: "70.9640",
  },
  {
    slug: "st-pauls-church-diu",
    name: "St Paul's Church, Diu",
    state: "Daman and Diu",
    district: "Diu",
    category: "heritage",
    placeType: "Church",
    shortDescription: "Baroque 17th-century Portuguese church in Diu town, noted for its carved wooden interior.",
    description: "St Paul's Church, built by the Portuguese in 1610 and dedicated to Our Lady of Immaculate Conception, is Diu's most impressive colonial church and still in use. Its volute-scrolled baroque facade and finely carved Burma-teak woodwork inside are its highlights. It stands amid the atmospheric lanes of old Diu town.",
    imageUrl: null,
    openingTimings: "8:00 AM - 6:00 PM",
    entryFees: 0,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 52,
    latitude: "20.7150",
    longitude: "70.9330",
  },
  {
    slug: "jampore-beach-daman",
    name: "Jampore Beach, Daman",
    state: "Daman and Diu",
    district: "Daman",
    category: "beach",
    placeType: "Beach",
    shortDescription: "Quiet casuarina-lined beach in south Daman, popular for relaxed strolls and safe wading.",
    description: "Jampore Beach lies just south of Nani Daman, a calm stretch of brownish sand backed by shady casuarina groves. Its shallow waters and gentle waves make it a safe spot for wading and unwinding. Weekenders come for the peaceful atmosphere and seaside food stalls.",
    imageUrl: null,
    openingTimings: null,
    entryFees: 0,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 54,
    latitude: "20.3820",
    longitude: "72.8480",
  },
  {
    slug: "moti-daman-fort",
    name: "Moti Daman Fort",
    state: "Daman and Diu",
    district: "Daman",
    category: "heritage",
    placeType: "Fort",
    shortDescription: "Large 16th-century Portuguese fort enclosing old Daman, with churches, a lighthouse and river views.",
    description: "Moti Daman Fort is a sprawling 16th-century Portuguese fortification that encloses the older, quieter half of Daman on the south bank of the Damanganga river. Within its bastioned walls stand colonial churches, government offices, gardens and a lighthouse. A walk along its ramparts offers views over the river mouth and sea.",
    imageUrl: null,
    openingTimings: "8:00 AM - 4:00 PM",
    entryFees: 0,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 57,
    latitude: "20.4057687",
    longitude: "72.8344956",
  },
  {
    slug: "vanganga-lake-silvassa",
    name: "Vanganga Lake & Garden, Silvassa",
    state: "Dadra and Nagar Haveli",
    district: "Dadra and Nagar Haveli",
    category: "heritage",
    placeType: "Lake Garden",
    shortDescription: "Landscaped island-dotted lake garden near Silvassa with pedal boats, arched bridges and greenery.",
    description: "Vanganga Lake Garden, near Silvassa, is a landscaped park built around an artificial lake studded with small islands and Japanese-style arched bridges. Pedal boating, flowering gardens and shaded walkways make it a favourite family outing. It is one of the greener attractions of Dadra and Nagar Haveli.",
    imageUrl: null,
    openingTimings: "8:00 AM - 8:00 PM",
    entryFees: 20,
    budgetPerDay: 1600,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 50,
    latitude: "20.2360",
    longitude: "72.9860",
  },
  {
    slug: "dudhni-lake-silvassa",
    name: "Dudhni Lake",
    state: "Dadra and Nagar Haveli",
    district: "Dadra and Nagar Haveli",
    category: "adventure",
    placeType: "Lake",
    shortDescription: "Scenic reservoir near Silvassa ringed by hills, offering boating, kayaking and water sports.",
    description: "Dudhni Lake is a tranquil backwater of the Madhuban Dam, surrounded by low forested hills near the Maharashtra border. It is the adventure hub of Dadra and Nagar Haveli, with speedboats, kayaking, jet-skiing and pedal boats on offer. Calm waters and green surroundings make it a scenic day trip from Silvassa.",
    imageUrl: null,
    openingTimings: "9:00 AM - 6:00 PM",
    entryFees: 20,
    budgetPerDay: 1800,
    recommendedDays: 1,
    bestMonths: "Oct,Nov,Dec,Jan,Feb",
    isHidden: false,
    popularity: 53,
    latitude: "20.1830",
    longitude: "73.2000",
  },
];
